# accepts — generated by onix. Do not edit.
{
  "1.3.8" = {
    version = "1.3.8";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0xbds0r4v51s5lprkr6snag2xr5ssbavh9hmqygj4y427z59l65z";
    };
  };
}
