# alien-signals — generated by onix. Do not edit.
{
  "3.1.2" = {
    version = "3.1.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0kkxz1vy3zb7kw9njn80lprazxcgasxfy0gy53j9cvn9hhh0lq5d";
    };
  };
}
