# arctic — generated by onix. Do not edit.
{
  "3.7.0" = {
    version = "3.7.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "01wmmyfhbxypp0hw7y335mkladzzdz4vw1nvvd563hiaq5pzz2yx";
    };
  };
}
