# array-flatten — generated by onix. Do not edit.
{
  "1.1.1" = {
    version = "1.1.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1v96cj6w6f7g61c7fjfkxpkbbfkxl2ksh5zm7y5mfp96xivi5jhs";
    };
  };
}
