# ast-kit — generated by onix. Do not edit.
{
  "3.0.0-beta.1" = {
    version = "3.0.0-beta.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1x8dx3mw8s2mz91fc350svlfhav056k7hkzjzx7kvz07fws1yfsm";
    };
  };
}
