# @babel/types — generated by onix. Do not edit.
{
  "8.0.0-rc.1" = {
    version = "8.0.0-rc.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1jx1qj8zd1jv6c8ar8x2n70l504nbx2pq8ydz8w4fh0kvf8rsx1q";
    };
  };
}
