# @babel/helper-string-parser — generated by onix. Do not edit.
{
  "8.0.0-rc.1" = {
    version = "8.0.0-rc.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "03shxbzs3j8yplrh6mk1nzdmdk7c139ify6zw9vs6ingdmnhaikq";
    };
  };
}
