# base64-js — generated by onix. Do not edit.
{
  "1.5.1" = {
    version = "1.5.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "118a46skxnrgx5bdd68ny9xxjcvyb7b1clj2hf82d196nm2skdxi";
    };
  };
}
