# better-sqlite3 — generated by onix. Do not edit.
{
  "11.8.1" = {
    version = "11.8.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0h4k4jinzr88wsqf5ccb06xj2757j1rjawk3yznkrhj59z3k3ijb";
    };
  };
}
