# bindings — generated by onix. Do not edit.
{
  "1.5.0" = {
    version = "1.5.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "01q9xfgc5jl9h6ny44zb4xcin6sirmm5bignn68rmn2vihbq2xyp";
    };
    integrity = "sha512-p2q/t/mhvuOj/UeLlV6566GD/guowlr0hHxClI0W9m7MWYkL1F0hLo+0Aexs9HSPCtR1SXQ0TD3MMKrXZajbiQ==";
  };
}
