# bl — generated by onix. Do not edit.
{
  "4.1.0" = {
    version = "4.1.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1jx7lm4mr80nzdw0k873llpl1x6i1n0m422v1scwla8qml4vkpl3";
    };
    integrity = "sha512-1W07cM9gS6DcLperZfFSj+bWLtaPGSOHWhPiGzXmvVJbRLdG82sH/Kn8EtW1VqWVA54AKf2h5k5BbnIbwF3h6w==";
  };
}
