# body-parser — generated by onix. Do not edit.
{
  "1.20.3" = {
    version = "1.20.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "11kf9cx1sbajm3hdym66k10a8r310pvcsdpag6l1bajn8jzzlh6n";
    };
  };
}
