# buffer — generated by onix. Do not edit.
{
  "5.7.1" = {
    version = "5.7.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1g60az00dzb1grcszyg12gyrl9jr9bwvrk2y9xjdwym3nxasrgwq";
    };
  };
}
