# bun-types — generated by onix. Do not edit.
{
  "1.3.9" = {
    version = "1.3.9";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1ms8fx0qiw5mxa3i5qgh6yk6d81640iypgyg7y6g8wch216vijps";
    };
  };
}
