# bytes — generated by onix. Do not edit.
{
  "3.1.2" = {
    version = "3.1.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "10f5wgg4izi14lc425v7ljr1ayk28ycdjckfxpm4bnj0bankfpl3";
    };
  };
}
