# cac — generated by onix. Do not edit.
{
  "6.7.14" = {
    version = "6.7.14";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1gjj94xq29h2820v7fc9y9x4xmwj2vgynkhp5vj1xsq3m9hsbnyn";
    };
  };
}
