# call-bound — generated by onix. Do not edit.
{
  "1.0.4" = {
    version = "1.0.4";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0cmxdglg3lrrz7apqgvqbkd57jicr98fxwhi92rvkwgd5x4ny21j";
    };
  };
}
