# chownr — generated by onix. Do not edit.
{
  "1.1.4" = {
    version = "1.1.4";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0gl3b5fqhvgq3glfdq341jmkyi7hmw4kdg4wd3pis0sdsc2kx1kj";
    };
  };
}
