# content-type — generated by onix. Do not edit.
{
  "1.0.5" = {
    version = "1.0.5";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1j0jpnlxjrdpbnq7s1h1xga2n8562j5g6612f7fl40jz82cd0cdc";
    };
  };
}
