# cookie-signature — generated by onix. Do not edit.
{
  "1.0.6" = {
    version = "1.0.6";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "04sk9ma5a8xb4jib4wmsdj8pz5bk36yzavzbj3k0drdy9bi4bww9";
    };
  };
}
