# cookie — generated by onix. Do not edit.
{
  "0.7.1" = {
    version = "0.7.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1zajpxf0mgmsl4lh63dmlmqahcaqxbpch37k40qkcviz4gvb6s8p";
    };
    integrity = "sha512-6DnInpx7SJ2AK3+CTUE/ZM0vWTUboZCegxhC2xiIydHR9jNuTAASBrfEpHhiGOZw/nX51bHt6YQl8jsGo4y/0w==";
  };
}
