# debug — generated by onix. Do not edit.
{
  "2.6.9" = {
    version = "2.6.9";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "160wvc74r8aypds7pym3hq4qpa786hpk4vif58ggiwcqcv34ibil";
    };
  };
}
