# decompress-response — generated by onix. Do not edit.
{
  "6.0.0" = {
    version = "6.0.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0krv58fihkajrskzakm1i69kklv0ycabrjmlgk2a9kkv0idlqznm";
    };
  };
}
