# deep-extend — generated by onix. Do not edit.
{
  "0.6.0" = {
    version = "0.6.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "11hk1g7qjw9bj03c8y7v7n8p8mdfacpd9l8n57dga8qcj8s5zk0d";
    };
    integrity = "sha512-LOHxIOaPYdHlJRtCQfDIVZtfw/ufM8+rVj649RIHzcm/vGwQRXFt6OPqIFWsm2XEMrNIEtWR64sY1LEKD2vAOA==";
  };
}
