# defu — generated by onix. Do not edit.
{
  "6.1.4" = {
    version = "6.1.4";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "14mjwyg6h46cxibszhcixjlklvjbghzik49m96pw9q3rq0qh92ha";
    };
  };
}
