# detect-libc — generated by onix. Do not edit.
{
  "2.1.2" = {
    version = "2.1.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "09wlldyqvhf2w7q4xcch4xh6pvldy7c2vbx83m48dzvcq07yq397";
    };
    integrity = "sha512-Btj2BOOO83o3WyH59e8MgXsxEQVcarkUOpEYrubB0urwnN10yQ364rsiByU11nZlqWYZm05i/of7io4mzihBtQ==";
  };
}
