# detect-libc — generated by onix. Do not edit.
{
  "2.1.2" = {
    version = "2.1.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "09wlldyqvhf2w7q4xcch4xh6pvldy7c2vbx83m48dzvcq07yq397";
    };
  };
}
