# dts-resolver — generated by onix. Do not edit.
{
  "2.1.3" = {
    version = "2.1.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1j6c86q3kq9w61519padla18y37zlf175z65nbh15wilvh6dwd6b";
    };
  };
}
