# @edgefirst-dev/data — generated by onix. Do not edit.
{
  "0.0.4" = {
    version = "0.0.4";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1mb4yr969q7df74npk0qj6x4sxfxgp5xjipc4ba0jy9lqvr298gr";
    };
  };
}
