# ee-first — generated by onix. Do not edit.
{
  "1.1.1" = {
    version = "1.1.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "175r500n567a04qmswzw5hkgdnika3dvn63n284jlar2gvmyhj2i";
    };
  };
}
