# @emnapi/wasi-threads — generated by onix. Do not edit.
{
  "1.1.0" = {
    version = "1.1.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "12j9w6nnx1fwxacpfz1gcvscllz783qsfra3ww5gfma07d4gfdvc";
    };
  };
}
