# @emnapi/runtime — generated by onix. Do not edit.
{
  "1.8.1" = {
    version = "1.8.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "05sg4ghr6s1axsjvn713nk7y0nsw8d60hyf7131j609arrxnz79i";
    };
  };
}
