# empathic — generated by onix. Do not edit.
{
  "2.0.0" = {
    version = "2.0.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0nalj6b9pcksl73zrxqxqfir59k89nrwldmvp6da9wkvwcr7g1aj";
    };
  };
}
