# encodeurl — generated by onix. Do not edit.
{
  "1.0.2" = {
    version = "1.0.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "13afvicx42ha4k29571sg0i4b76xjggyxvmmmibm258ipf6mjinb";
    };
  };
  "2.0.0" = {
    version = "2.0.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0agvpr5psd2nymhp51l5502fzifkshxxlnixl7kzkf2ii25l2blv";
    };
  };
}
