# end-of-stream — generated by onix. Do not edit.
{
  "1.4.5" = {
    version = "1.4.5";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "02d3hkin7l3ac84mn3icdm1dp30khbx9v5x4ndvjnr6w61h2m73d";
    };
    integrity = "sha512-ooEGc6HP26xXq/N+GCGOT0JKCLDGrq2bQUZrQ7gyrJiZANJ/8YDTxTpQBXGMn+WbIQXNVpyWymm7KYVICQnyOg==";
  };
}
