# es-errors — generated by onix. Do not edit.
{
  "1.3.0" = {
    version = "1.3.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "14q935xgv4cblmy8lk3brx4ypwxpgrid77r1lfnbilsbbg1x2kfi";
    };
  };
}
