# es-object-atoms — generated by onix. Do not edit.
{
  "1.1.1" = {
    version = "1.1.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1kkrwpp6nz2nc32zxin52xnngyg7qg38c5ljy5xyx2l1azby861y";
    };
  };
}
