# @esbuild/android-x64 — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1jvgb3kh3kj9yxr72596sgjvja1bjk0bbm3rsp96zvps7c4k9vh2";
    };
  };
}
