# @esbuild/linux-arm — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1m279n9r0qkv2jx39rq4v00n12cy770kry4gi5zl1b0skpdirs63";
    };
  };
}
