# @esbuild/freebsd-arm64 — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0nv4k0ndfdyr194yj8acg6jyzvrq5vcc5kdaxa5xsqh61n7vzcgn";
    };
  };
}
