# @esbuild/linux-loong64 — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "08fbzgalji1hg26ax2gvhd22j3xr8cmb197dywaxri0n8ygnsz65";
    };
  };
}
