# @esbuild/darwin-arm64 — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0fqkx3c4pphsvagdl7kvbr2kbyv768iisnvrd92rwdlzsj3qx80q";
    };
    os = [ "darwin" ];
    cpu = [ "arm64" ];
  };
}
