# @esbuild/win32-x64 — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0pyh6g57lgj947lksnaa8ryrp80c01ynnr3p1hz8n25p5ijjwr48";
    };
  };
}
