# @esbuild/linux-mips64el — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1yxjvdflhd0gw9gyc6il823sh988ckypgxnqh1vml69693m11939";
    };
  };
}
