# @esbuild/linux-riscv64 — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "17d96d17lr50i0719h0dbf4ign950cyr1lk5vmfdm5hhpxzx7nyg";
    };
  };
}
