# @esbuild/openbsd-x64 — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1fjb3b57spqhikdays9iimw2b2glrph28ss9sbjmyxq1bi1f9q6n";
    };
  };
}
