# @esbuild/openbsd-arm64 — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "09wwbcb36ar4mlf1h03aw2d0fkjm1p9n1xd54g0x5znshbipn0j6";
    };
  };
}
