# @esbuild/freebsd-arm64 — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "";
    };
    integrity = "sha512-UN8HXjtJ0k/Mj6a9+5u6+2eZ2ERD7Edt1Q9IZiB5UZAIdPnVKDoG7mdTVGhHJIeEml60JteamR3qhsr1r8gXvg==";
    os = [ "freebsd" ];
    cpu = [ "arm64" ];
  };
}
