# @esbuild/netbsd-arm64 — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "16902q1f90yl8ggg6rh5xpzdpxgg908bcgsfladi9l9bh5s94p9c";
    };
  };
}
