# esbuild — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0ivbz1pj3dyn8jhbqa8r4wqlhx64rvgz5nl4g87dv2vzviq62gl7";
    };
  };
}
