# @esbuild/linux-loong64 — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "";
    };
    integrity = "sha512-CN9AZr8kEndGooS35ntToZLTQLHEjtVB5n7dl8ZcTZMonJ7CCfStrYhrzF97eAecqVbVJ7APOEe18RPI4KLhwQ==";
    os = [ "linux" ];
    cpu = [ "loong64" ];
  };
}
