# @esbuild/linux-ppc64 — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0wxk9cif253xknnhy71p64ndz0jmpi53rblp2q3b711lbsbxlh86";
    };
  };
}
