# @esbuild/netbsd-x64 — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0qznaqcxlip1l6ir3w9k3hhrn6n03wh995gksrzczr73393na2nb";
    };
  };
}
