# @esbuild/linux-arm64 — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "05hf7whvyk0zrhf75akgqn7h35csbk3zqr7alxcqmi7bbi3h3ybx";
    };
  };
}
