# @esbuild/android-arm — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "09x381v8c09a44hf14lyd7cjmr4agnch88218ijvzbqimc4w7sd4";
    };
  };
}
