# @esbuild/win32-arm64 — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "08zws6xfmhy8l0hw2d9h63m6wjaapa2hn2j9zp0pwkzx2wgkn0is";
    };
  };
}
