# @esbuild/darwin-x64 — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0835b7i0k44l2vqil58sqf4i0j4jidb6jli3vjgsmgp73np7x18m";
    };
  };
}
