# @esbuild/sunos-x64 — generated by onix. Do not edit.
{
  "0.24.2" = {
    version = "0.24.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "17pd2bl7q2f28pdy3y1vn3mxhj97nhivycxxz6hhdcj5g7sz4rmr";
    };
  };
}
