# estree-walker — generated by onix. Do not edit.
{
  "3.0.3" = {
    version = "3.0.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1cvj3jfzlrg1dskkcwbjaccc00s16jma8mag8yg0kvyrdk0zvgdv";
    };
  };
}
