# express — generated by onix. Do not edit.
{
  "4.21.2" = {
    version = "4.21.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0270hgkkhxvvhjiyfsi28lyfv1alyfj26wddqr9zpby7glgajhzw";
    };
    integrity = "sha512-28HqgMZAmih1Czt9ny7qr6ek2qddF4FclbMzwhCREB6OFfH+rXAnuNCwo1/wFvrtbgsQDb4kSbX9de9lFbrXnA==";
  };
}
