# express — generated by onix. Do not edit.
{
  "4.21.2" = {
    version = "4.21.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0270hgkkhxvvhjiyfsi28lyfv1alyfj26wddqr9zpby7glgajhzw";
    };
  };
}
