# fdir — generated by onix. Do not edit.
{
  "6.5.0" = {
    version = "6.5.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0pin1ngw51v3z7q8gs4q84bwwcw3pdyh29jk8351yahyygcxq794";
    };
  };
}
