# file-uri-to-path — generated by onix. Do not edit.
{
  "1.0.0" = {
    version = "1.0.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1cvgn3xfpkzy20vjfw093mdjam1x9hfkrrkbdbrrdavmgvvcsh2l";
    };
    integrity = "sha512-0Zt+s3L7Vf1biwWZ29aARiVYLx7iMGnEUl9x33fbB/j3jR81u/O2LbqK+Bm1CDSNDKVtJ/YjwY7TUd5SkeLQLw==";
  };
}
