# finalhandler — generated by onix. Do not edit.
{
  "1.3.1" = {
    version = "1.3.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1bn1fn4m2jv490cckfkb8i4axbzfjjyp2fy7wdyb1dcqx5972l7d";
    };
    integrity = "sha512-6BN9trH7bp3qvnrRyzsBz+g3lZxTNZTbVO2EV1CS0WIcDbawYVdYvGflME/9QP0h0pYlCDBCTjYa9nZzMDpyxQ==";
  };
}
