# forwarded — generated by onix. Do not edit.
{
  "0.2.0" = {
    version = "0.2.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "168w8dhfqp12llh2w802dm3z1fcarsacsksyvdccnpxqbzlmsnlv";
    };
  };
}
