# fresh — generated by onix. Do not edit.
{
  "0.5.2" = {
    version = "0.5.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0k44badcxkwy202kz404w078l660f65jaijg473xv38ay3wpdri5";
    };
    integrity = "sha512-zJ2mQYM18rEFOudeV4GShTGIQ7RbzA7ozbU9I/XBpm7kqgMywgmylMwXHxZJmkVoYkna9d2pVXVXPdYTP9ej8Q==";
  };
}
