# fs-constants — generated by onix. Do not edit.
{
  "1.0.0" = {
    version = "1.0.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1yn5qyvxf9i3zrfly77wgmi3j9fl61gh1i0jjgamnir43dz6v4z7";
    };
  };
}
