# get-proto — generated by onix. Do not edit.
{
  "1.0.1" = {
    version = "1.0.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1086swsp92367j7m6canvgf6zwghh0iqr9f2bwndh7qzzcmcab7b";
    };
    integrity = "sha512-sTSfBjoXBp89JvIKIefqw7U2CCebsc74kiY6awiGogKtoSGbgjYE/G/+l9sF3MWFPNc9IcoOC4ODfKHfxFmp0g==";
  };
}
