# get-tsconfig — generated by onix. Do not edit.
{
  "4.13.6" = {
    version = "4.13.6";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1p7czkgfz6skq3d2mgzbbkki651jxgj1i9h8chsw1aam34jcb5c9";
    };
  };
}
