# get-intrinsic — generated by onix. Do not edit.
{
  "1.3.0" = {
    version = "1.3.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0i05g3xvqgv16ss19k3jprfnkqsln2n4m7wgn3xldzh09vjjfbk6";
    };
  };
}
