# github-from-package — generated by onix. Do not edit.
{
  "0.0.0" = {
    version = "0.0.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1yj38h8r3z0gdfklghk3xz5gmfc2f6ya50rk7awfjakpw22z2iiy";
    };
    integrity = "sha512-SyHy3T1v2NUXn29OsWdxmK6RwHD+vkj3v8en8AOBZ1wBQ/hCAQ5bAQTD02kW4W9tUp/3Qh6J8r9EvntiyCmOOw==";
  };
}
