# hasown — generated by onix. Do not edit.
{
  "2.0.2" = {
    version = "2.0.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0zc0za6zy8y2iwy31ayzwmi4j912j382iwr9xsv09bhirp9c9kah";
    };
    integrity = "sha512-0hJU9SCPvmMzIBdZFqNPXWa6dqh7WdH0cII9y+CyS8rG3nL48Bclra9HmKhVVUHyPWNH5Y7xDwAB7bfgSjkUMQ==";
  };
}
