# http-errors — generated by onix. Do not edit.
{
  "2.0.0" = {
    version = "2.0.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1dypd936i09cvjyxx338da0nimbm4cqi2rrxhjch3ix2wmwx6ky1";
    };
  };
}
