# iconv-lite — generated by onix. Do not edit.
{
  "0.4.24" = {
    version = "0.4.24";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0da6ff7dlx6lfhdafsd9sv0h09sicpfakms8bqylrm4f17r68v2p";
    };
  };
}
