# ieee754 — generated by onix. Do not edit.
{
  "1.2.1" = {
    version = "1.2.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1b4xiyr6fmgl05cjgc8fiyfk2jagf7xq2y5rknw9scvy76dlpwcf";
    };
  };
}
