# import-without-cache — generated by onix. Do not edit.
{
  "0.2.5" = {
    version = "0.2.5";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "029ngjqfjlfj34iacwf9byzjqi76vifhxpgcbnqd7afw9a5j78dq";
    };
  };
}
