# inherits — generated by onix. Do not edit.
{
  "2.0.4" = {
    version = "2.0.4";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1bxg4igfni2hymabg8bkw86wd3qhhzhsswran47sridk3dnbqkfr";
    };
  };
}
