# ini — generated by onix. Do not edit.
{
  "1.3.8" = {
    version = "1.3.8";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0nk92bp5is23lsi1ip4qz5bjkzmjxkz9c1g79sx991ad212i37px";
    };
  };
}
