# @jridgewell/gen-mapping — generated by onix. Do not edit.
{
  "0.3.13" = {
    version = "0.3.13";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "10h05zv5qcbxiz5wslzqv1aik7zl0cfqiarqhw63xmpnq5cgc5mw";
    };
  };
}
