# @jridgewell/trace-mapping — generated by onix. Do not edit.
{
  "0.3.31" = {
    version = "0.3.31";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1krw8nqmca9k4gb20kh9mpfsjb2b6ggrx226haz5l3b336hp2k66";
    };
  };
}
