# @jridgewell/sourcemap-codec — generated by onix. Do not edit.
{
  "1.5.5" = {
    version = "1.5.5";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "11b5h4hihb2n8203znalqm53s7pv82a84jahsqgf7rd2406kpba7";
    };
  };
}
