# @jridgewell/resolve-uri — generated by onix. Do not edit.
{
  "3.1.2" = {
    version = "3.1.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0c72fqvljvr28rdmg6hjd8zc63vm00r9xlrx6l9spfjq4pvgjlnv";
    };
  };
}
