# jsesc — generated by onix. Do not edit.
{
  "3.1.0" = {
    version = "3.1.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "029w1pc3jck2y6bg2g9vvz3mij38l992zb7jhfzp16narhjj4w8c";
    };
  };
}
