# merge-descriptors — generated by onix. Do not edit.
{
  "1.0.3" = {
    version = "1.0.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1bidz6yhi4a01y886wr89h5ggmw1jc416bsxj32b4rxwjdlf0dcf";
    };
  };
}
