# merge-descriptors — generated by onix. Do not edit.
{
  "1.0.3" = {
    version = "1.0.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1bidz6yhi4a01y886wr89h5ggmw1jc416bsxj32b4rxwjdlf0dcf";
    };
    integrity = "sha512-gaNvAS7TZ897/rVaZ0nMtAyxNyi/pdbjbAwUpFQpN70GqnVfOiXpeUUMKRBmzXaSQ8DdTX4/0ms62r2K+hE6mQ==";
  };
}
