# mime — generated by onix. Do not edit.
{
  "1.6.0" = {
    version = "1.6.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "16iprk4h6nh780mvfv0p93k3yvj7jrq2qs92niaw6yk11qwi0li1";
    };
    integrity = "sha512-x0Vn8spI+wuJ1O6S7gnbaQg8Pxh4NNHb7KSINmEWKiPE4RKOplvijn+NkmYmmRgP68mc70j2EbeTFRsrswaQeg==";
  };
}
