# mime-db — generated by onix. Do not edit.
{
  "1.52.0" = {
    version = "1.52.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0fwyiyqi3w03w3xwy2jhm8rsa0y9wgkc0j6q3q6mvk9asns0prxq";
    };
  };
}
