# mime-types — generated by onix. Do not edit.
{
  "2.1.35" = {
    version = "2.1.35";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1hyi043kcqyfz82w19s357klvj54f0s94d40rymbms86i74lyws9";
    };
    integrity = "sha512-ZDY+bPm5zTTF+YpCrAU9nK0UgICYPT0QtT1NZWFv4s++TNkcgVaT0g6+4R2uI4MjQjzysHB1zxuWL50hzaeXiw==";
  };
}
