# mime — generated by onix. Do not edit.
{
  "1.6.0" = {
    version = "1.6.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "16iprk4h6nh780mvfv0p93k3yvj7jrq2qs92niaw6yk11qwi0li1";
    };
  };
}
