# mime-types — generated by onix. Do not edit.
{
  "2.1.35" = {
    version = "2.1.35";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1hyi043kcqyfz82w19s357klvj54f0s94d40rymbms86i74lyws9";
    };
  };
}
