# mimic-response — generated by onix. Do not edit.
{
  "3.1.0" = {
    version = "3.1.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0m6xcg030cw88cja84avw63q3jkvqgbdp74xvs1p3m2w2my9n7ij";
    };
    integrity = "sha512-z0yWI+4FDrrweS8Zmt4Ej5HdJmky15+L2e6Wgn3+iK5fWzb6T3fhNFq2+MeTRb064c6Wr4N/wv0DzQTjNzHNGQ==";
  };
}
