# mimic-response — generated by onix. Do not edit.
{
  "3.1.0" = {
    version = "3.1.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0m6xcg030cw88cja84avw63q3jkvqgbdp74xvs1p3m2w2my9n7ij";
    };
  };
}
