# minimist — generated by onix. Do not edit.
{
  "1.2.8" = {
    version = "1.2.8";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "10yfwkrl00d8gy9z622yrklg1jax3qk38j354jfw34xk2p0pc2im";
    };
  };
}
