# @mjackson/headers — generated by onix. Do not edit.
{
  "0.10.0" = {
    version = "0.10.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0afr78452par06dp6hq1syivi34avzk0rfs4ij3vgr3km2g1pwdh";
    };
  };
}
