# mkdirp-classic — generated by onix. Do not edit.
{
  "0.5.3" = {
    version = "0.5.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0ijj0y0ajccyfxfck4iq5yfkhlwcqipg2i1z9idlmk5mz56v9g19";
    };
  };
}
