# ms — generated by onix. Do not edit.
{
  "2.1.3" = {
    version = "2.1.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1ii24v83yrryzmj9p369qxmpr53337kkqbdaklpmbv9hwlanwqgn";
    };
  };
}
