# ms — generated by onix. Do not edit.
{
  "2.0.0" = {
    version = "2.0.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1jrysw9zx14av3jdvc3kywc3xkjqxh748g4s6p1iy634i2mm489n";
    };
  };
  "2.1.3" = {
    version = "2.1.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1ii24v83yrryzmj9p369qxmpr53337kkqbdaklpmbv9hwlanwqgn";
    };
  };
}
