# napi-build-utils — generated by onix. Do not edit.
{
  "2.0.0" = {
    version = "2.0.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "17ka0j4yhfm15asnzi7rjz5qkaikzarlxkfdvx6nqh6hcqxn75x5";
    };
  };
}
