# @napi-rs/wasm-runtime — generated by onix. Do not edit.
{
  "1.1.1" = {
    version = "1.1.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1wxcibcdx2rgk1lid7jq0i7ik7gwwrnkq8xmys029nfspy9zq5zv";
    };
  };
}
