# negotiator — generated by onix. Do not edit.
{
  "0.6.3" = {
    version = "0.6.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "04sjfqwmsamf29a67zwrjdi3h62avc3y6a9y6a74zsgpl1xnhbli";
    };
    integrity = "sha512-+EUsqGPLsM+j/zdChZjsnX51g4XrHFOIXwfnCVPGlQk/k5giakcKsuxCObBRu6DSm9opw/O6slWbJdghQM4bBg==";
  };
}
