# node-abi — generated by onix. Do not edit.
{
  "3.87.0" = {
    version = "3.87.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1lbzpz8wnpnzyp2q7zs12qx5maq9hg34786hz1ldkl2pmajkycaj";
    };
    integrity = "sha512-+CGM1L1CgmtheLcBuleyYOn7NWPVu0s0EJH2C4puxgEZb9h8QpR9G2dBfZJOAUhi7VQxuBPMd0hiISWcTyiYyQ==";
  };
}
