# object-inspect — generated by onix. Do not edit.
{
  "1.13.4" = {
    version = "1.13.4";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1gwh5vk75w4crskqjsn4ps9z8hqqpjp58d8y82q4b2px79x9c943";
    };
    integrity = "sha512-W67iLl4J2EXEGTbfeHCffrjDfitvLANg0UlX3wFUUSTx92KXRFegMHUVgSqE+wvhAbi4WqjGg9czysTV2Epbew==";
  };
}
