# obug — generated by onix. Do not edit.
{
  "2.1.1" = {
    version = "2.1.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0hxfqqjcy24n7ibc5rz30iqxxqjjm5jdsjzx407wnj14w2a1g913";
    };
  };
}
