# on-finished — generated by onix. Do not edit.
{
  "2.4.1" = {
    version = "2.4.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "02mxvpahgv07xaih7lmpn8wic9v4jph3fir0qpd6qf4w0kql4kgn";
    };
  };
}
