# @oslojs/binary — generated by onix. Do not edit.
{
  "1.0.0" = {
    version = "1.0.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0sca32shamakr59kafakl28m9najnvi0q5dglaz0y7jg6cn0lpya";
    };
  };
}
