# @oslojs/asn1 — generated by onix. Do not edit.
{
  "1.0.0" = {
    version = "1.0.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1c1a7qz4q93nh30w3qjjn2m56flj2bj7w2ynx4a48z51idbim30m";
    };
  };
}
