# @oslojs/jwt — generated by onix. Do not edit.
{
  "0.2.0" = {
    version = "0.2.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0id11srz7i9kkgsbifvf3rwj4k00igqj0qqrb5ypp65i78x2s4qn";
    };
  };
}
