# @oslojs/encoding — generated by onix. Do not edit.
{
  "0.4.1" = {
    version = "0.4.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "06im7q0wmlcny7zsr2vam41nmxb8bw5043z3zgipdwjhh45h0yin";
    };
  };
  "1.1.0" = {
    version = "1.1.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "01cscwjfaz03hyx4svjkk9gmlasb5ryp8az4hx1q2wyy6803zdiv";
    };
  };
}
