# @oslojs/crypto — generated by onix. Do not edit.
{
  "1.0.1" = {
    version = "1.0.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0jg1v96r01liw9li8dfr531b1zdr16xgxg9l7wwkzwkqzc7f09ga";
    };
  };
}
