# @oxc-project/types — generated by onix. Do not edit.
{
  "0.112.0" = {
    version = "0.112.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0qcjijc8q0gz9ghfgamkyg3nk1n7vkdffp1fnh1n9sckh5synli2";
    };
  };
}
