# parseurl — generated by onix. Do not edit.
{
  "1.3.3" = {
    version = "1.3.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "06h2bx1rilkdir3v9jlg94r1q2fn895s0vxjjs0wx5z027x4pvsn";
    };
  };
}
