# pathe — generated by onix. Do not edit.
{
  "2.0.3" = {
    version = "2.0.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0dnzjq3529b584wj6rich8p0c16s0ydlbn7miw88lzxvbny76fvf";
    };
  };
}
