# path-to-regexp — generated by onix. Do not edit.
{
  "0.1.12" = {
    version = "0.1.12";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1d2hdkry7lf7g1qjlh64r4h4159g7hy3afahja54ykcppkx1gzq3";
    };
  };
}
