# picocolors — generated by onix. Do not edit.
{
  "1.1.1" = {
    version = "1.1.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1nc2z3w16wpz2840srcwyxd747khwfvh66yigyrpwywn0wldpbnk";
    };
  };
}
