# prebuild-install — generated by onix. Do not edit.
{
  "7.1.3" = {
    version = "7.1.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1azr614z2qdb67swy33ngiwkhns0c0jkdjj84xjhlk62ygnbhhb7";
    };
  };
}
