# proxy-addr — generated by onix. Do not edit.
{
  "2.0.7" = {
    version = "2.0.7";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1na6xrmlga7qjd55gfhnp7m8qg43nynzg5ds54s76kkd9zrvdld0";
    };
  };
}
