# pump — generated by onix. Do not edit.
{
  "3.0.3" = {
    version = "3.0.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0d5ws5cxr3h0dwa535gykb6786a1fs47jd1naay98zv47mb813al";
    };
    integrity = "sha512-todwxLMY7/heScKmntwQG8CXVkWUOdYxIvY2s0VWAAMh/nd8SoYiRaKjlr7+iCs984f2P8zvrfWcDDYVb73NfA==";
  };
}
