# pump — generated by onix. Do not edit.
{
  "3.0.3" = {
    version = "3.0.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0d5ws5cxr3h0dwa535gykb6786a1fs47jd1naay98zv47mb813al";
    };
  };
}
