# qs — generated by onix. Do not edit.
{
  "6.13.0" = {
    version = "6.13.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1z88srnvwfqdxvy5sixyc5zyfxpb9khjflnp3dn4d3nwvsxymzxb";
    };
    integrity = "sha512-+38qI9SOr8tfZ4QmJNplMUxqjbe7LKvvZgWdExBOmd+egZTtjLB67Gu0HRX3u/XOq7UU2Nx6nsjvS16Z9uwfpg==";
  };
}
