# @quansync/fs — generated by onix. Do not edit.
{
  "1.0.0" = {
    version = "1.0.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0riqkljrfimr5cb6qghii3c82mcddy03y2276a1jlnxg4q1yljf1";
    };
  };
}
