# range-parser — generated by onix. Do not edit.
{
  "1.2.1" = {
    version = "1.2.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "09prs852snwqr9cfcrybm7ysl0z1wka9dh4dwc4v1415cvi6cllh";
    };
    integrity = "sha512-Hrgsx+orqoygnmhFbKaHE6c296J+HTAQXoxEF6gNupROmmGJRoyzfG3ccAveqCBrwr/2yxQ5BVd/GTl5agOwSg==";
  };
}
