# raw-body — generated by onix. Do not edit.
{
  "2.5.2" = {
    version = "2.5.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0by4zfp9mahjnr3rbnjqrr1a4rgg4jasr7dwvkbbfxcz8b469la2";
    };
  };
}
