# raw-body — generated by onix. Do not edit.
{
  "2.5.2" = {
    version = "2.5.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0by4zfp9mahjnr3rbnjqrr1a4rgg4jasr7dwvkbbfxcz8b469la2";
    };
    integrity = "sha512-8zGqypfENjCIqGhgXToC8aB2r7YrBX+AQAfIPs/Mlk+BtPTztOvTS01NRW/3Eh60J+a48lt8qsCzirQ6loCVfA==";
  };
}
