# rc — generated by onix. Do not edit.
{
  "1.2.8" = {
    version = "1.2.8";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0fz9r8aphj84cvxv8k0m7g008gffz561r6ryvljb8gi0hpjgm983";
    };
    integrity = "sha512-y3bGgqKj3QBdxLbLkomlohkvsA8gdAiUQlSBJnBhfn+BPxg4bc62d8TcBW15wavDfgexCgccckhcZvywyQYPOw==";
  };
}
