# readable-stream — generated by onix. Do not edit.
{
  "3.6.2" = {
    version = "3.6.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0pdb0mrh95ks672ikgj8frx9nh078bfyngknj70ak2iibv06dn7d";
    };
  };
}
