# @remix-run/dom — generated by onix. Do not edit.
{
  "0.0.0-experimental-remix-jam.6" = {
    version = "0.0.0-experimental-remix-jam.6";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "18fqx02zk2mzlaw8h12rf9kqxc6d2vfh9972gmgp9hpyj3c711qm";
    };
  };
}
