# @remix-run/fetch-router — generated by onix. Do not edit.
{
  "0.6.0" = {
    version = "0.6.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "14xi29xp17wg0dn0xdkz7wqji3ha49ralgnjkq79x947sxxqkhm2";
    };
  };
}
