# remix-auth-oauth2 — generated by onix. Do not edit.
{
  "3.4.1" = {
    version = "3.4.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0ps018b125jz589x86y0q5wivyyzxgfc9cyllwfj0kgpaid20hv2";
    };
  };
}
