# remix-auth — generated by onix. Do not edit.
{
  "4.2.0" = {
    version = "4.2.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0dxi39pzbvmnwwwr32vf4ajp0cll2a16kandzg691lxgd0fga69d";
    };
  };
}
