# @remix-run/form-data-parser — generated by onix. Do not edit.
{
  "0.11.0" = {
    version = "0.11.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1qsbli653p1lf1l3k346qn62d41xkfvnqjqy59k1mw3c3c81vm2a";
    };
  };
}
