# @remix-run/events — generated by onix. Do not edit.
{
  "0.0.0-experimental-remix-jam.5" = {
    version = "0.0.0-experimental-remix-jam.5";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0fj1j923y51d9b2x5snyggwc4ax6wmiw28mg9pdxym6nbz2yhb73";
    };
  };
}
