# resolve-pkg-maps — generated by onix. Do not edit.
{
  "1.0.0" = {
    version = "1.0.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0xnzn1fl08qp7s8n886hd7zrbd3pjnz2jw86cvjdc7ab0nvvsz2a";
    };
  };
}
