# @rolldown/binding-wasm32-wasi — generated by onix. Do not edit.
{
  "1.0.0-rc.3" = {
    version = "1.0.0-rc.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "";
    };
    cpu = [ "wasm32" ];
  };
}
