# @rolldown/binding-darwin-arm64 — generated by onix. Do not edit.
{
  "1.0.0-rc.3" = {
    version = "1.0.0-rc.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1k8nkirrgw1kjlifa97vb4si4nxr4p7hbmadp3zx6s7ddb30z0l2";
    };
    os = [ "darwin" ];
    cpu = [ "arm64" ];
  };
}
