# @rolldown/binding-linux-x64-gnu — generated by onix. Do not edit.
{
  "1.0.0-rc.3" = {
    version = "1.0.0-rc.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "";
    };
    os = [ "linux" ];
    cpu = [ "x64" ];
  };
}
