# rolldown-plugin-dts — generated by onix. Do not edit.
{
  "0.22.1" = {
    version = "0.22.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0d6z002lki0vvllbxpbwrcccxw348ija0ykpm5yvq7x8p82rv5k5";
    };
  };
}
