# rolldown — generated by onix. Do not edit.
{
  "1.0.0-rc.3" = {
    version = "1.0.0-rc.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "00h6whsmm9jwyiwqanvvmwb1g2bl2qbk650j7famcgb5zllf1zyw";
    };
  };
}
