# @rolldown/binding-android-arm64 — generated by onix. Do not edit.
{
  "1.0.0-rc.3" = {
    version = "1.0.0-rc.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "";
    };
    os = [ "android" ];
    cpu = [ "arm64" ];
  };
}
