# safe-buffer — generated by onix. Do not edit.
{
  "5.2.1" = {
    version = "5.2.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1s5kvjpwqsc682zcy71h9c6pxla21sysfwj270x6jjkca421h62x";
    };
  };
}
