# safer-buffer — generated by onix. Do not edit.
{
  "2.1.2" = {
    version = "2.1.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1cx383s7vchfac8jlg3mnb820hkgcvhcpfn9w4f0g61vmrjjz0bq";
    };
  };
}
