# semver — generated by onix. Do not edit.
{
  "7.7.1" = {
    version = "7.7.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1raxbg6wijzz62w0f0n8vfb1rxzjw8j52fm3c8ngadydvxkbl6qg";
    };
  };
}
