# send — generated by onix. Do not edit.
{
  "0.19.0" = {
    version = "0.19.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0rhbd0z9rx7wmxbqy3d9yjavzaqbs7nb2dh68z5g4dbphw9i41wa";
    };
    integrity = "sha512-dW41u5VfLXu8SJh5bwRmyYUbAoSB3c9uQh6L8h/KtsFREPWpbX1lrljJo186Jc4nmci/sGUZ9a0a0J2zgfq2hw==";
  };
}
