# send — generated by onix. Do not edit.
{
  "0.19.0" = {
    version = "0.19.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0rhbd0z9rx7wmxbqy3d9yjavzaqbs7nb2dh68z5g4dbphw9i41wa";
    };
  };
}
