# serve-static — generated by onix. Do not edit.
{
  "1.16.2" = {
    version = "1.16.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "12gkhivxasrhzchvzpk4qwv1j7mlgz2qv1gz974n6mld5cii7f45";
    };
    integrity = "sha512-VqpjJZKadQB/PEbEwvFdO43Ax5dFBZ2UECszz8bQ7pi7wt//PWe1P6MN7eCnjsatYtBT6EuiClbjSWP2WrIoTw==";
  };
}
