# side-channel-weakmap — generated by onix. Do not edit.
{
  "1.0.2" = {
    version = "1.0.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0vnhs2whvv59nkqdsfpmd1fwrcjzh2ka5z8giy68kbg7qpq58aiv";
    };
  };
}
