# simple-concat — generated by onix. Do not edit.
{
  "1.0.1" = {
    version = "1.0.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0gknha4csvbwagam34g0qx67nzlfg9wm22nki8ak77xbkiscpz3a";
    };
  };
}
