# simple-get — generated by onix. Do not edit.
{
  "4.0.1" = {
    version = "4.0.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0m4p8n4wai9dwykpbcjh0g1dz06lvhyq650rcd5l0z5vc7pa20pr";
    };
    integrity = "sha512-brv7p5WgH0jmQJr1ZDDfKDOSeWWg+OVypG99A/5vYGPqJ6pxiaHLy8nxtFjBA7oMa01ebA9gfh1uMCFqOuXxvA==";
  };
}
