# statuses — generated by onix. Do not edit.
{
  "2.0.1" = {
    version = "2.0.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0nig6ygf53sj8vcqvbcwrzm4ln986rcz16kn5qjv1y4s9m1l164i";
    };
  };
}
