# strip-json-comments — generated by onix. Do not edit.
{
  "2.0.1" = {
    version = "2.0.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "16aq89q4gbs10fgy3a5n5miqphvs1sy44ckk4mf2dxqvmzmmzr6v";
    };
  };
}
