# @tanstack/query-core — generated by onix. Do not edit.
{
  "5.90.20" = {
    version = "5.90.20";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0kqx3gm7fla4zbx7ryvqxjs2q332w8h4xkhxn0cjhyy4pmgydw8j";
    };
  };
}
