# tar-stream — generated by onix. Do not edit.
{
  "2.2.0" = {
    version = "2.2.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0nrrl6sgl5yazgllc8ryxpg083432xwqvqbrlqdl16sfszgq73rs";
    };
    integrity = "sha512-ujeqbceABgwMZxEJnk2HDY2DlnUZ+9oEcb1KzTVfYHio0UE6dG71n60d8D2I4qNvleWrrXpmjpt7vZeF1LnMZQ==";
  };
}
