# tar-stream — generated by onix. Do not edit.
{
  "2.2.0" = {
    version = "2.2.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0nrrl6sgl5yazgllc8ryxpg083432xwqvqbrlqdl16sfszgq73rs";
    };
  };
}
