# tar-fs — generated by onix. Do not edit.
{
  "2.1.4" = {
    version = "2.1.4";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "17qkddvagnzw9ab1anrmp5qwndj18pknxzy6dr86bs20qkllcj3c";
    };
    integrity = "sha512-mDAjwmZdh7LTT6pNleZ05Yt65HC3E+NiQzl672vQG38jIrehtJk/J3mNwIg+vShQPcLF/LV7CMnDW6vjj6sfYQ==";
  };
}
