# tinyglobby — generated by onix. Do not edit.
{
  "0.2.15" = {
    version = "0.2.15";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1p993j64mlwzk3c9c5vx2v4ja5x4yl4cszqhabczng9pzppzb4dr";
    };
  };
}
