# tree-kill — generated by onix. Do not edit.
{
  "1.2.2" = {
    version = "1.2.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0qb0wrhfilwn54v7zw7nb6a4j7h8hbb8pcx8vh99zwy3lqrqc62a";
    };
  };
}
