# @tybys/wasm-util — generated by onix. Do not edit.
{
  "0.10.1" = {
    version = "0.10.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1fyznbqc5cznj67a6njm67cdqn46yq16wc395mw4ji0x13kbvj1d";
    };
  };
}
