# @types/estree — generated by onix. Do not edit.
{
  "1.0.8" = {
    version = "1.0.8";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0jnm82j29n0mm527qsz7rv05sksxkgsa92c54f96mnijf7mm611r";
    };
  };
}
