# typescript — generated by onix. Do not edit.
{
  "5.7.3" = {
    version = "5.7.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1fvybxpfwl5bs5hask73lvxmdn06chny8y4iccfyif5sah9cmkw0";
    };
    integrity = "sha512-84MVSjMEHP+FQRPy3pX9sTVV/INIex71s9TL2Gm5FG/WG1SqXeKyZ0k7/blY/4FdOzI12CBy1vGc4og/eus0fw==";
  };
  "5.9.3" = {
    version = "5.9.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1lx1hwb5g73x06pylqzgrkran1dlbx8iizrx0mwjhpvxrz4hiq8h";
    };
  };
}
