# @types/node — generated by onix. Do not edit.
{
  "22.13.1" = {
    version = "22.13.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "100z31n82hcanqq1ws5z3kl1kjyk9d4zrn870ambzinrfh460j1w";
    };
    integrity = "sha512-jK8uzQlrvXqEU91UxiK5J7pKHyzgnI1Qnl0QDHIgVGuolJhRb9EEl28Cj9b3rGR8B2lhFCtvIm5os8lFnO/1Ew==";
  };
  "25.2.3" = {
    version = "25.2.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0h4vwj599h7fwivdj6icmwidbss0c240q37qhpj0z1lif2iqs2qq";
    };
  };
}
