# typescript — generated by onix. Do not edit.
{
  "5.7.3" = {
    version = "5.7.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1fvybxpfwl5bs5hask73lvxmdn06chny8y4iccfyif5sah9cmkw0";
    };
  };
}
