# @types/node — generated by onix. Do not edit.
{
  "22.13.1" = {
    version = "22.13.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "100z31n82hcanqq1ws5z3kl1kjyk9d4zrn870ambzinrfh460j1w";
    };
  };
}
