# @types/bun — generated by onix. Do not edit.
{
  "1.3.9" = {
    version = "1.3.9";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0nzxa1af7grk53hpaxvls1ln05ymzpc8dkcm5mxcgiglcr3n07d6";
    };
  };
}
