# @types/jsesc — generated by onix. Do not edit.
{
  "2.5.1" = {
    version = "2.5.1";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1y76h4kawlz174bi2q4dvndlhaz042wn164aj7a8hkh7lm4jiiwz";
    };
  };
}
