# unconfig-core — generated by onix. Do not edit.
{
  "7.4.2" = {
    version = "7.4.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "15i9ixpcrk19nq5qwx86jslhrnfqjdmh47qizpbjfjp4z4q1msvr";
    };
  };
}
