# undici-types — generated by onix. Do not edit.
{
  "6.20.0" = {
    version = "6.20.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0vldbr517hhwc3kpbxmwqag2inxvdzibaj6nvkj74qv7zzyak33j";
    };
  };
}
