# undici-types — generated by onix. Do not edit.
{
  "6.20.0" = {
    version = "6.20.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0vldbr517hhwc3kpbxmwqag2inxvdzibaj6nvkj74qv7zzyak33j";
    };
    integrity = "sha512-Ny6QZ2Nju20vw1SRHe3d9jVu6gJ+4e3+MMpqu7pqE5HT6WsTSlce++GQmK5UXS8mzV8DSYHrQH+Xrf2jVcuKNg==";
  };
  "7.16.0" = {
    version = "7.16.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1bzqndp6yf7582badgp5yzb31kfqw731q2z87148l4d42bxf5dak";
    };
  };
}
