# unpipe — generated by onix. Do not edit.
{
  "1.0.0" = {
    version = "1.0.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1dnzbqfmchls4jyvkw0wnkc09pig98y66zzsy3lizgyls435xyrd";
    };
    integrity = "sha512-pjy2bYhSsufwWlKwPc+l3cN7+wuJlK6uz0YdJEOlQDbl6jo/YlPi4mb8agUkVC8BF7V8NuzeyPNqRksA3hztKQ==";
  };
}
