# unpipe — generated by onix. Do not edit.
{
  "1.0.0" = {
    version = "1.0.0";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1dnzbqfmchls4jyvkw0wnkc09pig98y66zzsy3lizgyls435xyrd";
    };
  };
}
