# unrun — generated by onix. Do not edit.
{
  "0.2.27" = {
    version = "0.2.27";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1vwck5cp1s5cga4achfqfsfckajppfvp3n641lfmwyfvhzwfvndf";
    };
  };
}
