# wrappy — generated by onix. Do not edit.
{
  "1.0.2" = {
    version = "1.0.2";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1yzx63jf27yz0bk0m78vy4y1cqzm113d2mi9h91y3cdpj46p7wxg";
    };
  };
}
