#
# ╔═══════════════════════════════════════════════════════╗
# ║  GENERATED — do not edit.  Run bin/import to refresh ║
# ╚═══════════════════════════════════════════════════════╝
#
# CHATWOOT — 364 gems
# Generated from Gemfile.lock
#
[
  { name = "actioncable"; version = "7.1.5.2"; }
  { name = "actionmailbox"; version = "7.1.5.2"; }
  { name = "actionmailer"; version = "7.1.5.2"; }
  { name = "actionpack"; version = "7.1.5.2"; }
  { name = "actiontext"; version = "7.1.5.2"; }
  { name = "actionview"; version = "7.1.5.2"; }
  { name = "active_record_query_trace"; version = "1.8"; }
  { name = "activejob"; version = "7.1.5.2"; }
  { name = "activemodel"; version = "7.1.5.2"; }
  { name = "activerecord"; version = "7.1.5.2"; }
  { name = "activerecord-import"; version = "2.1.0"; }
  { name = "activestorage"; version = "7.1.5.2"; }
  { name = "activesupport"; version = "7.1.5.2"; }
  { name = "acts-as-taggable-on"; version = "12.0.0"; }
  { name = "addressable"; version = "2.8.7"; }
  { name = "administrate"; version = "0.20.1"; }
  { name = "administrate-field-active_storage"; version = "1.0.3"; }
  { name = "administrate-field-belongs_to_search"; version = "0.9.0"; }
  { name = "ai-agents"; version = "0.7.0"; }
  { name = "annotaterb"; version = "4.20.0"; }
  { name = "ast"; version = "2.4.3"; }
  { name = "attr_extras"; version = "7.1.0"; }
  { name = "audited"; version = "5.4.1"; }
  { name = "aws-actionmailbox-ses"; version = "0.1.0"; }
  { name = "aws-eventstream"; version = "1.4.0"; }
  { name = "aws-partitions"; version = "1.1198.0"; }
  { name = "aws-sdk-core"; version = "3.240.0"; }
  { name = "aws-sdk-kms"; version = "1.118.0"; }
  { name = "aws-sdk-s3"; version = "1.208.0"; }
  { name = "aws-sdk-sns"; version = "1.70.0"; }
  { name = "aws-sigv4"; version = "1.12.1"; }
  { name = "barnes"; version = "0.0.9"; }
  { name = "base64"; version = "0.3.0"; }
  { name = "bcrypt"; version = "3.1.20"; }
  { name = "benchmark"; version = "0.4.1"; }
  { name = "bigdecimal"; version = "3.2.2"; }
  { name = "bindex"; version = "0.8.1"; }
  { name = "bootsnap"; version = "1.16.0"; }
  { name = "brakeman"; version = "5.4.1"; }
  { name = "browser"; version = "5.3.1"; }
  { name = "builder"; version = "3.3.0"; }
  { name = "bullet"; version = "8.0.7"; }
  { name = "bundle-audit"; version = "0.1.0"; }
  { name = "bundler-audit"; version = "0.9.1"; }
  { name = "byebug"; version = "11.1.3"; }
  { name = "childprocess"; version = "5.1.0"; }
  { name = "climate_control"; version = "1.2.0"; }
  { name = "coderay"; version = "1.1.3"; }
  { name = "commonmarker"; version = "0.23.10"; }
  { name = "concurrent-ruby"; version = "1.3.5"; }
  { name = "connection_pool"; version = "2.5.3"; }
  { name = "crack"; version = "1.0.0"; }
  { name = "crass"; version = "1.0.6"; }
  { name = "csv"; version = "3.3.0"; }
  { name = "csv-safe"; version = "3.3.1"; }
  { name = "database_cleaner"; version = "2.0.2"; }
  { name = "database_cleaner-active_record"; version = "2.1.0"; }
  { name = "database_cleaner-core"; version = "2.0.1"; }
  { name = "datadog"; version = "2.19.0"; }
  { name = "datadog-ruby_core_source"; version = "3.4.1"; }
  { name = "date"; version = "3.4.1"; }
  { name = "debug"; version = "1.8.0"; }
  { name = "declarative"; version = "0.0.20"; }
  { name = "devise"; version = "4.9.4"; }
  { name = "devise-two-factor"; version = "6.1.0"; }
  { name = "devise_token_auth"; version = "1.2.5"; }
  { name = "diff-lcs"; version = "1.5.1"; }
  { name = "digest-crc"; version = "0.6.5"; }
  { name = "docile"; version = "1.4.1"; }
  { name = "domain_name"; version = "0.5.20190701"; }
  { name = "dotenv"; version = "3.1.2"; }
  { name = "dotenv-rails"; version = "3.1.2"; }
  { name = "down"; version = "5.4.0"; }
  { name = "drb"; version = "2.2.3"; }
  { name = "dry-cli"; version = "1.1.0"; }
  { name = "dry-configurable"; version = "1.3.0"; }
  { name = "dry-core"; version = "1.1.0"; }
  { name = "dry-inflector"; version = "1.2.0"; }
  { name = "dry-initializer"; version = "3.2.0"; }
  { name = "dry-logic"; version = "1.6.0"; }
  { name = "dry-schema"; version = "1.14.1"; }
  { name = "dry-types"; version = "1.8.3"; }
  { name = "ecma-re-validator"; version = "0.4.0"; }
  { name = "elastic-apm"; version = "4.6.2"; }
  { name = "email-provider-info"; version = "0.0.1"; }
  { name = "email_reply_trimmer"; version = "0.1.13"; }
  { name = "erubi"; version = "1.13.0"; }
  { name = "et-orbi"; version = "1.2.11"; }
  { name = "event_stream_parser"; version = "1.0.0"; }
  { name = "execjs"; version = "2.8.1"; }
  { name = "facebook-messenger"; version = "2.0.1"; }
  { name = "factory_bot"; version = "6.4.5"; }
  { name = "factory_bot_rails"; version = "6.4.3"; }
  { name = "faker"; version = "3.2.0"; }
  { name = "faraday"; version = "2.13.1"; }
  { name = "faraday-follow_redirects"; version = "0.3.0"; }
  { name = "faraday-mashify"; version = "1.0.0"; }
  { name = "faraday-multipart"; version = "1.0.4"; }
  { name = "faraday-net_http"; version = "3.4.0"; }
  { name = "faraday-net_http_persistent"; version = "2.1.0"; }
  { name = "faraday-retry"; version = "2.2.1"; }
  { name = "faraday_middleware-aws-sigv4"; version = "1.0.1"; }
  { name = "fast-mcp"; version = "1.5.0"; }
  { name = "fcm"; version = "1.0.8"; }
  { name = "ffi"; version = "1.17.2"; }
  { name = "ffi-compiler"; version = "1.0.1"; }
  { name = "flag_shih_tzu"; version = "0.3.23"; }
  { name = "foreman"; version = "0.87.2"; }
  { name = "fugit"; version = "1.11.1"; }
  { name = "gapic-common"; version = "0.20.0"; }
  { name = "geocoder"; version = "1.8.1"; }
  { name = "gli"; version = "2.22.2"; }
  { name = "globalid"; version = "1.2.1"; }
  { name = "gmail_xoauth"; version = "0.4.3"; }
  { name = "google-apis-core"; version = "0.15.1"; }
  { name = "google-apis-iamcredentials_v1"; version = "0.22.0"; }
  { name = "google-apis-storage_v1"; version = "0.47.0"; }
  { name = "google-cloud-core"; version = "1.7.1"; }
  { name = "google-cloud-dialogflow-v2"; version = "0.31.0"; }
  { name = "google-cloud-env"; version = "2.2.1"; }
  { name = "google-cloud-errors"; version = "1.3.1"; }
  { name = "google-cloud-location"; version = "0.6.0"; }
  { name = "google-cloud-storage"; version = "1.52.0"; }
  { name = "google-cloud-translate-v3"; version = "0.10.0"; }
  { name = "google-protobuf"; version = "3.25.7"; }
  { name = "googleapis-common-protos"; version = "1.6.0"; }
  { name = "googleapis-common-protos-types"; version = "1.20.0"; }
  { name = "googleauth"; version = "1.11.2"; }
  { name = "groupdate"; version = "6.2.1"; }
  { name = "grpc"; version = "1.72.0"; }
  { name = "gserver"; version = "0.0.1"; }
  { name = "haikunator"; version = "1.1.1"; }
  { name = "hairtrigger"; version = "1.0.0"; }
  { name = "hana"; version = "1.3.7"; }
  { name = "hash_diff"; version = "1.1.1"; }
  { name = "hashdiff"; version = "1.1.0"; }
  { name = "hashie"; version = "5.0.0"; }
  { name = "html2text"; version = "0.4.0"; }
  { name = "http"; version = "5.1.1"; }
  { name = "http-accept"; version = "1.7.0"; }
  { name = "http-cookie"; version = "1.0.5"; }
  { name = "http-form_data"; version = "2.3.0"; }
  { name = "httparty"; version = "0.24.0"; }
  { name = "httpclient"; version = "2.8.3"; }
  { name = "i18n"; version = "1.14.7"; }
  { name = "image_processing"; version = "1.12.2"; }
  { name = "io-console"; version = "0.6.0"; }
  { name = "irb"; version = "1.7.2"; }
  { name = "iso-639"; version = "0.3.8"; }
  { name = "jbuilder"; version = "2.11.5"; }
  { name = "jmespath"; version = "1.6.2"; }
  { name = "jquery-rails"; version = "4.6.0"; }
  { name = "json"; version = "2.13.2"; }
  { name = "json_refs"; version = "0.1.8"; }
  { name = "json_schemer"; version = "0.2.24"; }
  { name = "judoscale-rails"; version = "1.8.2"; }
  { name = "judoscale-ruby"; version = "1.8.2"; }
  { name = "judoscale-sidekiq"; version = "1.8.2"; }
  { name = "jwt"; version = "2.10.1"; }
  { name = "kaminari"; version = "1.2.2"; }
  { name = "kaminari-actionview"; version = "1.2.2"; }
  { name = "kaminari-activerecord"; version = "1.2.2"; }
  { name = "kaminari-core"; version = "1.2.2"; }
  { name = "koala"; version = "3.4.0"; }
  { name = "language_server-protocol"; version = "3.17.0.5"; }
  { name = "launchy"; version = "3.1.1"; }
  { name = "letter_opener"; version = "1.10.0"; }
  { name = "libdatadog"; version = "18.1.0.1.0"; }
  { name = "libddwaf"; version = "1.24.1.0.3"; }
  { name = "line-bot-api"; version = "1.28.0"; }
  { name = "lint_roller"; version = "1.1.0"; }
  { name = "liquid"; version = "5.4.0"; }
  { name = "listen"; version = "3.8.0"; }
  { name = "llhttp-ffi"; version = "0.4.0"; }
  { name = "logger"; version = "1.7.0"; }
  { name = "lograge"; version = "0.14.0"; }
  { name = "loofah"; version = "2.23.1"; }
  { name = "mail"; version = "2.8.1"; }
  { name = "marcel"; version = "1.0.4"; }
  { name = "maxminddb"; version = "0.1.22"; }
  { name = "meta_request"; version = "0.8.5"; }
  { name = "method_source"; version = "1.1.0"; }
  { name = "mime-types"; version = "3.4.1"; }
  { name = "mime-types-data"; version = "3.2023.0218.1"; }
  { name = "mini_magick"; version = "4.12.0"; }
  { name = "mini_mime"; version = "1.1.5"; }
  { name = "mini_portile2"; version = "2.8.9"; }
  { name = "minitest"; version = "5.25.5"; }
  { name = "mock_redis"; version = "0.36.0"; }
  { name = "msgpack"; version = "1.8.0"; }
  { name = "multi_json"; version = "1.15.0"; }
  { name = "multi_xml"; version = "0.8.0"; }
  { name = "multipart-post"; version = "2.3.0"; }
  { name = "mutex_m"; version = "0.3.0"; }
  { name = "neighbor"; version = "0.2.3"; }
  { name = "net-http"; version = "0.6.0"; }
  { name = "net-http-persistent"; version = "4.0.2"; }
  { name = "net-imap"; version = "0.4.20"; }
  { name = "net-pop"; version = "0.1.2"; }
  { name = "net-protocol"; version = "0.2.2"; }
  { name = "net-smtp"; version = "0.3.4"; }
  { name = "netrc"; version = "0.11.0"; }
  { name = "newrelic-sidekiq-metrics"; version = "1.6.2"; }
  { name = "newrelic_rpm"; version = "9.6.0"; }
  { name = "nio4r"; version = "2.7.3"; }
  { name = "nokogiri"; version = "1.18.9"; }
  { name = "oauth"; version = "1.1.0"; }
  { name = "oauth-tty"; version = "1.0.5"; }
  { name = "oauth2"; version = "2.0.9"; }
  { name = "oj"; version = "3.16.10"; }
  { name = "omniauth"; version = "2.1.4"; }
  { name = "omniauth-google-oauth2"; version = "1.1.3"; }
  { name = "omniauth-oauth2"; version = "1.8.0"; }
  { name = "omniauth-rails_csrf_protection"; version = "1.0.2"; }
  { name = "omniauth-saml"; version = "2.2.4"; }
  { name = "opensearch-ruby"; version = "3.4.0"; }
  { name = "openssl"; version = "3.2.0"; }
  { name = "opentelemetry-api"; version = "1.7.0"; }
  { name = "opentelemetry-common"; version = "0.23.0"; }
  { name = "opentelemetry-exporter-otlp"; version = "0.31.1"; }
  { name = "opentelemetry-registry"; version = "0.4.0"; }
  { name = "opentelemetry-sdk"; version = "1.10.0"; }
  { name = "opentelemetry-semantic_conventions"; version = "1.36.0"; }
  { name = "orm_adapter"; version = "0.5.0"; }
  { name = "os"; version = "1.1.4"; }
  { name = "ostruct"; version = "0.6.1"; }
  { name = "parallel"; version = "1.27.0"; }
  { name = "parser"; version = "3.3.8.0"; }
  { name = "pg"; version = "1.5.3"; }
  { name = "pg_search"; version = "2.3.6"; }
  { name = "pgvector"; version = "0.1.1"; }
  { name = "prism"; version = "1.4.0"; }
  { name = "procore-sift"; version = "1.0.0"; }
  { name = "pry"; version = "0.14.2"; }
  { name = "pry-rails"; version = "0.3.9"; }
  { name = "public_suffix"; version = "6.0.2"; }
  { name = "puma"; version = "6.4.3"; }
  { name = "pundit"; version = "2.3.0"; }
  { name = "raabro"; version = "1.4.0"; }
  { name = "racc"; version = "1.8.1"; }
  { name = "rack"; version = "3.2.3"; }
  { name = "rack-attack"; version = "6.7.0"; }
  { name = "rack-contrib"; version = "2.5.0"; }
  { name = "rack-cors"; version = "2.0.0"; }
  { name = "rack-mini-profiler"; version = "3.2.0"; }
  { name = "rack-protection"; version = "4.2.1"; }
  { name = "rack-proxy"; version = "0.7.7"; }
  { name = "rack-session"; version = "2.1.1"; }
  { name = "rack-test"; version = "2.1.0"; }
  { name = "rack-timeout"; version = "0.6.3"; }
  { name = "rackup"; version = "2.2.1"; }
  { name = "rails"; version = "7.1.5.2"; }
  { name = "rails-dom-testing"; version = "2.2.0"; }
  { name = "rails-html-sanitizer"; version = "1.6.1"; }
  { name = "railties"; version = "7.1.5.2"; }
  { name = "rainbow"; version = "3.1.1"; }
  { name = "rake"; version = "13.2.1"; }
  { name = "rb-fsevent"; version = "0.11.2"; }
  { name = "rb-inotify"; version = "0.10.1"; }
  { name = "redis"; version = "5.0.6"; }
  { name = "redis-client"; version = "0.22.2"; }
  { name = "redis-namespace"; version = "1.10.0"; }
  { name = "regexp_parser"; version = "2.10.0"; }
  { name = "reline"; version = "0.3.6"; }
  { name = "representable"; version = "3.2.0"; }
  { name = "request_store"; version = "1.5.1"; }
  { name = "responders"; version = "3.1.1"; }
  { name = "rest-client"; version = "2.1.0"; }
  { name = "retriable"; version = "3.1.2"; }
  { name = "reverse_markdown"; version = "2.1.1"; }
  { name = "rexml"; version = "3.4.4"; }
  { name = "rotp"; version = "6.3.0"; }
  { name = "rspec-core"; version = "3.13.0"; }
  { name = "rspec-expectations"; version = "3.13.2"; }
  { name = "rspec-mocks"; version = "3.13.1"; }
  { name = "rspec-rails"; version = "7.0.1"; }
  { name = "rspec-support"; version = "3.13.1"; }
  { name = "rspec_junit_formatter"; version = "0.6.0"; }
  { name = "rubocop"; version = "1.75.6"; }
  { name = "rubocop-ast"; version = "1.44.1"; }
  { name = "rubocop-factory_bot"; version = "2.27.1"; }
  { name = "rubocop-performance"; version = "1.25.0"; }
  { name = "rubocop-rails"; version = "2.32.0"; }
  { name = "rubocop-rspec"; version = "3.6.0"; }
  { name = "ruby-openai"; version = "7.3.1"; }
  { name = "ruby-progressbar"; version = "1.13.0"; }
  { name = "ruby-saml"; version = "1.18.1"; }
  { name = "ruby-vips"; version = "2.1.4"; }
  { name = "ruby2_keywords"; version = "0.0.5"; }
  { name = "ruby2ruby"; version = "2.5.0"; }
  { name = "ruby_llm"; version = "1.8.2"; }
  { name = "ruby_llm-schema"; version = "0.2.5"; }
  { name = "ruby_parser"; version = "3.20.0"; }
  { name = "sass"; version = "3.7.4"; }
  { name = "sass-listen"; version = "4.0.0"; }
  { name = "sassc"; version = "2.4.0"; }
  { name = "sassc-rails"; version = "2.1.2"; }
  { name = "scout_apm"; version = "5.3.3"; }
  { name = "scss_lint"; version = "0.60.0"; }
  { name = "searchkick"; version = "5.5.2"; }
  { name = "securerandom"; version = "0.4.1"; }
  { name = "seed_dump"; version = "3.3.1"; }
  { name = "selectize-rails"; version = "0.12.6"; }
  { name = "sentry-rails"; version = "5.19.0"; }
  { name = "sentry-ruby"; version = "5.19.0"; }
  { name = "sentry-sidekiq"; version = "5.19.0"; }
  { name = "sexp_processor"; version = "4.17.0"; }
  { name = "shopify_api"; version = "14.8.0"; }
  { name = "shoulda-matchers"; version = "5.3.0"; }
  { name = "sidekiq"; version = "7.3.1"; }
  { name = "sidekiq-cron"; version = "1.12.0"; }
  { name = "sidekiq_alive"; version = "2.5.0"; }
  { name = "signet"; version = "0.17.0"; }
  { name = "simplecov"; version = "0.22.0"; }
  { name = "simplecov-html"; version = "0.13.2"; }
  { name = "simplecov_json_formatter"; version = "0.1.4"; }
  { name = "slack-ruby-client"; version = "2.7.0"; }
  { name = "snaky_hash"; version = "2.0.1"; }
  { name = "sorbet-runtime"; version = "0.5.11934"; }
  { name = "spring"; version = "4.1.1"; }
  { name = "spring-watcher-listen"; version = "2.1.0"; }
  { name = "sprockets"; version = "4.2.1"; }
  { name = "sprockets-rails"; version = "3.4.2"; }
  { name = "squasher"; version = "0.7.2"; }
  { name = "stackprof"; version = "0.2.25"; }
  { name = "statsd-ruby"; version = "1.5.0"; }
  { name = "stripe"; version = "18.0.1"; }
  { name = "telephone_number"; version = "1.4.20"; }
  { name = "test-prof"; version = "1.2.1"; }
  { name = "thor"; version = "1.4.0"; }
  { name = "tidewave"; version = "0.2.0"; }
  { name = "tilt"; version = "2.3.0"; }
  { name = "time_diff"; version = "0.3.0"; }
  { name = "timeout"; version = "0.4.3"; }
  { name = "trailblazer-option"; version = "0.1.2"; }
  { name = "twilio-ruby"; version = "7.6.0"; }
  { name = "twitty"; version = "0.1.5"; }
  { name = "tzinfo"; version = "2.0.6"; }
  { name = "tzinfo-data"; version = "1.2023.3"; }
  { name = "uber"; version = "0.1.0"; }
  { name = "uglifier"; version = "4.2.0"; }
  { name = "unf"; version = "0.1.4"; }
  { name = "unf_ext"; version = "0.0.8.2"; }
  { name = "unicode-display_width"; version = "3.1.4"; }
  { name = "unicode-emoji"; version = "4.0.4"; }
  { name = "uniform_notifier"; version = "1.17.0"; }
  { name = "uri"; version = "1.0.4"; }
  { name = "uri_template"; version = "0.7.0"; }
  { name = "valid_email2"; version = "5.2.6"; }
  { name = "version_gem"; version = "1.1.4"; }
  { name = "vite_rails"; version = "3.0.17"; }
  { name = "vite_ruby"; version = "3.8.0"; }
  { name = "warden"; version = "1.2.9"; }
  { name = "web-console"; version = "4.2.1"; }
  { name = "web-push"; version = "3.0.1"; }
  { name = "webmock"; version = "3.23.1"; }
  { name = "websocket-driver"; version = "0.7.7"; }
  { name = "websocket-extensions"; version = "0.1.5"; }
  { name = "wisper"; version = "2.0.0"; }
  { name = "working_hours"; version = "1.4.1"; }
  { name = "zeitwerk"; version = "2.6.17"; }
  # git: azure-storage-ruby @ 9957cf899d33
  { name = "azure-storage-ruby"; git.rev = "9957cf899d33"; }
  # git: devise-secure_password @ adcc85fe1bab
  { name = "devise-secure_password"; git.rev = "adcc85fe1bab"; }
]
