#
# ╔═══════════════════════════════════════════════════════╗
# ║  GENERATED — do not edit.  Run bin/import to refresh ║
# ╚═══════════════════════════════════════════════════════╝
#
# FOREM — 381 gems
# Generated from Gemfile.lock
#
[
  { name = "actioncable"; version = "7.0.8.7"; }
  { name = "actionmailbox"; version = "7.0.8.7"; }
  { name = "actionmailer"; version = "7.0.8.7"; }
  { name = "actionpack"; version = "7.0.8.7"; }
  { name = "actiontext"; version = "7.0.8.7"; }
  { name = "actionview"; version = "7.0.8.7"; }
  { name = "active_record_union"; version = "1.3.0"; }
  { name = "activejob"; version = "7.0.8.7"; }
  { name = "activemodel"; version = "7.0.8.7"; }
  { name = "activerecord"; version = "7.0.8.7"; }
  { name = "activestorage"; version = "7.0.8.7"; }
  { name = "activesupport"; version = "7.0.8.7"; }
  { name = "acts-as-taggable-on"; version = "10.0.0"; }
  { name = "addressable"; version = "2.8.7"; }
  { name = "ahoy_email"; version = "2.2.0"; }
  { name = "ahoy_matey"; version = "5.0.2"; }
  { name = "algolia"; version = "2.3.4"; }
  { name = "algoliasearch-rails"; version = "2.3.2"; }
  { name = "amazing_print"; version = "1.6.0"; }
  { name = "ancestry"; version = "4.3.3"; }
  { name = "anyway_config"; version = "2.3.0"; }
  { name = "ast"; version = "2.4.2"; }
  { name = "aws-eventstream"; version = "1.3.0"; }
  { name = "aws-sigv4"; version = "1.8.0"; }
  { name = "aws_cf_signer"; version = "0.1.3"; }
  { name = "backport"; version = "1.2.0"; }
  { name = "base64"; version = "0.2.0"; }
  { name = "bcrypt"; version = "3.1.20"; }
  { name = "benchmark"; version = "0.3.0"; }
  { name = "benchmark-ips"; version = "2.10.0"; }
  { name = "better_errors"; version = "2.10.1"; }
  { name = "better_html"; version = "2.0.2"; }
  { name = "bigdecimal"; version = "3.1.7"; }
  { name = "bindex"; version = "0.8.1"; }
  { name = "blazer"; version = "2.6.5"; }
  { name = "bootsnap"; version = "1.18.3"; }
  { name = "brakeman"; version = "5.4.1"; }
  { name = "browser"; version = "5.3.1"; }
  { name = "brpoplpush-redis_script"; version = "0.1.3"; }
  { name = "buftok"; version = "0.2.0"; }
  { name = "builder"; version = "3.3.0"; }
  { name = "bullet"; version = "7.1.6"; }
  { name = "bundler-audit"; version = "0.9.1"; }
  { name = "capybara"; version = "3.37.1"; }
  { name = "carrierwave"; version = "2.2.6"; }
  { name = "carrierwave-bombshelter"; version = "0.2.2"; }
  { name = "cgi"; version = "0.3.6"; }
  { name = "chartkick"; version = "4.2.1"; }
  { name = "cld3"; version = "3.6.0"; }
  { name = "cloudinary"; version = "1.29.0"; }
  { name = "coderay"; version = "1.1.3"; }
  { name = "coffee-rails"; version = "5.0.0"; }
  { name = "coffee-script"; version = "2.4.1"; }
  { name = "coffee-script-source"; version = "1.12.2"; }
  { name = "concurrent-ruby"; version = "1.3.4"; }
  { name = "connection_pool"; version = "2.4.1"; }
  { name = "counter_culture"; version = "3.5.3"; }
  { name = "countries"; version = "5.7.1"; }
  { name = "crack"; version = "1.0.0"; }
  { name = "crass"; version = "1.0.6"; }
  { name = "cuprite"; version = "0.15"; }
  { name = "cypress-rails"; version = "0.7.0"; }
  { name = "dante"; version = "0.2.0"; }
  { name = "datadog-ci"; version = "0.3.0"; }
  { name = "date"; version = "3.3.4"; }
  { name = "ddtrace"; version = "1.16.2"; }
  { name = "dead_end"; version = "4.0.0"; }
  { name = "debase-ruby_core_source"; version = "3.2.2"; }
  { name = "debug"; version = "1.9.2"; }
  { name = "derailed_benchmarks"; version = "2.1.2"; }
  { name = "device_detector"; version = "1.1.1"; }
  { name = "devise"; version = "4.9.4"; }
  { name = "devise_invitable"; version = "2.0.9"; }
  { name = "diff-lcs"; version = "1.5.1"; }
  { name = "docile"; version = "1.4.0"; }
  { name = "dogstatsd-ruby"; version = "5.6.1"; }
  { name = "domain_name"; version = "0.6.20240107"; }
  { name = "dotenv"; version = "2.8.1"; }
  { name = "dotenv-rails"; version = "2.8.1"; }
  { name = "e2mmap"; version = "0.1.0"; }
  { name = "easy_translate"; version = "0.5.1"; }
  { name = "email_validator"; version = "2.2.4"; }
  { name = "emoji_regex"; version = "3.2.3"; }
  { name = "equalizer"; version = "0.0.11"; }
  { name = "erb_lint"; version = "0.5.0"; }
  { name = "erubi"; version = "1.13.1"; }
  { name = "et-orbi"; version = "1.2.11"; }
  { name = "excon"; version = "0.104.0"; }
  { name = "execjs"; version = "2.9.1"; }
  { name = "exifr"; version = "1.4.0"; }
  { name = "factory_bot"; version = "6.4.5"; }
  { name = "factory_bot_rails"; version = "6.4.3"; }
  { name = "faker"; version = "3.5.1"; }
  { name = "fakeredis"; version = "0.8.0"; }
  { name = "faraday"; version = "2.9.0"; }
  { name = "faraday-cookie_jar"; version = "0.0.7"; }
  { name = "faraday-encoding"; version = "0.0.5"; }
  { name = "faraday-follow_redirects"; version = "0.3.0"; }
  { name = "faraday-gzip"; version = "1.0.0"; }
  { name = "faraday-http-cache"; version = "2.5.0"; }
  { name = "faraday-net_http"; version = "3.1.0"; }
  { name = "faraday-net_http_persistent"; version = "2.1.0"; }
  { name = "faraday-retry"; version = "2.1.0"; }
  { name = "fastimage"; version = "2.3.1"; }
  { name = "fastly"; version = "3.0.2"; }
  { name = "feedjira"; version = "3.2.3"; }
  { name = "ferrum"; version = "0.14"; }
  { name = "ffi"; version = "1.16.3"; }
  { name = "ffi-compiler"; version = "1.0.1"; }
  { name = "field_test"; version = "0.6.0"; }
  { name = "flipper"; version = "0.25.4"; }
  { name = "flipper-active_record"; version = "0.25.4"; }
  { name = "flipper-active_support_cache_store"; version = "0.25.4"; }
  { name = "flipper-ui"; version = "0.25.4"; }
  { name = "fog-aws"; version = "3.21.0"; }
  { name = "fog-core"; version = "2.3.0"; }
  { name = "fog-json"; version = "1.2.0"; }
  { name = "fog-xml"; version = "0.1.4"; }
  { name = "formatador"; version = "1.1.0"; }
  { name = "front_matter_parser"; version = "1.0.1"; }
  { name = "fugit"; version = "1.11.1"; }
  { name = "gemoji"; version = "4.1.0"; }
  { name = "get_process_mem"; version = "0.2.7"; }
  { name = "gibbon"; version = "3.5.0"; }
  { name = "globalid"; version = "1.2.1"; }
  { name = "google-protobuf"; version = "3.25.5"; }
  { name = "guard"; version = "2.18.1"; }
  { name = "guard-compat"; version = "1.2.1"; }
  { name = "guard-rspec"; version = "4.7.3"; }
  { name = "hairtrigger"; version = "1.1.1"; }
  { name = "hashdiff"; version = "1.1.0"; }
  { name = "hashie"; version = "5.0.0"; }
  { name = "heapy"; version = "0.2.0"; }
  { name = "highline"; version = "2.1.0"; }
  { name = "hkdf"; version = "0.3.0"; }
  { name = "honeybadger"; version = "4.12.2"; }
  { name = "honeycomb-beeline"; version = "2.11.0"; }
  { name = "html_truncator"; version = "0.4.2"; }
  { name = "http"; version = "4.4.1"; }
  { name = "http-2"; version = "0.11.0"; }
  { name = "http-accept"; version = "1.7.0"; }
  { name = "http-cookie"; version = "1.0.5"; }
  { name = "http-form_data"; version = "2.3.0"; }
  { name = "http-parser"; version = "1.2.3"; }
  { name = "http_parser.rb"; version = "0.6.0"; }
  { name = "httparty"; version = "0.21.0"; }
  { name = "httpclient"; version = "2.8.3"; }
  { name = "hypershield"; version = "0.2.2"; }
  { name = "i18n"; version = "1.14.6"; }
  { name = "i18n-js"; version = "3.9.2"; }
  { name = "i18n-tasks"; version = "1.0.13"; }
  { name = "image_processing"; version = "1.12.2"; }
  { name = "imgproxy"; version = "2.1.0"; }
  { name = "inline_svg"; version = "1.9.0"; }
  { name = "io-console"; version = "0.7.2"; }
  { name = "irb"; version = "1.12.0"; }
  { name = "jaro_winkler"; version = "1.5.6"; }
  { name = "jbuilder"; version = "2.11.5"; }
  { name = "jquery-fileupload-rails"; version = "0.4.7"; }
  { name = "js-routes"; version = "2.2.8"; }
  { name = "jsbundling-rails"; version = "1.3.0"; }
  { name = "json"; version = "2.7.2"; }
  { name = "json-schema"; version = "2.8.1"; }
  { name = "jsonapi-serializer"; version = "2.2.0"; }
  { name = "jwt"; version = "2.8.1"; }
  { name = "kaminari"; version = "1.2.2"; }
  { name = "kaminari-actionview"; version = "1.2.2"; }
  { name = "kaminari-activerecord"; version = "1.2.2"; }
  { name = "kaminari-core"; version = "1.2.2"; }
  { name = "katex"; version = "0.9.0"; }
  { name = "knapsack_pro"; version = "5.7.0"; }
  { name = "kramdown"; version = "2.4.0"; }
  { name = "kramdown-parser-gfm"; version = "1.1.0"; }
  { name = "language_server-protocol"; version = "3.17.0.3"; }
  { name = "launchy"; version = "2.5.2"; }
  { name = "libdatadog"; version = "5.0.0.1.0"; }
  { name = "libddwaf"; version = "1.14.0.0.0"; }
  { name = "libhoney"; version = "2.2.0"; }
  { name = "liquid"; version = "5.4.0"; }
  { name = "listen"; version = "3.9.0"; }
  { name = "loofah"; version = "2.24.0"; }
  { name = "lumberjack"; version = "1.2.9"; }
  { name = "mail"; version = "2.8.1"; }
  { name = "marcel"; version = "1.0.4"; }
  { name = "matrix"; version = "0.4.2"; }
  { name = "memoizable"; version = "0.4.2"; }
  { name = "memory_profiler"; version = "1.0.1"; }
  { name = "metainspector"; version = "5.15.0"; }
  { name = "method_source"; version = "1.1.0"; }
  { name = "mime-types"; version = "3.5.2"; }
  { name = "mime-types-data"; version = "3.2024.0305"; }
  { name = "mini_histogram"; version = "0.3.1"; }
  { name = "mini_magick"; version = "4.13.2"; }
  { name = "mini_mime"; version = "1.1.5"; }
  { name = "mini_portile2"; version = "2.8.8"; }
  { name = "minitest"; version = "5.25.4"; }
  { name = "modis"; version = "4.0.1"; }
  { name = "msgpack"; version = "1.7.2"; }
  { name = "multi_json"; version = "1.15.0"; }
  { name = "multi_xml"; version = "0.7.1"; }
  { name = "multipart-post"; version = "2.2.3"; }
  { name = "nakayoshi_fork"; version = "0.0.4"; }
  { name = "naught"; version = "1.1.0"; }
  { name = "nenv"; version = "0.3.0"; }
  { name = "nesty"; version = "1.0.2"; }
  { name = "net-http"; version = "0.4.1"; }
  { name = "net-http-persistent"; version = "4.0.1"; }
  { name = "net-http2"; version = "0.18.4"; }
  { name = "net-imap"; version = "0.4.10"; }
  { name = "net-pop"; version = "0.1.2"; }
  { name = "net-protocol"; version = "0.2.2"; }
  { name = "net-smtp"; version = "0.4.0.1"; }
  { name = "netrc"; version = "0.11.0"; }
  { name = "nio4r"; version = "2.7.0"; }
  { name = "nokogiri"; version = "1.16.5"; }
  { name = "notiffany"; version = "0.1.3"; }
  { name = "oauth"; version = "0.5.10"; }
  { name = "oauth2"; version = "2.0.9"; }
  { name = "octokit"; version = "5.6.1"; }
  { name = "oj"; version = "3.16.3"; }
  { name = "omniauth"; version = "2.1.2"; }
  { name = "omniauth-apple"; version = "1.2.2"; }
  { name = "omniauth-facebook"; version = "9.0.0"; }
  { name = "omniauth-github"; version = "2.0.1"; }
  { name = "omniauth-google-oauth2"; version = "1.1.2"; }
  { name = "omniauth-oauth"; version = "1.2.0"; }
  { name = "omniauth-oauth2"; version = "1.8.0"; }
  { name = "omniauth-rails_csrf_protection"; version = "1.0.2"; }
  { name = "omniauth-twitter"; version = "1.4.0"; }
  { name = "orm_adapter"; version = "0.5.0"; }
  { name = "parallel"; version = "1.24.0"; }
  { name = "parser"; version = "3.3.1.0"; }
  { name = "pg"; version = "1.5.6"; }
  { name = "pg_query"; version = "4.2.3"; }
  { name = "pg_search"; version = "2.3.6"; }
  { name = "pghero"; version = "3.6.1"; }
  { name = "pry"; version = "0.14.2"; }
  { name = "pry-rails"; version = "0.3.9"; }
  { name = "psych"; version = "5.1.2"; }
  { name = "public_suffix"; version = "6.0.1"; }
  { name = "puma"; version = "5.6.9"; }
  { name = "pundit"; version = "2.3.1"; }
  { name = "pundit-matchers"; version = "1.9.0"; }
  { name = "raabro"; version = "1.4.0"; }
  { name = "racc"; version = "1.8.1"; }
  { name = "rack"; version = "2.2.10"; }
  { name = "rack-attack"; version = "6.7.0"; }
  { name = "rack-cors"; version = "1.1.1"; }
  { name = "rack-host-redirect"; version = "1.3.0"; }
  { name = "rack-protection"; version = "3.2.0"; }
  { name = "rack-session"; version = "1.0.2"; }
  { name = "rack-test"; version = "2.2.0"; }
  { name = "rack-timeout"; version = "0.6.3"; }
  { name = "rails"; version = "7.0.8.7"; }
  { name = "rails-controller-testing"; version = "1.0.5"; }
  { name = "rails-dom-testing"; version = "2.2.0"; }
  { name = "rails-html-sanitizer"; version = "1.6.1"; }
  { name = "rails-i18n"; version = "7.0.8"; }
  { name = "railties"; version = "7.0.8.7"; }
  { name = "rainbow"; version = "3.1.1"; }
  { name = "rake"; version = "13.2.1"; }
  { name = "ransack"; version = "3.2.1"; }
  { name = "rb-fsevent"; version = "0.11.2"; }
  { name = "rb-inotify"; version = "0.10.1"; }
  { name = "rbs"; version = "2.8.4"; }
  { name = "rdoc"; version = "6.6.3.1"; }
  { name = "recaptcha"; version = "5.16.0"; }
  { name = "redcarpet"; version = "3.6.0"; }
  { name = "redis"; version = "4.7.1"; }
  { name = "redis-actionpack"; version = "5.4.0"; }
  { name = "redis-rack"; version = "3.0.0"; }
  { name = "redis-store"; version = "1.10.0"; }
  { name = "regexp_parser"; version = "2.9.0"; }
  { name = "reline"; version = "0.5.3"; }
  { name = "request_store"; version = "1.6.0"; }
  { name = "responders"; version = "3.1.1"; }
  { name = "rest-client"; version = "2.1.0"; }
  { name = "reverse_markdown"; version = "2.1.1"; }
  { name = "rexml"; version = "3.4.0"; }
  { name = "rice"; version = "4.1.0"; }
  { name = "rolify"; version = "6.0.1"; }
  { name = "rouge"; version = "4.2.1"; }
  { name = "rpush"; version = "7.0.1"; }
  { name = "rpush-redis"; version = "1.2.0"; }
  { name = "rspec"; version = "3.12.0"; }
  { name = "rspec-core"; version = "3.12.3"; }
  { name = "rspec-expectations"; version = "3.12.4"; }
  { name = "rspec-mocks"; version = "3.12.7"; }
  { name = "rspec-rails"; version = "6.1.1"; }
  { name = "rspec-retry"; version = "0.6.2"; }
  { name = "rspec-support"; version = "3.12.2"; }
  { name = "rspec_junit_formatter"; version = "0.6.0"; }
  { name = "rss"; version = "0.2.9"; }
  { name = "rswag-specs"; version = "2.5.1"; }
  { name = "rubocop"; version = "1.63.4"; }
  { name = "rubocop-ast"; version = "1.31.2"; }
  { name = "rubocop-capybara"; version = "2.20.0"; }
  { name = "rubocop-factory_bot"; version = "2.25.1"; }
  { name = "rubocop-performance"; version = "1.21.0"; }
  { name = "rubocop-rails"; version = "2.24.1"; }
  { name = "rubocop-rspec"; version = "2.29.1"; }
  { name = "rubocop-rspec_rails"; version = "2.28.3"; }
  { name = "ruby-next-core"; version = "0.15.2"; }
  { name = "ruby-prof"; version = "1.7.0"; }
  { name = "ruby-progressbar"; version = "1.13.0"; }
  { name = "ruby-statistics"; version = "3.0.0"; }
  { name = "ruby-vips"; version = "2.2.1"; }
  { name = "ruby2ruby"; version = "2.5.0"; }
  { name = "ruby_parser"; version = "3.21.0"; }
  { name = "rubyzip"; version = "2.3.2"; }
  { name = "s3_direct_upload"; version = "0.1.7"; }
  { name = "safely_block"; version = "0.4.0"; }
  { name = "sanitize"; version = "6.0.2"; }
  { name = "sass"; version = "3.7.4"; }
  { name = "sass-listen"; version = "4.0.0"; }
  { name = "sass-rails"; version = "6.0.0"; }
  { name = "sassc"; version = "2.4.0"; }
  { name = "sassc-rails"; version = "2.1.2"; }
  { name = "sawyer"; version = "0.9.2"; }
  { name = "sax-machine"; version = "1.3.2"; }
  { name = "sexp_processor"; version = "4.17.1"; }
  { name = "shellany"; version = "0.0.1"; }
  { name = "shoulda-matchers"; version = "5.3.0"; }
  { name = "sidekiq"; version = "6.5.12"; }
  { name = "sidekiq-cron"; version = "1.12.0"; }
  { name = "sidekiq-unique-jobs"; version = "7.1.33"; }
  { name = "simple_oauth"; version = "0.3.1"; }
  { name = "simplecov"; version = "0.21.2"; }
  { name = "simplecov-html"; version = "0.12.3"; }
  { name = "simplecov_json_formatter"; version = "0.1.4"; }
  { name = "slack-notifier"; version = "2.4.0"; }
  { name = "smart_properties"; version = "1.17.0"; }
  { name = "snaky_hash"; version = "2.0.1"; }
  { name = "solargraph"; version = "0.50.0"; }
  { name = "solargraph-rails"; version = "0.3.1"; }
  { name = "sprockets"; version = "4.1.1"; }
  { name = "sprockets-rails"; version = "3.4.2"; }
  { name = "ssrf_filter"; version = "1.1.2"; }
  { name = "stackprof"; version = "0.2.26"; }
  { name = "sterile"; version = "1.0.26"; }
  { name = "stringio"; version = "3.1.0"; }
  { name = "stripe"; version = "5.55.0"; }
  { name = "stripe-ruby-mock"; version = "3.1.0.rc3"; }
  { name = "strong_migrations"; version = "1.8.0"; }
  { name = "terminal-table"; version = "3.0.2"; }
  { name = "terser"; version = "1.2.2"; }
  { name = "test-prof"; version = "1.3.3"; }
  { name = "thor"; version = "1.3.1"; }
  { name = "thread"; version = "0.2.2"; }
  { name = "thread_safe"; version = "0.3.6"; }
  { name = "tilt"; version = "2.3.0"; }
  { name = "timecop"; version = "0.9.8"; }
  { name = "timeout"; version = "0.4.1"; }
  { name = "twitter"; version = "7.0.0"; }
  { name = "tzinfo"; version = "2.0.6"; }
  { name = "unaccent"; version = "0.4.0"; }
  { name = "unicode-display_width"; version = "2.5.0"; }
  { name = "uniform_notifier"; version = "1.16.0"; }
  { name = "uri"; version = "0.13.0"; }
  { name = "validate_url"; version = "1.0.15"; }
  { name = "vault"; version = "0.18.2"; }
  { name = "vcr"; version = "6.3.1"; }
  { name = "version_gem"; version = "1.1.4"; }
  { name = "warden"; version = "1.2.9"; }
  { name = "warning"; version = "1.3.0"; }
  { name = "wcag_color_contrast"; version = "0.1.0"; }
  { name = "web-console"; version = "4.2.1"; }
  { name = "webmock"; version = "3.23.0"; }
  { name = "webpush"; version = "1.1.0"; }
  { name = "webrick"; version = "1.8.2"; }
  { name = "websocket-driver"; version = "0.7.6"; }
  { name = "websocket-extensions"; version = "0.1.5"; }
  { name = "with_model"; version = "2.1.7"; }
  { name = "xpath"; version = "3.2.0"; }
  { name = "yard"; version = "0.9.36"; }
  { name = "yard-activerecord"; version = "0.0.16"; }
  { name = "yard-activesupport-concern"; version = "0.0.1"; }
  { name = "zeitwerk"; version = "2.6.13"; }
  { name = "zlib"; version = "2.1.1"; }
  { name = "zonebie"; version = "0.6.1"; }
  # git: acts_as_follower @ 06393d3693a1
  { name = "acts_as_follower"; git.rev = "06393d3693a1"; }
]
