#
# ╔═══════════════════════════════════════════════════════╗
# ║  GENERATED — do not edit.  Run bin/import to refresh ║
# ╚═══════════════════════════════════════════════════════╝
#
# MASTODON — 350 gems
# Generated from Gemfile.lock
#
[
  { name = "actioncable"; version = "8.0.3"; }
  { name = "actionmailbox"; version = "8.0.3"; }
  { name = "actionmailer"; version = "8.0.3"; }
  { name = "actionpack"; version = "8.0.3"; }
  { name = "actiontext"; version = "8.0.3"; }
  { name = "actionview"; version = "8.0.3"; }
  { name = "active_model_serializers"; version = "0.10.16"; }
  { name = "activejob"; version = "8.0.3"; }
  { name = "activemodel"; version = "8.0.3"; }
  { name = "activerecord"; version = "8.0.3"; }
  { name = "activestorage"; version = "8.0.3"; }
  { name = "activesupport"; version = "8.0.3"; }
  { name = "addressable"; version = "2.8.8"; }
  { name = "aes_key_wrap"; version = "1.1.0"; }
  { name = "android_key_attestation"; version = "0.3.0"; }
  { name = "annotaterb"; version = "4.21.0"; }
  { name = "ast"; version = "2.4.3"; }
  { name = "attr_required"; version = "1.0.2"; }
  { name = "aws-eventstream"; version = "1.4.0"; }
  { name = "aws-partitions"; version = "1.1212.0"; }
  { name = "aws-sdk-core"; version = "3.242.0"; }
  { name = "aws-sdk-kms"; version = "1.121.0"; }
  { name = "aws-sdk-s3"; version = "1.213.0"; }
  { name = "aws-sigv4"; version = "1.12.1"; }
  { name = "azure-blob"; version = "0.5.9.1"; }
  { name = "base64"; version = "0.3.0"; }
  { name = "bcp47_spec"; version = "0.2.1"; }
  { name = "bcrypt"; version = "3.1.21"; }
  { name = "benchmark"; version = "0.5.0"; }
  { name = "better_errors"; version = "2.10.1"; }
  { name = "bigdecimal"; version = "3.3.1"; }
  { name = "bindata"; version = "2.5.1"; }
  { name = "binding_of_caller"; version = "1.0.1"; }
  { name = "blurhash"; version = "0.1.8"; }
  { name = "bootsnap"; version = "1.20.1"; }
  { name = "brakeman"; version = "8.0.2"; }
  { name = "browser"; version = "6.2.0"; }
  { name = "builder"; version = "3.3.0"; }
  { name = "bundler-audit"; version = "0.9.3"; }
  { name = "capybara"; version = "3.40.0"; }
  { name = "capybara-playwright-driver"; version = "0.5.7"; }
  { name = "case_transform"; version = "0.2"; }
  { name = "cbor"; version = "0.5.10.1"; }
  { name = "cgi"; version = "0.4.2"; }
  { name = "charlock_holmes"; version = "0.7.9"; }
  { name = "chewy"; version = "7.6.0"; }
  { name = "childprocess"; version = "5.1.0"; }
  { name = "chunky_png"; version = "1.4.0"; }
  { name = "climate_control"; version = "1.2.0"; }
  { name = "cocoon"; version = "1.2.15"; }
  { name = "color_diff"; version = "0.2"; }
  { name = "concurrent-ruby"; version = "1.3.6"; }
  { name = "connection_pool"; version = "2.5.5"; }
  { name = "cose"; version = "1.3.1"; }
  { name = "crack"; version = "1.0.1"; }
  { name = "crass"; version = "1.0.6"; }
  { name = "css_parser"; version = "1.21.1"; }
  { name = "csv"; version = "3.3.5"; }
  { name = "database_cleaner-active_record"; version = "2.2.2"; }
  { name = "database_cleaner-core"; version = "2.0.1"; }
  { name = "date"; version = "3.5.1"; }
  { name = "debug"; version = "1.11.1"; }
  { name = "debug_inspector"; version = "1.2.0"; }
  { name = "devise"; version = "5.0.0"; }
  { name = "devise-two-factor"; version = "6.4.0"; }
  { name = "devise_pam_authenticatable2"; version = "9.2.0"; }
  { name = "diff-lcs"; version = "1.6.2"; }
  { name = "discard"; version = "1.4.0"; }
  { name = "docile"; version = "1.4.1"; }
  { name = "domain_name"; version = "0.6.20240107"; }
  { name = "doorkeeper"; version = "5.8.2"; }
  { name = "dotenv"; version = "3.2.0"; }
  { name = "drb"; version = "2.2.3"; }
  { name = "dry-cli"; version = "1.3.0"; }
  { name = "elasticsearch"; version = "7.17.11"; }
  { name = "elasticsearch-api"; version = "7.17.11"; }
  { name = "elasticsearch-dsl"; version = "0.1.10"; }
  { name = "elasticsearch-transport"; version = "7.17.11"; }
  { name = "email_spec"; version = "2.3.0"; }
  { name = "email_validator"; version = "2.2.4"; }
  { name = "erb"; version = "6.0.1"; }
  { name = "erubi"; version = "1.13.1"; }
  { name = "et-orbi"; version = "1.4.0"; }
  { name = "excon"; version = "1.3.2"; }
  { name = "fabrication"; version = "3.0.0"; }
  { name = "faker"; version = "3.6.0"; }
  { name = "faraday"; version = "2.14.0"; }
  { name = "faraday-follow_redirects"; version = "0.5.0"; }
  { name = "faraday-httpclient"; version = "2.0.2"; }
  { name = "faraday-net_http"; version = "3.4.2"; }
  { name = "fast_blank"; version = "1.0.1"; }
  { name = "fastimage"; version = "2.4.0"; }
  { name = "ffi"; version = "1.17.3"; }
  { name = "ffi-compiler"; version = "1.3.2"; }
  { name = "flatware"; version = "2.3.4"; }
  { name = "flatware-rspec"; version = "2.3.4"; }
  { name = "fog-core"; version = "2.6.0"; }
  { name = "fog-json"; version = "1.2.0"; }
  { name = "fog-openstack"; version = "1.1.5"; }
  { name = "formatador"; version = "1.2.3"; }
  { name = "forwardable"; version = "1.4.0"; }
  { name = "fugit"; version = "1.12.1"; }
  { name = "globalid"; version = "1.3.0"; }
  { name = "google-protobuf"; version = "4.33.2"; }
  { name = "googleapis-common-protos-types"; version = "1.22.0"; }
  { name = "haml"; version = "7.2.0"; }
  { name = "haml-rails"; version = "3.0.0"; }
  { name = "haml_lint"; version = "0.69.0"; }
  { name = "hashdiff"; version = "1.2.1"; }
  { name = "hashie"; version = "5.1.0"; }
  { name = "hcaptcha"; version = "7.1.0"; }
  { name = "highline"; version = "3.1.2"; }
  { name = "hiredis"; version = "0.6.3"; }
  { name = "hiredis-client"; version = "0.26.4"; }
  { name = "hkdf"; version = "0.3.0"; }
  { name = "htmlentities"; version = "4.3.4"; }
  { name = "http"; version = "5.3.1"; }
  { name = "http-cookie"; version = "1.1.0"; }
  { name = "http-form_data"; version = "2.3.0"; }
  { name = "http_accept_language"; version = "2.1.1"; }
  { name = "httpclient"; version = "2.9.0"; }
  { name = "httplog"; version = "1.8.0"; }
  { name = "i18n"; version = "1.14.8"; }
  { name = "i18n-tasks"; version = "1.1.2"; }
  { name = "idn-ruby"; version = "0.1.5"; }
  { name = "inline_svg"; version = "1.10.0"; }
  { name = "io-console"; version = "0.8.2"; }
  { name = "irb"; version = "1.16.0"; }
  { name = "jd-paperclip-azure"; version = "3.0.0"; }
  { name = "jmespath"; version = "1.6.2"; }
  { name = "json"; version = "2.18.0"; }
  { name = "json-canonicalization"; version = "1.0.0"; }
  { name = "json-jwt"; version = "1.17.0"; }
  { name = "json-ld"; version = "3.3.2"; }
  { name = "json-ld-preloaded"; version = "3.3.2"; }
  { name = "json-schema"; version = "6.1.0"; }
  { name = "jsonapi-renderer"; version = "0.2.2"; }
  { name = "jwt"; version = "2.10.2"; }
  { name = "kaminari"; version = "1.2.2"; }
  { name = "kaminari-actionview"; version = "1.2.2"; }
  { name = "kaminari-activerecord"; version = "1.2.2"; }
  { name = "kaminari-core"; version = "1.2.2"; }
  { name = "kt-paperclip"; version = "7.3.0"; }
  { name = "language_server-protocol"; version = "3.17.0.5"; }
  { name = "launchy"; version = "3.1.1"; }
  { name = "letter_opener"; version = "1.10.0"; }
  { name = "letter_opener_web"; version = "3.0.0"; }
  { name = "link_header"; version = "0.0.8"; }
  { name = "lint_roller"; version = "1.1.0"; }
  { name = "linzer"; version = "0.7.7"; }
  { name = "llhttp-ffi"; version = "0.5.1"; }
  { name = "logger"; version = "1.7.0"; }
  { name = "lograge"; version = "0.14.0"; }
  { name = "loofah"; version = "2.25.0"; }
  { name = "mail"; version = "2.9.0"; }
  { name = "marcel"; version = "1.0.4"; }
  { name = "mario-redis-lock"; version = "1.2.1"; }
  { name = "matrix"; version = "0.4.3"; }
  { name = "memory_profiler"; version = "1.1.0"; }
  { name = "mime-types"; version = "3.7.0"; }
  { name = "mime-types-data"; version = "3.2026.0127"; }
  { name = "mini_mime"; version = "1.1.5"; }
  { name = "mini_portile2"; version = "2.8.9"; }
  { name = "minitest"; version = "6.0.1"; }
  { name = "msgpack"; version = "1.8.0"; }
  { name = "multi_json"; version = "1.19.1"; }
  { name = "mutex_m"; version = "0.3.0"; }
  { name = "net-http"; version = "0.6.0"; }
  { name = "net-imap"; version = "0.6.2"; }
  { name = "net-ldap"; version = "0.20.0"; }
  { name = "net-pop"; version = "0.1.2"; }
  { name = "net-protocol"; version = "0.2.2"; }
  { name = "net-smtp"; version = "0.5.1"; }
  { name = "nio4r"; version = "2.7.5"; }
  { name = "nokogiri"; version = "1.19.0"; }
  { name = "oj"; version = "3.16.14"; }
  { name = "omniauth"; version = "2.1.4"; }
  { name = "omniauth-cas"; version = "3.0.2"; }
  { name = "omniauth-rails_csrf_protection"; version = "2.0.1"; }
  { name = "omniauth-saml"; version = "2.2.4"; }
  { name = "omniauth_openid_connect"; version = "0.8.0"; }
  { name = "openid_connect"; version = "2.3.1"; }
  { name = "openssl"; version = "3.3.2"; }
  { name = "openssl-signature_algorithm"; version = "1.3.0"; }
  { name = "opentelemetry-api"; version = "1.7.0"; }
  { name = "opentelemetry-common"; version = "0.23.0"; }
  { name = "opentelemetry-exporter-otlp"; version = "0.31.1"; }
  { name = "opentelemetry-helpers-sql"; version = "0.3.0"; }
  { name = "opentelemetry-helpers-sql-processor"; version = "0.4.0"; }
  { name = "opentelemetry-instrumentation-action_mailer"; version = "0.6.1"; }
  { name = "opentelemetry-instrumentation-action_pack"; version = "0.15.1"; }
  { name = "opentelemetry-instrumentation-action_view"; version = "0.11.1"; }
  { name = "opentelemetry-instrumentation-active_job"; version = "0.10.1"; }
  { name = "opentelemetry-instrumentation-active_model_serializers"; version = "0.24.0"; }
  { name = "opentelemetry-instrumentation-active_record"; version = "0.11.1"; }
  { name = "opentelemetry-instrumentation-active_storage"; version = "0.3.1"; }
  { name = "opentelemetry-instrumentation-active_support"; version = "0.10.1"; }
  { name = "opentelemetry-instrumentation-base"; version = "0.25.0"; }
  { name = "opentelemetry-instrumentation-concurrent_ruby"; version = "0.24.0"; }
  { name = "opentelemetry-instrumentation-excon"; version = "0.27.0"; }
  { name = "opentelemetry-instrumentation-faraday"; version = "0.31.0"; }
  { name = "opentelemetry-instrumentation-http"; version = "0.28.0"; }
  { name = "opentelemetry-instrumentation-http_client"; version = "0.27.0"; }
  { name = "opentelemetry-instrumentation-net_http"; version = "0.27.0"; }
  { name = "opentelemetry-instrumentation-pg"; version = "0.35.0"; }
  { name = "opentelemetry-instrumentation-rack"; version = "0.29.0"; }
  { name = "opentelemetry-instrumentation-rails"; version = "0.39.1"; }
  { name = "opentelemetry-instrumentation-redis"; version = "0.28.0"; }
  { name = "opentelemetry-instrumentation-sidekiq"; version = "0.28.1"; }
  { name = "opentelemetry-registry"; version = "0.4.0"; }
  { name = "opentelemetry-sdk"; version = "1.10.0"; }
  { name = "opentelemetry-semantic_conventions"; version = "1.36.0"; }
  { name = "orm_adapter"; version = "0.5.0"; }
  { name = "ostruct"; version = "0.6.3"; }
  { name = "ox"; version = "2.14.23"; }
  { name = "parallel"; version = "1.27.0"; }
  { name = "parser"; version = "3.3.10.1"; }
  { name = "parslet"; version = "2.0.0"; }
  { name = "pastel"; version = "0.8.0"; }
  { name = "pg"; version = "1.6.3"; }
  { name = "pghero"; version = "3.7.0"; }
  { name = "playwright-ruby-client"; version = "1.57.1"; }
  { name = "pp"; version = "0.6.3"; }
  { name = "premailer"; version = "1.27.0"; }
  { name = "premailer-rails"; version = "1.12.0"; }
  { name = "prettyprint"; version = "0.2.0"; }
  { name = "prism"; version = "1.9.0"; }
  { name = "prometheus_exporter"; version = "2.3.1"; }
  { name = "propshaft"; version = "1.3.1"; }
  { name = "psych"; version = "5.3.1"; }
  { name = "public_suffix"; version = "7.0.2"; }
  { name = "puma"; version = "7.1.0"; }
  { name = "pundit"; version = "2.5.2"; }
  { name = "raabro"; version = "1.4.0"; }
  { name = "racc"; version = "1.8.1"; }
  { name = "rack"; version = "3.2.4"; }
  { name = "rack-attack"; version = "6.8.0"; }
  { name = "rack-cors"; version = "3.0.0"; }
  { name = "rack-oauth2"; version = "2.3.0"; }
  { name = "rack-protection"; version = "4.2.1"; }
  { name = "rack-proxy"; version = "0.7.7"; }
  { name = "rack-session"; version = "2.1.1"; }
  { name = "rack-test"; version = "2.2.0"; }
  { name = "rackup"; version = "2.3.1"; }
  { name = "rails"; version = "8.0.3"; }
  { name = "rails-dom-testing"; version = "2.3.0"; }
  { name = "rails-html-sanitizer"; version = "1.6.2"; }
  { name = "rails-i18n"; version = "8.1.0"; }
  { name = "railties"; version = "8.0.3"; }
  { name = "rainbow"; version = "3.1.1"; }
  { name = "rake"; version = "13.3.1"; }
  { name = "rdf"; version = "3.3.4"; }
  { name = "rdf-normalize"; version = "0.7.0"; }
  { name = "rdoc"; version = "7.1.0"; }
  { name = "readline"; version = "0.0.4"; }
  { name = "redcarpet"; version = "3.6.1"; }
  { name = "redis"; version = "4.8.1"; }
  { name = "redis-client"; version = "0.26.4"; }
  { name = "regexp_parser"; version = "2.11.3"; }
  { name = "reline"; version = "0.6.3"; }
  { name = "request_store"; version = "1.7.0"; }
  { name = "responders"; version = "3.2.0"; }
  { name = "rexml"; version = "3.4.4"; }
  { name = "rotp"; version = "6.3.0"; }
  { name = "rouge"; version = "4.7.0"; }
  { name = "rpam2"; version = "4.0.2"; }
  { name = "rqrcode"; version = "3.2.0"; }
  { name = "rqrcode_core"; version = "2.1.0"; }
  { name = "rspec"; version = "3.13.2"; }
  { name = "rspec-core"; version = "3.13.6"; }
  { name = "rspec-expectations"; version = "3.13.5"; }
  { name = "rspec-github"; version = "3.0.0"; }
  { name = "rspec-mocks"; version = "3.13.7"; }
  { name = "rspec-rails"; version = "8.0.2"; }
  { name = "rspec-sidekiq"; version = "5.2.0"; }
  { name = "rspec-support"; version = "3.13.6"; }
  { name = "rubocop"; version = "1.84.0"; }
  { name = "rubocop-ast"; version = "1.49.0"; }
  { name = "rubocop-capybara"; version = "2.22.1"; }
  { name = "rubocop-i18n"; version = "3.2.3"; }
  { name = "rubocop-performance"; version = "1.26.1"; }
  { name = "rubocop-rails"; version = "2.34.3"; }
  { name = "rubocop-rspec"; version = "3.9.0"; }
  { name = "rubocop-rspec_rails"; version = "2.32.0"; }
  { name = "ruby-prof"; version = "1.7.2"; }
  { name = "ruby-progressbar"; version = "1.13.0"; }
  { name = "ruby-saml"; version = "1.18.1"; }
  { name = "ruby-vips"; version = "2.3.0"; }
  { name = "rubyzip"; version = "3.2.2"; }
  { name = "rufus-scheduler"; version = "3.9.2"; }
  { name = "safety_net_attestation"; version = "0.5.0"; }
  { name = "sanitize"; version = "7.0.0"; }
  { name = "scenic"; version = "1.9.0"; }
  { name = "securerandom"; version = "0.4.1"; }
  { name = "shoulda-matchers"; version = "7.0.1"; }
  { name = "sidekiq"; version = "8.0.10"; }
  { name = "sidekiq-bulk"; version = "0.2.0"; }
  { name = "sidekiq-scheduler"; version = "6.0.1"; }
  { name = "sidekiq-unique-jobs"; version = "8.0.13"; }
  { name = "simple-navigation"; version = "4.4.1"; }
  { name = "simple_form"; version = "5.4.1"; }
  { name = "simplecov"; version = "0.22.0"; }
  { name = "simplecov-html"; version = "0.13.2"; }
  { name = "simplecov-lcov"; version = "0.9.0"; }
  { name = "simplecov_json_formatter"; version = "0.1.4"; }
  { name = "stackprof"; version = "0.2.27"; }
  { name = "starry"; version = "0.2.0"; }
  { name = "stoplight"; version = "5.7.0"; }
  { name = "stringio"; version = "3.2.0"; }
  { name = "strong_migrations"; version = "2.5.2"; }
  { name = "swd"; version = "2.0.3"; }
  { name = "sysexits"; version = "1.2.0"; }
  { name = "temple"; version = "0.10.4"; }
  { name = "terminal-table"; version = "4.0.0"; }
  { name = "terrapin"; version = "1.1.1"; }
  { name = "test-prof"; version = "1.5.2"; }
  { name = "thor"; version = "1.5.0"; }
  { name = "tilt"; version = "2.7.0"; }
  { name = "timeout"; version = "0.6.0"; }
  { name = "tpm-key_attestation"; version = "0.14.1"; }
  { name = "tsort"; version = "0.2.0"; }
  { name = "tty-color"; version = "0.6.0"; }
  { name = "tty-cursor"; version = "0.7.1"; }
  { name = "tty-prompt"; version = "0.23.1"; }
  { name = "tty-reader"; version = "0.9.0"; }
  { name = "tty-screen"; version = "0.8.2"; }
  { name = "twitter-text"; version = "3.1.0"; }
  { name = "tzinfo"; version = "2.0.6"; }
  { name = "tzinfo-data"; version = "1.2025.3"; }
  { name = "unf"; version = "0.1.4"; }
  { name = "unf_ext"; version = "0.0.9.1"; }
  { name = "unicode-display_width"; version = "3.2.0"; }
  { name = "unicode-emoji"; version = "4.2.0"; }
  { name = "uri"; version = "1.1.1"; }
  { name = "useragent"; version = "0.16.11"; }
  { name = "validate_url"; version = "1.0.15"; }
  { name = "vite_rails"; version = "3.0.20"; }
  { name = "vite_ruby"; version = "3.9.2"; }
  { name = "warden"; version = "1.2.9"; }
  { name = "webauthn"; version = "3.4.3"; }
  { name = "webfinger"; version = "2.1.3"; }
  { name = "webmock"; version = "3.26.1"; }
  { name = "webrick"; version = "1.9.2"; }
  { name = "websocket-driver"; version = "0.8.0"; }
  { name = "websocket-extensions"; version = "0.1.5"; }
  { name = "wisper"; version = "2.0.1"; }
  { name = "xorcist"; version = "1.1.3"; }
  { name = "xpath"; version = "3.2.0"; }
  { name = "zeitwerk"; version = "2.7.4"; }
  # git: webpush @ 9631ac63045c
  { name = "webpush"; git.rev = "9631ac63045c"; }
]
