#
# ╔═══════════════════════════════════════════════════════╗
# ║  GENERATED — do not edit.  Run bin/import to refresh ║
# ╚═══════════════════════════════════════════════════════╝
#
# REDMINE — 154 gems
# Generated from Gemfile.lock
#
[
  { name = "action_text-trix"; version = "2.1.16"; }
  { name = "actioncable"; version = "8.1.2"; }
  { name = "actionmailbox"; version = "8.1.2"; }
  { name = "actionmailer"; version = "8.1.2"; }
  { name = "actionpack"; version = "8.1.2"; }
  { name = "actionpack-xml_parser"; version = "2.0.1"; }
  { name = "actiontext"; version = "8.1.2"; }
  { name = "actionview"; version = "8.1.2"; }
  { name = "activejob"; version = "8.1.2"; }
  { name = "activemodel"; version = "8.1.2"; }
  { name = "activerecord"; version = "8.1.2"; }
  { name = "activestorage"; version = "8.1.2"; }
  { name = "activesupport"; version = "8.1.2"; }
  { name = "addressable"; version = "2.8.8"; }
  { name = "ast"; version = "2.4.3"; }
  { name = "base64"; version = "0.3.0"; }
  { name = "bcrypt"; version = "3.1.21"; }
  { name = "benchmark"; version = "0.5.0"; }
  { name = "bigdecimal"; version = "4.0.1"; }
  { name = "builder"; version = "3.3.0"; }
  { name = "bullet"; version = "8.1.0"; }
  { name = "bundle-audit"; version = "0.2.0"; }
  { name = "bundler-audit"; version = "0.9.3"; }
  { name = "capybara"; version = "3.40.0"; }
  { name = "chunky_png"; version = "1.4.0"; }
  { name = "commonmarker"; version = "2.6.3"; }
  { name = "concurrent-ruby"; version = "1.3.6"; }
  { name = "connection_pool"; version = "3.0.2"; }
  { name = "crass"; version = "1.0.6"; }
  { name = "css_parser"; version = "1.21.1"; }
  { name = "csv"; version = "3.3.5"; }
  { name = "date"; version = "3.5.1"; }
  { name = "debug"; version = "1.11.1"; }
  { name = "docile"; version = "1.4.1"; }
  { name = "domain_name"; version = "0.6.20240107"; }
  { name = "doorkeeper"; version = "5.8.2"; }
  { name = "doorkeeper-i18n"; version = "5.2.8"; }
  { name = "drb"; version = "2.2.3"; }
  { name = "erb"; version = "6.0.1"; }
  { name = "erubi"; version = "1.13.1"; }
  { name = "faraday"; version = "2.14.1"; }
  { name = "faraday-net_http"; version = "3.4.2"; }
  { name = "ffi"; version = "1.17.3"; }
  { name = "globalid"; version = "1.3.0"; }
  { name = "hashie"; version = "5.1.0"; }
  { name = "htmlentities"; version = "4.4.2"; }
  { name = "http-accept"; version = "1.7.0"; }
  { name = "http-cookie"; version = "1.1.0"; }
  { name = "i18n"; version = "1.14.8"; }
  { name = "importmap-rails"; version = "2.2.3"; }
  { name = "io-console"; version = "0.8.2"; }
  { name = "irb"; version = "1.16.0"; }
  { name = "json"; version = "2.18.1"; }
  { name = "jwt"; version = "3.1.2"; }
  { name = "language_server-protocol"; version = "3.17.0.5"; }
  { name = "lint_roller"; version = "1.1.0"; }
  { name = "listen"; version = "3.10.0"; }
  { name = "logger"; version = "1.7.0"; }
  { name = "loofah"; version = "2.25.0"; }
  { name = "mail"; version = "2.9.0"; }
  { name = "marcel"; version = "1.1.0"; }
  { name = "matrix"; version = "0.4.3"; }
  { name = "mime-types"; version = "3.7.0"; }
  { name = "mime-types-data"; version = "3.2026.0203"; }
  { name = "mini_magick"; version = "5.2.0"; }
  { name = "mini_mime"; version = "1.1.5"; }
  { name = "mini_portile2"; version = "2.8.9"; }
  { name = "minitest"; version = "6.0.1"; }
  { name = "mocha"; version = "3.0.1"; }
  { name = "multi_xml"; version = "0.8.1"; }
  { name = "net-http"; version = "0.9.1"; }
  { name = "net-imap"; version = "0.6.2"; }
  { name = "net-ldap"; version = "0.17.1"; }
  { name = "net-pop"; version = "0.1.2"; }
  { name = "net-protocol"; version = "0.2.2"; }
  { name = "net-smtp"; version = "0.5.1"; }
  { name = "netrc"; version = "0.11.0"; }
  { name = "nio4r"; version = "2.7.5"; }
  { name = "nokogiri"; version = "1.18.10"; }
  { name = "oauth2"; version = "2.0.18"; }
  { name = "ostruct"; version = "0.6.3"; }
  { name = "parallel"; version = "1.27.0"; }
  { name = "parser"; version = "3.3.10.1"; }
  { name = "pp"; version = "0.6.3"; }
  { name = "prettyprint"; version = "0.2.0"; }
  { name = "prism"; version = "1.9.0"; }
  { name = "propshaft"; version = "1.3.1"; }
  { name = "psych"; version = "5.3.1"; }
  { name = "public_suffix"; version = "7.0.2"; }
  { name = "puma"; version = "7.2.0"; }
  { name = "racc"; version = "1.8.1"; }
  { name = "rack"; version = "3.2.4"; }
  { name = "rack-session"; version = "2.1.1"; }
  { name = "rack-test"; version = "2.2.0"; }
  { name = "rackup"; version = "2.3.1"; }
  { name = "rails"; version = "8.1.2"; }
  { name = "rails-dom-testing"; version = "2.3.0"; }
  { name = "rails-html-sanitizer"; version = "1.6.2"; }
  { name = "railties"; version = "8.1.2"; }
  { name = "rainbow"; version = "3.1.1"; }
  { name = "rake"; version = "13.3.1"; }
  { name = "rake-compiler-dock"; version = "1.11.0"; }
  { name = "rb-fsevent"; version = "0.11.2"; }
  { name = "rb-inotify"; version = "0.11.1"; }
  { name = "rb_sys"; version = "0.9.124"; }
  { name = "rbpdf"; version = "1.21.4"; }
  { name = "rbpdf-font"; version = "1.19.1"; }
  { name = "rdoc"; version = "7.1.0"; }
  { name = "regexp_parser"; version = "2.11.3"; }
  { name = "reline"; version = "0.6.3"; }
  { name = "requestjs-rails"; version = "0.0.14"; }
  { name = "rest-client"; version = "2.1.0"; }
  { name = "rexml"; version = "3.4.4"; }
  { name = "roadie"; version = "5.2.1"; }
  { name = "roadie-rails"; version = "3.4.0"; }
  { name = "rotp"; version = "6.3.0"; }
  { name = "rouge"; version = "4.7.0"; }
  { name = "rqrcode"; version = "3.2.0"; }
  { name = "rqrcode_core"; version = "2.1.0"; }
  { name = "rubocop"; version = "1.81.7"; }
  { name = "rubocop-ast"; version = "1.49.0"; }
  { name = "rubocop-performance"; version = "1.26.1"; }
  { name = "rubocop-rails"; version = "2.33.4"; }
  { name = "ruby-progressbar"; version = "1.13.0"; }
  { name = "ruby2_keywords"; version = "0.0.5"; }
  { name = "rubyzip"; version = "3.2.2"; }
  { name = "sanitize"; version = "7.0.0"; }
  { name = "securerandom"; version = "0.4.1"; }
  { name = "selenium-webdriver"; version = "4.40.0"; }
  { name = "simplecov"; version = "0.22.0"; }
  { name = "simplecov-html"; version = "0.13.2"; }
  { name = "simplecov_json_formatter"; version = "0.1.4"; }
  { name = "snaky_hash"; version = "2.0.3"; }
  { name = "stimulus-rails"; version = "1.3.4"; }
  { name = "stringio"; version = "3.2.0"; }
  { name = "svg_optimizer"; version = "0.3.0"; }
  { name = "svg_sprite"; version = "1.0.3"; }
  { name = "thor"; version = "1.5.0"; }
  { name = "timeout"; version = "0.6.0"; }
  { name = "tsort"; version = "0.2.0"; }
  { name = "tzinfo"; version = "2.0.6"; }
  { name = "tzinfo-data"; version = "1.2025.3"; }
  { name = "unicode-display_width"; version = "3.2.0"; }
  { name = "unicode-emoji"; version = "4.2.0"; }
  { name = "uniform_notifier"; version = "1.18.0"; }
  { name = "uri"; version = "1.1.1"; }
  { name = "useragent"; version = "0.16.11"; }
  { name = "version_gem"; version = "1.1.9"; }
  { name = "websocket"; version = "1.2.11"; }
  { name = "websocket-driver"; version = "0.8.0"; }
  { name = "websocket-extensions"; version = "0.1.5"; }
  { name = "xpath"; version = "3.2.0"; }
  { name = "yard"; version = "0.9.38"; }
  { name = "zeitwerk"; version = "2.7.4"; }
]
