#
# ╔═══════════════════════════════════════════════════════╗
# ║  GENERATED — do not edit.  Run bin/import to refresh ║
# ╚═══════════════════════════════════════════════════════╝
#
# SOLIDUS — 200 gems
# Generated from Gemfile.lock
#
[
  { name = "action_text-trix"; version = "2.1.16"; }
  { name = "actioncable"; version = "8.1.2"; }
  { name = "actionmailbox"; version = "8.1.2"; }
  { name = "actionmailer"; version = "8.1.2"; }
  { name = "actionpack"; version = "8.1.2"; }
  { name = "actiontext"; version = "8.1.2"; }
  { name = "actionview"; version = "8.1.2"; }
  { name = "activejob"; version = "8.1.2"; }
  { name = "activemerchant"; version = "1.137.0"; }
  { name = "activemodel"; version = "8.1.2"; }
  { name = "activerecord"; version = "8.1.2"; }
  { name = "activestorage"; version = "8.1.2"; }
  { name = "activesupport"; version = "8.1.2"; }
  { name = "acts_as_list"; version = "1.2.6"; }
  { name = "addressable"; version = "2.8.8"; }
  { name = "ast"; version = "2.4.3"; }
  { name = "awesome_nested_set"; version = "3.9.0"; }
  { name = "axe-core-api"; version = "4.11.1"; }
  { name = "axe-core-capybara"; version = "4.11.1"; }
  { name = "axe-core-rspec"; version = "4.11.1"; }
  { name = "axiom-types"; version = "0.1.1"; }
  { name = "base64"; version = "0.3.0"; }
  { name = "benchmark"; version = "0.5.0"; }
  { name = "bigdecimal"; version = "4.0.1"; }
  { name = "blueprinter"; version = "1.2.1"; }
  { name = "builder"; version = "3.3.0"; }
  { name = "cancancan"; version = "3.6.1"; }
  { name = "capybara"; version = "3.40.0"; }
  { name = "capybara-screenshot"; version = "1.0.26"; }
  { name = "carmen"; version = "1.1.3"; }
  { name = "childprocess"; version = "5.1.0"; }
  { name = "climate_control"; version = "1.2.0"; }
  { name = "coercible"; version = "1.0.0"; }
  { name = "concurrent-ruby"; version = "1.3.6"; }
  { name = "connection_pool"; version = "3.0.2"; }
  { name = "crass"; version = "1.0.6"; }
  { name = "csv"; version = "3.3.5"; }
  { name = "database_cleaner"; version = "2.1.0"; }
  { name = "database_cleaner-active_record"; version = "2.2.2"; }
  { name = "database_cleaner-core"; version = "2.0.1"; }
  { name = "date"; version = "3.5.1"; }
  { name = "db-query-matchers"; version = "0.15.0"; }
  { name = "debug"; version = "1.11.1"; }
  { name = "descendants_tracker"; version = "0.0.4"; }
  { name = "diff-lcs"; version = "2.0.0.beta.2"; }
  { name = "discard"; version = "1.4.0"; }
  { name = "docile"; version = "1.4.1"; }
  { name = "drb"; version = "2.2.3"; }
  { name = "dumb_delegator"; version = "1.1.0"; }
  { name = "erb"; version = "6.0.1"; }
  { name = "erb-formatter"; version = "0.7.3"; }
  { name = "erubi"; version = "1.13.1"; }
  { name = "execjs"; version = "2.10.0"; }
  { name = "factory_bot"; version = "6.5.6"; }
  { name = "factory_bot_rails"; version = "6.5.1"; }
  { name = "faraday"; version = "2.14.1"; }
  { name = "faraday-net_http"; version = "3.4.2"; }
  { name = "faraday-retry"; version = "2.4.0"; }
  { name = "fast_sqlite"; version = "0.0.1"; }
  { name = "ffi"; version = "1.17.3"; }
  { name = "flickwerk"; version = "0.3.6"; }
  { name = "font-awesome-rails"; version = "4.7.0.9"; }
  { name = "friendly_id"; version = "5.6.0"; }
  { name = "geared_pagination"; version = "1.2.0"; }
  { name = "globalid"; version = "1.3.0"; }
  { name = "handlebars_assets"; version = "0.23.9"; }
  { name = "highline"; version = "3.1.2"; }
  { name = "i18n"; version = "1.14.8"; }
  { name = "i18n-tasks"; version = "0.9.37"; }
  { name = "ice_nine"; version = "0.11.2"; }
  { name = "image_processing"; version = "1.14.0"; }
  { name = "importmap-rails"; version = "2.2.3"; }
  { name = "io-console"; version = "0.8.2"; }
  { name = "irb"; version = "1.16.0"; }
  { name = "jbuilder"; version = "2.14.1"; }
  { name = "jquery-rails"; version = "4.6.1"; }
  { name = "json"; version = "2.18.1"; }
  { name = "kaminari"; version = "1.2.2"; }
  { name = "kaminari-actionview"; version = "1.2.2"; }
  { name = "kaminari-activerecord"; version = "1.2.2"; }
  { name = "kaminari-core"; version = "1.2.2"; }
  { name = "kt-paperclip"; version = "7.3.0"; }
  { name = "language_server-protocol"; version = "3.17.0.5"; }
  { name = "launchy"; version = "3.1.1"; }
  { name = "lint_roller"; version = "1.1.0"; }
  { name = "logger"; version = "1.7.0"; }
  { name = "loofah"; version = "2.25.0"; }
  { name = "mail"; version = "2.9.0"; }
  { name = "marcel"; version = "1.0.4"; }
  { name = "matrix"; version = "0.4.3"; }
  { name = "method_source"; version = "1.1.0"; }
  { name = "mime-types"; version = "3.7.0"; }
  { name = "mime-types-data"; version = "3.2026.0203"; }
  { name = "mini_magick"; version = "4.13.2"; }
  { name = "mini_mime"; version = "1.1.5"; }
  { name = "mini_portile2"; version = "2.8.9"; }
  { name = "minitest"; version = "6.0.1"; }
  { name = "monetize"; version = "1.13.0"; }
  { name = "money"; version = "6.19.0"; }
  { name = "net-http"; version = "0.9.1"; }
  { name = "net-imap"; version = "0.6.2"; }
  { name = "net-pop"; version = "0.1.2"; }
  { name = "net-protocol"; version = "0.2.2"; }
  { name = "net-smtp"; version = "0.5.1"; }
  { name = "nio4r"; version = "2.7.5"; }
  { name = "nokogiri"; version = "1.19.0"; }
  { name = "octokit"; version = "7.2.0"; }
  { name = "omnes"; version = "0.2.3"; }
  { name = "ostruct"; version = "0.6.3"; }
  { name = "parallel"; version = "1.27.0"; }
  { name = "parser"; version = "3.3.10.1"; }
  { name = "pp"; version = "0.6.3"; }
  { name = "prettier_print"; version = "1.2.1"; }
  { name = "prettyprint"; version = "0.2.0"; }
  { name = "prism"; version = "1.9.0"; }
  { name = "psych"; version = "5.3.1"; }
  { name = "public_suffix"; version = "7.0.2"; }
  { name = "puma"; version = "7.0.0.pre1"; }
  { name = "racc"; version = "1.8.1"; }
  { name = "rack"; version = "3.0.0.rc1"; }
  { name = "rack-session"; version = "1.0.2"; }
  { name = "rack-test"; version = "2.2.0"; }
  { name = "rackup"; version = "1.0.1"; }
  { name = "rails"; version = "8.1.2"; }
  { name = "rails-controller-testing"; version = "1.0.5"; }
  { name = "rails-dom-testing"; version = "2.3.0"; }
  { name = "rails-html-sanitizer"; version = "1.6.2"; }
  { name = "rails-i18n"; version = "8.1.0"; }
  { name = "railties"; version = "8.1.2"; }
  { name = "rainbow"; version = "3.1.1"; }
  { name = "rake"; version = "13.3.1"; }
  { name = "ransack"; version = "4.4.1"; }
  { name = "ransack-enum"; version = "1.0.0"; }
  { name = "rdoc"; version = "7.1.0"; }
  { name = "regexp_parser"; version = "2.11.3"; }
  { name = "reline"; version = "0.6.3"; }
  { name = "responders"; version = "3.2.0"; }
  { name = "rexml"; version = "3.4.4"; }
  { name = "rspec"; version = "3.13.2"; }
  { name = "rspec-activemodel-mocks"; version = "1.3.0"; }
  { name = "rspec-core"; version = "3.13.6"; }
  { name = "rspec-expectations"; version = "3.13.5"; }
  { name = "rspec-mocks"; version = "3.13.7"; }
  { name = "rspec-rails"; version = "6.0.4"; }
  { name = "rspec-retry"; version = "0.6.2"; }
  { name = "rspec-support"; version = "3.13.7"; }
  { name = "rspec_junit_formatter"; version = "0.6.0"; }
  { name = "rubocop"; version = "1.84.1"; }
  { name = "rubocop-ast"; version = "1.49.0"; }
  { name = "rubocop-performance"; version = "1.26.1"; }
  { name = "rubocop-rails"; version = "2.34.3"; }
  { name = "ruby-progressbar"; version = "1.13.0"; }
  { name = "ruby-vips"; version = "2.3.0"; }
  { name = "rubyzip"; version = "3.2.2"; }
  { name = "sassc"; version = "2.4.0"; }
  { name = "sassc-rails"; version = "2.1.2"; }
  { name = "sawyer"; version = "0.9.3"; }
  { name = "securerandom"; version = "0.4.1"; }
  { name = "selenium-webdriver"; version = "4.40.0"; }
  { name = "shoulda-matchers"; version = "5.3.0"; }
  { name = "simplecov"; version = "0.22.0"; }
  { name = "simplecov-cobertura"; version = "3.1.0"; }
  { name = "simplecov-html"; version = "0.13.2"; }
  { name = "simplecov_json_formatter"; version = "0.1.4"; }
  { name = "solidus_support"; version = "0.15.0"; }
  { name = "sprockets"; version = "4.2.2"; }
  { name = "sprockets-rails"; version = "3.5.2"; }
  { name = "sqlite3"; version = "2.9.0"; }
  { name = "state_machines"; version = "0.6.0"; }
  { name = "state_machines-activemodel"; version = "0.9.0"; }
  { name = "state_machines-activerecord"; version = "0.9.0"; }
  { name = "stimulus-rails"; version = "1.3.4"; }
  { name = "stringio"; version = "3.2.0"; }
  { name = "syntax_tree"; version = "6.3.0"; }
  { name = "tailwindcss-rails"; version = "3.3.2"; }
  { name = "tailwindcss-ruby"; version = "3.4.19"; }
  { name = "teaspoon"; version = "1.4.0"; }
  { name = "teaspoon-mocha"; version = "2.3.3"; }
  { name = "terminal-table"; version = "4.0.0"; }
  { name = "terrapin"; version = "1.1.1"; }
  { name = "thor"; version = "1.5.0"; }
  { name = "thread_safe"; version = "0.3.6"; }
  { name = "tilt"; version = "2.7.0"; }
  { name = "timeout"; version = "0.6.0"; }
  { name = "tsort"; version = "0.2.0"; }
  { name = "turbo-rails"; version = "2.0.23"; }
  { name = "tzinfo"; version = "2.0.6"; }
  { name = "unicode-display_width"; version = "3.2.0"; }
  { name = "unicode-emoji"; version = "4.2.0"; }
  { name = "uri"; version = "1.1.1"; }
  { name = "useragent"; version = "0.16.11"; }
  { name = "view_component"; version = "3.24.0"; }
  { name = "virtus"; version = "2.0.0"; }
  { name = "webrick"; version = "1.9.2"; }
  { name = "websocket"; version = "1.2.11"; }
  { name = "websocket-driver"; version = "0.8.0"; }
  { name = "websocket-extensions"; version = "0.1.5"; }
  { name = "xpath"; version = "3.2.0"; }
  { name = "yard"; version = "0.9.38"; }
  { name = "zeitwerk"; version = "2.7.4"; }
]
