# node-basic — generated by onix. Do not edit.
{ pkgs ? import <nixpkgs> { config = {}; overlays = []; }, nodejs ? pkgs.nodejs_22 }:
let
  buildNpm = import ./build-npm.nix { inherit pkgs nodejs; };
  buildPackageByName = name:
    let
      versions = import (./node + "/${name}.nix");
      version = pkgs.lib.last (builtins.attrNames versions);
      spec = versions.${version};
    in buildNpm (spec // { pkgName = name; });
  npmConfig = import ./npm-config.nix {
    inherit pkgs nodejs;
    overlayDir = ../overlays/node;
    nodeDir = ./node;
    buildPackageFn = buildPackageByName;
  };

  build = name: version:
    let
      safeName = builtins.replaceStrings ["/" "@"] ["--" ""] name;
      versions = import (./node + "/${safeName}.nix");
      spec = versions.${version};
      config = npmConfig.${name} or {};
    in buildNpm (spec // {
      pkgName = name;
      hasNative = (spec.hasNative or false) || (config ? deps && config.deps != []);
      nativeBuildInputs = config.deps or [];
      buildFlags = config.buildFlags or "";
      beforeBuild = config.beforeBuild or "";
      afterBuild = config.afterBuild or "";
    } // (if config ? buildPhase then { inherit (config) buildPhase; } else {})
      // (if config ? postInstall then { inherit (config) postInstall; } else {})
      // (if config ? skip then { inherit (config) skip; } else {})
      // (if config ? buildPackages then { inherit (config) buildPackages; } else {}));

  packages = {
    "@esbuild/aix-ppc64@0.24.2" = build "@esbuild/aix-ppc64" "0.24.2";
    "@esbuild/android-arm@0.24.2" = build "@esbuild/android-arm" "0.24.2";
    "@esbuild/android-arm64@0.24.2" = build "@esbuild/android-arm64" "0.24.2";
    "@esbuild/android-x64@0.24.2" = build "@esbuild/android-x64" "0.24.2";
    "@esbuild/darwin-arm64@0.24.2" = build "@esbuild/darwin-arm64" "0.24.2";
    "@esbuild/darwin-x64@0.24.2" = build "@esbuild/darwin-x64" "0.24.2";
    "@esbuild/freebsd-arm64@0.24.2" = build "@esbuild/freebsd-arm64" "0.24.2";
    "@esbuild/freebsd-x64@0.24.2" = build "@esbuild/freebsd-x64" "0.24.2";
    "@esbuild/linux-arm@0.24.2" = build "@esbuild/linux-arm" "0.24.2";
    "@esbuild/linux-arm64@0.24.2" = build "@esbuild/linux-arm64" "0.24.2";
    "@esbuild/linux-ia32@0.24.2" = build "@esbuild/linux-ia32" "0.24.2";
    "@esbuild/linux-loong64@0.24.2" = build "@esbuild/linux-loong64" "0.24.2";
    "@esbuild/linux-mips64el@0.24.2" = build "@esbuild/linux-mips64el" "0.24.2";
    "@esbuild/linux-ppc64@0.24.2" = build "@esbuild/linux-ppc64" "0.24.2";
    "@esbuild/linux-riscv64@0.24.2" = build "@esbuild/linux-riscv64" "0.24.2";
    "@esbuild/linux-s390x@0.24.2" = build "@esbuild/linux-s390x" "0.24.2";
    "@esbuild/linux-x64@0.24.2" = build "@esbuild/linux-x64" "0.24.2";
    "@esbuild/netbsd-arm64@0.24.2" = build "@esbuild/netbsd-arm64" "0.24.2";
    "@esbuild/netbsd-x64@0.24.2" = build "@esbuild/netbsd-x64" "0.24.2";
    "@esbuild/openbsd-arm64@0.24.2" = build "@esbuild/openbsd-arm64" "0.24.2";
    "@esbuild/openbsd-x64@0.24.2" = build "@esbuild/openbsd-x64" "0.24.2";
    "@esbuild/sunos-x64@0.24.2" = build "@esbuild/sunos-x64" "0.24.2";
    "@esbuild/win32-arm64@0.24.2" = build "@esbuild/win32-arm64" "0.24.2";
    "@esbuild/win32-ia32@0.24.2" = build "@esbuild/win32-ia32" "0.24.2";
    "@esbuild/win32-x64@0.24.2" = build "@esbuild/win32-x64" "0.24.2";
    "@types/node@22.13.1" = build "@types/node" "22.13.1";
    "accepts@1.3.8" = build "accepts" "1.3.8";
    "array-flatten@1.1.1" = build "array-flatten" "1.1.1";
    "base64-js@1.5.1" = build "base64-js" "1.5.1";
    "better-sqlite3@11.8.1" = build "better-sqlite3" "11.8.1";
    "bindings@1.5.0" = build "bindings" "1.5.0";
    "bl@4.1.0" = build "bl" "4.1.0";
    "body-parser@1.20.3" = build "body-parser" "1.20.3";
    "buffer@5.7.1" = build "buffer" "5.7.1";
    "bytes@3.1.2" = build "bytes" "3.1.2";
    "call-bind-apply-helpers@1.0.2" = build "call-bind-apply-helpers" "1.0.2";
    "call-bound@1.0.4" = build "call-bound" "1.0.4";
    "chownr@1.1.4" = build "chownr" "1.1.4";
    "content-disposition@0.5.4" = build "content-disposition" "0.5.4";
    "content-type@1.0.5" = build "content-type" "1.0.5";
    "cookie@0.7.1" = build "cookie" "0.7.1";
    "cookie-signature@1.0.6" = build "cookie-signature" "1.0.6";
    "debug@2.6.9" = build "debug" "2.6.9";
    "decompress-response@6.0.0" = build "decompress-response" "6.0.0";
    "deep-extend@0.6.0" = build "deep-extend" "0.6.0";
    "depd@2.0.0" = build "depd" "2.0.0";
    "destroy@1.2.0" = build "destroy" "1.2.0";
    "detect-libc@2.1.2" = build "detect-libc" "2.1.2";
    "dunder-proto@1.0.1" = build "dunder-proto" "1.0.1";
    "ee-first@1.1.1" = build "ee-first" "1.1.1";
    "encodeurl@1.0.2" = build "encodeurl" "1.0.2";
    "encodeurl@2.0.0" = build "encodeurl" "2.0.0";
    "end-of-stream@1.4.5" = build "end-of-stream" "1.4.5";
    "es-define-property@1.0.1" = build "es-define-property" "1.0.1";
    "es-errors@1.3.0" = build "es-errors" "1.3.0";
    "es-object-atoms@1.1.1" = build "es-object-atoms" "1.1.1";
    "esbuild@0.24.2" = build "esbuild" "0.24.2";
    "escape-html@1.0.3" = build "escape-html" "1.0.3";
    "etag@1.8.1" = build "etag" "1.8.1";
    "expand-template@2.0.3" = build "expand-template" "2.0.3";
    "express@4.21.2" = build "express" "4.21.2";
    "file-uri-to-path@1.0.0" = build "file-uri-to-path" "1.0.0";
    "finalhandler@1.3.1" = build "finalhandler" "1.3.1";
    "forwarded@0.2.0" = build "forwarded" "0.2.0";
    "fresh@0.5.2" = build "fresh" "0.5.2";
    "fs-constants@1.0.0" = build "fs-constants" "1.0.0";
    "function-bind@1.1.2" = build "function-bind" "1.1.2";
    "get-intrinsic@1.3.0" = build "get-intrinsic" "1.3.0";
    "get-proto@1.0.1" = build "get-proto" "1.0.1";
    "github-from-package@0.0.0" = build "github-from-package" "0.0.0";
    "gopd@1.2.0" = build "gopd" "1.2.0";
    "has-symbols@1.1.0" = build "has-symbols" "1.1.0";
    "hasown@2.0.2" = build "hasown" "2.0.2";
    "http-errors@2.0.0" = build "http-errors" "2.0.0";
    "iconv-lite@0.4.24" = build "iconv-lite" "0.4.24";
    "ieee754@1.2.1" = build "ieee754" "1.2.1";
    "inherits@2.0.4" = build "inherits" "2.0.4";
    "ini@1.3.8" = build "ini" "1.3.8";
    "ipaddr.js@1.9.1" = build "ipaddr.js" "1.9.1";
    "math-intrinsics@1.1.0" = build "math-intrinsics" "1.1.0";
    "media-typer@0.3.0" = build "media-typer" "0.3.0";
    "merge-descriptors@1.0.3" = build "merge-descriptors" "1.0.3";
    "methods@1.1.2" = build "methods" "1.1.2";
    "mime@1.6.0" = build "mime" "1.6.0";
    "mime-db@1.52.0" = build "mime-db" "1.52.0";
    "mime-types@2.1.35" = build "mime-types" "2.1.35";
    "mimic-response@3.1.0" = build "mimic-response" "3.1.0";
    "minimist@1.2.8" = build "minimist" "1.2.8";
    "mkdirp-classic@0.5.3" = build "mkdirp-classic" "0.5.3";
    "ms@2.0.0" = build "ms" "2.0.0";
    "ms@2.1.3" = build "ms" "2.1.3";
    "napi-build-utils@2.0.0" = build "napi-build-utils" "2.0.0";
    "negotiator@0.6.3" = build "negotiator" "0.6.3";
    "node-abi@3.87.0" = build "node-abi" "3.87.0";
    "object-inspect@1.13.4" = build "object-inspect" "1.13.4";
    "on-finished@2.4.1" = build "on-finished" "2.4.1";
    "once@1.4.0" = build "once" "1.4.0";
    "parseurl@1.3.3" = build "parseurl" "1.3.3";
    "path-to-regexp@0.1.12" = build "path-to-regexp" "0.1.12";
    "picocolors@1.1.1" = build "picocolors" "1.1.1";
    "prebuild-install@7.1.3" = build "prebuild-install" "7.1.3";
    "proxy-addr@2.0.7" = build "proxy-addr" "2.0.7";
    "pump@3.0.3" = build "pump" "3.0.3";
    "qs@6.13.0" = build "qs" "6.13.0";
    "range-parser@1.2.1" = build "range-parser" "1.2.1";
    "raw-body@2.5.2" = build "raw-body" "2.5.2";
    "rc@1.2.8" = build "rc" "1.2.8";
    "readable-stream@3.6.2" = build "readable-stream" "3.6.2";
    "safe-buffer@5.2.1" = build "safe-buffer" "5.2.1";
    "safer-buffer@2.1.2" = build "safer-buffer" "2.1.2";
    "semver@7.7.1" = build "semver" "7.7.1";
    "send@0.19.0" = build "send" "0.19.0";
    "serve-static@1.16.2" = build "serve-static" "1.16.2";
    "setprototypeof@1.2.0" = build "setprototypeof" "1.2.0";
    "side-channel@1.1.0" = build "side-channel" "1.1.0";
    "side-channel-list@1.0.0" = build "side-channel-list" "1.0.0";
    "side-channel-map@1.0.1" = build "side-channel-map" "1.0.1";
    "side-channel-weakmap@1.0.2" = build "side-channel-weakmap" "1.0.2";
    "simple-concat@1.0.1" = build "simple-concat" "1.0.1";
    "simple-get@4.0.1" = build "simple-get" "4.0.1";
    "statuses@2.0.1" = build "statuses" "2.0.1";
    "string_decoder@1.3.0" = build "string_decoder" "1.3.0";
    "strip-json-comments@2.0.1" = build "strip-json-comments" "2.0.1";
    "tar-fs@2.1.4" = build "tar-fs" "2.1.4";
    "tar-stream@2.2.0" = build "tar-stream" "2.2.0";
    "toidentifier@1.0.1" = build "toidentifier" "1.0.1";
    "tunnel-agent@0.6.0" = build "tunnel-agent" "0.6.0";
    "type-is@1.6.18" = build "type-is" "1.6.18";
    "typescript@5.7.3" = build "typescript" "5.7.3";
    "undici-types@6.20.0" = build "undici-types" "6.20.0";
    "unpipe@1.0.0" = build "unpipe" "1.0.0";
    "util-deprecate@1.0.2" = build "util-deprecate" "1.0.2";
    "utils-merge@1.0.1" = build "utils-merge" "1.0.1";
    "vary@1.1.2" = build "vary" "1.1.2";
    "wrappy@1.0.2" = build "wrappy" "1.0.2";
  };

  packageDir = pkgs.runCommand "node-basic-packages" {} ''
    mkdir -p $out
    mkdir -p "$out/@esbuild"
    mkdir -p "$out/@types"
    ln -s ${packages."@esbuild/aix-ppc64@0.24.2"} "$out/@esbuild/aix-ppc64@0.24.2"
    ln -s ${packages."@esbuild/android-arm@0.24.2"} "$out/@esbuild/android-arm@0.24.2"
    ln -s ${packages."@esbuild/android-arm64@0.24.2"} "$out/@esbuild/android-arm64@0.24.2"
    ln -s ${packages."@esbuild/android-x64@0.24.2"} "$out/@esbuild/android-x64@0.24.2"
    ln -s ${packages."@esbuild/darwin-arm64@0.24.2"} "$out/@esbuild/darwin-arm64@0.24.2"
    ln -s ${packages."@esbuild/darwin-x64@0.24.2"} "$out/@esbuild/darwin-x64@0.24.2"
    ln -s ${packages."@esbuild/freebsd-arm64@0.24.2"} "$out/@esbuild/freebsd-arm64@0.24.2"
    ln -s ${packages."@esbuild/freebsd-x64@0.24.2"} "$out/@esbuild/freebsd-x64@0.24.2"
    ln -s ${packages."@esbuild/linux-arm@0.24.2"} "$out/@esbuild/linux-arm@0.24.2"
    ln -s ${packages."@esbuild/linux-arm64@0.24.2"} "$out/@esbuild/linux-arm64@0.24.2"
    ln -s ${packages."@esbuild/linux-ia32@0.24.2"} "$out/@esbuild/linux-ia32@0.24.2"
    ln -s ${packages."@esbuild/linux-loong64@0.24.2"} "$out/@esbuild/linux-loong64@0.24.2"
    ln -s ${packages."@esbuild/linux-mips64el@0.24.2"} "$out/@esbuild/linux-mips64el@0.24.2"
    ln -s ${packages."@esbuild/linux-ppc64@0.24.2"} "$out/@esbuild/linux-ppc64@0.24.2"
    ln -s ${packages."@esbuild/linux-riscv64@0.24.2"} "$out/@esbuild/linux-riscv64@0.24.2"
    ln -s ${packages."@esbuild/linux-s390x@0.24.2"} "$out/@esbuild/linux-s390x@0.24.2"
    ln -s ${packages."@esbuild/linux-x64@0.24.2"} "$out/@esbuild/linux-x64@0.24.2"
    ln -s ${packages."@esbuild/netbsd-arm64@0.24.2"} "$out/@esbuild/netbsd-arm64@0.24.2"
    ln -s ${packages."@esbuild/netbsd-x64@0.24.2"} "$out/@esbuild/netbsd-x64@0.24.2"
    ln -s ${packages."@esbuild/openbsd-arm64@0.24.2"} "$out/@esbuild/openbsd-arm64@0.24.2"
    ln -s ${packages."@esbuild/openbsd-x64@0.24.2"} "$out/@esbuild/openbsd-x64@0.24.2"
    ln -s ${packages."@esbuild/sunos-x64@0.24.2"} "$out/@esbuild/sunos-x64@0.24.2"
    ln -s ${packages."@esbuild/win32-arm64@0.24.2"} "$out/@esbuild/win32-arm64@0.24.2"
    ln -s ${packages."@esbuild/win32-ia32@0.24.2"} "$out/@esbuild/win32-ia32@0.24.2"
    ln -s ${packages."@esbuild/win32-x64@0.24.2"} "$out/@esbuild/win32-x64@0.24.2"
    ln -s ${packages."@types/node@22.13.1"} "$out/@types/node@22.13.1"
    ln -s ${packages."accepts@1.3.8"} "$out/accepts@1.3.8"
    ln -s ${packages."array-flatten@1.1.1"} "$out/array-flatten@1.1.1"
    ln -s ${packages."base64-js@1.5.1"} "$out/base64-js@1.5.1"
    ln -s ${packages."better-sqlite3@11.8.1"} "$out/better-sqlite3@11.8.1"
    ln -s ${packages."bindings@1.5.0"} "$out/bindings@1.5.0"
    ln -s ${packages."bl@4.1.0"} "$out/bl@4.1.0"
    ln -s ${packages."body-parser@1.20.3"} "$out/body-parser@1.20.3"
    ln -s ${packages."buffer@5.7.1"} "$out/buffer@5.7.1"
    ln -s ${packages."bytes@3.1.2"} "$out/bytes@3.1.2"
    ln -s ${packages."call-bind-apply-helpers@1.0.2"} "$out/call-bind-apply-helpers@1.0.2"
    ln -s ${packages."call-bound@1.0.4"} "$out/call-bound@1.0.4"
    ln -s ${packages."chownr@1.1.4"} "$out/chownr@1.1.4"
    ln -s ${packages."content-disposition@0.5.4"} "$out/content-disposition@0.5.4"
    ln -s ${packages."content-type@1.0.5"} "$out/content-type@1.0.5"
    ln -s ${packages."cookie@0.7.1"} "$out/cookie@0.7.1"
    ln -s ${packages."cookie-signature@1.0.6"} "$out/cookie-signature@1.0.6"
    ln -s ${packages."debug@2.6.9"} "$out/debug@2.6.9"
    ln -s ${packages."decompress-response@6.0.0"} "$out/decompress-response@6.0.0"
    ln -s ${packages."deep-extend@0.6.0"} "$out/deep-extend@0.6.0"
    ln -s ${packages."depd@2.0.0"} "$out/depd@2.0.0"
    ln -s ${packages."destroy@1.2.0"} "$out/destroy@1.2.0"
    ln -s ${packages."detect-libc@2.1.2"} "$out/detect-libc@2.1.2"
    ln -s ${packages."dunder-proto@1.0.1"} "$out/dunder-proto@1.0.1"
    ln -s ${packages."ee-first@1.1.1"} "$out/ee-first@1.1.1"
    ln -s ${packages."encodeurl@1.0.2"} "$out/encodeurl@1.0.2"
    ln -s ${packages."encodeurl@2.0.0"} "$out/encodeurl@2.0.0"
    ln -s ${packages."end-of-stream@1.4.5"} "$out/end-of-stream@1.4.5"
    ln -s ${packages."es-define-property@1.0.1"} "$out/es-define-property@1.0.1"
    ln -s ${packages."es-errors@1.3.0"} "$out/es-errors@1.3.0"
    ln -s ${packages."es-object-atoms@1.1.1"} "$out/es-object-atoms@1.1.1"
    ln -s ${packages."esbuild@0.24.2"} "$out/esbuild@0.24.2"
    ln -s ${packages."escape-html@1.0.3"} "$out/escape-html@1.0.3"
    ln -s ${packages."etag@1.8.1"} "$out/etag@1.8.1"
    ln -s ${packages."expand-template@2.0.3"} "$out/expand-template@2.0.3"
    ln -s ${packages."express@4.21.2"} "$out/express@4.21.2"
    ln -s ${packages."file-uri-to-path@1.0.0"} "$out/file-uri-to-path@1.0.0"
    ln -s ${packages."finalhandler@1.3.1"} "$out/finalhandler@1.3.1"
    ln -s ${packages."forwarded@0.2.0"} "$out/forwarded@0.2.0"
    ln -s ${packages."fresh@0.5.2"} "$out/fresh@0.5.2"
    ln -s ${packages."fs-constants@1.0.0"} "$out/fs-constants@1.0.0"
    ln -s ${packages."function-bind@1.1.2"} "$out/function-bind@1.1.2"
    ln -s ${packages."get-intrinsic@1.3.0"} "$out/get-intrinsic@1.3.0"
    ln -s ${packages."get-proto@1.0.1"} "$out/get-proto@1.0.1"
    ln -s ${packages."github-from-package@0.0.0"} "$out/github-from-package@0.0.0"
    ln -s ${packages."gopd@1.2.0"} "$out/gopd@1.2.0"
    ln -s ${packages."has-symbols@1.1.0"} "$out/has-symbols@1.1.0"
    ln -s ${packages."hasown@2.0.2"} "$out/hasown@2.0.2"
    ln -s ${packages."http-errors@2.0.0"} "$out/http-errors@2.0.0"
    ln -s ${packages."iconv-lite@0.4.24"} "$out/iconv-lite@0.4.24"
    ln -s ${packages."ieee754@1.2.1"} "$out/ieee754@1.2.1"
    ln -s ${packages."inherits@2.0.4"} "$out/inherits@2.0.4"
    ln -s ${packages."ini@1.3.8"} "$out/ini@1.3.8"
    ln -s ${packages."ipaddr.js@1.9.1"} "$out/ipaddr.js@1.9.1"
    ln -s ${packages."math-intrinsics@1.1.0"} "$out/math-intrinsics@1.1.0"
    ln -s ${packages."media-typer@0.3.0"} "$out/media-typer@0.3.0"
    ln -s ${packages."merge-descriptors@1.0.3"} "$out/merge-descriptors@1.0.3"
    ln -s ${packages."methods@1.1.2"} "$out/methods@1.1.2"
    ln -s ${packages."mime@1.6.0"} "$out/mime@1.6.0"
    ln -s ${packages."mime-db@1.52.0"} "$out/mime-db@1.52.0"
    ln -s ${packages."mime-types@2.1.35"} "$out/mime-types@2.1.35"
    ln -s ${packages."mimic-response@3.1.0"} "$out/mimic-response@3.1.0"
    ln -s ${packages."minimist@1.2.8"} "$out/minimist@1.2.8"
    ln -s ${packages."mkdirp-classic@0.5.3"} "$out/mkdirp-classic@0.5.3"
    ln -s ${packages."ms@2.0.0"} "$out/ms@2.0.0"
    ln -s ${packages."ms@2.1.3"} "$out/ms@2.1.3"
    ln -s ${packages."napi-build-utils@2.0.0"} "$out/napi-build-utils@2.0.0"
    ln -s ${packages."negotiator@0.6.3"} "$out/negotiator@0.6.3"
    ln -s ${packages."node-abi@3.87.0"} "$out/node-abi@3.87.0"
    ln -s ${packages."object-inspect@1.13.4"} "$out/object-inspect@1.13.4"
    ln -s ${packages."on-finished@2.4.1"} "$out/on-finished@2.4.1"
    ln -s ${packages."once@1.4.0"} "$out/once@1.4.0"
    ln -s ${packages."parseurl@1.3.3"} "$out/parseurl@1.3.3"
    ln -s ${packages."path-to-regexp@0.1.12"} "$out/path-to-regexp@0.1.12"
    ln -s ${packages."picocolors@1.1.1"} "$out/picocolors@1.1.1"
    ln -s ${packages."prebuild-install@7.1.3"} "$out/prebuild-install@7.1.3"
    ln -s ${packages."proxy-addr@2.0.7"} "$out/proxy-addr@2.0.7"
    ln -s ${packages."pump@3.0.3"} "$out/pump@3.0.3"
    ln -s ${packages."qs@6.13.0"} "$out/qs@6.13.0"
    ln -s ${packages."range-parser@1.2.1"} "$out/range-parser@1.2.1"
    ln -s ${packages."raw-body@2.5.2"} "$out/raw-body@2.5.2"
    ln -s ${packages."rc@1.2.8"} "$out/rc@1.2.8"
    ln -s ${packages."readable-stream@3.6.2"} "$out/readable-stream@3.6.2"
    ln -s ${packages."safe-buffer@5.2.1"} "$out/safe-buffer@5.2.1"
    ln -s ${packages."safer-buffer@2.1.2"} "$out/safer-buffer@2.1.2"
    ln -s ${packages."semver@7.7.1"} "$out/semver@7.7.1"
    ln -s ${packages."send@0.19.0"} "$out/send@0.19.0"
    ln -s ${packages."serve-static@1.16.2"} "$out/serve-static@1.16.2"
    ln -s ${packages."setprototypeof@1.2.0"} "$out/setprototypeof@1.2.0"
    ln -s ${packages."side-channel@1.1.0"} "$out/side-channel@1.1.0"
    ln -s ${packages."side-channel-list@1.0.0"} "$out/side-channel-list@1.0.0"
    ln -s ${packages."side-channel-map@1.0.1"} "$out/side-channel-map@1.0.1"
    ln -s ${packages."side-channel-weakmap@1.0.2"} "$out/side-channel-weakmap@1.0.2"
    ln -s ${packages."simple-concat@1.0.1"} "$out/simple-concat@1.0.1"
    ln -s ${packages."simple-get@4.0.1"} "$out/simple-get@4.0.1"
    ln -s ${packages."statuses@2.0.1"} "$out/statuses@2.0.1"
    ln -s ${packages."string_decoder@1.3.0"} "$out/string_decoder@1.3.0"
    ln -s ${packages."strip-json-comments@2.0.1"} "$out/strip-json-comments@2.0.1"
    ln -s ${packages."tar-fs@2.1.4"} "$out/tar-fs@2.1.4"
    ln -s ${packages."tar-stream@2.2.0"} "$out/tar-stream@2.2.0"
    ln -s ${packages."toidentifier@1.0.1"} "$out/toidentifier@1.0.1"
    ln -s ${packages."tunnel-agent@0.6.0"} "$out/tunnel-agent@0.6.0"
    ln -s ${packages."type-is@1.6.18"} "$out/type-is@1.6.18"
    ln -s ${packages."typescript@5.7.3"} "$out/typescript@5.7.3"
    ln -s ${packages."undici-types@6.20.0"} "$out/undici-types@6.20.0"
    ln -s ${packages."unpipe@1.0.0"} "$out/unpipe@1.0.0"
    ln -s ${packages."util-deprecate@1.0.2"} "$out/util-deprecate@1.0.2"
    ln -s ${packages."utils-merge@1.0.1"} "$out/utils-merge@1.0.1"
    ln -s ${packages."vary@1.1.2"} "$out/vary@1.1.2"
    ln -s ${packages."wrappy@1.0.2"} "$out/wrappy@1.0.2"
  '';
in packages // { inherit packageDir; }
