# node-basic — generated by onix. Do not edit.
{ pkgs ? import <nixpkgs> {}, nodejs ? pkgs.nodejs_22 }:
let
  buildNpm = import ./build-npm.nix { inherit pkgs nodejs; };
  buildPackageByName = name:
    let
      versions = import (./node + "/${name}.nix");
      version = builtins.head (builtins.attrNames versions);
      spec = versions.${version};
    in buildNpm (spec // { pkgName = name; });
  npmConfig = import ./npm-config.nix {
    inherit pkgs nodejs;
    overlayDir = ../overlays;
    nodeDir = ./node;
    buildPackageFn = buildPackageByName;
  };

  build = name: version:
    let
      safeName = builtins.replaceStrings ["/" "@"] ["--" ""] name;
      versions = import (./node + "/${safeName}.nix");
      spec = versions.${version};
      config = npmConfig.${name} or {};
    in buildNpm (spec // {
      pkgName = name;
      hasNative = spec.hasNative or false;
      nativeBuildInputs = config.deps or [];
      buildFlags = config.buildFlags or "";
      beforeBuild = config.beforeBuild or "";
      afterBuild = config.afterBuild or "";
    } // (if config ? buildPhase then { inherit (config) buildPhase; } else {})
      // (if config ? postInstall then { inherit (config) postInstall; } else {})
      // (if config ? skip then { inherit (config) skip; } else {})
      // (if config ? buildPackages then { inherit (config) buildPackages; } else {}));

  packages = {
    "@esbuild/aix-ppc64" = build "@esbuild/aix-ppc64" "0.24.2";
    "@esbuild/android-arm" = build "@esbuild/android-arm" "0.24.2";
    "@esbuild/android-arm64" = build "@esbuild/android-arm64" "0.24.2";
    "@esbuild/android-x64" = build "@esbuild/android-x64" "0.24.2";
    "@esbuild/darwin-arm64" = build "@esbuild/darwin-arm64" "0.24.2";
    "@esbuild/darwin-x64" = build "@esbuild/darwin-x64" "0.24.2";
    "@esbuild/freebsd-arm64" = build "@esbuild/freebsd-arm64" "0.24.2";
    "@esbuild/freebsd-x64" = build "@esbuild/freebsd-x64" "0.24.2";
    "@esbuild/linux-arm" = build "@esbuild/linux-arm" "0.24.2";
    "@esbuild/linux-arm64" = build "@esbuild/linux-arm64" "0.24.2";
    "@esbuild/linux-ia32" = build "@esbuild/linux-ia32" "0.24.2";
    "@esbuild/linux-loong64" = build "@esbuild/linux-loong64" "0.24.2";
    "@esbuild/linux-mips64el" = build "@esbuild/linux-mips64el" "0.24.2";
    "@esbuild/linux-ppc64" = build "@esbuild/linux-ppc64" "0.24.2";
    "@esbuild/linux-riscv64" = build "@esbuild/linux-riscv64" "0.24.2";
    "@esbuild/linux-s390x" = build "@esbuild/linux-s390x" "0.24.2";
    "@esbuild/linux-x64" = build "@esbuild/linux-x64" "0.24.2";
    "@esbuild/netbsd-arm64" = build "@esbuild/netbsd-arm64" "0.24.2";
    "@esbuild/netbsd-x64" = build "@esbuild/netbsd-x64" "0.24.2";
    "@esbuild/openbsd-arm64" = build "@esbuild/openbsd-arm64" "0.24.2";
    "@esbuild/openbsd-x64" = build "@esbuild/openbsd-x64" "0.24.2";
    "@esbuild/sunos-x64" = build "@esbuild/sunos-x64" "0.24.2";
    "@esbuild/win32-arm64" = build "@esbuild/win32-arm64" "0.24.2";
    "@esbuild/win32-ia32" = build "@esbuild/win32-ia32" "0.24.2";
    "@esbuild/win32-x64" = build "@esbuild/win32-x64" "0.24.2";
    "@types/node" = build "@types/node" "22.13.1";
    esbuild = build "esbuild" "0.24.2";
    ms = build "ms" "2.1.3";
    picocolors = build "picocolors" "1.1.1";
    semver = build "semver" "7.7.1";
    typescript = build "typescript" "5.7.3";
    "undici-types" = build "undici-types" "6.20.0";
  };

  nodeModules = pkgs.buildEnv {
    name = "node-basic-node-modules";
    paths = builtins.attrValues packages;
  };
in packages // {
  inherit nodeModules;
  devShell = { buildInputs ? [], shellHook ? "", ... }@args:
    pkgs.mkShell (builtins.removeAttrs args ["buildInputs" "shellHook"] // {
      name = "node-basic-devshell";
      buildInputs = [ nodejs ] ++ buildInputs;
      shellHook = ''
        export NODE_PATH="${nodeModules}"
      '' + shellHook;
    });
}
