# remix-v3 — generated by onix. Do not edit.
{ pkgs ? import <nixpkgs> { config = {}; overlays = []; }, nodejs ? pkgs.nodejs_22 }:
let
  buildNpm = import ./build-npm.nix { inherit pkgs nodejs; };
  buildPackageByName = name:
    let
      versions = import (./node + "/${name}.nix");
      version = pkgs.lib.last (builtins.attrNames versions);
      spec = versions.${version};
    in buildNpm (spec // { pkgName = name; });
  npmConfig = import ./npm-config.nix {
    inherit pkgs nodejs;
    overlayDir = ../overlays/node;
    nodeDir = ./node;
    buildPackageFn = buildPackageByName;
  };

  build = name: version:
    let
      safeName = builtins.replaceStrings ["/" "@"] ["--" ""] name;
      versions = import (./node + "/${safeName}.nix");
      spec = versions.${version};
      config = npmConfig.${name} or {};
    in buildNpm (spec // {
      pkgName = name;
      hasNative = (spec.hasNative or false) || (config ? deps && config.deps != []);
      nativeBuildInputs = config.deps or [];
      buildFlags = config.buildFlags or "";
      beforeBuild = config.beforeBuild or "";
      afterBuild = config.afterBuild or "";
    } // (if config ? buildPhase then { inherit (config) buildPhase; } else {})
      // (if config ? postInstall then { inherit (config) postInstall; } else {})
      // (if config ? skip then { inherit (config) skip; } else {})
      // (if config ? buildPackages then { inherit (config) buildPackages; } else {}));

  packages = {
    "@edgefirst-dev/data@0.0.4" = build "@edgefirst-dev/data" "0.0.4";
    "@mjackson/headers@0.10.0" = build "@mjackson/headers" "0.10.0";
    "@oslojs/asn1@1.0.0" = build "@oslojs/asn1" "1.0.0";
    "@oslojs/binary@1.0.0" = build "@oslojs/binary" "1.0.0";
    "@oslojs/crypto@1.0.1" = build "@oslojs/crypto" "1.0.1";
    "@oslojs/encoding@0.4.1" = build "@oslojs/encoding" "0.4.1";
    "@oslojs/encoding@1.1.0" = build "@oslojs/encoding" "1.1.0";
    "@oslojs/jwt@0.2.0" = build "@oslojs/jwt" "0.2.0";
    "@remix-run/dom@0.0.0-experimental-remix-jam.6" = build "@remix-run/dom" "0.0.0-experimental-remix-jam.6";
    "@remix-run/events@0.0.0-experimental-remix-jam.5" = build "@remix-run/events" "0.0.0-experimental-remix-jam.5";
    "@remix-run/fetch-router@0.6.0" = build "@remix-run/fetch-router" "0.6.0";
    "@remix-run/form-data-parser@0.11.0" = build "@remix-run/form-data-parser" "0.11.0";
    "@remix-run/headers@0.12.0" = build "@remix-run/headers" "0.12.0";
    "@remix-run/multipart-parser@0.11.0" = build "@remix-run/multipart-parser" "0.11.0";
    "@remix-run/route-pattern@0.14.0" = build "@remix-run/route-pattern" "0.14.0";
    "@remix-run/style@0.0.0-experimental-remix-jam.5" = build "@remix-run/style" "0.0.0-experimental-remix-jam.5";
    "@tanstack/query-core@5.90.20" = build "@tanstack/query-core" "5.90.20";
    "@types/bun@1.3.9" = build "@types/bun" "1.3.9";
    "@types/node@25.2.3" = build "@types/node" "25.2.3";
    "alien-signals@3.1.2" = build "alien-signals" "3.1.2";
    "arctic@3.7.0" = build "arctic" "3.7.0";
    "bun-types@1.3.9" = build "bun-types" "1.3.9";
    "remix-auth@4.2.0" = build "remix-auth" "4.2.0";
    "remix-auth-oauth2@3.4.1" = build "remix-auth-oauth2" "3.4.1";
    "typescript@5.9.3" = build "typescript" "5.9.3";
    "undici-types@7.16.0" = build "undici-types" "7.16.0";
  };

  packageDir = pkgs.runCommand "remix-v3-packages" {} ''
    mkdir -p $out
    mkdir -p "$out/@edgefirst-dev"
    mkdir -p "$out/@mjackson"
    mkdir -p "$out/@oslojs"
    mkdir -p "$out/@remix-run"
    mkdir -p "$out/@tanstack"
    mkdir -p "$out/@types"
    ln -s ${packages."@edgefirst-dev/data@0.0.4"} "$out/@edgefirst-dev/data@0.0.4"
    ln -s ${packages."@mjackson/headers@0.10.0"} "$out/@mjackson/headers@0.10.0"
    ln -s ${packages."@oslojs/asn1@1.0.0"} "$out/@oslojs/asn1@1.0.0"
    ln -s ${packages."@oslojs/binary@1.0.0"} "$out/@oslojs/binary@1.0.0"
    ln -s ${packages."@oslojs/crypto@1.0.1"} "$out/@oslojs/crypto@1.0.1"
    ln -s ${packages."@oslojs/encoding@0.4.1"} "$out/@oslojs/encoding@0.4.1"
    ln -s ${packages."@oslojs/encoding@1.1.0"} "$out/@oslojs/encoding@1.1.0"
    ln -s ${packages."@oslojs/jwt@0.2.0"} "$out/@oslojs/jwt@0.2.0"
    ln -s ${packages."@remix-run/dom@0.0.0-experimental-remix-jam.6"} "$out/@remix-run/dom@0.0.0-experimental-remix-jam.6"
    ln -s ${packages."@remix-run/events@0.0.0-experimental-remix-jam.5"} "$out/@remix-run/events@0.0.0-experimental-remix-jam.5"
    ln -s ${packages."@remix-run/fetch-router@0.6.0"} "$out/@remix-run/fetch-router@0.6.0"
    ln -s ${packages."@remix-run/form-data-parser@0.11.0"} "$out/@remix-run/form-data-parser@0.11.0"
    ln -s ${packages."@remix-run/headers@0.12.0"} "$out/@remix-run/headers@0.12.0"
    ln -s ${packages."@remix-run/multipart-parser@0.11.0"} "$out/@remix-run/multipart-parser@0.11.0"
    ln -s ${packages."@remix-run/route-pattern@0.14.0"} "$out/@remix-run/route-pattern@0.14.0"
    ln -s ${packages."@remix-run/style@0.0.0-experimental-remix-jam.5"} "$out/@remix-run/style@0.0.0-experimental-remix-jam.5"
    ln -s ${packages."@tanstack/query-core@5.90.20"} "$out/@tanstack/query-core@5.90.20"
    ln -s ${packages."@types/bun@1.3.9"} "$out/@types/bun@1.3.9"
    ln -s ${packages."@types/node@25.2.3"} "$out/@types/node@25.2.3"
    ln -s ${packages."alien-signals@3.1.2"} "$out/alien-signals@3.1.2"
    ln -s ${packages."arctic@3.7.0"} "$out/arctic@3.7.0"
    ln -s ${packages."bun-types@1.3.9"} "$out/bun-types@1.3.9"
    ln -s ${packages."remix-auth@4.2.0"} "$out/remix-auth@4.2.0"
    ln -s ${packages."remix-auth-oauth2@3.4.1"} "$out/remix-auth-oauth2@3.4.1"
    ln -s ${packages."typescript@5.9.3"} "$out/typescript@5.9.3"
    ln -s ${packages."undici-types@7.16.0"} "$out/undici-types@7.16.0"
  '';
in packages // { inherit packageDir; }
