# remix-v3 — generated by onix. Do not edit.
#
# pnpm-style node_modules layout:
#   node_modules/.pnpm/<name>@<version>/node_modules/<name>  ← package contents
#   node_modules/.pnpm/<name>@<version>/node_modules/<dep>   ← symlink to dep's .pnpm entry
#   node_modules/<name>                                      ← symlink to .pnpm entry
#
{ pkgs ? import <nixpkgs> {}, nodejs ? pkgs.nodejs_22 }:
let
  buildNpm = import ./build-npm.nix { inherit pkgs nodejs; };
  buildPackageByName = name:
    let
      versions = import (./node + "/${name}.nix");
      version = builtins.head (builtins.attrNames versions);
      spec = versions.${version};
    in buildNpm (spec // { pkgName = name; });
  npmConfig = import ./npm-config.nix {
    inherit pkgs nodejs;
    overlayDir = ../overlays;
    nodeDir = ./node;
    buildPackageFn = buildPackageByName;
  };

  build = name: version:
    let
      safeName = builtins.replaceStrings ["/" "@"] ["--" ""] name;
      versions = import (./node + "/${safeName}.nix");
      spec = versions.${version};
      config = npmConfig.${name} or {};
    in buildNpm (spec // {
      pkgName = name;
      hasNative = (spec.hasNative or false) || (config ? deps && config.deps != []);
      nativeBuildInputs = config.deps or [];
      buildFlags = config.buildFlags or "";
      beforeBuild = config.beforeBuild or "";
      afterBuild = config.afterBuild or "";
    } // (if config ? buildPhase then { inherit (config) buildPhase; } else {})
      // (if config ? postInstall then { inherit (config) postInstall; } else {})
      // (if config ? skip then { inherit (config) skip; } else {})
      // (if config ? buildPackages then { inherit (config) buildPackages; } else {}));

  # Per-package derivations (used by .pnpm/ entries)
  packages = {
    "@edgefirst-dev/data@0.0.4" = build "@edgefirst-dev/data" "0.0.4";
    "@mjackson/headers@0.10.0" = build "@mjackson/headers" "0.10.0";
    "@oslojs/asn1@1.0.0" = build "@oslojs/asn1" "1.0.0";
    "@oslojs/binary@1.0.0" = build "@oslojs/binary" "1.0.0";
    "@oslojs/crypto@1.0.1" = build "@oslojs/crypto" "1.0.1";
    "@oslojs/encoding@0.4.1" = build "@oslojs/encoding" "0.4.1";
    "@oslojs/encoding@1.1.0" = build "@oslojs/encoding" "1.1.0";
    "@oslojs/jwt@0.2.0" = build "@oslojs/jwt" "0.2.0";
    "@remix-run/dom@0.0.0-experimental-remix-jam.6" = build "@remix-run/dom" "0.0.0-experimental-remix-jam.6";
    "@remix-run/events@0.0.0-experimental-remix-jam.5" = build "@remix-run/events" "0.0.0-experimental-remix-jam.5";
    "@remix-run/fetch-router@0.6.0" = build "@remix-run/fetch-router" "0.6.0";
    "@remix-run/form-data-parser@0.11.0" = build "@remix-run/form-data-parser" "0.11.0";
    "@remix-run/headers@0.12.0" = build "@remix-run/headers" "0.12.0";
    "@remix-run/multipart-parser@0.11.0" = build "@remix-run/multipart-parser" "0.11.0";
    "@remix-run/route-pattern@0.14.0" = build "@remix-run/route-pattern" "0.14.0";
    "@remix-run/style@0.0.0-experimental-remix-jam.5" = build "@remix-run/style" "0.0.0-experimental-remix-jam.5";
    "@tanstack/query-core@5.90.20" = build "@tanstack/query-core" "5.90.20";
    "@types/bun@1.3.9" = build "@types/bun" "1.3.9";
    "@types/node@25.2.3" = build "@types/node" "25.2.3";
    "alien-signals@3.1.2" = build "alien-signals" "3.1.2";
    "arctic@3.7.0" = build "arctic" "3.7.0";
    "bun-types@1.3.9" = build "bun-types" "1.3.9";
    "remix-auth-oauth2@3.4.1" = build "remix-auth-oauth2" "3.4.1";
    "remix-auth@4.2.0" = build "remix-auth" "4.2.0";
    "typescript@5.9.3" = build "typescript" "5.9.3";
    "undici-types@7.16.0" = build "undici-types" "7.16.0";
  };

  # pnpm-style .pnpm/ virtual store + top-level symlinks
  nodeModules = pkgs.runCommand "remix-v3-node-modules" {} ''
    mkdir -p $out/node_modules/.pnpm $out/node_modules/.bin
    mkdir -p $out/node_modules/.pnpm/@edgefirst-dev+data@0.0.4/node_modules/@edgefirst-dev
    cp -r ${packages."@edgefirst-dev/data@0.0.4"}/node_modules/@edgefirst-dev/data/. $out/node_modules/.pnpm/@edgefirst-dev+data@0.0.4/node_modules/@edgefirst-dev/data
    mkdir -p $out/node_modules/.pnpm/@mjackson+headers@0.10.0/node_modules/@mjackson
    cp -r ${packages."@mjackson/headers@0.10.0"}/node_modules/@mjackson/headers/. $out/node_modules/.pnpm/@mjackson+headers@0.10.0/node_modules/@mjackson/headers
    mkdir -p $out/node_modules/.pnpm/@oslojs+asn1@1.0.0/node_modules/@oslojs
    cp -r ${packages."@oslojs/asn1@1.0.0"}/node_modules/@oslojs/asn1/. $out/node_modules/.pnpm/@oslojs+asn1@1.0.0/node_modules/@oslojs/asn1
    mkdir -p $out/node_modules/.pnpm/@oslojs+asn1@1.0.0/node_modules/@oslojs
    ln -sf ../../@oslojs+binary@1.0.0/node_modules/@oslojs/binary $out/node_modules/.pnpm/@oslojs+asn1@1.0.0/node_modules/@oslojs/binary
    mkdir -p $out/node_modules/.pnpm/@oslojs+binary@1.0.0/node_modules/@oslojs
    cp -r ${packages."@oslojs/binary@1.0.0"}/node_modules/@oslojs/binary/. $out/node_modules/.pnpm/@oslojs+binary@1.0.0/node_modules/@oslojs/binary
    mkdir -p $out/node_modules/.pnpm/@oslojs+crypto@1.0.1/node_modules/@oslojs
    cp -r ${packages."@oslojs/crypto@1.0.1"}/node_modules/@oslojs/crypto/. $out/node_modules/.pnpm/@oslojs+crypto@1.0.1/node_modules/@oslojs/crypto
    mkdir -p $out/node_modules/.pnpm/@oslojs+crypto@1.0.1/node_modules/@oslojs
    ln -sf ../../@oslojs+asn1@1.0.0/node_modules/@oslojs/asn1 $out/node_modules/.pnpm/@oslojs+crypto@1.0.1/node_modules/@oslojs/asn1
    mkdir -p $out/node_modules/.pnpm/@oslojs+crypto@1.0.1/node_modules/@oslojs
    ln -sf ../../@oslojs+binary@1.0.0/node_modules/@oslojs/binary $out/node_modules/.pnpm/@oslojs+crypto@1.0.1/node_modules/@oslojs/binary
    mkdir -p $out/node_modules/.pnpm/@oslojs+encoding@0.4.1/node_modules/@oslojs
    cp -r ${packages."@oslojs/encoding@0.4.1"}/node_modules/@oslojs/encoding/. $out/node_modules/.pnpm/@oslojs+encoding@0.4.1/node_modules/@oslojs/encoding
    mkdir -p $out/node_modules/.pnpm/@oslojs+encoding@1.1.0/node_modules/@oslojs
    cp -r ${packages."@oslojs/encoding@1.1.0"}/node_modules/@oslojs/encoding/. $out/node_modules/.pnpm/@oslojs+encoding@1.1.0/node_modules/@oslojs/encoding
    mkdir -p $out/node_modules/.pnpm/@oslojs+jwt@0.2.0/node_modules/@oslojs
    cp -r ${packages."@oslojs/jwt@0.2.0"}/node_modules/@oslojs/jwt/. $out/node_modules/.pnpm/@oslojs+jwt@0.2.0/node_modules/@oslojs/jwt
    mkdir -p $out/node_modules/.pnpm/@oslojs+jwt@0.2.0/node_modules/@oslojs
    ln -sf ../../@oslojs+encoding@0.4.1/node_modules/@oslojs/encoding $out/node_modules/.pnpm/@oslojs+jwt@0.2.0/node_modules/@oslojs/encoding
    mkdir -p $out/node_modules/.pnpm/@remix-run+dom@0.0.0-experimental-remix-jam.6/node_modules/@remix-run
    cp -r ${packages."@remix-run/dom@0.0.0-experimental-remix-jam.6"}/node_modules/@remix-run/dom/. $out/node_modules/.pnpm/@remix-run+dom@0.0.0-experimental-remix-jam.6/node_modules/@remix-run/dom
    mkdir -p $out/node_modules/.pnpm/@remix-run+dom@0.0.0-experimental-remix-jam.6/node_modules/@remix-run
    ln -sf ../../@remix-run+events@0.0.0-experimental-remix-jam.5/node_modules/@remix-run/events $out/node_modules/.pnpm/@remix-run+dom@0.0.0-experimental-remix-jam.6/node_modules/@remix-run/events
    mkdir -p $out/node_modules/.pnpm/@remix-run+dom@0.0.0-experimental-remix-jam.6/node_modules/@remix-run
    ln -sf ../../@remix-run+style@0.0.0-experimental-remix-jam.5/node_modules/@remix-run/style $out/node_modules/.pnpm/@remix-run+dom@0.0.0-experimental-remix-jam.6/node_modules/@remix-run/style
    mkdir -p $out/node_modules/.pnpm/@remix-run+events@0.0.0-experimental-remix-jam.5/node_modules/@remix-run
    cp -r ${packages."@remix-run/events@0.0.0-experimental-remix-jam.5"}/node_modules/@remix-run/events/. $out/node_modules/.pnpm/@remix-run+events@0.0.0-experimental-remix-jam.5/node_modules/@remix-run/events
    mkdir -p $out/node_modules/.pnpm/@remix-run+fetch-router@0.6.0/node_modules/@remix-run
    cp -r ${packages."@remix-run/fetch-router@0.6.0"}/node_modules/@remix-run/fetch-router/. $out/node_modules/.pnpm/@remix-run+fetch-router@0.6.0/node_modules/@remix-run/fetch-router
    mkdir -p $out/node_modules/.pnpm/@remix-run+fetch-router@0.6.0/node_modules/@remix-run
    ln -sf ../../@remix-run+form-data-parser@0.11.0/node_modules/@remix-run/form-data-parser $out/node_modules/.pnpm/@remix-run+fetch-router@0.6.0/node_modules/@remix-run/form-data-parser
    mkdir -p $out/node_modules/.pnpm/@remix-run+fetch-router@0.6.0/node_modules/@remix-run
    ln -sf ../../@remix-run+route-pattern@0.14.0/node_modules/@remix-run/route-pattern $out/node_modules/.pnpm/@remix-run+fetch-router@0.6.0/node_modules/@remix-run/route-pattern
    mkdir -p $out/node_modules/.pnpm/@remix-run+form-data-parser@0.11.0/node_modules/@remix-run
    cp -r ${packages."@remix-run/form-data-parser@0.11.0"}/node_modules/@remix-run/form-data-parser/. $out/node_modules/.pnpm/@remix-run+form-data-parser@0.11.0/node_modules/@remix-run/form-data-parser
    mkdir -p $out/node_modules/.pnpm/@remix-run+form-data-parser@0.11.0/node_modules/@remix-run
    ln -sf ../../@remix-run+multipart-parser@0.11.0/node_modules/@remix-run/multipart-parser $out/node_modules/.pnpm/@remix-run+form-data-parser@0.11.0/node_modules/@remix-run/multipart-parser
    mkdir -p $out/node_modules/.pnpm/@remix-run+headers@0.12.0/node_modules/@remix-run
    cp -r ${packages."@remix-run/headers@0.12.0"}/node_modules/@remix-run/headers/. $out/node_modules/.pnpm/@remix-run+headers@0.12.0/node_modules/@remix-run/headers
    mkdir -p $out/node_modules/.pnpm/@remix-run+multipart-parser@0.11.0/node_modules/@remix-run
    cp -r ${packages."@remix-run/multipart-parser@0.11.0"}/node_modules/@remix-run/multipart-parser/. $out/node_modules/.pnpm/@remix-run+multipart-parser@0.11.0/node_modules/@remix-run/multipart-parser
    mkdir -p $out/node_modules/.pnpm/@remix-run+multipart-parser@0.11.0/node_modules/@remix-run
    ln -sf ../../@remix-run+headers@0.12.0/node_modules/@remix-run/headers $out/node_modules/.pnpm/@remix-run+multipart-parser@0.11.0/node_modules/@remix-run/headers
    mkdir -p $out/node_modules/.pnpm/@remix-run+route-pattern@0.14.0/node_modules/@remix-run
    cp -r ${packages."@remix-run/route-pattern@0.14.0"}/node_modules/@remix-run/route-pattern/. $out/node_modules/.pnpm/@remix-run+route-pattern@0.14.0/node_modules/@remix-run/route-pattern
    mkdir -p $out/node_modules/.pnpm/@remix-run+style@0.0.0-experimental-remix-jam.5/node_modules/@remix-run
    cp -r ${packages."@remix-run/style@0.0.0-experimental-remix-jam.5"}/node_modules/@remix-run/style/. $out/node_modules/.pnpm/@remix-run+style@0.0.0-experimental-remix-jam.5/node_modules/@remix-run/style
    mkdir -p $out/node_modules/.pnpm/@tanstack+query-core@5.90.20/node_modules/@tanstack
    cp -r ${packages."@tanstack/query-core@5.90.20"}/node_modules/@tanstack/query-core/. $out/node_modules/.pnpm/@tanstack+query-core@5.90.20/node_modules/@tanstack/query-core
    mkdir -p $out/node_modules/.pnpm/@types+bun@1.3.9/node_modules/@types
    cp -r ${packages."@types/bun@1.3.9"}/node_modules/@types/bun/. $out/node_modules/.pnpm/@types+bun@1.3.9/node_modules/@types/bun
    ln -sf ../../bun-types@1.3.9/node_modules/bun-types $out/node_modules/.pnpm/@types+bun@1.3.9/node_modules/bun-types
    mkdir -p $out/node_modules/.pnpm/@types+node@25.2.3/node_modules/@types
    cp -r ${packages."@types/node@25.2.3"}/node_modules/@types/node/. $out/node_modules/.pnpm/@types+node@25.2.3/node_modules/@types/node
    ln -sf ../../undici-types@7.16.0/node_modules/undici-types $out/node_modules/.pnpm/@types+node@25.2.3/node_modules/undici-types
    mkdir -p $out/node_modules/.pnpm/alien-signals@3.1.2/node_modules
    cp -r ${packages."alien-signals@3.1.2"}/node_modules/alien-signals/. $out/node_modules/.pnpm/alien-signals@3.1.2/node_modules/alien-signals
    mkdir -p $out/node_modules/.pnpm/arctic@3.7.0/node_modules
    cp -r ${packages."arctic@3.7.0"}/node_modules/arctic/. $out/node_modules/.pnpm/arctic@3.7.0/node_modules/arctic
    mkdir -p $out/node_modules/.pnpm/arctic@3.7.0/node_modules/@oslojs
    ln -sf ../../@oslojs+crypto@1.0.1/node_modules/@oslojs/crypto $out/node_modules/.pnpm/arctic@3.7.0/node_modules/@oslojs/crypto
    mkdir -p $out/node_modules/.pnpm/arctic@3.7.0/node_modules/@oslojs
    ln -sf ../../@oslojs+encoding@1.1.0/node_modules/@oslojs/encoding $out/node_modules/.pnpm/arctic@3.7.0/node_modules/@oslojs/encoding
    mkdir -p $out/node_modules/.pnpm/arctic@3.7.0/node_modules/@oslojs
    ln -sf ../../@oslojs+jwt@0.2.0/node_modules/@oslojs/jwt $out/node_modules/.pnpm/arctic@3.7.0/node_modules/@oslojs/jwt
    mkdir -p $out/node_modules/.pnpm/bun-types@1.3.9/node_modules
    cp -r ${packages."bun-types@1.3.9"}/node_modules/bun-types/. $out/node_modules/.pnpm/bun-types@1.3.9/node_modules/bun-types
    mkdir -p $out/node_modules/.pnpm/bun-types@1.3.9/node_modules/@types
    ln -sf ../../@types+node@25.2.3/node_modules/@types/node $out/node_modules/.pnpm/bun-types@1.3.9/node_modules/@types/node
    mkdir -p $out/node_modules/.pnpm/remix-auth-oauth2@3.4.1/node_modules
    cp -r ${packages."remix-auth-oauth2@3.4.1"}/node_modules/remix-auth-oauth2/. $out/node_modules/.pnpm/remix-auth-oauth2@3.4.1/node_modules/remix-auth-oauth2
    mkdir -p $out/node_modules/.pnpm/remix-auth@4.2.0/node_modules
    cp -r ${packages."remix-auth@4.2.0"}/node_modules/remix-auth/. $out/node_modules/.pnpm/remix-auth@4.2.0/node_modules/remix-auth
    mkdir -p $out/node_modules/.pnpm/typescript@5.9.3/node_modules
    cp -r ${packages."typescript@5.9.3"}/node_modules/typescript/. $out/node_modules/.pnpm/typescript@5.9.3/node_modules/typescript
    mkdir -p $out/node_modules/.pnpm/undici-types@7.16.0/node_modules
    cp -r ${packages."undici-types@7.16.0"}/node_modules/undici-types/. $out/node_modules/.pnpm/undici-types@7.16.0/node_modules/undici-types

    # top-level symlinks
    mkdir -p $out/node_modules/@edgefirst-dev
    ln -sf ../.pnpm/@edgefirst-dev+data@0.0.4/node_modules/@edgefirst-dev/data $out/node_modules/@edgefirst-dev/data
    mkdir -p $out/node_modules/@mjackson
    ln -sf ../.pnpm/@mjackson+headers@0.10.0/node_modules/@mjackson/headers $out/node_modules/@mjackson/headers
    mkdir -p $out/node_modules/@oslojs
    ln -sf ../.pnpm/@oslojs+asn1@1.0.0/node_modules/@oslojs/asn1 $out/node_modules/@oslojs/asn1
    mkdir -p $out/node_modules/@oslojs
    ln -sf ../.pnpm/@oslojs+binary@1.0.0/node_modules/@oslojs/binary $out/node_modules/@oslojs/binary
    mkdir -p $out/node_modules/@oslojs
    ln -sf ../.pnpm/@oslojs+crypto@1.0.1/node_modules/@oslojs/crypto $out/node_modules/@oslojs/crypto
    mkdir -p $out/node_modules/@oslojs
    ln -sf ../.pnpm/@oslojs+encoding@1.1.0/node_modules/@oslojs/encoding $out/node_modules/@oslojs/encoding
    mkdir -p $out/node_modules/@oslojs
    ln -sf ../.pnpm/@oslojs+jwt@0.2.0/node_modules/@oslojs/jwt $out/node_modules/@oslojs/jwt
    mkdir -p $out/node_modules/@remix-run
    ln -sf ../.pnpm/@remix-run+dom@0.0.0-experimental-remix-jam.6/node_modules/@remix-run/dom $out/node_modules/@remix-run/dom
    mkdir -p $out/node_modules/@remix-run
    ln -sf ../.pnpm/@remix-run+events@0.0.0-experimental-remix-jam.5/node_modules/@remix-run/events $out/node_modules/@remix-run/events
    mkdir -p $out/node_modules/@remix-run
    ln -sf ../.pnpm/@remix-run+fetch-router@0.6.0/node_modules/@remix-run/fetch-router $out/node_modules/@remix-run/fetch-router
    mkdir -p $out/node_modules/@remix-run
    ln -sf ../.pnpm/@remix-run+form-data-parser@0.11.0/node_modules/@remix-run/form-data-parser $out/node_modules/@remix-run/form-data-parser
    mkdir -p $out/node_modules/@remix-run
    ln -sf ../.pnpm/@remix-run+headers@0.12.0/node_modules/@remix-run/headers $out/node_modules/@remix-run/headers
    mkdir -p $out/node_modules/@remix-run
    ln -sf ../.pnpm/@remix-run+multipart-parser@0.11.0/node_modules/@remix-run/multipart-parser $out/node_modules/@remix-run/multipart-parser
    mkdir -p $out/node_modules/@remix-run
    ln -sf ../.pnpm/@remix-run+route-pattern@0.14.0/node_modules/@remix-run/route-pattern $out/node_modules/@remix-run/route-pattern
    mkdir -p $out/node_modules/@remix-run
    ln -sf ../.pnpm/@remix-run+style@0.0.0-experimental-remix-jam.5/node_modules/@remix-run/style $out/node_modules/@remix-run/style
    mkdir -p $out/node_modules/@tanstack
    ln -sf ../.pnpm/@tanstack+query-core@5.90.20/node_modules/@tanstack/query-core $out/node_modules/@tanstack/query-core
    mkdir -p $out/node_modules/@types
    ln -sf ../.pnpm/@types+bun@1.3.9/node_modules/@types/bun $out/node_modules/@types/bun
    mkdir -p $out/node_modules/@types
    ln -sf ../.pnpm/@types+node@25.2.3/node_modules/@types/node $out/node_modules/@types/node
    ln -sf .pnpm/alien-signals@3.1.2/node_modules/alien-signals $out/node_modules/alien-signals
    ln -sf .pnpm/arctic@3.7.0/node_modules/arctic $out/node_modules/arctic
    ln -sf .pnpm/bun-types@1.3.9/node_modules/bun-types $out/node_modules/bun-types
    ln -sf .pnpm/remix-auth@4.2.0/node_modules/remix-auth $out/node_modules/remix-auth
    ln -sf .pnpm/remix-auth-oauth2@3.4.1/node_modules/remix-auth-oauth2 $out/node_modules/remix-auth-oauth2
    ln -sf .pnpm/typescript@5.9.3/node_modules/typescript $out/node_modules/typescript
    ln -sf .pnpm/undici-types@7.16.0/node_modules/undici-types $out/node_modules/undici-types

    # bin links
    if [ -d ${packages."@edgefirst-dev/data@0.0.4"}/node_modules/.bin ]; then
      for b in ${packages."@edgefirst-dev/data@0.0.4"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@edgefirst-dev+data@0.0.4/node_modules/@edgefirst-dev/data/$(readlink $b | sed "s|.*node_modules/@edgefirst-dev/data/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@mjackson/headers@0.10.0"}/node_modules/.bin ]; then
      for b in ${packages."@mjackson/headers@0.10.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@mjackson+headers@0.10.0/node_modules/@mjackson/headers/$(readlink $b | sed "s|.*node_modules/@mjackson/headers/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@oslojs/asn1@1.0.0"}/node_modules/.bin ]; then
      for b in ${packages."@oslojs/asn1@1.0.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@oslojs+asn1@1.0.0/node_modules/@oslojs/asn1/$(readlink $b | sed "s|.*node_modules/@oslojs/asn1/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@oslojs/binary@1.0.0"}/node_modules/.bin ]; then
      for b in ${packages."@oslojs/binary@1.0.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@oslojs+binary@1.0.0/node_modules/@oslojs/binary/$(readlink $b | sed "s|.*node_modules/@oslojs/binary/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@oslojs/crypto@1.0.1"}/node_modules/.bin ]; then
      for b in ${packages."@oslojs/crypto@1.0.1"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@oslojs+crypto@1.0.1/node_modules/@oslojs/crypto/$(readlink $b | sed "s|.*node_modules/@oslojs/crypto/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@oslojs/encoding@0.4.1"}/node_modules/.bin ]; then
      for b in ${packages."@oslojs/encoding@0.4.1"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@oslojs+encoding@0.4.1/node_modules/@oslojs/encoding/$(readlink $b | sed "s|.*node_modules/@oslojs/encoding/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@oslojs/encoding@1.1.0"}/node_modules/.bin ]; then
      for b in ${packages."@oslojs/encoding@1.1.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@oslojs+encoding@1.1.0/node_modules/@oslojs/encoding/$(readlink $b | sed "s|.*node_modules/@oslojs/encoding/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@oslojs/jwt@0.2.0"}/node_modules/.bin ]; then
      for b in ${packages."@oslojs/jwt@0.2.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@oslojs+jwt@0.2.0/node_modules/@oslojs/jwt/$(readlink $b | sed "s|.*node_modules/@oslojs/jwt/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@remix-run/dom@0.0.0-experimental-remix-jam.6"}/node_modules/.bin ]; then
      for b in ${packages."@remix-run/dom@0.0.0-experimental-remix-jam.6"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@remix-run+dom@0.0.0-experimental-remix-jam.6/node_modules/@remix-run/dom/$(readlink $b | sed "s|.*node_modules/@remix-run/dom/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@remix-run/events@0.0.0-experimental-remix-jam.5"}/node_modules/.bin ]; then
      for b in ${packages."@remix-run/events@0.0.0-experimental-remix-jam.5"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@remix-run+events@0.0.0-experimental-remix-jam.5/node_modules/@remix-run/events/$(readlink $b | sed "s|.*node_modules/@remix-run/events/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@remix-run/fetch-router@0.6.0"}/node_modules/.bin ]; then
      for b in ${packages."@remix-run/fetch-router@0.6.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@remix-run+fetch-router@0.6.0/node_modules/@remix-run/fetch-router/$(readlink $b | sed "s|.*node_modules/@remix-run/fetch-router/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@remix-run/form-data-parser@0.11.0"}/node_modules/.bin ]; then
      for b in ${packages."@remix-run/form-data-parser@0.11.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@remix-run+form-data-parser@0.11.0/node_modules/@remix-run/form-data-parser/$(readlink $b | sed "s|.*node_modules/@remix-run/form-data-parser/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@remix-run/headers@0.12.0"}/node_modules/.bin ]; then
      for b in ${packages."@remix-run/headers@0.12.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@remix-run+headers@0.12.0/node_modules/@remix-run/headers/$(readlink $b | sed "s|.*node_modules/@remix-run/headers/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@remix-run/multipart-parser@0.11.0"}/node_modules/.bin ]; then
      for b in ${packages."@remix-run/multipart-parser@0.11.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@remix-run+multipart-parser@0.11.0/node_modules/@remix-run/multipart-parser/$(readlink $b | sed "s|.*node_modules/@remix-run/multipart-parser/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@remix-run/route-pattern@0.14.0"}/node_modules/.bin ]; then
      for b in ${packages."@remix-run/route-pattern@0.14.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@remix-run+route-pattern@0.14.0/node_modules/@remix-run/route-pattern/$(readlink $b | sed "s|.*node_modules/@remix-run/route-pattern/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@remix-run/style@0.0.0-experimental-remix-jam.5"}/node_modules/.bin ]; then
      for b in ${packages."@remix-run/style@0.0.0-experimental-remix-jam.5"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@remix-run+style@0.0.0-experimental-remix-jam.5/node_modules/@remix-run/style/$(readlink $b | sed "s|.*node_modules/@remix-run/style/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@tanstack/query-core@5.90.20"}/node_modules/.bin ]; then
      for b in ${packages."@tanstack/query-core@5.90.20"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@tanstack+query-core@5.90.20/node_modules/@tanstack/query-core/$(readlink $b | sed "s|.*node_modules/@tanstack/query-core/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@types/bun@1.3.9"}/node_modules/.bin ]; then
      for b in ${packages."@types/bun@1.3.9"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@types+bun@1.3.9/node_modules/@types/bun/$(readlink $b | sed "s|.*node_modules/@types/bun/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@types/node@25.2.3"}/node_modules/.bin ]; then
      for b in ${packages."@types/node@25.2.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@types+node@25.2.3/node_modules/@types/node/$(readlink $b | sed "s|.*node_modules/@types/node/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."alien-signals@3.1.2"}/node_modules/.bin ]; then
      for b in ${packages."alien-signals@3.1.2"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/alien-signals@3.1.2/node_modules/alien-signals/$(readlink $b | sed "s|.*node_modules/alien-signals/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."arctic@3.7.0"}/node_modules/.bin ]; then
      for b in ${packages."arctic@3.7.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/arctic@3.7.0/node_modules/arctic/$(readlink $b | sed "s|.*node_modules/arctic/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."bun-types@1.3.9"}/node_modules/.bin ]; then
      for b in ${packages."bun-types@1.3.9"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/bun-types@1.3.9/node_modules/bun-types/$(readlink $b | sed "s|.*node_modules/bun-types/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."remix-auth-oauth2@3.4.1"}/node_modules/.bin ]; then
      for b in ${packages."remix-auth-oauth2@3.4.1"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/remix-auth-oauth2@3.4.1/node_modules/remix-auth-oauth2/$(readlink $b | sed "s|.*node_modules/remix-auth-oauth2/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."remix-auth@4.2.0"}/node_modules/.bin ]; then
      for b in ${packages."remix-auth@4.2.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/remix-auth@4.2.0/node_modules/remix-auth/$(readlink $b | sed "s|.*node_modules/remix-auth/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."typescript@5.9.3"}/node_modules/.bin ]; then
      for b in ${packages."typescript@5.9.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/typescript@5.9.3/node_modules/typescript/$(readlink $b | sed "s|.*node_modules/typescript/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."undici-types@7.16.0"}/node_modules/.bin ]; then
      for b in ${packages."undici-types@7.16.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/undici-types@7.16.0/node_modules/undici-types/$(readlink $b | sed "s|.*node_modules/undici-types/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
  '';
in packages // {
  inherit nodeModules;
  devShell = { buildInputs ? [], shellHook ? "", ... }@args:
    pkgs.mkShell (builtins.removeAttrs args ["buildInputs" "shellHook"] // {
      name = "remix-v3-devshell";
      buildInputs = [ nodejs ] ++ buildInputs;
      shellHook = ''
        export NODE_PATH="${nodeModules}/node_modules"
      '' + shellHook;
    });
}
