# tsdown-starter — generated by onix. Do not edit.
#
# pnpm-style node_modules layout:
#   node_modules/.pnpm/<name>@<version>/node_modules/<name>  <- package contents
#   node_modules/.pnpm/<name>@<version>/node_modules/<dep>   <- symlink to dep's .pnpm entry
#   node_modules/<name>                                      <- symlink to .pnpm entry
#
{ pkgs ? import <nixpkgs> { config = {}; overlays = []; }, nodejs ? pkgs.nodejs_22 }:
let
  buildNpm = import ./build-npm.nix { inherit pkgs nodejs; };
  buildPackageByName = name:
    let
      versions = import (./node + "/${name}.nix");
      version = pkgs.lib.last (builtins.attrNames versions);
      spec = versions.${version};
    in buildNpm (spec // { pkgName = name; });
  npmConfig = import ./npm-config.nix {
    inherit pkgs nodejs;
    overlayDir = ../overlays;
    nodeDir = ./node;
    buildPackageFn = buildPackageByName;
  };

  build = name: version:
    let
      safeName = builtins.replaceStrings ["/" "@"] ["--" ""] name;
      versions = import (./node + "/${safeName}.nix");
      spec = versions.${version};
      config = npmConfig.${name} or {};
    in buildNpm (spec // {
      pkgName = name;
      hasNative = (spec.hasNative or false) || (config ? deps && config.deps != []);
      nativeBuildInputs = config.deps or [];
      buildFlags = config.buildFlags or "";
      beforeBuild = config.beforeBuild or "";
      afterBuild = config.afterBuild or "";
    } // (if config ? buildPhase then { inherit (config) buildPhase; } else {})
      // (if config ? postInstall then { inherit (config) postInstall; } else {})
      // (if config ? skip then { inherit (config) skip; } else {})
      // (if config ? buildPackages then { inherit (config) buildPackages; } else {}));

  # Per-package derivations (used by .pnpm/ entries)
  packages = {
    "@babel/generator@8.0.0-rc.1" = build "@babel/generator" "8.0.0-rc.1";
    "@babel/helper-string-parser@8.0.0-rc.1" = build "@babel/helper-string-parser" "8.0.0-rc.1";
    "@babel/helper-validator-identifier@8.0.0-rc.1" = build "@babel/helper-validator-identifier" "8.0.0-rc.1";
    "@babel/parser@8.0.0-rc.1" = build "@babel/parser" "8.0.0-rc.1";
    "@babel/types@8.0.0-rc.1" = build "@babel/types" "8.0.0-rc.1";
    "@emnapi/core@1.8.1" = build "@emnapi/core" "1.8.1";
    "@emnapi/runtime@1.8.1" = build "@emnapi/runtime" "1.8.1";
    "@emnapi/wasi-threads@1.1.0" = build "@emnapi/wasi-threads" "1.1.0";
    "@jridgewell/gen-mapping@0.3.13" = build "@jridgewell/gen-mapping" "0.3.13";
    "@jridgewell/resolve-uri@3.1.2" = build "@jridgewell/resolve-uri" "3.1.2";
    "@jridgewell/sourcemap-codec@1.5.5" = build "@jridgewell/sourcemap-codec" "1.5.5";
    "@jridgewell/trace-mapping@0.3.31" = build "@jridgewell/trace-mapping" "0.3.31";
    "@napi-rs/wasm-runtime@1.1.1" = build "@napi-rs/wasm-runtime" "1.1.1";
    "@oxc-project/types@0.112.0" = build "@oxc-project/types" "0.112.0";
    "@quansync/fs@1.0.0" = build "@quansync/fs" "1.0.0";
    "@rolldown/binding-android-arm64@1.0.0-rc.3" = build "@rolldown/binding-android-arm64" "1.0.0-rc.3";
    "@rolldown/binding-darwin-arm64@1.0.0-rc.3" = build "@rolldown/binding-darwin-arm64" "1.0.0-rc.3";
    "@rolldown/binding-darwin-x64@1.0.0-rc.3" = build "@rolldown/binding-darwin-x64" "1.0.0-rc.3";
    "@rolldown/binding-freebsd-x64@1.0.0-rc.3" = build "@rolldown/binding-freebsd-x64" "1.0.0-rc.3";
    "@rolldown/binding-linux-arm-gnueabihf@1.0.0-rc.3" = build "@rolldown/binding-linux-arm-gnueabihf" "1.0.0-rc.3";
    "@rolldown/binding-linux-arm64-gnu@1.0.0-rc.3" = build "@rolldown/binding-linux-arm64-gnu" "1.0.0-rc.3";
    "@rolldown/binding-linux-arm64-musl@1.0.0-rc.3" = build "@rolldown/binding-linux-arm64-musl" "1.0.0-rc.3";
    "@rolldown/binding-linux-x64-gnu@1.0.0-rc.3" = build "@rolldown/binding-linux-x64-gnu" "1.0.0-rc.3";
    "@rolldown/binding-linux-x64-musl@1.0.0-rc.3" = build "@rolldown/binding-linux-x64-musl" "1.0.0-rc.3";
    "@rolldown/binding-openharmony-arm64@1.0.0-rc.3" = build "@rolldown/binding-openharmony-arm64" "1.0.0-rc.3";
    "@rolldown/binding-wasm32-wasi@1.0.0-rc.3" = build "@rolldown/binding-wasm32-wasi" "1.0.0-rc.3";
    "@rolldown/binding-win32-arm64-msvc@1.0.0-rc.3" = build "@rolldown/binding-win32-arm64-msvc" "1.0.0-rc.3";
    "@rolldown/binding-win32-x64-msvc@1.0.0-rc.3" = build "@rolldown/binding-win32-x64-msvc" "1.0.0-rc.3";
    "@rolldown/pluginutils@1.0.0-rc.3" = build "@rolldown/pluginutils" "1.0.0-rc.3";
    "@tybys/wasm-util@0.10.1" = build "@tybys/wasm-util" "0.10.1";
    "@types/estree@1.0.8" = build "@types/estree" "1.0.8";
    "@types/jsesc@2.5.1" = build "@types/jsesc" "2.5.1";
    "ansis@4.2.0" = build "ansis" "4.2.0";
    "ast-kit@3.0.0-beta.1" = build "ast-kit" "3.0.0-beta.1";
    "birpc@4.0.0" = build "birpc" "4.0.0";
    "cac@6.7.14" = build "cac" "6.7.14";
    "defu@6.1.4" = build "defu" "6.1.4";
    "dts-resolver@2.1.3" = build "dts-resolver" "2.1.3";
    "empathic@2.0.0" = build "empathic" "2.0.0";
    "estree-walker@3.0.3" = build "estree-walker" "3.0.3";
    "fdir@6.5.0" = build "fdir" "6.5.0";
    "get-tsconfig@4.13.6" = build "get-tsconfig" "4.13.6";
    "hookable@6.0.1" = build "hookable" "6.0.1";
    "import-without-cache@0.2.5" = build "import-without-cache" "0.2.5";
    "jsesc@3.1.0" = build "jsesc" "3.1.0";
    "obug@2.1.1" = build "obug" "2.1.1";
    "pathe@2.0.3" = build "pathe" "2.0.3";
    "picomatch@4.0.3" = build "picomatch" "4.0.3";
    "quansync@1.0.0" = build "quansync" "1.0.0";
    "resolve-pkg-maps@1.0.0" = build "resolve-pkg-maps" "1.0.0";
    "rolldown@1.0.0-rc.3" = build "rolldown" "1.0.0-rc.3";
    "rolldown-plugin-dts@0.22.1" = build "rolldown-plugin-dts" "0.22.1";
    "semver@7.7.4" = build "semver" "7.7.4";
    "tinyexec@1.0.2" = build "tinyexec" "1.0.2";
    "tinyglobby@0.2.15" = build "tinyglobby" "0.2.15";
    "tree-kill@1.2.2" = build "tree-kill" "1.2.2";
    "tsdown@0.20.3" = build "tsdown" "0.20.3";
    "tslib@2.8.1" = build "tslib" "2.8.1";
    "typescript@5.9.3" = build "typescript" "5.9.3";
    "unconfig-core@7.4.2" = build "unconfig-core" "7.4.2";
    "unrun@0.2.27" = build "unrun" "0.2.27";
  };

  # pnpm-style .pnpm/ virtual store + top-level symlinks
  nodeModules = pkgs.runCommand "tsdown-starter-node-modules" {} ''
    mkdir -p $out/node_modules/.pnpm $out/node_modules/.bin
    mkdir -p $out/node_modules/.pnpm/@babel+generator@8.0.0-rc.1/node_modules/@babel/generator
    cp -r --reflink=auto ${packages."@babel/generator@8.0.0-rc.1"}/node_modules/@babel/generator/. $out/node_modules/.pnpm/@babel+generator@8.0.0-rc.1/node_modules/@babel/generator/
    mkdir -p $out/node_modules/.pnpm/@babel+generator@8.0.0-rc.1/node_modules/@babel
    ln -sf ../../@babel+parser@8.0.0-rc.1/node_modules/@babel/parser $out/node_modules/.pnpm/@babel+generator@8.0.0-rc.1/node_modules/@babel/parser
    mkdir -p $out/node_modules/.pnpm/@babel+generator@8.0.0-rc.1/node_modules/@babel
    ln -sf ../../@babel+types@8.0.0-rc.1/node_modules/@babel/types $out/node_modules/.pnpm/@babel+generator@8.0.0-rc.1/node_modules/@babel/types
    mkdir -p $out/node_modules/.pnpm/@babel+generator@8.0.0-rc.1/node_modules/@jridgewell
    ln -sf ../../@jridgewell+gen-mapping@0.3.13/node_modules/@jridgewell/gen-mapping $out/node_modules/.pnpm/@babel+generator@8.0.0-rc.1/node_modules/@jridgewell/gen-mapping
    mkdir -p $out/node_modules/.pnpm/@babel+generator@8.0.0-rc.1/node_modules/@jridgewell
    ln -sf ../../@jridgewell+trace-mapping@0.3.31/node_modules/@jridgewell/trace-mapping $out/node_modules/.pnpm/@babel+generator@8.0.0-rc.1/node_modules/@jridgewell/trace-mapping
    mkdir -p $out/node_modules/.pnpm/@babel+generator@8.0.0-rc.1/node_modules/@types
    ln -sf ../../@types+jsesc@2.5.1/node_modules/@types/jsesc $out/node_modules/.pnpm/@babel+generator@8.0.0-rc.1/node_modules/@types/jsesc
    ln -sf ../../jsesc@3.1.0/node_modules/jsesc $out/node_modules/.pnpm/@babel+generator@8.0.0-rc.1/node_modules/jsesc
    mkdir -p $out/node_modules/.pnpm/@babel+helper-string-parser@8.0.0-rc.1/node_modules/@babel/helper-string-parser
    cp -r --reflink=auto ${packages."@babel/helper-string-parser@8.0.0-rc.1"}/node_modules/@babel/helper-string-parser/. $out/node_modules/.pnpm/@babel+helper-string-parser@8.0.0-rc.1/node_modules/@babel/helper-string-parser/
    mkdir -p $out/node_modules/.pnpm/@babel+helper-validator-identifier@8.0.0-rc.1/node_modules/@babel/helper-validator-identifier
    cp -r --reflink=auto ${packages."@babel/helper-validator-identifier@8.0.0-rc.1"}/node_modules/@babel/helper-validator-identifier/. $out/node_modules/.pnpm/@babel+helper-validator-identifier@8.0.0-rc.1/node_modules/@babel/helper-validator-identifier/
    mkdir -p $out/node_modules/.pnpm/@babel+parser@8.0.0-rc.1/node_modules/@babel/parser
    cp -r --reflink=auto ${packages."@babel/parser@8.0.0-rc.1"}/node_modules/@babel/parser/. $out/node_modules/.pnpm/@babel+parser@8.0.0-rc.1/node_modules/@babel/parser/
    mkdir -p $out/node_modules/.pnpm/@babel+parser@8.0.0-rc.1/node_modules/@babel
    ln -sf ../../@babel+types@8.0.0-rc.1/node_modules/@babel/types $out/node_modules/.pnpm/@babel+parser@8.0.0-rc.1/node_modules/@babel/types
    mkdir -p $out/node_modules/.pnpm/@babel+types@8.0.0-rc.1/node_modules/@babel/types
    cp -r --reflink=auto ${packages."@babel/types@8.0.0-rc.1"}/node_modules/@babel/types/. $out/node_modules/.pnpm/@babel+types@8.0.0-rc.1/node_modules/@babel/types/
    mkdir -p $out/node_modules/.pnpm/@babel+types@8.0.0-rc.1/node_modules/@babel
    ln -sf ../../@babel+helper-string-parser@8.0.0-rc.1/node_modules/@babel/helper-string-parser $out/node_modules/.pnpm/@babel+types@8.0.0-rc.1/node_modules/@babel/helper-string-parser
    mkdir -p $out/node_modules/.pnpm/@babel+types@8.0.0-rc.1/node_modules/@babel
    ln -sf ../../@babel+helper-validator-identifier@8.0.0-rc.1/node_modules/@babel/helper-validator-identifier $out/node_modules/.pnpm/@babel+types@8.0.0-rc.1/node_modules/@babel/helper-validator-identifier
    mkdir -p $out/node_modules/.pnpm/@emnapi+core@1.8.1/node_modules/@emnapi/core
    cp -r --reflink=auto ${packages."@emnapi/core@1.8.1"}/node_modules/@emnapi/core/. $out/node_modules/.pnpm/@emnapi+core@1.8.1/node_modules/@emnapi/core/
    mkdir -p $out/node_modules/.pnpm/@emnapi+core@1.8.1/node_modules/@emnapi
    ln -sf ../../@emnapi+wasi-threads@1.1.0/node_modules/@emnapi/wasi-threads $out/node_modules/.pnpm/@emnapi+core@1.8.1/node_modules/@emnapi/wasi-threads
    ln -sf ../../tslib@2.8.1/node_modules/tslib $out/node_modules/.pnpm/@emnapi+core@1.8.1/node_modules/tslib
    mkdir -p $out/node_modules/.pnpm/@emnapi+runtime@1.8.1/node_modules/@emnapi/runtime
    cp -r --reflink=auto ${packages."@emnapi/runtime@1.8.1"}/node_modules/@emnapi/runtime/. $out/node_modules/.pnpm/@emnapi+runtime@1.8.1/node_modules/@emnapi/runtime/
    ln -sf ../../tslib@2.8.1/node_modules/tslib $out/node_modules/.pnpm/@emnapi+runtime@1.8.1/node_modules/tslib
    mkdir -p $out/node_modules/.pnpm/@emnapi+wasi-threads@1.1.0/node_modules/@emnapi/wasi-threads
    cp -r --reflink=auto ${packages."@emnapi/wasi-threads@1.1.0"}/node_modules/@emnapi/wasi-threads/. $out/node_modules/.pnpm/@emnapi+wasi-threads@1.1.0/node_modules/@emnapi/wasi-threads/
    ln -sf ../../tslib@2.8.1/node_modules/tslib $out/node_modules/.pnpm/@emnapi+wasi-threads@1.1.0/node_modules/tslib
    mkdir -p $out/node_modules/.pnpm/@jridgewell+gen-mapping@0.3.13/node_modules/@jridgewell/gen-mapping
    cp -r --reflink=auto ${packages."@jridgewell/gen-mapping@0.3.13"}/node_modules/@jridgewell/gen-mapping/. $out/node_modules/.pnpm/@jridgewell+gen-mapping@0.3.13/node_modules/@jridgewell/gen-mapping/
    mkdir -p $out/node_modules/.pnpm/@jridgewell+gen-mapping@0.3.13/node_modules/@jridgewell
    ln -sf ../../@jridgewell+sourcemap-codec@1.5.5/node_modules/@jridgewell/sourcemap-codec $out/node_modules/.pnpm/@jridgewell+gen-mapping@0.3.13/node_modules/@jridgewell/sourcemap-codec
    mkdir -p $out/node_modules/.pnpm/@jridgewell+gen-mapping@0.3.13/node_modules/@jridgewell
    ln -sf ../../@jridgewell+trace-mapping@0.3.31/node_modules/@jridgewell/trace-mapping $out/node_modules/.pnpm/@jridgewell+gen-mapping@0.3.13/node_modules/@jridgewell/trace-mapping
    mkdir -p $out/node_modules/.pnpm/@jridgewell+resolve-uri@3.1.2/node_modules/@jridgewell/resolve-uri
    cp -r --reflink=auto ${packages."@jridgewell/resolve-uri@3.1.2"}/node_modules/@jridgewell/resolve-uri/. $out/node_modules/.pnpm/@jridgewell+resolve-uri@3.1.2/node_modules/@jridgewell/resolve-uri/
    mkdir -p $out/node_modules/.pnpm/@jridgewell+sourcemap-codec@1.5.5/node_modules/@jridgewell/sourcemap-codec
    cp -r --reflink=auto ${packages."@jridgewell/sourcemap-codec@1.5.5"}/node_modules/@jridgewell/sourcemap-codec/. $out/node_modules/.pnpm/@jridgewell+sourcemap-codec@1.5.5/node_modules/@jridgewell/sourcemap-codec/
    mkdir -p $out/node_modules/.pnpm/@jridgewell+trace-mapping@0.3.31/node_modules/@jridgewell/trace-mapping
    cp -r --reflink=auto ${packages."@jridgewell/trace-mapping@0.3.31"}/node_modules/@jridgewell/trace-mapping/. $out/node_modules/.pnpm/@jridgewell+trace-mapping@0.3.31/node_modules/@jridgewell/trace-mapping/
    mkdir -p $out/node_modules/.pnpm/@jridgewell+trace-mapping@0.3.31/node_modules/@jridgewell
    ln -sf ../../@jridgewell+resolve-uri@3.1.2/node_modules/@jridgewell/resolve-uri $out/node_modules/.pnpm/@jridgewell+trace-mapping@0.3.31/node_modules/@jridgewell/resolve-uri
    mkdir -p $out/node_modules/.pnpm/@jridgewell+trace-mapping@0.3.31/node_modules/@jridgewell
    ln -sf ../../@jridgewell+sourcemap-codec@1.5.5/node_modules/@jridgewell/sourcemap-codec $out/node_modules/.pnpm/@jridgewell+trace-mapping@0.3.31/node_modules/@jridgewell/sourcemap-codec
    mkdir -p $out/node_modules/.pnpm/@napi-rs+wasm-runtime@1.1.1/node_modules/@napi-rs/wasm-runtime
    cp -r --reflink=auto ${packages."@napi-rs/wasm-runtime@1.1.1"}/node_modules/@napi-rs/wasm-runtime/. $out/node_modules/.pnpm/@napi-rs+wasm-runtime@1.1.1/node_modules/@napi-rs/wasm-runtime/
    mkdir -p $out/node_modules/.pnpm/@napi-rs+wasm-runtime@1.1.1/node_modules/@emnapi
    ln -sf ../../@emnapi+core@1.8.1/node_modules/@emnapi/core $out/node_modules/.pnpm/@napi-rs+wasm-runtime@1.1.1/node_modules/@emnapi/core
    mkdir -p $out/node_modules/.pnpm/@napi-rs+wasm-runtime@1.1.1/node_modules/@emnapi
    ln -sf ../../@emnapi+runtime@1.8.1/node_modules/@emnapi/runtime $out/node_modules/.pnpm/@napi-rs+wasm-runtime@1.1.1/node_modules/@emnapi/runtime
    mkdir -p $out/node_modules/.pnpm/@napi-rs+wasm-runtime@1.1.1/node_modules/@tybys
    ln -sf ../../@tybys+wasm-util@0.10.1/node_modules/@tybys/wasm-util $out/node_modules/.pnpm/@napi-rs+wasm-runtime@1.1.1/node_modules/@tybys/wasm-util
    mkdir -p $out/node_modules/.pnpm/@oxc-project+types@0.112.0/node_modules/@oxc-project/types
    cp -r --reflink=auto ${packages."@oxc-project/types@0.112.0"}/node_modules/@oxc-project/types/. $out/node_modules/.pnpm/@oxc-project+types@0.112.0/node_modules/@oxc-project/types/
    mkdir -p $out/node_modules/.pnpm/@quansync+fs@1.0.0/node_modules/@quansync/fs
    cp -r --reflink=auto ${packages."@quansync/fs@1.0.0"}/node_modules/@quansync/fs/. $out/node_modules/.pnpm/@quansync+fs@1.0.0/node_modules/@quansync/fs/
    ln -sf ../../quansync@1.0.0/node_modules/quansync $out/node_modules/.pnpm/@quansync+fs@1.0.0/node_modules/quansync
    mkdir -p $out/node_modules/.pnpm/@rolldown+binding-android-arm64@1.0.0-rc.3/node_modules/@rolldown/binding-android-arm64
    cp -r --reflink=auto ${packages."@rolldown/binding-android-arm64@1.0.0-rc.3"}/node_modules/@rolldown/binding-android-arm64/. $out/node_modules/.pnpm/@rolldown+binding-android-arm64@1.0.0-rc.3/node_modules/@rolldown/binding-android-arm64/
    mkdir -p $out/node_modules/.pnpm/@rolldown+binding-darwin-arm64@1.0.0-rc.3/node_modules/@rolldown/binding-darwin-arm64
    cp -r --reflink=auto ${packages."@rolldown/binding-darwin-arm64@1.0.0-rc.3"}/node_modules/@rolldown/binding-darwin-arm64/. $out/node_modules/.pnpm/@rolldown+binding-darwin-arm64@1.0.0-rc.3/node_modules/@rolldown/binding-darwin-arm64/
    mkdir -p $out/node_modules/.pnpm/@rolldown+binding-darwin-x64@1.0.0-rc.3/node_modules/@rolldown/binding-darwin-x64
    cp -r --reflink=auto ${packages."@rolldown/binding-darwin-x64@1.0.0-rc.3"}/node_modules/@rolldown/binding-darwin-x64/. $out/node_modules/.pnpm/@rolldown+binding-darwin-x64@1.0.0-rc.3/node_modules/@rolldown/binding-darwin-x64/
    mkdir -p $out/node_modules/.pnpm/@rolldown+binding-freebsd-x64@1.0.0-rc.3/node_modules/@rolldown/binding-freebsd-x64
    cp -r --reflink=auto ${packages."@rolldown/binding-freebsd-x64@1.0.0-rc.3"}/node_modules/@rolldown/binding-freebsd-x64/. $out/node_modules/.pnpm/@rolldown+binding-freebsd-x64@1.0.0-rc.3/node_modules/@rolldown/binding-freebsd-x64/
    mkdir -p $out/node_modules/.pnpm/@rolldown+binding-linux-arm-gnueabihf@1.0.0-rc.3/node_modules/@rolldown/binding-linux-arm-gnueabihf
    cp -r --reflink=auto ${packages."@rolldown/binding-linux-arm-gnueabihf@1.0.0-rc.3"}/node_modules/@rolldown/binding-linux-arm-gnueabihf/. $out/node_modules/.pnpm/@rolldown+binding-linux-arm-gnueabihf@1.0.0-rc.3/node_modules/@rolldown/binding-linux-arm-gnueabihf/
    mkdir -p $out/node_modules/.pnpm/@rolldown+binding-linux-arm64-gnu@1.0.0-rc.3/node_modules/@rolldown/binding-linux-arm64-gnu
    cp -r --reflink=auto ${packages."@rolldown/binding-linux-arm64-gnu@1.0.0-rc.3"}/node_modules/@rolldown/binding-linux-arm64-gnu/. $out/node_modules/.pnpm/@rolldown+binding-linux-arm64-gnu@1.0.0-rc.3/node_modules/@rolldown/binding-linux-arm64-gnu/
    mkdir -p $out/node_modules/.pnpm/@rolldown+binding-linux-arm64-musl@1.0.0-rc.3/node_modules/@rolldown/binding-linux-arm64-musl
    cp -r --reflink=auto ${packages."@rolldown/binding-linux-arm64-musl@1.0.0-rc.3"}/node_modules/@rolldown/binding-linux-arm64-musl/. $out/node_modules/.pnpm/@rolldown+binding-linux-arm64-musl@1.0.0-rc.3/node_modules/@rolldown/binding-linux-arm64-musl/
    mkdir -p $out/node_modules/.pnpm/@rolldown+binding-linux-x64-gnu@1.0.0-rc.3/node_modules/@rolldown/binding-linux-x64-gnu
    cp -r --reflink=auto ${packages."@rolldown/binding-linux-x64-gnu@1.0.0-rc.3"}/node_modules/@rolldown/binding-linux-x64-gnu/. $out/node_modules/.pnpm/@rolldown+binding-linux-x64-gnu@1.0.0-rc.3/node_modules/@rolldown/binding-linux-x64-gnu/
    mkdir -p $out/node_modules/.pnpm/@rolldown+binding-linux-x64-musl@1.0.0-rc.3/node_modules/@rolldown/binding-linux-x64-musl
    cp -r --reflink=auto ${packages."@rolldown/binding-linux-x64-musl@1.0.0-rc.3"}/node_modules/@rolldown/binding-linux-x64-musl/. $out/node_modules/.pnpm/@rolldown+binding-linux-x64-musl@1.0.0-rc.3/node_modules/@rolldown/binding-linux-x64-musl/
    mkdir -p $out/node_modules/.pnpm/@rolldown+binding-openharmony-arm64@1.0.0-rc.3/node_modules/@rolldown/binding-openharmony-arm64
    cp -r --reflink=auto ${packages."@rolldown/binding-openharmony-arm64@1.0.0-rc.3"}/node_modules/@rolldown/binding-openharmony-arm64/. $out/node_modules/.pnpm/@rolldown+binding-openharmony-arm64@1.0.0-rc.3/node_modules/@rolldown/binding-openharmony-arm64/
    mkdir -p $out/node_modules/.pnpm/@rolldown+binding-wasm32-wasi@1.0.0-rc.3/node_modules/@rolldown/binding-wasm32-wasi
    cp -r --reflink=auto ${packages."@rolldown/binding-wasm32-wasi@1.0.0-rc.3"}/node_modules/@rolldown/binding-wasm32-wasi/. $out/node_modules/.pnpm/@rolldown+binding-wasm32-wasi@1.0.0-rc.3/node_modules/@rolldown/binding-wasm32-wasi/
    mkdir -p $out/node_modules/.pnpm/@rolldown+binding-wasm32-wasi@1.0.0-rc.3/node_modules/@napi-rs
    ln -sf ../../@napi-rs+wasm-runtime@1.1.1/node_modules/@napi-rs/wasm-runtime $out/node_modules/.pnpm/@rolldown+binding-wasm32-wasi@1.0.0-rc.3/node_modules/@napi-rs/wasm-runtime
    mkdir -p $out/node_modules/.pnpm/@rolldown+binding-win32-arm64-msvc@1.0.0-rc.3/node_modules/@rolldown/binding-win32-arm64-msvc
    cp -r --reflink=auto ${packages."@rolldown/binding-win32-arm64-msvc@1.0.0-rc.3"}/node_modules/@rolldown/binding-win32-arm64-msvc/. $out/node_modules/.pnpm/@rolldown+binding-win32-arm64-msvc@1.0.0-rc.3/node_modules/@rolldown/binding-win32-arm64-msvc/
    mkdir -p $out/node_modules/.pnpm/@rolldown+binding-win32-x64-msvc@1.0.0-rc.3/node_modules/@rolldown/binding-win32-x64-msvc
    cp -r --reflink=auto ${packages."@rolldown/binding-win32-x64-msvc@1.0.0-rc.3"}/node_modules/@rolldown/binding-win32-x64-msvc/. $out/node_modules/.pnpm/@rolldown+binding-win32-x64-msvc@1.0.0-rc.3/node_modules/@rolldown/binding-win32-x64-msvc/
    mkdir -p $out/node_modules/.pnpm/@rolldown+pluginutils@1.0.0-rc.3/node_modules/@rolldown/pluginutils
    cp -r --reflink=auto ${packages."@rolldown/pluginutils@1.0.0-rc.3"}/node_modules/@rolldown/pluginutils/. $out/node_modules/.pnpm/@rolldown+pluginutils@1.0.0-rc.3/node_modules/@rolldown/pluginutils/
    mkdir -p $out/node_modules/.pnpm/@tybys+wasm-util@0.10.1/node_modules/@tybys/wasm-util
    cp -r --reflink=auto ${packages."@tybys/wasm-util@0.10.1"}/node_modules/@tybys/wasm-util/. $out/node_modules/.pnpm/@tybys+wasm-util@0.10.1/node_modules/@tybys/wasm-util/
    ln -sf ../../tslib@2.8.1/node_modules/tslib $out/node_modules/.pnpm/@tybys+wasm-util@0.10.1/node_modules/tslib
    mkdir -p $out/node_modules/.pnpm/@types+estree@1.0.8/node_modules/@types/estree
    cp -r --reflink=auto ${packages."@types/estree@1.0.8"}/node_modules/@types/estree/. $out/node_modules/.pnpm/@types+estree@1.0.8/node_modules/@types/estree/
    mkdir -p $out/node_modules/.pnpm/@types+jsesc@2.5.1/node_modules/@types/jsesc
    cp -r --reflink=auto ${packages."@types/jsesc@2.5.1"}/node_modules/@types/jsesc/. $out/node_modules/.pnpm/@types+jsesc@2.5.1/node_modules/@types/jsesc/
    mkdir -p $out/node_modules/.pnpm/ansis@4.2.0/node_modules/ansis
    cp -r --reflink=auto ${packages."ansis@4.2.0"}/node_modules/ansis/. $out/node_modules/.pnpm/ansis@4.2.0/node_modules/ansis/
    mkdir -p $out/node_modules/.pnpm/ast-kit@3.0.0-beta.1/node_modules/ast-kit
    cp -r --reflink=auto ${packages."ast-kit@3.0.0-beta.1"}/node_modules/ast-kit/. $out/node_modules/.pnpm/ast-kit@3.0.0-beta.1/node_modules/ast-kit/
    mkdir -p $out/node_modules/.pnpm/ast-kit@3.0.0-beta.1/node_modules/@babel
    ln -sf ../../@babel+parser@8.0.0-rc.1/node_modules/@babel/parser $out/node_modules/.pnpm/ast-kit@3.0.0-beta.1/node_modules/@babel/parser
    ln -sf ../../estree-walker@3.0.3/node_modules/estree-walker $out/node_modules/.pnpm/ast-kit@3.0.0-beta.1/node_modules/estree-walker
    ln -sf ../../pathe@2.0.3/node_modules/pathe $out/node_modules/.pnpm/ast-kit@3.0.0-beta.1/node_modules/pathe
    mkdir -p $out/node_modules/.pnpm/birpc@4.0.0/node_modules/birpc
    cp -r --reflink=auto ${packages."birpc@4.0.0"}/node_modules/birpc/. $out/node_modules/.pnpm/birpc@4.0.0/node_modules/birpc/
    mkdir -p $out/node_modules/.pnpm/cac@6.7.14/node_modules/cac
    cp -r --reflink=auto ${packages."cac@6.7.14"}/node_modules/cac/. $out/node_modules/.pnpm/cac@6.7.14/node_modules/cac/
    mkdir -p $out/node_modules/.pnpm/defu@6.1.4/node_modules/defu
    cp -r --reflink=auto ${packages."defu@6.1.4"}/node_modules/defu/. $out/node_modules/.pnpm/defu@6.1.4/node_modules/defu/
    mkdir -p $out/node_modules/.pnpm/dts-resolver@2.1.3/node_modules/dts-resolver
    cp -r --reflink=auto ${packages."dts-resolver@2.1.3"}/node_modules/dts-resolver/. $out/node_modules/.pnpm/dts-resolver@2.1.3/node_modules/dts-resolver/
    mkdir -p $out/node_modules/.pnpm/empathic@2.0.0/node_modules/empathic
    cp -r --reflink=auto ${packages."empathic@2.0.0"}/node_modules/empathic/. $out/node_modules/.pnpm/empathic@2.0.0/node_modules/empathic/
    mkdir -p $out/node_modules/.pnpm/estree-walker@3.0.3/node_modules/estree-walker
    cp -r --reflink=auto ${packages."estree-walker@3.0.3"}/node_modules/estree-walker/. $out/node_modules/.pnpm/estree-walker@3.0.3/node_modules/estree-walker/
    mkdir -p $out/node_modules/.pnpm/estree-walker@3.0.3/node_modules/@types
    ln -sf ../../@types+estree@1.0.8/node_modules/@types/estree $out/node_modules/.pnpm/estree-walker@3.0.3/node_modules/@types/estree
    mkdir -p $out/node_modules/.pnpm/fdir@6.5.0/node_modules/fdir
    cp -r --reflink=auto ${packages."fdir@6.5.0"}/node_modules/fdir/. $out/node_modules/.pnpm/fdir@6.5.0/node_modules/fdir/
    mkdir -p $out/node_modules/.pnpm/get-tsconfig@4.13.6/node_modules/get-tsconfig
    cp -r --reflink=auto ${packages."get-tsconfig@4.13.6"}/node_modules/get-tsconfig/. $out/node_modules/.pnpm/get-tsconfig@4.13.6/node_modules/get-tsconfig/
    ln -sf ../../resolve-pkg-maps@1.0.0/node_modules/resolve-pkg-maps $out/node_modules/.pnpm/get-tsconfig@4.13.6/node_modules/resolve-pkg-maps
    mkdir -p $out/node_modules/.pnpm/hookable@6.0.1/node_modules/hookable
    cp -r --reflink=auto ${packages."hookable@6.0.1"}/node_modules/hookable/. $out/node_modules/.pnpm/hookable@6.0.1/node_modules/hookable/
    mkdir -p $out/node_modules/.pnpm/import-without-cache@0.2.5/node_modules/import-without-cache
    cp -r --reflink=auto ${packages."import-without-cache@0.2.5"}/node_modules/import-without-cache/. $out/node_modules/.pnpm/import-without-cache@0.2.5/node_modules/import-without-cache/
    mkdir -p $out/node_modules/.pnpm/jsesc@3.1.0/node_modules/jsesc
    cp -r --reflink=auto ${packages."jsesc@3.1.0"}/node_modules/jsesc/. $out/node_modules/.pnpm/jsesc@3.1.0/node_modules/jsesc/
    mkdir -p $out/node_modules/.pnpm/obug@2.1.1/node_modules/obug
    cp -r --reflink=auto ${packages."obug@2.1.1"}/node_modules/obug/. $out/node_modules/.pnpm/obug@2.1.1/node_modules/obug/
    mkdir -p $out/node_modules/.pnpm/pathe@2.0.3/node_modules/pathe
    cp -r --reflink=auto ${packages."pathe@2.0.3"}/node_modules/pathe/. $out/node_modules/.pnpm/pathe@2.0.3/node_modules/pathe/
    mkdir -p $out/node_modules/.pnpm/picomatch@4.0.3/node_modules/picomatch
    cp -r --reflink=auto ${packages."picomatch@4.0.3"}/node_modules/picomatch/. $out/node_modules/.pnpm/picomatch@4.0.3/node_modules/picomatch/
    mkdir -p $out/node_modules/.pnpm/quansync@1.0.0/node_modules/quansync
    cp -r --reflink=auto ${packages."quansync@1.0.0"}/node_modules/quansync/. $out/node_modules/.pnpm/quansync@1.0.0/node_modules/quansync/
    mkdir -p $out/node_modules/.pnpm/resolve-pkg-maps@1.0.0/node_modules/resolve-pkg-maps
    cp -r --reflink=auto ${packages."resolve-pkg-maps@1.0.0"}/node_modules/resolve-pkg-maps/. $out/node_modules/.pnpm/resolve-pkg-maps@1.0.0/node_modules/resolve-pkg-maps/
    mkdir -p $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/rolldown
    cp -r --reflink=auto ${packages."rolldown@1.0.0-rc.3"}/node_modules/rolldown/. $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/rolldown/
    mkdir -p $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@oxc-project
    ln -sf ../../@oxc-project+types@0.112.0/node_modules/@oxc-project/types $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@oxc-project/types
    mkdir -p $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown
    ln -sf ../../@rolldown+pluginutils@1.0.0-rc.3/node_modules/@rolldown/pluginutils $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown/pluginutils
    mkdir -p $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown
    ln -sf ../../@rolldown+binding-android-arm64@1.0.0-rc.3/node_modules/@rolldown/binding-android-arm64 $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown/binding-android-arm64
    mkdir -p $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown
    ln -sf ../../@rolldown+binding-darwin-arm64@1.0.0-rc.3/node_modules/@rolldown/binding-darwin-arm64 $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown/binding-darwin-arm64
    mkdir -p $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown
    ln -sf ../../@rolldown+binding-darwin-x64@1.0.0-rc.3/node_modules/@rolldown/binding-darwin-x64 $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown/binding-darwin-x64
    mkdir -p $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown
    ln -sf ../../@rolldown+binding-freebsd-x64@1.0.0-rc.3/node_modules/@rolldown/binding-freebsd-x64 $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown/binding-freebsd-x64
    mkdir -p $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown
    ln -sf ../../@rolldown+binding-linux-arm-gnueabihf@1.0.0-rc.3/node_modules/@rolldown/binding-linux-arm-gnueabihf $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown/binding-linux-arm-gnueabihf
    mkdir -p $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown
    ln -sf ../../@rolldown+binding-linux-arm64-gnu@1.0.0-rc.3/node_modules/@rolldown/binding-linux-arm64-gnu $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown/binding-linux-arm64-gnu
    mkdir -p $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown
    ln -sf ../../@rolldown+binding-linux-arm64-musl@1.0.0-rc.3/node_modules/@rolldown/binding-linux-arm64-musl $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown/binding-linux-arm64-musl
    mkdir -p $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown
    ln -sf ../../@rolldown+binding-linux-x64-gnu@1.0.0-rc.3/node_modules/@rolldown/binding-linux-x64-gnu $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown/binding-linux-x64-gnu
    mkdir -p $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown
    ln -sf ../../@rolldown+binding-linux-x64-musl@1.0.0-rc.3/node_modules/@rolldown/binding-linux-x64-musl $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown/binding-linux-x64-musl
    mkdir -p $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown
    ln -sf ../../@rolldown+binding-openharmony-arm64@1.0.0-rc.3/node_modules/@rolldown/binding-openharmony-arm64 $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown/binding-openharmony-arm64
    mkdir -p $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown
    ln -sf ../../@rolldown+binding-wasm32-wasi@1.0.0-rc.3/node_modules/@rolldown/binding-wasm32-wasi $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown/binding-wasm32-wasi
    mkdir -p $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown
    ln -sf ../../@rolldown+binding-win32-arm64-msvc@1.0.0-rc.3/node_modules/@rolldown/binding-win32-arm64-msvc $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown/binding-win32-arm64-msvc
    mkdir -p $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown
    ln -sf ../../@rolldown+binding-win32-x64-msvc@1.0.0-rc.3/node_modules/@rolldown/binding-win32-x64-msvc $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/@rolldown/binding-win32-x64-msvc
    mkdir -p $out/node_modules/.pnpm/rolldown-plugin-dts@0.22.1/node_modules/rolldown-plugin-dts
    cp -r --reflink=auto ${packages."rolldown-plugin-dts@0.22.1"}/node_modules/rolldown-plugin-dts/. $out/node_modules/.pnpm/rolldown-plugin-dts@0.22.1/node_modules/rolldown-plugin-dts/
    mkdir -p $out/node_modules/.pnpm/semver@7.7.4/node_modules/semver
    cp -r --reflink=auto ${packages."semver@7.7.4"}/node_modules/semver/. $out/node_modules/.pnpm/semver@7.7.4/node_modules/semver/
    mkdir -p $out/node_modules/.pnpm/tinyexec@1.0.2/node_modules/tinyexec
    cp -r --reflink=auto ${packages."tinyexec@1.0.2"}/node_modules/tinyexec/. $out/node_modules/.pnpm/tinyexec@1.0.2/node_modules/tinyexec/
    mkdir -p $out/node_modules/.pnpm/tinyglobby@0.2.15/node_modules/tinyglobby
    cp -r --reflink=auto ${packages."tinyglobby@0.2.15"}/node_modules/tinyglobby/. $out/node_modules/.pnpm/tinyglobby@0.2.15/node_modules/tinyglobby/
    ln -sf ../../picomatch@4.0.3/node_modules/picomatch $out/node_modules/.pnpm/tinyglobby@0.2.15/node_modules/picomatch
    mkdir -p $out/node_modules/.pnpm/tree-kill@1.2.2/node_modules/tree-kill
    cp -r --reflink=auto ${packages."tree-kill@1.2.2"}/node_modules/tree-kill/. $out/node_modules/.pnpm/tree-kill@1.2.2/node_modules/tree-kill/
    mkdir -p $out/node_modules/.pnpm/tsdown@0.20.3/node_modules/tsdown
    cp -r --reflink=auto ${packages."tsdown@0.20.3"}/node_modules/tsdown/. $out/node_modules/.pnpm/tsdown@0.20.3/node_modules/tsdown/
    mkdir -p $out/node_modules/.pnpm/tslib@2.8.1/node_modules/tslib
    cp -r --reflink=auto ${packages."tslib@2.8.1"}/node_modules/tslib/. $out/node_modules/.pnpm/tslib@2.8.1/node_modules/tslib/
    mkdir -p $out/node_modules/.pnpm/typescript@5.9.3/node_modules/typescript
    cp -r --reflink=auto ${packages."typescript@5.9.3"}/node_modules/typescript/. $out/node_modules/.pnpm/typescript@5.9.3/node_modules/typescript/
    mkdir -p $out/node_modules/.pnpm/unconfig-core@7.4.2/node_modules/unconfig-core
    cp -r --reflink=auto ${packages."unconfig-core@7.4.2"}/node_modules/unconfig-core/. $out/node_modules/.pnpm/unconfig-core@7.4.2/node_modules/unconfig-core/
    mkdir -p $out/node_modules/.pnpm/unconfig-core@7.4.2/node_modules/@quansync
    ln -sf ../../@quansync+fs@1.0.0/node_modules/@quansync/fs $out/node_modules/.pnpm/unconfig-core@7.4.2/node_modules/@quansync/fs
    ln -sf ../../quansync@1.0.0/node_modules/quansync $out/node_modules/.pnpm/unconfig-core@7.4.2/node_modules/quansync
    mkdir -p $out/node_modules/.pnpm/unrun@0.2.27/node_modules/unrun
    cp -r --reflink=auto ${packages."unrun@0.2.27"}/node_modules/unrun/. $out/node_modules/.pnpm/unrun@0.2.27/node_modules/unrun/
    ln -sf ../../rolldown@1.0.0-rc.3/node_modules/rolldown $out/node_modules/.pnpm/unrun@0.2.27/node_modules/rolldown

    # top-level symlinks
    mkdir -p $out/node_modules/@babel
    ln -sf ../.pnpm/@babel+generator@8.0.0-rc.1/node_modules/@babel/generator $out/node_modules/@babel/generator
    mkdir -p $out/node_modules/@babel
    ln -sf ../.pnpm/@babel+helper-string-parser@8.0.0-rc.1/node_modules/@babel/helper-string-parser $out/node_modules/@babel/helper-string-parser
    mkdir -p $out/node_modules/@babel
    ln -sf ../.pnpm/@babel+helper-validator-identifier@8.0.0-rc.1/node_modules/@babel/helper-validator-identifier $out/node_modules/@babel/helper-validator-identifier
    mkdir -p $out/node_modules/@babel
    ln -sf ../.pnpm/@babel+parser@8.0.0-rc.1/node_modules/@babel/parser $out/node_modules/@babel/parser
    mkdir -p $out/node_modules/@babel
    ln -sf ../.pnpm/@babel+types@8.0.0-rc.1/node_modules/@babel/types $out/node_modules/@babel/types
    mkdir -p $out/node_modules/@emnapi
    ln -sf ../.pnpm/@emnapi+core@1.8.1/node_modules/@emnapi/core $out/node_modules/@emnapi/core
    mkdir -p $out/node_modules/@emnapi
    ln -sf ../.pnpm/@emnapi+runtime@1.8.1/node_modules/@emnapi/runtime $out/node_modules/@emnapi/runtime
    mkdir -p $out/node_modules/@emnapi
    ln -sf ../.pnpm/@emnapi+wasi-threads@1.1.0/node_modules/@emnapi/wasi-threads $out/node_modules/@emnapi/wasi-threads
    mkdir -p $out/node_modules/@jridgewell
    ln -sf ../.pnpm/@jridgewell+gen-mapping@0.3.13/node_modules/@jridgewell/gen-mapping $out/node_modules/@jridgewell/gen-mapping
    mkdir -p $out/node_modules/@jridgewell
    ln -sf ../.pnpm/@jridgewell+resolve-uri@3.1.2/node_modules/@jridgewell/resolve-uri $out/node_modules/@jridgewell/resolve-uri
    mkdir -p $out/node_modules/@jridgewell
    ln -sf ../.pnpm/@jridgewell+sourcemap-codec@1.5.5/node_modules/@jridgewell/sourcemap-codec $out/node_modules/@jridgewell/sourcemap-codec
    mkdir -p $out/node_modules/@jridgewell
    ln -sf ../.pnpm/@jridgewell+trace-mapping@0.3.31/node_modules/@jridgewell/trace-mapping $out/node_modules/@jridgewell/trace-mapping
    mkdir -p $out/node_modules/@napi-rs
    ln -sf ../.pnpm/@napi-rs+wasm-runtime@1.1.1/node_modules/@napi-rs/wasm-runtime $out/node_modules/@napi-rs/wasm-runtime
    mkdir -p $out/node_modules/@oxc-project
    ln -sf ../.pnpm/@oxc-project+types@0.112.0/node_modules/@oxc-project/types $out/node_modules/@oxc-project/types
    mkdir -p $out/node_modules/@quansync
    ln -sf ../.pnpm/@quansync+fs@1.0.0/node_modules/@quansync/fs $out/node_modules/@quansync/fs
    mkdir -p $out/node_modules/@rolldown
    ln -sf ../.pnpm/@rolldown+binding-android-arm64@1.0.0-rc.3/node_modules/@rolldown/binding-android-arm64 $out/node_modules/@rolldown/binding-android-arm64
    mkdir -p $out/node_modules/@rolldown
    ln -sf ../.pnpm/@rolldown+binding-darwin-arm64@1.0.0-rc.3/node_modules/@rolldown/binding-darwin-arm64 $out/node_modules/@rolldown/binding-darwin-arm64
    mkdir -p $out/node_modules/@rolldown
    ln -sf ../.pnpm/@rolldown+binding-darwin-x64@1.0.0-rc.3/node_modules/@rolldown/binding-darwin-x64 $out/node_modules/@rolldown/binding-darwin-x64
    mkdir -p $out/node_modules/@rolldown
    ln -sf ../.pnpm/@rolldown+binding-freebsd-x64@1.0.0-rc.3/node_modules/@rolldown/binding-freebsd-x64 $out/node_modules/@rolldown/binding-freebsd-x64
    mkdir -p $out/node_modules/@rolldown
    ln -sf ../.pnpm/@rolldown+binding-linux-arm-gnueabihf@1.0.0-rc.3/node_modules/@rolldown/binding-linux-arm-gnueabihf $out/node_modules/@rolldown/binding-linux-arm-gnueabihf
    mkdir -p $out/node_modules/@rolldown
    ln -sf ../.pnpm/@rolldown+binding-linux-arm64-gnu@1.0.0-rc.3/node_modules/@rolldown/binding-linux-arm64-gnu $out/node_modules/@rolldown/binding-linux-arm64-gnu
    mkdir -p $out/node_modules/@rolldown
    ln -sf ../.pnpm/@rolldown+binding-linux-arm64-musl@1.0.0-rc.3/node_modules/@rolldown/binding-linux-arm64-musl $out/node_modules/@rolldown/binding-linux-arm64-musl
    mkdir -p $out/node_modules/@rolldown
    ln -sf ../.pnpm/@rolldown+binding-linux-x64-gnu@1.0.0-rc.3/node_modules/@rolldown/binding-linux-x64-gnu $out/node_modules/@rolldown/binding-linux-x64-gnu
    mkdir -p $out/node_modules/@rolldown
    ln -sf ../.pnpm/@rolldown+binding-linux-x64-musl@1.0.0-rc.3/node_modules/@rolldown/binding-linux-x64-musl $out/node_modules/@rolldown/binding-linux-x64-musl
    mkdir -p $out/node_modules/@rolldown
    ln -sf ../.pnpm/@rolldown+binding-openharmony-arm64@1.0.0-rc.3/node_modules/@rolldown/binding-openharmony-arm64 $out/node_modules/@rolldown/binding-openharmony-arm64
    mkdir -p $out/node_modules/@rolldown
    ln -sf ../.pnpm/@rolldown+binding-wasm32-wasi@1.0.0-rc.3/node_modules/@rolldown/binding-wasm32-wasi $out/node_modules/@rolldown/binding-wasm32-wasi
    mkdir -p $out/node_modules/@rolldown
    ln -sf ../.pnpm/@rolldown+binding-win32-arm64-msvc@1.0.0-rc.3/node_modules/@rolldown/binding-win32-arm64-msvc $out/node_modules/@rolldown/binding-win32-arm64-msvc
    mkdir -p $out/node_modules/@rolldown
    ln -sf ../.pnpm/@rolldown+binding-win32-x64-msvc@1.0.0-rc.3/node_modules/@rolldown/binding-win32-x64-msvc $out/node_modules/@rolldown/binding-win32-x64-msvc
    mkdir -p $out/node_modules/@rolldown
    ln -sf ../.pnpm/@rolldown+pluginutils@1.0.0-rc.3/node_modules/@rolldown/pluginutils $out/node_modules/@rolldown/pluginutils
    mkdir -p $out/node_modules/@tybys
    ln -sf ../.pnpm/@tybys+wasm-util@0.10.1/node_modules/@tybys/wasm-util $out/node_modules/@tybys/wasm-util
    mkdir -p $out/node_modules/@types
    ln -sf ../.pnpm/@types+estree@1.0.8/node_modules/@types/estree $out/node_modules/@types/estree
    mkdir -p $out/node_modules/@types
    ln -sf ../.pnpm/@types+jsesc@2.5.1/node_modules/@types/jsesc $out/node_modules/@types/jsesc
    ln -sf .pnpm/ansis@4.2.0/node_modules/ansis $out/node_modules/ansis
    ln -sf .pnpm/ast-kit@3.0.0-beta.1/node_modules/ast-kit $out/node_modules/ast-kit
    ln -sf .pnpm/birpc@4.0.0/node_modules/birpc $out/node_modules/birpc
    ln -sf .pnpm/cac@6.7.14/node_modules/cac $out/node_modules/cac
    ln -sf .pnpm/defu@6.1.4/node_modules/defu $out/node_modules/defu
    ln -sf .pnpm/dts-resolver@2.1.3/node_modules/dts-resolver $out/node_modules/dts-resolver
    ln -sf .pnpm/empathic@2.0.0/node_modules/empathic $out/node_modules/empathic
    ln -sf .pnpm/estree-walker@3.0.3/node_modules/estree-walker $out/node_modules/estree-walker
    ln -sf .pnpm/fdir@6.5.0/node_modules/fdir $out/node_modules/fdir
    ln -sf .pnpm/get-tsconfig@4.13.6/node_modules/get-tsconfig $out/node_modules/get-tsconfig
    ln -sf .pnpm/hookable@6.0.1/node_modules/hookable $out/node_modules/hookable
    ln -sf .pnpm/import-without-cache@0.2.5/node_modules/import-without-cache $out/node_modules/import-without-cache
    ln -sf .pnpm/jsesc@3.1.0/node_modules/jsesc $out/node_modules/jsesc
    ln -sf .pnpm/obug@2.1.1/node_modules/obug $out/node_modules/obug
    ln -sf .pnpm/pathe@2.0.3/node_modules/pathe $out/node_modules/pathe
    ln -sf .pnpm/picomatch@4.0.3/node_modules/picomatch $out/node_modules/picomatch
    ln -sf .pnpm/quansync@1.0.0/node_modules/quansync $out/node_modules/quansync
    ln -sf .pnpm/resolve-pkg-maps@1.0.0/node_modules/resolve-pkg-maps $out/node_modules/resolve-pkg-maps
    ln -sf .pnpm/rolldown@1.0.0-rc.3/node_modules/rolldown $out/node_modules/rolldown
    ln -sf .pnpm/rolldown-plugin-dts@0.22.1/node_modules/rolldown-plugin-dts $out/node_modules/rolldown-plugin-dts
    ln -sf .pnpm/semver@7.7.4/node_modules/semver $out/node_modules/semver
    ln -sf .pnpm/tinyexec@1.0.2/node_modules/tinyexec $out/node_modules/tinyexec
    ln -sf .pnpm/tinyglobby@0.2.15/node_modules/tinyglobby $out/node_modules/tinyglobby
    ln -sf .pnpm/tree-kill@1.2.2/node_modules/tree-kill $out/node_modules/tree-kill
    ln -sf .pnpm/tsdown@0.20.3/node_modules/tsdown $out/node_modules/tsdown
    ln -sf .pnpm/tslib@2.8.1/node_modules/tslib $out/node_modules/tslib
    ln -sf .pnpm/typescript@5.9.3/node_modules/typescript $out/node_modules/typescript
    ln -sf .pnpm/unconfig-core@7.4.2/node_modules/unconfig-core $out/node_modules/unconfig-core
    ln -sf .pnpm/unrun@0.2.27/node_modules/unrun $out/node_modules/unrun

    # bin links
    if [ -d ${packages."@babel/generator@8.0.0-rc.1"}/node_modules/.bin ]; then
      for b in ${packages."@babel/generator@8.0.0-rc.1"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@babel+generator@8.0.0-rc.1/node_modules/@babel/generator/$(readlink $b | sed "s|.*node_modules/@babel/generator/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@babel/helper-string-parser@8.0.0-rc.1"}/node_modules/.bin ]; then
      for b in ${packages."@babel/helper-string-parser@8.0.0-rc.1"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@babel+helper-string-parser@8.0.0-rc.1/node_modules/@babel/helper-string-parser/$(readlink $b | sed "s|.*node_modules/@babel/helper-string-parser/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@babel/helper-validator-identifier@8.0.0-rc.1"}/node_modules/.bin ]; then
      for b in ${packages."@babel/helper-validator-identifier@8.0.0-rc.1"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@babel+helper-validator-identifier@8.0.0-rc.1/node_modules/@babel/helper-validator-identifier/$(readlink $b | sed "s|.*node_modules/@babel/helper-validator-identifier/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@babel/parser@8.0.0-rc.1"}/node_modules/.bin ]; then
      for b in ${packages."@babel/parser@8.0.0-rc.1"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@babel+parser@8.0.0-rc.1/node_modules/@babel/parser/$(readlink $b | sed "s|.*node_modules/@babel/parser/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@babel/types@8.0.0-rc.1"}/node_modules/.bin ]; then
      for b in ${packages."@babel/types@8.0.0-rc.1"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@babel+types@8.0.0-rc.1/node_modules/@babel/types/$(readlink $b | sed "s|.*node_modules/@babel/types/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@emnapi/core@1.8.1"}/node_modules/.bin ]; then
      for b in ${packages."@emnapi/core@1.8.1"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@emnapi+core@1.8.1/node_modules/@emnapi/core/$(readlink $b | sed "s|.*node_modules/@emnapi/core/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@emnapi/runtime@1.8.1"}/node_modules/.bin ]; then
      for b in ${packages."@emnapi/runtime@1.8.1"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@emnapi+runtime@1.8.1/node_modules/@emnapi/runtime/$(readlink $b | sed "s|.*node_modules/@emnapi/runtime/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@emnapi/wasi-threads@1.1.0"}/node_modules/.bin ]; then
      for b in ${packages."@emnapi/wasi-threads@1.1.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@emnapi+wasi-threads@1.1.0/node_modules/@emnapi/wasi-threads/$(readlink $b | sed "s|.*node_modules/@emnapi/wasi-threads/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@jridgewell/gen-mapping@0.3.13"}/node_modules/.bin ]; then
      for b in ${packages."@jridgewell/gen-mapping@0.3.13"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@jridgewell+gen-mapping@0.3.13/node_modules/@jridgewell/gen-mapping/$(readlink $b | sed "s|.*node_modules/@jridgewell/gen-mapping/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@jridgewell/resolve-uri@3.1.2"}/node_modules/.bin ]; then
      for b in ${packages."@jridgewell/resolve-uri@3.1.2"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@jridgewell+resolve-uri@3.1.2/node_modules/@jridgewell/resolve-uri/$(readlink $b | sed "s|.*node_modules/@jridgewell/resolve-uri/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@jridgewell/sourcemap-codec@1.5.5"}/node_modules/.bin ]; then
      for b in ${packages."@jridgewell/sourcemap-codec@1.5.5"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@jridgewell+sourcemap-codec@1.5.5/node_modules/@jridgewell/sourcemap-codec/$(readlink $b | sed "s|.*node_modules/@jridgewell/sourcemap-codec/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@jridgewell/trace-mapping@0.3.31"}/node_modules/.bin ]; then
      for b in ${packages."@jridgewell/trace-mapping@0.3.31"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@jridgewell+trace-mapping@0.3.31/node_modules/@jridgewell/trace-mapping/$(readlink $b | sed "s|.*node_modules/@jridgewell/trace-mapping/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@napi-rs/wasm-runtime@1.1.1"}/node_modules/.bin ]; then
      for b in ${packages."@napi-rs/wasm-runtime@1.1.1"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@napi-rs+wasm-runtime@1.1.1/node_modules/@napi-rs/wasm-runtime/$(readlink $b | sed "s|.*node_modules/@napi-rs/wasm-runtime/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@oxc-project/types@0.112.0"}/node_modules/.bin ]; then
      for b in ${packages."@oxc-project/types@0.112.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@oxc-project+types@0.112.0/node_modules/@oxc-project/types/$(readlink $b | sed "s|.*node_modules/@oxc-project/types/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@quansync/fs@1.0.0"}/node_modules/.bin ]; then
      for b in ${packages."@quansync/fs@1.0.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@quansync+fs@1.0.0/node_modules/@quansync/fs/$(readlink $b | sed "s|.*node_modules/@quansync/fs/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@rolldown/binding-android-arm64@1.0.0-rc.3"}/node_modules/.bin ]; then
      for b in ${packages."@rolldown/binding-android-arm64@1.0.0-rc.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@rolldown+binding-android-arm64@1.0.0-rc.3/node_modules/@rolldown/binding-android-arm64/$(readlink $b | sed "s|.*node_modules/@rolldown/binding-android-arm64/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@rolldown/binding-darwin-arm64@1.0.0-rc.3"}/node_modules/.bin ]; then
      for b in ${packages."@rolldown/binding-darwin-arm64@1.0.0-rc.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@rolldown+binding-darwin-arm64@1.0.0-rc.3/node_modules/@rolldown/binding-darwin-arm64/$(readlink $b | sed "s|.*node_modules/@rolldown/binding-darwin-arm64/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@rolldown/binding-darwin-x64@1.0.0-rc.3"}/node_modules/.bin ]; then
      for b in ${packages."@rolldown/binding-darwin-x64@1.0.0-rc.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@rolldown+binding-darwin-x64@1.0.0-rc.3/node_modules/@rolldown/binding-darwin-x64/$(readlink $b | sed "s|.*node_modules/@rolldown/binding-darwin-x64/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@rolldown/binding-freebsd-x64@1.0.0-rc.3"}/node_modules/.bin ]; then
      for b in ${packages."@rolldown/binding-freebsd-x64@1.0.0-rc.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@rolldown+binding-freebsd-x64@1.0.0-rc.3/node_modules/@rolldown/binding-freebsd-x64/$(readlink $b | sed "s|.*node_modules/@rolldown/binding-freebsd-x64/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@rolldown/binding-linux-arm-gnueabihf@1.0.0-rc.3"}/node_modules/.bin ]; then
      for b in ${packages."@rolldown/binding-linux-arm-gnueabihf@1.0.0-rc.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@rolldown+binding-linux-arm-gnueabihf@1.0.0-rc.3/node_modules/@rolldown/binding-linux-arm-gnueabihf/$(readlink $b | sed "s|.*node_modules/@rolldown/binding-linux-arm-gnueabihf/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@rolldown/binding-linux-arm64-gnu@1.0.0-rc.3"}/node_modules/.bin ]; then
      for b in ${packages."@rolldown/binding-linux-arm64-gnu@1.0.0-rc.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@rolldown+binding-linux-arm64-gnu@1.0.0-rc.3/node_modules/@rolldown/binding-linux-arm64-gnu/$(readlink $b | sed "s|.*node_modules/@rolldown/binding-linux-arm64-gnu/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@rolldown/binding-linux-arm64-musl@1.0.0-rc.3"}/node_modules/.bin ]; then
      for b in ${packages."@rolldown/binding-linux-arm64-musl@1.0.0-rc.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@rolldown+binding-linux-arm64-musl@1.0.0-rc.3/node_modules/@rolldown/binding-linux-arm64-musl/$(readlink $b | sed "s|.*node_modules/@rolldown/binding-linux-arm64-musl/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@rolldown/binding-linux-x64-gnu@1.0.0-rc.3"}/node_modules/.bin ]; then
      for b in ${packages."@rolldown/binding-linux-x64-gnu@1.0.0-rc.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@rolldown+binding-linux-x64-gnu@1.0.0-rc.3/node_modules/@rolldown/binding-linux-x64-gnu/$(readlink $b | sed "s|.*node_modules/@rolldown/binding-linux-x64-gnu/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@rolldown/binding-linux-x64-musl@1.0.0-rc.3"}/node_modules/.bin ]; then
      for b in ${packages."@rolldown/binding-linux-x64-musl@1.0.0-rc.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@rolldown+binding-linux-x64-musl@1.0.0-rc.3/node_modules/@rolldown/binding-linux-x64-musl/$(readlink $b | sed "s|.*node_modules/@rolldown/binding-linux-x64-musl/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@rolldown/binding-openharmony-arm64@1.0.0-rc.3"}/node_modules/.bin ]; then
      for b in ${packages."@rolldown/binding-openharmony-arm64@1.0.0-rc.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@rolldown+binding-openharmony-arm64@1.0.0-rc.3/node_modules/@rolldown/binding-openharmony-arm64/$(readlink $b | sed "s|.*node_modules/@rolldown/binding-openharmony-arm64/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@rolldown/binding-wasm32-wasi@1.0.0-rc.3"}/node_modules/.bin ]; then
      for b in ${packages."@rolldown/binding-wasm32-wasi@1.0.0-rc.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@rolldown+binding-wasm32-wasi@1.0.0-rc.3/node_modules/@rolldown/binding-wasm32-wasi/$(readlink $b | sed "s|.*node_modules/@rolldown/binding-wasm32-wasi/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@rolldown/binding-win32-arm64-msvc@1.0.0-rc.3"}/node_modules/.bin ]; then
      for b in ${packages."@rolldown/binding-win32-arm64-msvc@1.0.0-rc.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@rolldown+binding-win32-arm64-msvc@1.0.0-rc.3/node_modules/@rolldown/binding-win32-arm64-msvc/$(readlink $b | sed "s|.*node_modules/@rolldown/binding-win32-arm64-msvc/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@rolldown/binding-win32-x64-msvc@1.0.0-rc.3"}/node_modules/.bin ]; then
      for b in ${packages."@rolldown/binding-win32-x64-msvc@1.0.0-rc.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@rolldown+binding-win32-x64-msvc@1.0.0-rc.3/node_modules/@rolldown/binding-win32-x64-msvc/$(readlink $b | sed "s|.*node_modules/@rolldown/binding-win32-x64-msvc/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@rolldown/pluginutils@1.0.0-rc.3"}/node_modules/.bin ]; then
      for b in ${packages."@rolldown/pluginutils@1.0.0-rc.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@rolldown+pluginutils@1.0.0-rc.3/node_modules/@rolldown/pluginutils/$(readlink $b | sed "s|.*node_modules/@rolldown/pluginutils/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@tybys/wasm-util@0.10.1"}/node_modules/.bin ]; then
      for b in ${packages."@tybys/wasm-util@0.10.1"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@tybys+wasm-util@0.10.1/node_modules/@tybys/wasm-util/$(readlink $b | sed "s|.*node_modules/@tybys/wasm-util/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@types/estree@1.0.8"}/node_modules/.bin ]; then
      for b in ${packages."@types/estree@1.0.8"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@types+estree@1.0.8/node_modules/@types/estree/$(readlink $b | sed "s|.*node_modules/@types/estree/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."@types/jsesc@2.5.1"}/node_modules/.bin ]; then
      for b in ${packages."@types/jsesc@2.5.1"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/@types+jsesc@2.5.1/node_modules/@types/jsesc/$(readlink $b | sed "s|.*node_modules/@types/jsesc/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."ansis@4.2.0"}/node_modules/.bin ]; then
      for b in ${packages."ansis@4.2.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/ansis@4.2.0/node_modules/ansis/$(readlink $b | sed "s|.*node_modules/ansis/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."ast-kit@3.0.0-beta.1"}/node_modules/.bin ]; then
      for b in ${packages."ast-kit@3.0.0-beta.1"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/ast-kit@3.0.0-beta.1/node_modules/ast-kit/$(readlink $b | sed "s|.*node_modules/ast-kit/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."birpc@4.0.0"}/node_modules/.bin ]; then
      for b in ${packages."birpc@4.0.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/birpc@4.0.0/node_modules/birpc/$(readlink $b | sed "s|.*node_modules/birpc/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."cac@6.7.14"}/node_modules/.bin ]; then
      for b in ${packages."cac@6.7.14"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/cac@6.7.14/node_modules/cac/$(readlink $b | sed "s|.*node_modules/cac/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."defu@6.1.4"}/node_modules/.bin ]; then
      for b in ${packages."defu@6.1.4"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/defu@6.1.4/node_modules/defu/$(readlink $b | sed "s|.*node_modules/defu/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."dts-resolver@2.1.3"}/node_modules/.bin ]; then
      for b in ${packages."dts-resolver@2.1.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/dts-resolver@2.1.3/node_modules/dts-resolver/$(readlink $b | sed "s|.*node_modules/dts-resolver/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."empathic@2.0.0"}/node_modules/.bin ]; then
      for b in ${packages."empathic@2.0.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/empathic@2.0.0/node_modules/empathic/$(readlink $b | sed "s|.*node_modules/empathic/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."estree-walker@3.0.3"}/node_modules/.bin ]; then
      for b in ${packages."estree-walker@3.0.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/estree-walker@3.0.3/node_modules/estree-walker/$(readlink $b | sed "s|.*node_modules/estree-walker/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."fdir@6.5.0"}/node_modules/.bin ]; then
      for b in ${packages."fdir@6.5.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/fdir@6.5.0/node_modules/fdir/$(readlink $b | sed "s|.*node_modules/fdir/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."get-tsconfig@4.13.6"}/node_modules/.bin ]; then
      for b in ${packages."get-tsconfig@4.13.6"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/get-tsconfig@4.13.6/node_modules/get-tsconfig/$(readlink $b | sed "s|.*node_modules/get-tsconfig/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."hookable@6.0.1"}/node_modules/.bin ]; then
      for b in ${packages."hookable@6.0.1"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/hookable@6.0.1/node_modules/hookable/$(readlink $b | sed "s|.*node_modules/hookable/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."import-without-cache@0.2.5"}/node_modules/.bin ]; then
      for b in ${packages."import-without-cache@0.2.5"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/import-without-cache@0.2.5/node_modules/import-without-cache/$(readlink $b | sed "s|.*node_modules/import-without-cache/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."jsesc@3.1.0"}/node_modules/.bin ]; then
      for b in ${packages."jsesc@3.1.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/jsesc@3.1.0/node_modules/jsesc/$(readlink $b | sed "s|.*node_modules/jsesc/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."obug@2.1.1"}/node_modules/.bin ]; then
      for b in ${packages."obug@2.1.1"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/obug@2.1.1/node_modules/obug/$(readlink $b | sed "s|.*node_modules/obug/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."pathe@2.0.3"}/node_modules/.bin ]; then
      for b in ${packages."pathe@2.0.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/pathe@2.0.3/node_modules/pathe/$(readlink $b | sed "s|.*node_modules/pathe/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."picomatch@4.0.3"}/node_modules/.bin ]; then
      for b in ${packages."picomatch@4.0.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/picomatch@4.0.3/node_modules/picomatch/$(readlink $b | sed "s|.*node_modules/picomatch/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."quansync@1.0.0"}/node_modules/.bin ]; then
      for b in ${packages."quansync@1.0.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/quansync@1.0.0/node_modules/quansync/$(readlink $b | sed "s|.*node_modules/quansync/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."resolve-pkg-maps@1.0.0"}/node_modules/.bin ]; then
      for b in ${packages."resolve-pkg-maps@1.0.0"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/resolve-pkg-maps@1.0.0/node_modules/resolve-pkg-maps/$(readlink $b | sed "s|.*node_modules/resolve-pkg-maps/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."rolldown@1.0.0-rc.3"}/node_modules/.bin ]; then
      for b in ${packages."rolldown@1.0.0-rc.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/rolldown@1.0.0-rc.3/node_modules/rolldown/$(readlink $b | sed "s|.*node_modules/rolldown/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."rolldown-plugin-dts@0.22.1"}/node_modules/.bin ]; then
      for b in ${packages."rolldown-plugin-dts@0.22.1"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/rolldown-plugin-dts@0.22.1/node_modules/rolldown-plugin-dts/$(readlink $b | sed "s|.*node_modules/rolldown-plugin-dts/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."semver@7.7.4"}/node_modules/.bin ]; then
      for b in ${packages."semver@7.7.4"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/semver@7.7.4/node_modules/semver/$(readlink $b | sed "s|.*node_modules/semver/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."tinyexec@1.0.2"}/node_modules/.bin ]; then
      for b in ${packages."tinyexec@1.0.2"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/tinyexec@1.0.2/node_modules/tinyexec/$(readlink $b | sed "s|.*node_modules/tinyexec/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."tinyglobby@0.2.15"}/node_modules/.bin ]; then
      for b in ${packages."tinyglobby@0.2.15"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/tinyglobby@0.2.15/node_modules/tinyglobby/$(readlink $b | sed "s|.*node_modules/tinyglobby/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."tree-kill@1.2.2"}/node_modules/.bin ]; then
      for b in ${packages."tree-kill@1.2.2"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/tree-kill@1.2.2/node_modules/tree-kill/$(readlink $b | sed "s|.*node_modules/tree-kill/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."tsdown@0.20.3"}/node_modules/.bin ]; then
      for b in ${packages."tsdown@0.20.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/tsdown@0.20.3/node_modules/tsdown/$(readlink $b | sed "s|.*node_modules/tsdown/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."tslib@2.8.1"}/node_modules/.bin ]; then
      for b in ${packages."tslib@2.8.1"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/tslib@2.8.1/node_modules/tslib/$(readlink $b | sed "s|.*node_modules/tslib/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."typescript@5.9.3"}/node_modules/.bin ]; then
      for b in ${packages."typescript@5.9.3"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/typescript@5.9.3/node_modules/typescript/$(readlink $b | sed "s|.*node_modules/typescript/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."unconfig-core@7.4.2"}/node_modules/.bin ]; then
      for b in ${packages."unconfig-core@7.4.2"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/unconfig-core@7.4.2/node_modules/unconfig-core/$(readlink $b | sed "s|.*node_modules/unconfig-core/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
    if [ -d ${packages."unrun@0.2.27"}/node_modules/.bin ]; then
      for b in ${packages."unrun@0.2.27"}/node_modules/.bin/*; do
        bname=$(basename $b)
        ln -sf $out/node_modules/.pnpm/unrun@0.2.27/node_modules/unrun/$(readlink $b | sed "s|.*node_modules/unrun/||" ) $out/node_modules/.bin/$bname 2>/dev/null || true
      done
    fi
  '';

  # Core sync logic (sentinel check, copy, pnpm metadata)
  # NOTE: Does NOT include 'export NODE_PATH' — that only works in
  # sourced contexts (devShell), not executed contexts (syncScript/dev.yml meet)
  syncBash = ''
    _onix_nm="${nodeModules}"
    _onix_sentinel="node_modules/.nix-sentinel"

    if [ ! -f "$_onix_sentinel" ] || [ "$(cat "$_onix_sentinel" 2>/dev/null)" != "$_onix_nm" ]; then
      # Remove stale node_modules if sentinel exists (derivation changed)
      if [ -f "$_onix_sentinel" ]; then
        chmod -R u+w node_modules 2>/dev/null; rm -rf node_modules
      fi

      # Sync: copy symlink tree from Nix store
      cp -rP "$_onix_nm/node_modules" node_modules

      # Make the copied tree writable (pnpm needs write access to subdirs)
      chmod -R u+w node_modules

      # Copy lockfile as pnpm's "current lockfile" (what's installed = what's desired)
      # pnpm compares this with pnpm-lock.yaml using deep structural equality
      # after YAML parse — an exact file copy guarantees match.
      if [ -f pnpm-lock.yaml ]; then
        cp pnpm-lock.yaml node_modules/.pnpm/lock.yaml
      fi

      # Generate pnpm metadata so headless install sees matching state.
      # The .modules.yaml tells pnpm about its settings; the workspace state
      # tells the optimistic fast-path that deps were already validated.
      if command -v pnpm >/dev/null 2>&1; then
        _pnpm_version=$(pnpm --version 2>/dev/null || echo "9.0.0")
        _store_dir=$(pnpm store path 2>/dev/null || echo "''${XDG_DATA_HOME:-$HOME/.local/share}/pnpm/store/v3")

        cat > node_modules/.modules.yaml << MODULES
hoistedDependencies: {}
included:
  dependencies: true
  devDependencies: true
  optionalDependencies: true
layoutVersion: 5
nodeLinker: isolated
packageManager: pnpm@$_pnpm_version
pendingBuilds: []
prunedAt: $(date -u '+%a, %d %b %Y %H:%M:%S GMT')
registries:
  default: https://registry.npmjs.org/
skipped: []
storeDir: $_store_dir
virtualStoreDir: .pnpm
virtualStoreDirMaxLength: 120
MODULES
      fi

      # Write sentinel
      echo "$_onix_nm" > "$_onix_sentinel"
      # shellcheck disable=SC2012
      echo "onix: node_modules ready ($(ls node_modules/.pnpm/ | wc -l | tr -d ' ') packages)"
    fi
  '';
in packages // {
  inherit nodeModules;

  # Standalone script for dev.yml meet — runs as subprocess
  # Uses writeShellApplication for build-time shellcheck validation
  syncScript = pkgs.writeShellApplication {
    name = "tsdown-starter-onix-sync";
    text = syncBash;
  };

  # devShell — shellHook is sourced, so NODE_PATH export works here
  devShell = { buildInputs ? [], shellHook ? "", ... }@args:
    pkgs.mkShell (builtins.removeAttrs args ["buildInputs" "shellHook"] // {
      name = "tsdown-starter-devshell";
      buildInputs = [ nodejs ] ++ buildInputs;
      shellHook = syncBash + ''
        export NODE_PATH="$PWD/node_modules"
      '' + shellHook;
    });
}
