# eslint-plugin-import-x — generated by onix. Do not edit.
{
  "4.16.1(@typescript-eslint/utils@8.54.0(eslint@9.39.2(jiti@2.6.1)(ms@2.1.3))(ms@2.1.3)(typescript@5.9.3))(eslint@9.39.2(jiti@2.6.1)(ms@2.1.3))(ms@2.1.3)" = {
    version = "4.16.1(@typescript-eslint/utils@8.54.0(eslint@9.39.2(jiti@2.6.1)(ms@2.1.3))(ms@2.1.3)(typescript@5.9.3))(eslint@9.39.2(jiti@2.6.1)(ms@2.1.3))(ms@2.1.3)";
    source = "pnpm";
    deps = [ "@typescript-eslint/types" "comment-parser" "debug" "eslint" "eslint-import-context" "is-glob" "minimatch" "semver" "stable-hash-x" "unrs-resolver" ];
    groups = [ "development" ];
  };
}
