# vite — generated by onix. Do not edit.
{
  "link:packages/vite" = {
    version = "link:packages/vite";
    source = "link";
    deps = [  ];
    groups = [ "development" ];
    path = "packages/vite";
  };
}
