# frozen_string_literal: true

module Onix
  module Commands
    # Node-specific generation methods, included by Generate.
    module NodeGenerator
      private

      # ── Node prefetch ─────────────────────────────────────────

      def prefetch_npm(packages, jobs, hashes, progress)
        errors = []
        mutex = Mutex.new
        queue = Queue.new
        packages.each { |p| queue << p }
        jobs.times { queue << nil }

        threads = jobs.times.map do
          Thread.new do
            while (e = queue.pop)
              # Use exact tarball URL from lockfile when available (private registries),
              # otherwise construct from registry URL
              url = if e.tarball
                e.tarball
              else
                basename = e.name.include?("/") ? e.name.split("/").last : e.name
                "#{e.remote}/#{e.name}/-/#{basename}-#{e.version}.tgz"
              end
              # Use .npmrc auth for private registries, fall back to scint credentials
              auth_url = @npmrc ? @npmrc.inject_auth(url) : inject_credentials(url)
              sha256 = nix_prefetch_url(auth_url)

              key = "#{e.name}/#{e.version}"
              mutex.synchronize do
                if sha256
                  hashes[key] = sha256
                  progress.advance
                else
                  errors << "#{e.name} #{e.version}: failed to prefetch"
                  progress.advance(success: false)
                end
              end
            end
          end
        end
        threads.each(&:join)
        errors
      end

      # ── Node nix writers ─────────────────────────────────────

      def write_npm_nix(dir, name, entries, sha256_for)
        nix = +"# #{name} — generated by onix. Do not edit.\n{\n"

        entries.sort_by(&:version).each do |e|
          sha256 = sha256_for["#{e.name}/#{e.version}"]
          nix << "  #{nix_str e.version} = {\n"
          nix << "    version = #{nix_str e.version};\n"

          if e.source == "git"
            nix << "    source = {\n"
            nix << "      type = \"git\";\n"
            nix << "      url = #{nix_str e.uri};\n"
            nix << "      rev = #{nix_str e.rev};\n"
            nix << "      sha256 = #{nix_str sha256};\n"
            nix << "    };\n"
            nix << "    subdir = #{nix_str e.subdir};\n" if e.subdir && e.subdir != "."
          else
            nix << "    source = {\n"
            nix << "      type = \"tarball\";\n"
            nix << "      remotes = [ #{nix_str e.remote} ];\n"
            nix << "      sha256 = #{nix_str sha256};\n"
            nix << "      url = #{nix_str e.tarball};\n" if e.tarball
            nix << "    };\n"
          end

          if e.bin && !e.bin.empty?
            nix << "    bin = {\n"
            e.bin.sort.each do |bin_name, bin_path|
              nix << "      #{nix_str bin_name} = #{nix_str bin_path};\n"
            end
            nix << "    };\n"
          end

          nix << "    hasNative = true;\n" if e.has_native
          nix << "  };\n"
        end

        nix << "}\n"
        safe_name = entries.first.safe_nix_filename
        File.write(File.join(dir, "#{safe_name}.nix"), nix)
      end

      def write_node_project_nix(dir, project_name, entries, meta)
        buildable = entries.reject { |e| e.source == "builtin" || e.source == "path" }

        # Build dep graph: "name@version" => entry
        entry_by_key = {}
        buildable.each { |e| entry_by_key["#{e.name}@#{e.version}"] = e }

        # Collect top-level packages (one per name, last version wins)
        top_level = {}
        buildable.each { |e| top_level[e.name] = e }

        # Deduplicated, sorted package list
        unique_packages = buildable.uniq { |e| [e.name, e.version] }
                                   .sort_by { |e| [e.name, e.version] }

        nix = +"# #{project_name} — generated by onix. Do not edit.\n"
        nix << "#\n"
        nix << "# pnpm-style node_modules layout:\n"
        nix << "#   node_modules/.pnpm/<name>@<version>/node_modules/<name>  <- package contents\n"
        nix << "#   node_modules/.pnpm/<name>@<version>/node_modules/<dep>   <- symlink to dep's .pnpm entry\n"
        nix << "#   node_modules/<name>                                      <- symlink to .pnpm entry\n"
        nix << "#\n"
        # Use node version from meta if available, otherwise default to nodejs_22
        nodejs_attr = "nodejs_22"
        if meta&.node
          major = meta.node.to_s.split(".").first
          nodejs_attr = "nodejs_#{major}" if major.to_i >= 18
        end
        nix << "{ pkgs ? import <nixpkgs> {}, nodejs ? pkgs.#{nodejs_attr} }:\n"
        nix << "let\n"
        nix << "  buildNpm = import ./build-npm.nix { inherit pkgs nodejs; };\n"
        nix << "  buildPackageByName = name:\n"
        nix << "    let\n"
        nix << "      versions = import (./node + \"/\${name}.nix\");\n"
        nix << "      version = builtins.head (builtins.attrNames versions);\n"
        nix << "      spec = versions.\${version};\n"
        nix << "    in buildNpm (spec // { pkgName = name; });\n"
        nix << "  npmConfig = import ./npm-config.nix {\n"
        nix << "    inherit pkgs nodejs;\n"
        nix << "    overlayDir = ../overlays;\n"
        nix << "    nodeDir = ./node;\n"
        nix << "    buildPackageFn = buildPackageByName;\n"
        nix << "  };\n"
        nix << "\n"
        nix << "  build = name: version:\n"
        nix << "    let\n"
        nix << "      safeName = builtins.replaceStrings [\"/\" \"@\"] [\"--\" \"\"] name;\n"
        nix << "      versions = import (./node + \"/\${safeName}.nix\");\n"
        nix << "      spec = versions.\${version};\n"
        nix << "      config = npmConfig.\${name} or {};\n"
        nix << "    in buildNpm (spec // {\n"
        nix << "      pkgName = name;\n"
        nix << "      hasNative = (spec.hasNative or false) || (config ? deps && config.deps != []);\n"
        nix << "      nativeBuildInputs = config.deps or [];\n"
        nix << "      buildFlags = config.buildFlags or \"\";\n"
        nix << "      beforeBuild = config.beforeBuild or \"\";\n"
        nix << "      afterBuild = config.afterBuild or \"\";\n"
        nix << "    } // (if config ? buildPhase then { inherit (config) buildPhase; } else {})\n"
        nix << "      // (if config ? postInstall then { inherit (config) postInstall; } else {})\n"
        nix << "      // (if config ? skip then { inherit (config) skip; } else {})\n"
        nix << "      // (if config ? buildPackages then { inherit (config) buildPackages; } else {}));\n"
        nix << "\n"
        nix << "  # Per-package derivations (used by .pnpm/ entries)\n"
        nix << "  packages = {\n"
        unique_packages.each do |e|
          key = nix_key("#{e.name}@#{e.version}")
          nix << "    #{key} = build #{nix_str e.name} #{nix_str e.version};\n"
        end
        nix << "  };\n"

        # ── Generate pnpm layout shell commands ───────────────────
        pnpm_cmds = []
        bin_cmds = []

        unique_packages.each do |e|
          pnpm_cmds.concat(pnpm_entry_commands(e, entry_by_key))
          bin_cmds.concat(pnpm_bin_commands(e))
        end

        # Top-level symlinks
        top_cmds = top_level.values.sort_by(&:name).flat_map { |e| pnpm_top_level_command(e) }

        nix << "\n"
        nix << "  # pnpm-style .pnpm/ virtual store + top-level symlinks\n"
        nix << "  nodeModules = pkgs.runCommand #{nix_str "#{project_name}-node-modules"} {} ''\n"
        nix << "    mkdir -p $out/node_modules/.pnpm $out/node_modules/.bin\n"
        pnpm_cmds.each { |cmd| nix << "    #{cmd}\n" }
        nix << "\n    # top-level symlinks\n"
        top_cmds.each { |cmd| nix << "    #{cmd}\n" }
        nix << "\n    # bin links\n"
        bin_cmds.each { |cmd| nix << "    #{cmd}\n" }
        nix << "  '';\n"

        nix << "in packages // {\n"
        nix << "  inherit nodeModules;\n"
        nix << "  devShell = { buildInputs ? [], shellHook ? \"\", ... }@args:\n"
        nix << "    pkgs.mkShell (builtins.removeAttrs args [\"buildInputs\" \"shellHook\"] // {\n"
        nix << "      name = #{nix_str "#{project_name}-devshell"};\n"
        nix << "      buildInputs = [ nodejs ] ++ buildInputs;\n"
        nix << "      shellHook = ''\n"
        nix << "        export NODE_PATH=\"${nodeModules}/node_modules\"\n"
        nix << "      '' + shellHook;\n"
        nix << "    });\n"
        nix << "}\n"

        File.write(File.join(dir, "#{project_name}.nix"), nix)
        UI.wrote "nix/#{project_name}.nix"
      end

      # Shell commands for one .pnpm/ entry: create dir, copy contents, link deps.
      def pnpm_entry_commands(entry, entry_by_key)
        cmds = []
        escaped = escape_pnpm_path("#{entry.name}@#{entry.version}")
        pkg_key = nix_key("#{entry.name}@#{entry.version}")
        entry_base = ".pnpm/#{escaped}/node_modules"

        if entry.name.include?("/")
          scope = entry.name.split("/").first
          cmds << "mkdir -p $out/node_modules/#{entry_base}/#{scope}"
        else
          cmds << "mkdir -p $out/node_modules/#{entry_base}"
        end
        cmds << "cp -r ${packages.#{pkg_key}}/node_modules/#{entry.name}/. $out/node_modules/#{entry_base}/#{entry.name}"

        entry.node_deps.each do |dep_name, dep_version|
          dep_key = "#{dep_name}@#{dep_version}"
          next unless entry_by_key.key?(dep_key)

          dep_escaped = escape_pnpm_path(dep_key)
          rel_target = "../../#{dep_escaped}/node_modules/#{dep_name}"

          if dep_name.include?("/")
            dep_scope = dep_name.split("/").first
            cmds << "mkdir -p $out/node_modules/#{entry_base}/#{dep_scope}"
          end
          cmds << "ln -sf #{rel_target} $out/node_modules/#{entry_base}/#{dep_name}"
        end

        cmds
      end

      # Shell commands for bin links from a .pnpm/ entry.
      def pnpm_bin_commands(entry)
        escaped = escape_pnpm_path("#{entry.name}@#{entry.version}")
        pkg_key = nix_key("#{entry.name}@#{entry.version}")
        entry_base = ".pnpm/#{escaped}/node_modules"

        [
          "if [ -d ${packages.#{pkg_key}}/node_modules/.bin ]; then",
          "  for b in ${packages.#{pkg_key}}/node_modules/.bin/*; do",
          "    bname=$(basename $b)",
          "    ln -sf $out/node_modules/#{entry_base}/#{entry.name}/$(readlink $b | sed \"s|.*node_modules/#{entry.name}/||\" ) $out/node_modules/.bin/$bname 2>/dev/null || true",
          "  done",
          "fi",
        ]
      end

      # Shell commands for a top-level symlink into .pnpm/.
      def pnpm_top_level_command(entry)
        escaped = escape_pnpm_path("#{entry.name}@#{entry.version}")
        if entry.name.include?("/")
          scope = entry.name.split("/").first
          [
            "mkdir -p $out/node_modules/#{scope}",
            "ln -sf ../.pnpm/#{escaped}/node_modules/#{entry.name} $out/node_modules/#{entry.name}",
          ]
        else
          ["ln -sf .pnpm/#{escaped}/node_modules/#{entry.name} $out/node_modules/#{entry.name}"]
        end
      end

      # Escape a pnpm snapshot key for filesystem use (matches pnpm behavior).
      def escape_pnpm_path(key)
        key.gsub("/", "+").gsub(/[()#:\\*?"<>|]/, "_")
      end
    end
  end
end
