#!/usr/bin/env bash
set -euo pipefail

dir="$(cd "$(dirname "$0")" && pwd)"
app_dir="/tmp/onix-tests/liquid"

if [ ! -d "$app_dir" ]; then
  echo "Cloning liquid to $app_dir..."
  git clone --depth 1 https://github.com/Shopify/liquid.git "$app_dir"
fi

cd "$app_dir"

exec nix-shell "$dir/devshell.nix" --run "
  rake test
"
