# active_record_query_trace — generated by onix. Do not edit.
{
  "1.8" = {
    version = "1.8";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "19888wjdpqvr2kaci6v6jyjw9pjf682zb1iyx2lz12mpdmy3500n";
    };
  };
}
