# actiontext — generated by onix. Do not edit.
{
  "7.0.8.7" = {
    version = "7.0.8.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1818spc73y96n94jssh77z2w4dnz84sn83ywrk5cicnmjzdx4xfb";
    };
  };
  "7.1.5.2" = {
    version = "7.1.5.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "01q275ihq4gds2yvlbzdpqap95z5divwany0x5lcnqhpc7j7hmjh";
    };
  };
  "8.0.3" = {
    version = "8.0.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1x4xd8h5sdwdm3rc8h2pxxmq4a0i0wa0gk6c56zq58pzc3xgsihw";
    };
  };
  "8.2.0.alpha" = {
    version = "8.2.0.alpha";
    source = {
      type = "git";
      url = "https://github.com/rails/rails.git";
      rev = "60d92e4e7dfe923528ccdccc18820ccfe841b7b8";
      sha256 = "sha256-SzsJ41egLhybFG3+JHcn8tAY3lMfVWg/cmU5gg0G8Hg=";
      fetchSubmodules = false;
    };
    subdir = "actiontext";
  };
}
