# action_text-trix — generated by onix. Do not edit.
{
  "2.1.16" = {
    version = "2.1.16";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "12isf17cd4xyx5vg97nzxsi92703yh40fxyns6gl9f11331a4ign";
    };
  };
}
