# actionpack — generated by onix. Do not edit.
{
  "7.0.8.7" = {
    version = "7.0.8.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0b2y7wy6gx59zb88v1fqiyxdkafrsfma67sx5394yjlhhzbb3rj0";
    };
  };
  "7.1.5.2" = {
    version = "7.1.5.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1za4sv0ch8j7adfldglp8jalcc8s68h031sqldw0f9pbmb4fvgx7";
    };
  };
  "8.0.3" = {
    version = "8.0.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1lsspr8nffzn8qpfmj654w1qja1915x6bnzzhpbjj1cy235j2g6n";
    };
  };
  "8.0.4" = {
    version = "8.0.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1nyd4f58r11b0x5gsjlnyk2k9y2kd0zhv8szf82g9j1j5xccfr03";
    };
  };
  "8.2.0.alpha" = {
    version = "8.2.0.alpha";
    source = {
      type = "git";
      url = "https://github.com/rails/rails.git";
      rev = "60d92e4e7dfe923528ccdccc18820ccfe841b7b8";
      sha256 = "sha256-SzsJ41egLhybFG3+JHcn8tAY3lMfVWg/cmU5gg0G8Hg=";
      fetchSubmodules = false;
    };
    subdir = "actionpack";
  };
}
