# activestorage — generated by onix. Do not edit.
{
  "7.0.8.7" = {
    version = "7.0.8.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1xcy76cwskwfm39lr4cg7bmknc8j0vymp55h8hzrhl1sfdriwhfa";
    };
  };
  "7.1.5.2" = {
    version = "7.1.5.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "163wq77fx38vjdb4jhvfphahnrzdp2kq9ngg02g5y4zaghacp6pd";
    };
  };
  "8.0.3" = {
    version = "8.0.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0plck0b57b9ni8n52hj5slv5n8i7w3nfwq6r47nkb2hjbpmsskjg";
    };
  };
  "8.2.0.alpha" = {
    version = "8.2.0.alpha";
    source = {
      type = "git";
      url = "https://github.com/rails/rails.git";
      rev = "60d92e4e7dfe923528ccdccc18820ccfe841b7b8";
      sha256 = "sha256-SzsJ41egLhybFG3+JHcn8tAY3lMfVWg/cmU5gg0G8Hg=";
      fetchSubmodules = false;
    };
    subdir = "activestorage";
  };
}
