# active_record_union — generated by onix. Do not edit.
{
  "1.3.0" = {
    version = "1.3.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "14l1mb4vmqydbfqq8ny8xcmwb1pn5gdiy33ygz78wg0hca45fpw6";
    };
  };
}
