# active_model_serializers — generated by onix. Do not edit.
{
  "0.8.4" = {
    version = "0.8.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0k3mgia2ahh7mbk30hjq9pzqbk0kh281s91kq2z6p555nv9y6l3k";
    };
  };
  "0.10.16" = {
    version = "0.10.16";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "06h6rknvpapvx8l4sfd72msi422fghhchmqd1jn8zh7a4wd3gdma";
    };
  };
}
