# acts-as-taggable-on — generated by onix. Do not edit.
{
  "10.0.0" = {
    version = "10.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "10yvdqrmykjpfjchnbh7q85vm5fgz20g9ip5iwphl0922rpyjq6k";
    };
  };
  "12.0.0" = {
    version = "12.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "05q44r8yrc9yz00idxmyxgfrfgsanmzcsdkk32bqkvrcc2hiak6i";
    };
  };
}
