# acts_as_follower — generated by onix. Do not edit.
{
  "0.2.1" = {
    version = "0.2.1";
    source = {
      type = "git";
      url = "https://github.com/forem/acts_as_follower.git";
      rev = "06393d3693a1a3d4b390aec4976c8b8f3a81cf01";
      sha256 = "sha256-QTOeldjl104+I5Qx/ajStw2aDU8r2yt5uZIx0Rr782Y=";
      fetchSubmodules = false;
    };
  };
}
