# addressable — generated by onix. Do not edit.
{
  "2.8.7" = {
    version = "2.8.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0cl2qpvwiffym62z991ynks7imsm87qmgxf0yfsmlwzkgi9qcaa6";
    };
  };
  "2.8.8" = {
    version = "2.8.8";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0mxhjgihzsx45l9wh2n0ywl9w0c6k70igm5r0d63dxkcagwvh4vw";
    };
  };
}
