# administrate-field-active_storage — generated by onix. Do not edit.
{
  "1.0.3" = {
    version = "1.0.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1s32js3r0gygj8i3080z6my663xa6xrkg78aqrdwb01jn6c7gs50";
    };
  };
}
