# administrate-field-belongs_to_search — generated by onix. Do not edit.
{
  "0.9.0" = {
    version = "0.9.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1hvafdicccb2svrj5k5q6bgvl4970ijvy4dx3r4ka76r1g5gq0x7";
    };
  };
}
