# administrate — generated by onix. Do not edit.
{
  "0.20.1" = {
    version = "0.20.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1mb7gdzpbsp8w0mrg9gvs2713rjfxdrj2zg6wiplhvj47h0738jb";
    };
  };
}
