# aes_key_wrap — generated by onix. Do not edit.
{
  "1.1.0" = {
    version = "1.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "19bn0y70qm6mfj4y1m0j3s8ggh6dvxwrwrj5vfamhdrpddsz8ddr";
    };
  };
}
