# ai-agents — generated by onix. Do not edit.
{
  "0.7.0" = {
    version = "0.7.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1laaqk1faz2yimw160ybnjq1vi0nw6q5yg10a2rmb4as1icrxscw";
    };
  };
}
