# amq-protocol — generated by onix. Do not edit.
{
  "2.3.2" = {
    version = "2.3.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "05m8vmrhp93j7v2dkhq9sijmh475aymxgmmg7wpnplmfybw5w59x";
    };
  };
}
