# ancestry — generated by onix. Do not edit.
{
  "4.3.3" = {
    version = "4.3.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "183wbrpriw4yamlm5zkng66vm3760s19qnzc5vq9l8aw837nngxg";
    };
  };
}
