# annotaterb — generated by onix. Do not edit.
{
  "4.20.0" = {
    version = "4.20.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1xwbz5zk37f7p3g6ypxzamisay06hidjmdsrvhxw4q0xin4jw6w7";
    };
  };
  "4.21.0" = {
    version = "4.21.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "18wdmkyjiqlichky5798najsdwcbac893ipkm2s8ckz6gdj3pmi9";
    };
  };
}
