# anyway_config — generated by onix. Do not edit.
{
  "2.3.0" = {
    version = "2.3.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "000krhgxl7c3qkc402zwninvlh65m3dj0m23njcr7fpm301d6fa8";
    };
  };
}
