# ast — generated by onix. Do not edit.
{
  "2.4.2" = {
    version = "2.4.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "04nc8x27hlzlrr5c2gn7mar4vdr0apw5xg22wp6m8dx3wqr04a0y";
    };
  };
  "2.4.3" = {
    version = "2.4.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "10yknjyn0728gjn6b5syynvrvrwm66bhssbxq8mkhshxghaiailm";
    };
  };
}
