# attr_extras — generated by onix. Do not edit.
{
  "7.1.0" = {
    version = "7.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "09y83ygjsk4rva8bn9mfb4whjh7q2sl4093n6wnvm1axvnlwjvyr";
    };
  };
}
