# audited — generated by onix. Do not edit.
{
  "5.4.1" = {
    version = "5.4.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0rnpjahkb8lc78pl0lkicns628m6xgdq06sx2vx7gg0l22l9313c";
    };
  };
}
