# aws-partitions — generated by onix. Do not edit.
{
  "1.1134.0" = {
    version = "1.1134.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0gkd4q0bbmw6vah15vkghvij398l7g5yd7570ilk9b3pcwazdx98";
    };
  };
  "1.1150.0" = {
    version = "1.1150.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0rhgbgaj42idhsf07v5k51jap0z1dis2q943izks974bfi1ijhdr";
    };
  };
  "1.1198.0" = {
    version = "1.1198.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1lm28rj9418d4m2q02iqgix5f9nfcbzc81knvn2nnby0czx0vjfw";
    };
  };
  "1.1213.0" = {
    version = "1.1213.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0pp0sagj31zvmv8ca0hf0kgdfb7wwkq733sv2812gvs43pck5hay";
    };
  };
}
