# aws-sdk-core — generated by onix. Do not edit.
{
  "3.227.0" = {
    version = "3.227.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "17n7vw9djnw74x7cgwsxfi0k033l351mf56i7y3lg4yawg2iy1wr";
    };
  };
  "3.230.0" = {
    version = "3.230.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1ah10fvjlp3hjxvlp618qhrni45m606hhqdbqij66gw9q55j08a6";
    };
  };
  "3.240.0" = {
    version = "3.240.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "17hqin6ngvlhhb414pxlq8q95j0fndljcblp09kzbajwaa83idl6";
    };
  };
  "3.242.0" = {
    version = "3.242.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1819b99lgs3i637j2y6f95vlsppw3id2hys3m30q13f7mh1k0yy1";
    };
  };
}
