# aws-sdk-s3 — generated by onix. Do not edit.
{
  "1.182.0" = {
    version = "1.182.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "03a55dbihv6xvgfwhx0f35rwc7q3rr0555vfpxlwpdjw75wkbz6h";
    };
  };
  "1.197.0" = {
    version = "1.197.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0zz8zpwahyzhq7j3xg6msig5ipkdv8708caz4d0qkq1lrmm597mc";
    };
  };
  "1.208.0" = {
    version = "1.208.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0vbxg6hy0j2b931llwc0jxg1q27grbs31zdhzwjy9fki05817kiz";
    };
  };
  "1.213.0" = {
    version = "1.213.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "03g5k3jl0sgp60ppmxa267qflxlj174mrs8hnrnl10j5ak7nqndg";
    };
  };
}
