# aws-sdk-mediaconvert — generated by onix. Do not edit.
{
  "1.165.0" = {
    version = "1.165.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1r0182r7scavikd82v7392mzj2x76cihy7cffz00f14brmqsamfr";
    };
  };
}
