# aws-sdk-kms — generated by onix. Do not edit.
{
  "1.99.0" = {
    version = "1.99.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1a3mh89kfh6flqxw48wfv9wfwkj2zxazw096mqm56wnnzz1jyads";
    };
  };
  "1.110.0" = {
    version = "1.110.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1r55plz8911pvspx7wamlg50x0vsnb1wqyajg9rsw8h4n4zsdd5q";
    };
  };
  "1.118.0" = {
    version = "1.118.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1gbgf7xgg2hrrc51g3mpf0isba801w0r0z45mjnh45agdmcm3iy9";
    };
  };
  "1.121.0" = {
    version = "1.121.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1q015l5gm3f230jz9l6si9s3hlw7ra76q8biqvxlwxdmnk7w2qym";
    };
  };
}
