# aws-sigv4 — generated by onix. Do not edit.
{
  "1.8.0" = {
    version = "1.8.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1g3w27wzjy4si6kp49w10as6ml6g6zl3xrfqs5ikpfciidv9kpc4";
    };
  };
  "1.12.1" = {
    version = "1.12.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "003ch8qzh3mppsxch83ns0jra8d222ahxs96p9cdrl0grfazywv9";
    };
  };
}
