# aws-sdk-sns — generated by onix. Do not edit.
{
  "1.70.0" = {
    version = "1.70.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0zbn3gfksbszgdk806l96fmqa9npqm2gqgvjrqm4x44hl1a5cf8z";
    };
  };
  "1.92.0" = {
    version = "1.92.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1lpiwcjlangrbp43w84nhzcr6j0rr3p3gs7h1yx0n8f9kh2ml0rk";
    };
  };
  "1.96.0" = {
    version = "1.96.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1m3dz9cz7zlwhbd5n5wnsqm00c7khpmbnggvraqq2cf50dr3qazr";
    };
  };
}
