# aws_cf_signer — generated by onix. Do not edit.
{
  "0.1.3" = {
    version = "0.1.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0jh4299w86dlhxwsb6wvbgz5k8l042r66mwpip8yfcbipx9igl73";
    };
  };
}
