# azure-blob — generated by onix. Do not edit.
{
  "0.5.9.1" = {
    version = "0.5.9.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "198ndg8m0w54csxb3fidzpjp491ak9jcrmjc8zmp7axi0ncvbsmx";
    };
  };
}
