# azure-storage-common — generated by onix. Do not edit.
{
  "2.0.4" = {
    version = "2.0.4";
    source = {
      type = "git";
      url = "https://github.com/chatwoot/azure-storage-ruby";
      rev = "9957cf899d33a285b5dfe15bdb875292398e392b";
      sha256 = "sha256-AdI/XLPIu8k0IZEZBX1tSWyqOXhv6zxUiFN5Rk8iNW4=";
      fetchSubmodules = false;
    };
    subdir = "common";
  };
}
