# backport — generated by onix. Do not edit.
{
  "1.2.0" = {
    version = "1.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0xbzzjrgah0f8ifgd449kak2vyf30micpz6x2g82aipfv7ypsb4i";
    };
  };
}
