# barnes — generated by onix. Do not edit.
{
  "0.0.9" = {
    version = "0.0.9";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "16v48b6fkp95m3h6vnwync1fh3wrrkj00nyqn30fxwm5a0zqq562";
    };
  };
}
