# bcp47_spec — generated by onix. Do not edit.
{
  "0.2.1" = {
    version = "0.2.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "043qld01c163yc7fxlar3046dac2833rlcg44jbbs9n1jvgjxmiz";
    };
  };
}
