# bcrypt_pbkdf — generated by onix. Do not edit.
{
  "1.1.1" = {
    version = "1.1.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "04rb3rp9bdxn1y3qiflfpj7ccwb8ghrfbydh5vfz1l9px3fpg41g";
    };
  };
}
