# beaneater — generated by onix. Do not edit.
{
  "1.1.3" = {
    version = "1.1.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1jwa5nn2gfrhi85by6af155paqdcsnjxzk3b91ddi17r9lynggix";
    };
  };
}
