# better_html — generated by onix. Do not edit.
{
  "2.0.2" = {
    version = "2.0.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1sk5s5lpwbd53s4a1xzm02nys3kfqdw5mh9i2qfn04hjsk8wk3gc";
    };
  };
}
