# better_errors — generated by onix. Do not edit.
{
  "2.10.1" = {
    version = "2.10.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0wqazisnn6hn1wsza412xribpw5wzx6b5z5p4mcpfgizr6xg367p";
    };
  };
}
