# bindata — generated by onix. Do not edit.
{
  "2.5.1" = {
    version = "2.5.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0n4ymlgik3xcg94h52dzmh583ss40rl3sn0kni63v56sq8g6l62k";
    };
  };
}
