# binding_of_caller — generated by onix. Do not edit.
{
  "1.0.1" = {
    version = "1.0.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "16mjj15ks5ws53v2y31hxcmf46d0qjdvdaadpk7xsij2zymh4a9b";
    };
  };
}
