# bindex — generated by onix. Do not edit.
{
  "0.8.1" = {
    version = "0.8.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0zmirr3m02p52bzq4xgksq4pn8j641rx5d4czk68pv9rqnfwq7kv";
    };
  };
}
