# blurhash — generated by onix. Do not edit.
{
  "0.1.8" = {
    version = "0.1.8";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1wni86h2mlb7sj51nq3iwsvkrzlaggls9xlf4p9dzr1ns79dphca";
    };
  };
}
