# buftok — generated by onix. Do not edit.
{
  "0.2.0" = {
    version = "0.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1rzsy1vy50v55x9z0nivf23y0r9jkmq6i130xa75pq9i8qrn1mxs";
    };
  };
}
