# builder — generated by onix. Do not edit.
{
  "3.3.0" = {
    version = "3.3.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0pw3r2lyagsxkm71bf44v5b74f7l9r7di22brbyji9fwz791hya9";
    };
  };
}
