# bullet — generated by onix. Do not edit.
{
  "7.1.6" = {
    version = "7.1.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1zs6dwspb0m9ygl7lwdmilhdn9ka85a0qfiip49m9rfpfj46lps0";
    };
  };
  "8.0.7" = {
    version = "8.0.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1wbrwdg80d3rg2ggrsplbv6z639kmf1z8rk15kl412dkh475a83x";
    };
  };
  "8.1.0" = {
    version = "8.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1zwq7g98c1mdigahb50c980a0fcc4ib1m9ivmgf3f8gc6qk7wjv0";
    };
  };
}
