# bundle-audit — generated by onix. Do not edit.
{
  "0.1.0" = {
    version = "0.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0hvs3blinwd1ngqpf27p8rzim32r11xwhsdy6yl1ns6y1j98bw68";
    };
  };
}
