# byebug — generated by onix. Do not edit.
{
  "11.1.3" = {
    version = "11.1.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0nx3yjf4xzdgb8jkmk2344081gqr22pgjqnmjg2q64mj5d6r9194";
    };
  };
}
