# capybara-playwright-driver — generated by onix. Do not edit.
{
  "0.5.7" = {
    version = "0.5.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0hnjmbhyvfs543g96bc4sx94fdx2054ng12g925vwmkx0wl1jnl7";
    };
  };
}
