# carrierwave-bombshelter — generated by onix. Do not edit.
{
  "0.2.2" = {
    version = "0.2.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1796vq23nlq06n3vd4jka678r0wfiv8l51rygrald2fwhkr1q90v";
    };
  };
}
