# carrierwave — generated by onix. Do not edit.
{
  "2.2.6" = {
    version = "2.2.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1hysq3ymzx7jz06xsvw1jqyg42cs66yn3idwgxzfji3mzh4636yd";
    };
  };
}
