# charlock_holmes — generated by onix. Do not edit.
{
  "0.7.9" = {
    version = "0.7.9";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1c1dws56r7p8y363dhyikg7205z59a3bn4amnv2y488rrq8qm7ml";
    };
  };
}
