# chartkick — generated by onix. Do not edit.
{
  "4.2.1" = {
    version = "4.2.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1lh0jxb59nymikl415iv5ac1d5iaknwych59vwwnjxbbjh77rz3l";
    };
  };
}
