# chef-utils — generated by onix. Do not edit.
{
  "18.6.2" = {
    version = "18.6.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0jl32d5fbll7zw2iq8wlqp2xvrmlsvf0jkxs1m4irzfhqa7s1l6l";
    };
  };
}
