# chewy — generated by onix. Do not edit.
{
  "7.6.0" = {
    version = "7.6.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0kgqj7hcs09ln7i1rds1xify08rzjk02ryzvjdvnllg1fkh3vm2b";
    };
  };
}
