# childprocess — generated by onix. Do not edit.
{
  "5.1.0" = {
    version = "5.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1v5nalaarxnfdm6rxb7q6fmc6nx097jd630ax6h9ch7xw95li3cs";
    };
  };
}
