# chunky_png — generated by onix. Do not edit.
{
  "1.4.0" = {
    version = "1.4.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1znw5x86hmm9vfhidwdsijz8m38pqgmv98l9ryilvky0aldv7mc9";
    };
  };
}
