# coderay — generated by onix. Do not edit.
{
  "1.1.3" = {
    version = "1.1.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0jvxqxzply1lwp7ysn94zjhh57vc14mcshw1ygw14ib8lhc00lyw";
    };
  };
}
