# coffee-script-source — generated by onix. Do not edit.
{
  "1.12.2" = {
    version = "1.12.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1907v9q1zcqmmyqzhzych5l7qifgls2rlbnbhy5vzyr7i7yicaz1";
    };
  };
}
