# coffee-rails — generated by onix. Do not edit.
{
  "5.0.0" = {
    version = "5.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "170sp4y82bf6nsczkkkzypzv368sgjg6lfrkib4hfjgxa6xa3ajx";
    };
  };
}
