# color_diff — generated by onix. Do not edit.
{
  "0.2" = {
    version = "0.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "094hvvpr7x7m6qq3yhmnzv7yv5clmmps1fy1rply10j6gcl1wpyf";
    };
  };
}
