# colored2 — generated by onix. Do not edit.
{
  "4.0.3" = {
    version = "4.0.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0drbrv5m3l3qpal7s87gvss81cbzl76gad1hqkpqfqlphf0h7qb3";
    };
  };
}
