# commonmarker — generated by onix. Do not edit.
{
  "0.23.10" = {
    version = "0.23.10";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1lb5slzbqrca49h0gaifg82xky5r7i9xgm4560pin1xl5fp15lzx";
    };
  };
  "2.6.3" = {
    version = "2.6.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1y1ng052vqapxqykmmgl7ymqiy0q078y6lradjzm3s9damb36c3f";
    };
  };
}
