# concurrent-ruby — generated by onix. Do not edit.
{
  "1.3.4" = {
    version = "1.3.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0chwfdq2a6kbj6xz9l6zrdfnyghnh32si82la1dnpa5h75ir5anl";
    };
  };
  "1.3.5" = {
    version = "1.3.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1ipbrgvf0pp6zxdk5ascp6i29aybz2bx9wdrlchjmpx6mhvkwfw1";
    };
  };
  "1.3.6" = {
    version = "1.3.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1aymcakhzl83k77g2f2krz07bg1cbafbcd2ghvwr4lky3rz86mkb";
    };
  };
}
