# countries — generated by onix. Do not edit.
{
  "5.7.1" = {
    version = "5.7.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0wwjvwfbfbkhablr45k7aaib7jx5j1k6ii3wi6p3x0fq9f903q88";
    };
  };
}
