# crass — generated by onix. Do not edit.
{
  "1.0.6" = {
    version = "1.0.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0pfl5c0pyqaparxaqxi6s4gfl21bdldwiawrc0aknyvflli60lfw";
    };
  };
}
