# css_parser — generated by onix. Do not edit.
{
  "1.21.1" = {
    version = "1.21.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1izp5vna86s7xivqzml4nviy01bv76arrd5is8wkncwp1by3zzbc";
    };
  };
}
