# cssbundling-rails — generated by onix. Do not edit.
{
  "1.4.1" = {
    version = "1.4.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1qbwdksjq9lw2h4xs2lb7lvp94pwgv38hp0mm46qj8bvc8yjf8ab";
    };
  };
}
