# csv-safe — generated by onix. Do not edit.
{
  "3.3.1" = {
    version = "3.3.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0gx7j6976k0hl8nrgy8zw2yw149180djikd5jy0zb2im73649ay2";
    };
  };
}
