# csv — generated by onix. Do not edit.
{
  "3.3.0" = {
    version = "3.3.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0zfn40dvgjk1xv1z8l11hr9jfg3jncwsc9yhzsz4l4rivkpivg8b";
    };
  };
  "3.3.5" = {
    version = "3.3.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0gz7r2kazwwwyrwi95hbnhy54kwkfac5swh2gy5p5vw36fn38lbf";
    };
  };
}
