# cuprite — generated by onix. Do not edit.
{
  "0.15" = {
    version = "0.15";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1piq0q370xka10fzm1p34il7h9fg76xl207bykn67p8swqrq79rb";
    };
  };
}
