# cypress-rails — generated by onix. Do not edit.
{
  "0.7.0" = {
    version = "0.7.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1f01s4ljl3xir1p2ysp3bp1v0zc38i5zix80xnrz57aiankb2ica";
    };
  };
}
