# dalli — generated by onix. Do not edit.
{
  "5.0.0" = {
    version = "5.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0s6llfgkfnlwk74gb59r1zf48cjn1sp0jzz7d2nqry9yv8hyhnkx";
    };
  };
}
