# dartsass-rails — generated by onix. Do not edit.
{
  "0.5.1" = {
    version = "0.5.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "06is62xl51f6sy6ndz5nagb0mlpi2pb58sd074bnrir93gxi15gi";
    };
  };
}
