# datadog — generated by onix. Do not edit.
{
  "2.19.0" = {
    version = "2.19.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "06m24sih1l2l6c193p2vzsvkq59n817yz7xzjhf56nf4gn61kzm9";
    };
  };
}
