# datadog-ruby_core_source — generated by onix. Do not edit.
{
  "3.4.1" = {
    version = "3.4.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1f9gi9kzrg4ryjcazdclkwyfp6nkawmkhhv439jvcr7pr31z2h7s";
    };
  };
}
