# datadog-ci — generated by onix. Do not edit.
{
  "0.3.0" = {
    version = "0.3.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0bvjls422j26mvym3xn4bva9kqr8alxpy7sll4sgkp6jz8c94zhr";
    };
  };
}
