# ddtrace — generated by onix. Do not edit.
{
  "1.16.2" = {
    version = "1.16.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "175rzmz21wm9a97x5w28ahhkaiql83pk2n528czkpqm2i7jw0jm1";
    };
  };
}
