# debase-ruby_core_source — generated by onix. Do not edit.
{
  "3.2.2" = {
    version = "3.2.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0vcnz311yncw7ng9s1wf20dxivlhcivrrx6w0ljfgf5qd36ijxdm";
    };
  };
}
