# debug_inspector — generated by onix. Do not edit.
{
  "1.2.0" = {
    version = "1.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "18k8x9viqlkh7dbmjzh8crbjy8w480arpa766cw1dnn3xcpa1pwv";
    };
  };
}
