# declarative — generated by onix. Do not edit.
{
  "0.0.20" = {
    version = "0.0.20";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1yczgnqrbls7shrg63y88g7wand2yp9h6sf56c9bdcksn5nds8c0";
    };
  };
}
