# devise_pam_authenticatable2 — generated by onix. Do not edit.
{
  "9.2.0" = {
    version = "9.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "13ipl52pkhc6vxp8ca31viwv01237bi2bfk3b1fixq1x46nf87p2";
    };
  };
}
