# devise-secure_password — generated by onix. Do not edit.
{
  "2.0.1" = {
    version = "2.0.1";
    source = {
      type = "git";
      url = "https://github.com/chatwoot/devise-secure_password";
      rev = "adcc85fe1babfe40feae73dbcae64d14fff86e69";
      sha256 = "sha256-WivVQgJdXbRNPi1Y60VXE1KeJRJxmApxhnWr3i9WtjM=";
      fetchSubmodules = false;
    };
  };
}
