# devise — generated by onix. Do not edit.
{
  "4.9.4" = {
    version = "4.9.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1y57fpcvy1kjd4nb7zk7mvzq62wqcpfynrgblj558k3hbvz4404j";
    };
  };
  "5.0.0" = {
    version = "5.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0sq57y3gg845cmzqawbh5nrqjynz3zc184lpwpdxgxgdrhwpvwrz";
    };
  };
}
