# diffy — generated by onix. Do not edit.
{
  "3.4.4" = {
    version = "3.4.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1qs7drxvyzk3dg22xgblc12lq5kww9hhj7vpn8ay3l42rasllf3r";
    };
  };
}
