# digest-xxhash — generated by onix. Do not edit.
{
  "0.2.9" = {
    version = "0.2.9";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1mwqln5078r4arxzngbzvr82fshl1bn836ga9dm17i03khqdi2d9";
    };
  };
}
