# digest-crc — generated by onix. Do not edit.
{
  "0.6.5" = {
    version = "0.6.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "09114ndpnnyamc2q07bmpzw7kp3rbbfv7plmxcbzzi9d6prmd92w";
    };
  };
}
