# discourse-fonts — generated by onix. Do not edit.
{
  "0.0.19" = {
    version = "0.0.19";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0cq0ds6c2hz1qs2f3skdbs9pqy4dkl1jfm3778q0hnb1f7bdvm3q";
    };
  };
}
