# discourse_ai-tokenizers — generated by onix. Do not edit.
{
  "0.4" = {
    version = "0.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1i84h7qdh78s5hvivd9nffh04ikb222ll3xrawqbpwvrak6dvmsl";
    };
  };
}
