# discourse-seed-fu — generated by onix. Do not edit.
{
  "2.3.12" = {
    version = "2.3.12";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1r3mbi72cx3xx8dnva1zhvxcacdma4xfn16d8s860m7d25fdjqag";
    };
  };
}
