# discard — generated by onix. Do not edit.
{
  "1.4.0" = {
    version = "1.4.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1l35bpwnxqd6pqqy315a1y6bi2n8y6cd69dqh4gpi5nz7njx5z3f";
    };
  };
}
