# domain_name — generated by onix. Do not edit.
{
  "0.5.20190701" = {
    version = "0.5.20190701";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0lcqjsmixjp52bnlgzh4lg9ppsk52x9hpwdjd53k8jnbah2602h0";
    };
  };
  "0.6.20240107" = {
    version = "0.6.20240107";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0cyr2xm576gqhqicsyqnhanni47408w2pgvrfi8pd13h2li3nsaz";
    };
  };
}
