# doorkeeper — generated by onix. Do not edit.
{
  "5.8.2" = {
    version = "5.8.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1lsh9lzrglqlwm9icmn0ggrwjc9iy9308f9m59z1w2srmyp0fgd7";
    };
  };
}
