# dotenv-rails — generated by onix. Do not edit.
{
  "2.8.1" = {
    version = "2.8.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0v0gcbxzypcvy6fqq4gp80jb310xvdwj5n8qw9ci67g5yjvq2nxh";
    };
  };
  "3.1.2" = {
    version = "3.1.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0sjxr93yv1pg0dvqsfvsc5rmqrs847nwxhlfvm1ff7fab8davlk6";
    };
  };
}
