# dotenv — generated by onix. Do not edit.
{
  "2.8.1" = {
    version = "2.8.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1n0pi8x8ql5h1mijvm8lgn6bhq4xjb5a500p5r1krq4s6j9lg565";
    };
  };
  "3.1.2" = {
    version = "3.1.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0y24jabiz4cf9ni9vi4j8sab8b5phpf2mpw3981r0r94l4m6q0q8";
    };
  };
  "3.1.7" = {
    version = "3.1.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1wrw6fm0s38cd6h55w79bkvjhcj2zfkargjpws4kilkmhr3xyw66";
    };
  };
  "3.2.0" = {
    version = "3.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "17b1zr9kih0i3wb7h4yq9i8vi6hjfq07857j437a8z7a44qvhxg3";
    };
  };
}
