# down — generated by onix. Do not edit.
{
  "5.4.0" = {
    version = "5.4.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "01ffxsghfggscb380lh2z7xq3pxscv3ap61wgkm16knbbfmch92y";
    };
  };
}
