# drb — generated by onix. Do not edit.
{
  "2.2.3" = {
    version = "2.2.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0wrkl7yiix268s2md1h6wh91311w95ikd8fy8m5gx589npyxc00b";
    };
  };
}
