# dry-schema — generated by onix. Do not edit.
{
  "1.14.1" = {
    version = "1.14.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1wczkg5wd29c8gg1r10wxfpyavw4q6ia7xi2dapar709lwwpbk9g";
    };
  };
}
