# dry-initializer — generated by onix. Do not edit.
{
  "3.2.0" = {
    version = "3.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1qy4cv0j0ahabprdbp02nc3r1606jd5dp90lzqg0mp0jz6c9gm9p";
    };
  };
}
