# dry-inflector — generated by onix. Do not edit.
{
  "1.2.0" = {
    version = "1.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0blgyg9l4gpzhb7rs9hqq9j7br80ngiigjp2ayp78w6m1ysx1x92";
    };
  };
}
