# dry-types — generated by onix. Do not edit.
{
  "1.8.3" = {
    version = "1.8.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1g61cnmmwzff05sf8bh95qjd3hikasgvrmf3q0qk29zdw12pmndm";
    };
  };
}
