# easy_translate — generated by onix. Do not edit.
{
  "0.5.1" = {
    version = "0.5.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "02h47i69w4ly9cb0n1pvnr35qipbpy4rpji4crx0mrq7mcql20s4";
    };
  };
}
