# elasticsearch-api — generated by onix. Do not edit.
{
  "7.17.11" = {
    version = "7.17.11";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "01wi43a3zylrq2vca08vir5va142g5m3jcsak3rprjck8jvggn7y";
    };
  };
}
