# elasticsearch-dsl — generated by onix. Do not edit.
{
  "0.1.10" = {
    version = "0.1.10";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "174m3fwm3mawbkjg2xbmqvljq7ava4s95m8vpg5khcvfj506wxfk";
    };
  };
}
