# email_reply_trimmer — generated by onix. Do not edit.
{
  "0.1.13" = {
    version = "0.1.13";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1jgcxifm48xq5dz9k47q43pqm5bfnf14l62l3bqhmv8f6z8dw4ki";
    };
  };
  "0.2.0" = {
    version = "0.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "09f5sq41fb912jxsbzh68hmkwq9gj9p8fg0zbwikf80sxsjkz105";
    };
  };
}
