# email_validator — generated by onix. Do not edit.
{
  "2.2.4" = {
    version = "2.2.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0106y8xakq6frv2xc68zz76q2l2cqvhfjc7ji69yyypcbc4kicjs";
    };
  };
}
