# email-provider-info — generated by onix. Do not edit.
{
  "0.0.1" = {
    version = "0.0.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "113mcpcp67yq0gp1pjh7y4iqchshm29wyv1x99xyp9ccwsb0dgdq";
    };
  };
}
