# emoji_regex — generated by onix. Do not edit.
{
  "3.2.3" = {
    version = "3.2.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0jsnrkfy345v66jlm2xrz8znivfnamg3mfzkddn414bndf2vxn7c";
    };
  };
}
