# erubi — generated by onix. Do not edit.
{
  "1.13.0" = {
    version = "1.13.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0qnd6ff4az22ysnmni3730c41b979xinilahzg86bn7gv93ip9pw";
    };
  };
  "1.13.1" = {
    version = "1.13.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1naaxsqkv5b3vklab5sbb9sdpszrjzlfsbqpy7ncbnw510xi10m0";
    };
  };
}
