# et-orbi — generated by onix. Do not edit.
{
  "1.2.11" = {
    version = "1.2.11";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0r6zylqjfv0xhdxvldr0kgmnglm57nm506pcm6085f0xqa68cvnj";
    };
  };
  "1.4.0" = {
    version = "1.4.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1g785lz4z2k7jrdl7bnnjllzfrwpv9pyki94ngizj8cqfy83qzkc";
    };
  };
}
