# event_emitter — generated by onix. Do not edit.
{
  "0.2.6" = {
    version = "0.2.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "148k9qv8102l3m6klc24dwip79f9y4bjr5z19dckd7ffbjyrf9n7";
    };
  };
}
