# excon — generated by onix. Do not edit.
{
  "0.104.0" = {
    version = "0.104.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "104vrqqy6bszbhpvabgz9ra7dm6lnb5jwzwqm2fks0ka44spknyl";
    };
  };
  "1.3.2" = {
    version = "1.3.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "19a4ln8s8bz2vnv15mikgr908cqqplmjnm3x5825i3k3k2zbm2d0";
    };
  };
}
