# execjs — generated by onix. Do not edit.
{
  "2.8.1" = {
    version = "2.8.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "121h6af4i6wr3wxvv84y53jcyw2sk71j5wsncm6wq6yqrwcrk4vd";
    };
  };
  "2.9.1" = {
    version = "2.9.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1yywajqlpjhrj1m43s3lfg3i4lkb6pxwccmwps7qw37ndmphdzg8";
    };
  };
  "2.10.0" = {
    version = "2.10.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "03a590q16nhqvfms0lh42mp6a1i41w41qpdnf39zjbq5y3l8pjvb";
    };
  };
}
