# exifr — generated by onix. Do not edit.
{
  "1.4.0" = {
    version = "1.4.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "11v201jljn327fwjqcsglrbdnyhivnj7j6nh6wym5zjqgrwxy3kn";
    };
  };
  "1.4.1" = {
    version = "1.4.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "155qqhai5z2742aqa4mwkxmqrpcv48siqz55rcx79wvgdg6790vn";
    };
  };
}
