# extralite-bundle — generated by onix. Do not edit.
{
  "2.13" = {
    version = "2.13";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1k5kglcva79sxvqj10x481r1w8ql6zdr77mv095g8j5ksf6k600d";
    };
  };
}
