# facebook-messenger — generated by onix. Do not edit.
{
  "2.0.1" = {
    version = "2.0.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "00jgwyv48dcq1pjsb3cz7n7mknw6xavghncmc4a5gzcaq58f96w6";
    };
  };
}
