# factory_bot_rails — generated by onix. Do not edit.
{
  "6.4.3" = {
    version = "6.4.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1j6w4rr2cb5wng9yrn2ya9k40q52m0pbz47kzw8xrwqg3jncwwza";
    };
  };
}
