# fakeredis — generated by onix. Do not edit.
{
  "0.8.0" = {
    version = "0.8.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1v4f1nzmk4fg60kzsnwvm091vd6r51gwaikid2j8idm6dh92h0c1";
    };
  };
}
