# faraday-encoding — generated by onix. Do not edit.
{
  "0.0.5" = {
    version = "0.0.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "04ndchylmimpf4xbz8pimym3lv1lpbi3zsgyplwp7bx1mpc7x79h";
    };
  };
}
