# faraday-net_http — generated by onix. Do not edit.
{
  "3.1.0" = {
    version = "3.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "17w51yk4rrm9rpnbc3x509s619kba0jga3qrj4b17l30950vw9qn";
    };
  };
  "3.4.2" = {
    version = "3.4.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0v4hfmc7d4lrqqj2wl366rm9551gd08zkv2ppwwnjlnkc217aizi";
    };
  };
}
