# faraday-httpclient — generated by onix. Do not edit.
{
  "2.0.2" = {
    version = "2.0.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0z6nv0cxxk9rm69x84861f5zn8jck99prmjpg4apxa75rihbwpyr";
    };
  };
}
