# faraday-http-cache — generated by onix. Do not edit.
{
  "2.5.0" = {
    version = "2.5.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0qvl49xpl2mwxgcj6aj11qrjk94xrqhbnpl5vp1y2275crnkddv4";
    };
  };
}
