# faraday-gzip — generated by onix. Do not edit.
{
  "1.0.0" = {
    version = "1.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1bqhppqf9r3iac8qqdfn2p14lwmxkzympxlbpni5y39rb619sazj";
    };
  };
}
