# faraday-multipart — generated by onix. Do not edit.
{
  "1.0.4" = {
    version = "1.0.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "09871c4hd7s5ws1wl4gs7js1k2wlby6v947m2bbzg43pnld044lh";
    };
  };
  "1.1.1" = {
    version = "1.1.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "00w9imp55hi81q0wsgwak90ldkk7gbyb8nzmmv8hy0s907s8z8bp";
    };
  };
}
