# faraday-mashify — generated by onix. Do not edit.
{
  "1.0.0" = {
    version = "1.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0bsly35pakjpzmbwizc94mj5jqna3jfgmwgpz89rkd6bzmm6111n";
    };
  };
}
