# faraday — generated by onix. Do not edit.
{
  "2.9.0" = {
    version = "2.9.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1qqb1rmk0f9m82iijjlqadh5yby1bhnr6svjk9vxdvh6f181988s";
    };
  };
  "2.14.0" = {
    version = "2.14.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1ka175ci0q9ylpcy651pjj580diplkaskycn4n7jcmbyv7jwz6c6";
    };
  };
  "2.14.1" = {
    version = "2.14.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "077n5ss3z3ds4vj54w201kd12smai853dp9c9n7ii7g3q7nwwg54";
    };
  };
}
