# fast-mcp — generated by onix. Do not edit.
{
  "1.5.0" = {
    version = "1.5.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0rk6dvx53zy92kxbwp03fh0n971vblrd2blwrnm70nvbm1wzi1aa";
    };
  };
}
