# fastly — generated by onix. Do not edit.
{
  "3.0.2" = {
    version = "3.0.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "05gn2x6zmv6lrx3ww1syxa76yf33k3rkp4kfw06cln4bhnfp163h";
    };
  };
}
