# fcm — generated by onix. Do not edit.
{
  "1.0.8" = {
    version = "1.0.8";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "10h8zy0n35ff7wcbr0w7mlkzxmrv9vi2xczvdadyzi5724k4fpzb";
    };
  };
}
