# ferrum — generated by onix. Do not edit.
{
  "0.14" = {
    version = "0.14";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "09f72adiwg80kj8zmawr6sb0bkdd6gf0mwg54ncpvy4vs91gk8z9";
    };
  };
}
