# field_test — generated by onix. Do not edit.
{
  "0.6.0" = {
    version = "0.6.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "08v2l1c99wfvnk6ahvbdhv7vwkn5d87kjqdqkyl4am8n0c6s2saa";
    };
  };
}
