# flag_shih_tzu — generated by onix. Do not edit.
{
  "0.3.23" = {
    version = "0.3.23";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1gk1f24w94bfmnih5l1gfm84c2676j7y111qw5qicxwnbdd230h9";
    };
  };
}
