# flatware-rspec — generated by onix. Do not edit.
{
  "2.3.4" = {
    version = "2.3.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1gqkjilaqbd6qq80rx3fbjppjbllndvhd629yyd29943lrp3m9nb";
    };
  };
}
