# flatware — generated by onix. Do not edit.
{
  "2.3.4" = {
    version = "2.3.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "06yllpzx5ib7cv1ar03279gm2qywnzsqfiz42g5y9fmp7z24yiik";
    };
  };
}
