# flipper-ui — generated by onix. Do not edit.
{
  "0.25.4" = {
    version = "0.25.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1cwkm9bzm375dnql36q7nrlb4jdx6zr87sjij7frk6zvpsjaik8x";
    };
  };
}
