# flipper-active_record — generated by onix. Do not edit.
{
  "0.25.4" = {
    version = "0.25.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0ariszl038cixlibzyf7d0hvdfgy06vy6l61fw536cp7w70ngs1c";
    };
  };
}
