# flipper — generated by onix. Do not edit.
{
  "0.25.4" = {
    version = "0.25.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "04qckwljl5j8z02gkg20kjmp3p9gg3zq1icg62xp3r2jydr8j7az";
    };
  };
}
