# fog-aws — generated by onix. Do not edit.
{
  "3.21.0" = {
    version = "3.21.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1fvwm5fsd99i714984z4ppr87b4f30zwb7x30bpniwc8rvvq09gi";
    };
  };
}
