# fog-json — generated by onix. Do not edit.
{
  "1.2.0" = {
    version = "1.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1zj8llzc119zafbmfa4ai3z5s7c4vp9akfs0f9l2piyvcarmlkyx";
    };
  };
}
