# fog-xml — generated by onix. Do not edit.
{
  "0.1.4" = {
    version = "0.1.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1vyyb2429xqzys39xyk2r3fal80qqn397aj2kqsjrgg2y6m59i41";
    };
  };
}
