# foreman — generated by onix. Do not edit.
{
  "0.87.2" = {
    version = "0.87.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0szgxvnzwkzrfbq5dkwa98mig78aqglfy6irdsvq1gq045pbq9r7";
    };
  };
}
