# formatador — generated by onix. Do not edit.
{
  "1.1.0" = {
    version = "1.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1l06bv4avphbdmr1y4g0rqlczr38k6r65b3zghrbj2ynyhm3xqjl";
    };
  };
  "1.2.3" = {
    version = "1.2.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "156qa2wiizmdalz6cim04yaasdz1q6c6k7yhnpdnrhn26f0qkyhr";
    };
  };
}
