# gemoji — generated by onix. Do not edit.
{
  "4.1.0" = {
    version = "4.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "06nw5mfscjmpap7f0bc9f2hj6zd4jy3pk1lhs6llx5my1h138i3k";
    };
  };
}
