# geocoder — generated by onix. Do not edit.
{
  "1.8.1" = {
    version = "1.8.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "04i0z628nsvdgkxsg6main871jyx341g582h0qq5sk7j0aiwlbxb";
    };
  };
}
