# get_process_mem — generated by onix. Do not edit.
{
  "0.2.7" = {
    version = "0.2.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1fkyyyxjcx4iigm8vhraa629k2lxa1npsv4015y82snx84v3rzaa";
    };
  };
}
