# gibbon — generated by onix. Do not edit.
{
  "3.5.0" = {
    version = "3.5.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1xh2frxvmxa43pmqf8lvxphywwn54dhib4fp4mf16pv5lzn84xr4";
    };
  };
}
