# gli — generated by onix. Do not edit.
{
  "2.22.2" = {
    version = "2.22.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1c2x5wh3d3mz8vg5bs7c5is0zvc56j6a2b4biv5z1w5hi1n8s3jq";
    };
  };
}
