# gmail_xoauth — generated by onix. Do not edit.
{
  "0.4.3" = {
    version = "0.4.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1ys5mv3im4w229fjshmbf9s4bs11n9m8j6h9vplacr05ssdzb9gd";
    };
  };
}
