# google-cloud-storage — generated by onix. Do not edit.
{
  "1.52.0" = {
    version = "1.52.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "125fdz19y1rm0b33nqg0vahgm8mqd7v8jgwdrz73rhpq3k2sfq0f";
    };
  };
  "1.54.0" = {
    version = "1.54.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1kj31s7p0abgh6llknk9rymybnrhxjncma3lwzisyl4k9srx9sa4";
    };
  };
}
