# google-cloud-env — generated by onix. Do not edit.
{
  "2.2.1" = {
    version = "2.2.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1ks9yv21d8bl9cw0sz5gy6npll1ig3m2bq9w7yw67j5mw2p64q1w";
    };
  };
}
