# google-cloud-core — generated by onix. Do not edit.
{
  "1.7.1" = {
    version = "1.7.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0bh1yzv26mqn2qmzkqa0qwzmq4w0dcphjla4w5m2f2qlkj583wjs";
    };
  };
}
