# google-cloud-translate-v3 — generated by onix. Do not edit.
{
  "0.10.0" = {
    version = "0.10.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1p9qslv61xliiav8xysp9hk230w7md7mrykk7xh8rs0d2n27yvvd";
    };
  };
}
