# googleapis-common-protos — generated by onix. Do not edit.
{
  "1.6.0" = {
    version = "1.6.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0ycd7bqvjjrviy4wfykxdda1scvyzwl5sj9nx7z38jzxfm512h6m";
    };
  };
}
