# googleauth — generated by onix. Do not edit.
{
  "1.11.2" = {
    version = "1.11.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "07kk8h5f9q62qf1mk7rycgv6m09rd0k8baffdpb3vsksxnpaqsvy";
    };
  };
  "1.12.2" = {
    version = "1.12.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0zynv2s6s6i5d8x84p1axin21bfgmgy92ai2jb7a7aaknaqpfc9x";
    };
  };
}
