# google-logging-utils — generated by onix. Do not edit.
{
  "0.1.0" = {
    version = "0.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1mgw0n97prlvgvd81dci8rx93xranr3xnyhn5v7p6hii94g0p5bh";
    };
  };
}
