# google-apis-iamcredentials_v1 — generated by onix. Do not edit.
{
  "0.22.0" = {
    version = "0.22.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1b9xgbp7wr39aggaxd8r27kvmwcjanxj98a1i0wh462l7n8xxh9q";
    };
  };
}
