# google-protobuf — generated by onix. Do not edit.
{
  "3.25.5" = {
    version = "3.25.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0fanhdf3vzghma51w1hqpp8s585mwzxgqkwvxj5is4q9j0pgwcs3";
    };
  };
  "3.25.7" = {
    version = "3.25.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1afriizkvwwcyh0s0j1x9d9045pn4f767gpj5q49hicsqz8flq58";
    };
  };
  "4.29.3" = {
    version = "4.29.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0rmmp533ypc5c2r3ks8zqxchqkf1g8laig87f7hdfmwz0p07cmcs";
    };
  };
  "4.33.2" = {
    version = "4.33.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0583agdf2jvnq78scf8008bddrmbybn27ylyydg6bza2qvb510bl";
    };
  };
  "4.33.5" = {
    version = "4.33.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "180dc99dgq6gsi65q8sxcdqxjkz09fifq8v97yn266qh9ivznr0v";
    };
  };
}
