# groupdate — generated by onix. Do not edit.
{
  "6.2.1" = {
    version = "6.2.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0mh91hpww2cx3946734ca97aa9njyahgwwgfd6vf5qmswrbqh1vw";
    };
  };
}
