# grpc — generated by onix. Do not edit.
{
  "1.72.0" = {
    version = "1.72.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "02gakdhvpl777b41i8cgkrj7gk0jlq4fza9hjksp2r7ryji0vyjn";
    };
  };
}
