# gserver — generated by onix. Do not edit.
{
  "0.0.1" = {
    version = "0.0.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1lscj8ds2fcdzzs0jrk4dsqlpm0k0z0y71749i6180rlbcs5igir";
    };
  };
}
