# guard-rspec — generated by onix. Do not edit.
{
  "4.7.3" = {
    version = "4.7.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1jkm5xp90gm4c5s51pmf92i9hc10gslwwic6mvk72g0yplya0yx4";
    };
  };
}
