# haml_lint — generated by onix. Do not edit.
{
  "0.69.0" = {
    version = "0.69.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "16bxvnisrg15sdhc93l34ggrmxrjb92xa34f7a7bbr8zd68gyslb";
    };
  };
}
