# haml — generated by onix. Do not edit.
{
  "7.2.0" = {
    version = "7.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0nnmzj6g2wynxbrp9j885zab4nkzfryhl2bv6cj1gazyyxqjpzc7";
    };
  };
}
