# hana — generated by onix. Do not edit.
{
  "1.3.7" = {
    version = "1.3.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "03cvrv2wl25j9n4n509hjvqnmwa60k92j741b64a1zjisr1dn9al";
    };
  };
}
