# hash_diff — generated by onix. Do not edit.
{
  "1.1.1" = {
    version = "1.1.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "18q45wsvbfcjgjqackcrj5xx929vbakpa7vnp6wp173rsm67x64b";
    };
  };
}
