# hcaptcha — generated by onix. Do not edit.
{
  "7.1.0" = {
    version = "7.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0fh6391zlv2ikvzqj2gymb70k1avk1j9da8bzgw0scsz2wqq98m2";
    };
  };
}
