# heapy — generated by onix. Do not edit.
{
  "0.2.0" = {
    version = "0.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1sl56ma851i82g3ax08igbn48igriiy152xzx30wgzv1bn21w53l";
    };
  };
}
