# highline — generated by onix. Do not edit.
{
  "2.1.0" = {
    version = "2.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1f8cr014j7mdqpdb9q17fp5vb5b8n1pswqaif91s3ylg5x3pygfn";
    };
  };
  "3.1.2" = {
    version = "3.1.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0jmvyhjp2v3iq47la7w6psrxbprnbnmzz0hxxski3vzn356x7jv7";
    };
  };
}
