# hiredis-client — generated by onix. Do not edit.
{
  "0.26.4" = {
    version = "0.26.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0rp0xq5x1n1sf7jwh2kczc4y4xb6k3nca5spr14lgw5czgankskl";
    };
  };
}
