# hiredis — generated by onix. Do not edit.
{
  "0.6.3" = {
    version = "0.6.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "04jj8k7lxqxw24sp0jiravigdkgsyrpprxpxm71ba93x1wr2w1bz";
    };
  };
}
