# hkdf — generated by onix. Do not edit.
{
  "0.3.0" = {
    version = "0.3.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "04fixg0a51n4vy0j6c1hvisa2yl33m3jrrpxpb5sq6j511vjriil";
    };
  };
}
