# honeycomb-beeline — generated by onix. Do not edit.
{
  "2.11.0" = {
    version = "2.11.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1pmcvkg3jr66v70q5qixxfh4jxkc8cl0pdjag01h748r37m26ywb";
    };
  };
}
