# honeybadger — generated by onix. Do not edit.
{
  "4.12.2" = {
    version = "4.12.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0p790pgbxmym0gbbpfghc26m1rv2dfy0ylqjwgx8khh16zac3cgz";
    };
  };
}
