# html2text — generated by onix. Do not edit.
{
  "0.4.0" = {
    version = "0.4.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1igx1ab5kgyflfpv7g136a6f7ms9g9ixiikx7xikj1qmp6hczgmi";
    };
  };
}
