# htmlentities — generated by onix. Do not edit.
{
  "4.3.4" = {
    version = "4.3.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1nkklqsn8ir8wizzlakncfv42i32wc0w9hxp00hvdlgjr7376nhj";
    };
  };
  "4.4.2" = {
    version = "4.4.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1hy5jvzd4wagk0k0yq7bjm6fa7ba7vjggzjfpri95jifkzvbvbxv";
    };
  };
}
