# httpclient — generated by onix. Do not edit.
{
  "2.8.3" = {
    version = "2.8.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "19mxmvghp7ki3klsxwrlwr431li7hm1lczhhj8z4qihl2acy8l99";
    };
  };
  "2.9.0" = {
    version = "2.9.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1j4qwj1nv66v3n9s4xqf64x2galvjm630bwa5xngicllwic5jr2b";
    };
  };
}
