# http_parser.rb — generated by onix. Do not edit.
{
  "0.6.0" = {
    version = "0.6.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "15nidriy0v5yqfjsgsra51wmknxci2n2grliz78sf9pga3n0l7gi";
    };
  };
}
