# http-cookie — generated by onix. Do not edit.
{
  "1.0.5" = {
    version = "1.0.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "13rilvlv8kwbzqfb644qp6hrbsj82cbqmnzcvqip1p6vqx36sxbk";
    };
  };
  "1.1.0" = {
    version = "1.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "06dvmngd4hwrr6k774i1h6c50h2l8nww9f1id0wvrvi72l6yd99q";
    };
  };
}
