# httparty — generated by onix. Do not edit.
{
  "0.21.0" = {
    version = "0.21.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "050jzsa6fbfvy2rldhk7mf1sigildaqvbplfz2zs6c0zlzwppvq0";
    };
  };
  "0.24.0" = {
    version = "0.24.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1b5h8d8ygq0qradp7yr3wxd4wf9q78972pjlggvpscicv71yx4yd";
    };
  };
}
