# http-parser — generated by onix. Do not edit.
{
  "1.2.3" = {
    version = "1.2.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "18qqvckvqjffh88hfib6c8pl9qwk9gp89w89hl3f2s1x8hgyqka1";
    };
  };
}
