# http-accept — generated by onix. Do not edit.
{
  "1.7.0" = {
    version = "1.7.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "09m1facypsdjynfwrcv19xcb1mqg8z6kk31g8r33pfxzh838c9n6";
    };
  };
}
