# httplog — generated by onix. Do not edit.
{
  "1.8.0" = {
    version = "1.8.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1gq7cra0d9h5mc1295h3xknqwany9xbxasgliyq6axr74rmbs51b";
    };
  };
}
