# http-form_data — generated by onix. Do not edit.
{
  "2.3.0" = {
    version = "2.3.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1wx591jdhy84901pklh1n9sgh74gnvq1qyqxwchni1yrc49ynknc";
    };
  };
}
