# i18n-js — generated by onix. Do not edit.
{
  "3.9.2" = {
    version = "3.9.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "13kr7gmas0cvn7d4njimlpf77q4b4pb2lf3jldss9zis33rhphil";
    };
  };
}
