# i18n — generated by onix. Do not edit.
{
  "1.14.6" = {
    version = "1.14.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0k31wcgnvcvd14snz0pfqj976zv6drfsnq6x8acz10fiyms9l8nw";
    };
  };
  "1.14.7" = {
    version = "1.14.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "03sx3ahz1v5kbqjwxj48msw3maplpp2iyzs22l4jrzrqh4zmgfnf";
    };
  };
  "1.14.8" = {
    version = "1.14.8";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1994i044vdmzzkyr76g8rpl1fq1532wf0sb21xg5r1ilj5iphmr8";
    };
  };
}
