# i18n-tasks — generated by onix. Do not edit.
{
  "1.0.13" = {
    version = "1.0.13";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1s4kgpv7hmlg99cnpyvajba73vib67pdp1pa3g5rwkl838xgvnji";
    };
  };
  "1.1.2" = {
    version = "1.1.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0yk3lgzmym02bvpqhvccrfjvnkyqh35idcqwcqq3yqiawm4vmksd";
    };
  };
}
