# idn-ruby — generated by onix. Do not edit.
{
  "0.1.5" = {
    version = "0.1.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0dy04jx3n1ddz744b80mg7hp87miysnjp0h21lqr43hpmhdglxih";
    };
  };
}
