# image_optim — generated by onix. Do not edit.
{
  "0.31.4" = {
    version = "0.31.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1h3n8x1rlxz4mkk49lij22x1nn0qk5cvir3fsj4x3s382a4x1zsv";
    };
  };
}
