# imgproxy — generated by onix. Do not edit.
{
  "2.1.0" = {
    version = "2.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1g1sdz0qjyh6d7rlhxg5hbkdf181w1fll1xh919fjd6lgn5ka4cc";
    };
  };
}
