# in_threads — generated by onix. Do not edit.
{
  "1.6.0" = {
    version = "1.6.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0j9132d4g8prjafgdh4pw948j527kr09m2lvylrcd797il9yd9wi";
    };
  };
}
