# inline_svg — generated by onix. Do not edit.
{
  "1.9.0" = {
    version = "1.9.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1mimwp5d6j52n4givnsyhmym3173rv4bfirhmlcxc7s05qymwk7l";
    };
  };
  "1.10.0" = {
    version = "1.10.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "03x1z55sh7cpb63g46cbd6135jmp13idcgqzqsnzinbg4cs2jrav";
    };
  };
}
