# iso-639 — generated by onix. Do not edit.
{
  "0.3.8" = {
    version = "0.3.8";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0dbmprc4j9qw6xjn7cs8s2sa1czfz1pf62bn6kd7ydjm9d511f28";
    };
  };
}
