# iso8601 — generated by onix. Do not edit.
{
  "0.13.0" = {
    version = "0.13.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "18js898rhh6byp0znvchiv6mcxi5l8v3v0bj2ddajpxynwajp319";
    };
  };
}
