# jbuilder — generated by onix. Do not edit.
{
  "2.11.5" = {
    version = "2.11.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1h58xgmp0fqpnd6mvw0zl0f76119v8lnf4xabqhckbzl6jrk8qpa";
    };
  };
  "2.13.0" = {
    version = "2.13.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1mi7s8kida8rg754bzgiik2mpdwx55x7wxd9ny0sm0803j5a603j";
    };
  };
  "2.14.1" = {
    version = "2.14.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0hmvz9lhx37x43gnms17hfczjwfj7i9xfvzxnh611vv0zxv67cjf";
    };
  };
}
