# jd-paperclip-azure — generated by onix. Do not edit.
{
  "3.0.0" = {
    version = "3.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1gcikrlqv6r9pqvw2kfyvmia3rikp9irhq1c10njz4z7i5za4xk9";
    };
  };
}
