# jmespath — generated by onix. Do not edit.
{
  "1.6.2" = {
    version = "1.6.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1cdw9vw2qly7q7r41s7phnac264rbsdqgj4l0h4nqgbjb157g393";
    };
  };
}
