# jquery-fileupload-rails — generated by onix. Do not edit.
{
  "0.4.7" = {
    version = "0.4.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1402wycbb790b0355xga36dzzqxx5k89qi28jl9qbfk0sy41kpx8";
    };
  };
}
