# jquery-rails — generated by onix. Do not edit.
{
  "4.6.0" = {
    version = "4.6.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1qm74n8g68a417ngb6kkw98x9ikjahdsmf1nv120nd3lfbs6nkiw";
    };
  };
}
