# js-routes — generated by onix. Do not edit.
{
  "2.2.8" = {
    version = "2.2.8";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0i3ascxpid120ijdfh03lz2c1md5ghbi142fkc9vv7shk7xck5z2";
    };
  };
}
