# jsbundling-rails — generated by onix. Do not edit.
{
  "1.3.0" = {
    version = "1.3.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0bfh1mwkpq53bd3k0nsnqwmsc76hrygfgngqd5hl7sy06wmp2h11";
    };
  };
  "1.3.1" = {
    version = "1.3.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1jn2n5i9qdw6iybb4f6gqkr7k61rafzdh8m0anzlqs8w0mnkz80g";
    };
  };
}
