# jsonapi-renderer — generated by onix. Do not edit.
{
  "0.2.2" = {
    version = "0.2.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0ys4drd0k9rw5ixf8n8fx8v0pjh792w4myh0cpdspd317l1lpi5m";
    };
  };
}
