# jsonapi-serializer — generated by onix. Do not edit.
{
  "2.2.0" = {
    version = "2.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0a80zdzg01xwj1q1v145qbzpnbgy38sghs6z2f2pxqf1y331l57q";
    };
  };
}
