# json_schemer — generated by onix. Do not edit.
{
  "0.2.24" = {
    version = "0.2.24";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0725230cl5kahpw6wlk0syvyhnzrh2szmk2lfavv7zl38wqcyv88";
    };
  };
  "2.5.0" = {
    version = "2.5.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "15p31bq932bfpsi1wgrkgwm71l7z1h1w53q6vl44w6kjrr6gn09g";
    };
  };
}
