# json_refs — generated by onix. Do not edit.
{
  "0.1.8" = {
    version = "0.1.8";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0yxi1nr0acgs6vayrccd30m9gz7ys68zwpan115yky02fa6nrlif";
    };
  };
}
