# judoscale-ruby — generated by onix. Do not edit.
{
  "1.8.2" = {
    version = "1.8.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1rl6d5zkfvknz3kaf0zqh9dy3gmydm4hlxbavpv1krxqswq09ppd";
    };
  };
}
