# judoscale-sidekiq — generated by onix. Do not edit.
{
  "1.8.2" = {
    version = "1.8.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "13p9hipnhbpp7p24yg59p2lnqviagn1dlkdzmzy2amf61k8a3qd8";
    };
  };
}
