# kamal — generated by onix. Do not edit.
{
  "2.4.0" = {
    version = "2.4.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "10aiz28g2jmm04y7w2mvqvwpw7lsr1sv0q2vwl31ap61ij2z2qjz";
    };
  };
}
