# kaminari-core — generated by onix. Do not edit.
{
  "1.2.2" = {
    version = "1.2.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1zw3pg6kj39y7jxakbx7if59pl28lhk98fx71ks5lr3hfgn6zliv";
    };
  };
}
