# kaminari-activerecord — generated by onix. Do not edit.
{
  "1.2.2" = {
    version = "1.2.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0c148z97s1cqivzbwrak149z7kl1rdmj7dxk6rpkasimmdxsdlqd";
    };
  };
}
