# kaminari-actionview — generated by onix. Do not edit.
{
  "1.2.2" = {
    version = "1.2.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "02f9ghl3a9b5q7l079d3yzmqjwkr4jigi7sldbps992rigygcc0k";
    };
  };
}
