# katex — generated by onix. Do not edit.
{
  "0.9.0" = {
    version = "0.9.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1bl5hgvsapkn4qk3ibz365x3q7qrypdb3dxn54q3p2cm10683z8w";
    };
  };
}
