# kgio — generated by onix. Do not edit.
{
  "2.11.4" = {
    version = "2.11.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1ipzvw7n0kz1w8rkqybyxvf3hb601a770khm0xdqm68mc4aa59xx";
    };
  };
}
