# knapsack_pro — generated by onix. Do not edit.
{
  "5.7.0" = {
    version = "5.7.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1rgbvvh6z0mdvhsiihvd6ck17n85bfzf1qr4fcfadazsa0inqwvc";
    };
  };
}
