# language_server-protocol — generated by onix. Do not edit.
{
  "3.17.0.3" = {
    version = "3.17.0.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0gvb1j8xsqxms9mww01rmdl78zkd72zgxaap56bhv8j45z05hp1x";
    };
  };
  "3.17.0.5" = {
    version = "3.17.0.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1k0311vah76kg5m6zr7wmkwyk5p2f9d9hyckjpn3xgr83ajkj7px";
    };
  };
}
