# launchy — generated by onix. Do not edit.
{
  "2.5.2" = {
    version = "2.5.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "06r43899384das2bkbrpsdxsafyyqa94il7111053idfalb4984a";
    };
  };
  "3.0.1" = {
    version = "3.0.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0b3zi9ydbibyyrrkr6l8mcs6l7yam18a4wg22ivgaz0rl2yn1ymp";
    };
  };
  "3.1.1" = {
    version = "3.1.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "17h522xhwi5m4n6n9m22kw8z0vy8100sz5f3wbfqj5cnrjslgf3j";
    };
  };
}
