# letter_opener — generated by onix. Do not edit.
{
  "1.10.0" = {
    version = "1.10.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1cnv3ggnzyagl50vzs1693aacv08bhwlprcvjp8jcg2w7cp3zwrg";
    };
  };
}
