# letter_opener_web — generated by onix. Do not edit.
{
  "3.0.0" = {
    version = "3.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0q4qfi5wnn5bv93zjf10agmzap3sn7gkfmdbryz296wb1vz1wf9z";
    };
  };
}
