# libdatadog — generated by onix. Do not edit.
{
  "5.0.0.1.0" = {
    version = "5.0.0.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1s2032dwbbif39f669xpfpb0yrjsismbfwcfmn4p0i029ic046y6";
    };
  };
  "18.1.0.1.0" = {
    version = "18.1.0.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "028v2pncb4p2rc6k3ha1afl4vvn44lbs70zi31258x149k979pgv";
    };
  };
}
