# libhoney — generated by onix. Do not edit.
{
  "2.2.0" = {
    version = "2.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0yqkm9izw6kayrl425gh322pyb1skxp7xbn4xn3sp26p7gq1g5q4";
    };
  };
}
