# line-bot-api — generated by onix. Do not edit.
{
  "1.28.0" = {
    version = "1.28.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "04b307nxwpx8yfbqjbnc517svb84dzqxbszx5asj77ypqlk34vb9";
    };
  };
}
