# link_header — generated by onix. Do not edit.
{
  "0.0.8" = {
    version = "0.0.8";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1yamrdq4rywmnpdhbygnkkl9fdy249fg5r851nrkkxr97gj5rihm";
    };
  };
}
