# lograge — generated by onix. Do not edit.
{
  "0.14.0" = {
    version = "0.14.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1qcsvh9k4c0cp6agqm9a8m4x2gg7vifryqr7yxkg2x9ph9silds2";
    };
  };
}
