# logster — generated by onix. Do not edit.
{
  "2.20.1" = {
    version = "2.20.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1a52r46d263h2kkxng7amrihz5c7xm9ak8vf4jq4x77rwxcbwjx8";
    };
  };
}
