# logstash-event — generated by onix. Do not edit.
{
  "1.2.02" = {
    version = "1.2.02";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1bk7fhhryjxp1klr3hq6i6srrc21wl4p980bysjp0w66z9hdr9w9";
    };
  };
}
