# loofah — generated by onix. Do not edit.
{
  "2.23.1" = {
    version = "2.23.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0ppp2cgli5avzk0z3dwnah6y65ymyr793yja28p2fs9vrci7986h";
    };
  };
  "2.24.0" = {
    version = "2.24.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "07pfa5kgl7k2hxlzzn89qna6bmiyrxlchgbzi0885frsi08agrk1";
    };
  };
  "2.24.1" = {
    version = "2.24.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0dx316q03x6rpdbl610rdaj2vfd5s8fanixk21j4gv3h5f230nk5";
    };
  };
  "2.25.0" = {
    version = "2.25.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1rk0n13c9nmk8di2x5gqk5r04vf8bkp7ff6z0b44wsmc7fndfpnz";
    };
  };
}
