# lumberjack — generated by onix. Do not edit.
{
  "1.2.9" = {
    version = "1.2.9";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0p43330qzn4r0rg2955g6g3xxd26y0k3nxajcwrymqm26rpiacp8";
    };
  };
}
