# lz4-ruby — generated by onix. Do not edit.
{
  "0.3.3" = {
    version = "0.3.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "12fymsvcb9kw6ycyfzc8b9svriq0afqf1qnl121xrz8c4gpfa6q1";
    };
  };
}
