# memoizable — generated by onix. Do not edit.
{
  "0.4.2" = {
    version = "0.4.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0v42bvghsvfpzybfazl14qhkrjvx0xlmxz0wwqc960ga1wld5x5c";
    };
  };
}
