# messageformat-wrapper — generated by onix. Do not edit.
{
  "1.1.0" = {
    version = "1.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1g30y5qv6jx39qz5g0yai37n46mvzjn7si8whjyd24p44sb8gspc";
    };
  };
}
