# message_bus — generated by onix. Do not edit.
{
  "4.5.1" = {
    version = "4.5.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "09aziih02r8y7c1s8ccl1v4p6ppzig4l23hq9g3k7qx08any8170";
    };
  };
}
