# metainspector — generated by onix. Do not edit.
{
  "5.15.0" = {
    version = "5.15.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1nqrcl2inr7wwxgzbx4rq6s1n1ylzl74zal67plrnbkdia4s3c80";
    };
  };
}
