# meta_request — generated by onix. Do not edit.
{
  "0.8.5" = {
    version = "0.8.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "117d26k77azb7h911cflyf3j1hy6fcd4pciphmbnkplpc1wld8y9";
    };
  };
}
