# mime-types-data — generated by onix. Do not edit.
{
  "3.2023.0218.1" = {
    version = "3.2023.0218.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1pky3vzaxlgm9gw5wlqwwi7wsw3jrglrfflrppvvnsrlaiz043z9";
    };
  };
  "3.2024.0305" = {
    version = "3.2024.0305";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "00x7w5xqsj9m33v3vkmy23wipkkysafksib53ypzn27p5g81w455";
    };
  };
  "3.2025.0924" = {
    version = "3.2025.0924";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0a27k4jcrx7pvb0p59fn1frh14iy087c2aygrdkmgwsrbshvqxpj";
    };
  };
  "3.2026.0203" = {
    version = "3.2026.0203";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0bradmf21c9g4z6f3hvqmnf6i2sbgp0630y2j5rq8a7h79lksdal";
    };
  };
}
