# minitest — generated by onix. Do not edit.
{
  "5.25.4" = {
    version = "5.25.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0izrg03wn2yj3gd76ck7ifbm9h2kgy8kpg4fk06ckpy4bbicmwlw";
    };
  };
  "5.25.5" = {
    version = "5.25.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0mn7q9yzrwinvfvkyjiz548a4rmcwbmz2fn9nyzh4j1snin6q6rr";
    };
  };
  "5.26.2" = {
    version = "5.26.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1qyda32pf9jivaw2m7yymxshqxxd0fhjn7zpbagvmfc5c65128gh";
    };
  };
  "6.0.0" = {
    version = "6.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1gjklhryvvd3byyk5psxyfka8vas3pxwb62b5f6s2pkk3py9g9ac";
    };
  };
  "6.0.1" = {
    version = "6.0.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1fslin1vyh60snwygx8jnaj4kwhk83f3m0v2j2b7bsg2917wfm3q";
    };
  };
}
