# mini_scheduler — generated by onix. Do not edit.
{
  "0.18.0" = {
    version = "0.18.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "00rmlcnwhi6gnrwpcv2yicm9ij8zs1mhsbx98ic6rmx8iprq9w6j";
    };
  };
}
