# minitest-retry — generated by onix. Do not edit.
{
  "0.2.3" = {
    version = "0.2.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0adzwww5i2dqirm4rks697s43i3ka87a8hmlmjhk3fdrxyb4hzvv";
    };
  };
}
