# mini_racer — generated by onix. Do not edit.
{
  "0.19.1" = {
    version = "0.19.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1qvdbmg8jwf2as1r7a3kl5kngp5m87kbdi4g7p13kfrypfzw2kiy";
    };
  };
}
