# mini_sql — generated by onix. Do not edit.
{
  "1.6.0" = {
    version = "1.6.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1vnn88gv935szjz2hndnisfgys19k9z07237w11vpxaad9zn75jj";
    };
  };
}
