# mini_mime — generated by onix. Do not edit.
{
  "1.1.5" = {
    version = "1.1.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1vycif7pjzkr29mfk4dlqv3disc5dn0va04lkwajlpr1wkibg0c6";
    };
  };
}
