# mini_histogram — generated by onix. Do not edit.
{
  "0.3.1" = {
    version = "0.3.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "156xs8k7fqqcbk1fbf0ndz6gfw380fb2jrycfvhb06269r84n4ba";
    };
  };
}
