# minitest-mock — generated by onix. Do not edit.
{
  "5.27.0" = {
    version = "5.27.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1c2m99b9hgvhyhzv0nxjqlgymr0vmxpalzlq41lrcyj1hmqysh3h";
    };
  };
}
