# mini_suffix — generated by onix. Do not edit.
{
  "0.3.3" = {
    version = "0.3.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1rr2nx1kixd7ccxqdnswjnflg46s6lr1f9vxkdy298k95zwk67cd";
    };
  };
}
