# mixlib-shellout — generated by onix. Do not edit.
{
  "3.3.4" = {
    version = "3.3.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "12rpd1l7m2xhvdkyz4i04zz9as7cr7shrgbxmhd46bk1d6gxxnzp";
    };
  };
}
