# mixlib-config — generated by onix. Do not edit.
{
  "3.0.27" = {
    version = "3.0.27";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0j0122lv2qgccl61njqi0pj6sp6nb85y07gcmw16bwg4k0c8nx6p";
    };
  };
}
