# mocha — generated by onix. Do not edit.
{
  "2.8.2" = {
    version = "2.8.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1vjfizp8yq0319dkc8yzzxr2bv5f1ki1qiknyx72prs7vclyfxqz";
    };
  };
}
