# mock_redis — generated by onix. Do not edit.
{
  "0.36.0" = {
    version = "0.36.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "05a6zhnh0wxc2n6883czs386s0ai3fym7pgrg0p1206ydxxkgsmc";
    };
  };
}
