# modis — generated by onix. Do not edit.
{
  "4.0.1" = {
    version = "4.0.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0kxbjbs20m4v5xf3mm12cpl24ck2nsgmfsh70bdjkfgrc4q141gf";
    };
  };
}
