# msgpack — generated by onix. Do not edit.
{
  "1.7.2" = {
    version = "1.7.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1a5adcb7bwan09mqhj3wi9ib52hmdzmqg7q08pggn3adibyn5asr";
    };
  };
  "1.7.5" = {
    version = "1.7.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1a5fsgchkpcca4wf3pipbb2jbj523l7fbaq37j10cr0yymwlkc7z";
    };
  };
  "1.8.0" = {
    version = "1.8.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0cnpnbn2yivj9gxkh8mjklbgnpx6nf7b8j2hky01dl0040hy0k76";
    };
  };
}
