# multipart-post — generated by onix. Do not edit.
{
  "2.2.3" = {
    version = "2.2.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1n0kvnrcrjn31jb97kcx3wj1f5kkjza7yygfq8rxzf3i57g7jaa6";
    };
  };
  "2.3.0" = {
    version = "2.3.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0lgyysrpl50wgcb9ahg29i4p01z0irb3p9lirygma0kkfr5dgk9x";
    };
  };
  "2.4.1" = {
    version = "2.4.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1a5lrlvmg2kb2dhw3lxcsv6x276bwgsxpnka1752082miqxd0wlq";
    };
  };
}
