# mustache — generated by onix. Do not edit.
{
  "1.1.1" = {
    version = "1.1.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1l0p4wx15mi3wnamfv92ipkia4nsx8qi132c6g51jfdma3fiz2ch";
    };
  };
}
