# mutex_m — generated by onix. Do not edit.
{
  "0.3.0" = {
    version = "0.3.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0l875dw0lk7b2ywa54l0wjcggs94vb7gs8khfw9li75n2sn09jyg";
    };
  };
}
