# mysql2 — generated by onix. Do not edit.
{
  "0.5.6" = {
    version = "0.5.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0cysv1wdfdbizwkd0d9s16s832khdwv31pgp01mw2g3bbpa4gx3h";
    };
  };
}
