# nakayoshi_fork — generated by onix. Do not edit.
{
  "0.0.4" = {
    version = "0.0.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1mj5czi7rxxmfq4v9qjz74lcqypvnjxhxqfs71zhb2rsfa97a6jg";
    };
  };
}
