# naught — generated by onix. Do not edit.
{
  "1.1.0" = {
    version = "1.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1wwjx35zgbc0nplp8a866iafk4zsrbhwwz4pav5gydr2wm26nksg";
    };
  };
}
