# neighbor — generated by onix. Do not edit.
{
  "0.2.3" = {
    version = "0.2.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1r9k34xz7x7fpd18bix0cd5bk2wv6mj8z67f8fr7l30d2717m23h";
    };
  };
}
