# net-http2 — generated by onix. Do not edit.
{
  "0.18.4" = {
    version = "0.18.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0xfrqc2l389szpm92vx354l7wf2wmaggd00qv6c9gqpgpjpc2v65";
    };
  };
}
