# net-scp — generated by onix. Do not edit.
{
  "4.0.0" = {
    version = "4.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1si2nq9l6jy5n2zw1q59a5gaji7v9vhy8qx08h4fg368906ysbdk";
    };
  };
}
