# net-ldap — generated by onix. Do not edit.
{
  "0.20.0" = {
    version = "0.20.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0wjkrvcwnxa6ggq0nfz004f1blm1c67fv7c6614sraak0wshn25j";
    };
  };
}
