# net-imap — generated by onix. Do not edit.
{
  "0.4.10" = {
    version = "0.4.10";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0zn7j2w0hc622ig0rslk4iy6yp3937dy9ibhyr1mwwx39n7paxaj";
    };
  };
  "0.4.20" = {
    version = "0.4.20";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "08ly904zlkwzj1zlqh1sn51b6y68yc436bmgknk4inpvf67bzgyc";
    };
  };
  "0.5.5" = {
    version = "0.5.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0ak8w6ypw4lba1y1mdmqwvkrh84ps6h9kd7hn029h9k85j9sirmb";
    };
  };
  "0.5.12" = {
    version = "0.5.12";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0i24prs7yy1p1zdps2x1ksb7lmvbn2f0llxwdjdw3z2ksddx136b";
    };
  };
  "0.6.2" = {
    version = "0.6.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1imc50a9ic3ynsl3k0japhmb0ggrgp2c186cfqbcclv892nsrjh8";
    };
  };
}
