# net-sftp — generated by onix. Do not edit.
{
  "4.0.0" = {
    version = "4.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0r33aa2d61hv1psm0l0mm6ik3ycsnq8symv7h84kpyf2b7493fv5";
    };
  };
}
