# net-pop — generated by onix. Do not edit.
{
  "0.1.2" = {
    version = "0.1.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1wyz41jd4zpjn0v1xsf9j778qx1vfrl24yc20cpmph8k42c4x2w4";
    };
  };
}
