# net-smtp — generated by onix. Do not edit.
{
  "0.3.4" = {
    version = "0.3.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0hwiqplhi29kfjl8jm0rhl51qv6wmxfynl4qap1dhv9xdwc4bm1x";
    };
  };
  "0.4.0.1" = {
    version = "0.4.0.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0csspzqrg7s2v2wdp6vqqs1rra6w5ilpgnps5h52ig6rp7x2i389";
    };
  };
  "0.5.1" = {
    version = "0.5.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0dh7nzjp0fiaqq1jz90nv4nxhc2w359d7c199gmzq965cfps15pd";
    };
  };
}
