# newrelic_rpm — generated by onix. Do not edit.
{
  "9.6.0" = {
    version = "9.6.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1scpa6lncwcz246a9mx1vyzggcs4y4f2fi1hfmz28m0qdk5i4x1k";
    };
  };
}
