# nio4r — generated by onix. Do not edit.
{
  "2.7.0" = {
    version = "2.7.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0xkjz56qc7hl7zy7i7bhiyw5pl85wwjsa4p70rj6s958xj2sd1lm";
    };
  };
  "2.7.3" = {
    version = "2.7.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "017nbw87dpr4wyk81cgj8kxkxqgsgblrkxnmmadc77cg9gflrfal";
    };
  };
  "2.7.4" = {
    version = "2.7.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1a9www524fl1ykspznz54i0phfqya4x45hqaz67in9dvw1lfwpfr";
    };
  };
  "2.7.5" = {
    version = "2.7.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "18fwy5yqnvgixq3cn0h63lm8jaxsjjxkmj8rhiv8wpzv9271d43c";
    };
  };
}
