# notiffany — generated by onix. Do not edit.
{
  "0.1.3" = {
    version = "0.1.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0f47h3bmg1apr4x51szqfv3rh2vq58z3grh4w02cp3bzbdh6jxnk";
    };
  };
}
