# oauth — generated by onix. Do not edit.
{
  "0.5.10" = {
    version = "0.5.10";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1asrxrbgzgzf1r9rb0c785zyyaq9v5z7v3k1avsais2sh9q1y763";
    };
  };
  "1.1.0" = {
    version = "1.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1syx3hfimaqycy21kn8gmal1cb3bw3hzalv3in2ixnay1xzjp41q";
    };
  };
  "1.1.3" = {
    version = "1.1.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0cynpns6p04i4pza1lcnwxavar20713i3q5fnalk3gv18m9ipjki";
    };
  };
}
