# oauth2 — generated by onix. Do not edit.
{
  "1.4.11" = {
    version = "1.4.11";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "042w5lamxhllfxsv0y8v9cvdhmlasy5kxbhcdd3lzj9bhz4gqfb7";
    };
  };
  "2.0.9" = {
    version = "2.0.9";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1yzpaghh8kwzgmvmrlbzf36ks5s2hf34rayzw081dp2jrzprs7xj";
    };
  };
}
