# oauth-tty — generated by onix. Do not edit.
{
  "1.0.5" = {
    version = "1.0.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "05wb5n36i4h23hh9dx2m2cwjxx5vj0vgyrn2xr6rsl54glq5rqil";
    };
  };
  "1.0.6" = {
    version = "1.0.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0liirgg4yaqng7makq4di6rpq78s5r7j33wd64ccwz1n3n3d32wy";
    };
  };
}
