# octokit — generated by onix. Do not edit.
{
  "5.6.1" = {
    version = "5.6.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "15g4kyag6gmxxq6d03472h7srm3imlsks1wg6nac7hl3mb1b5vs8";
    };
  };
}
