# oj — generated by onix. Do not edit.
{
  "3.16.3" = {
    version = "3.16.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0g5nx99lrwmk6ynfaacqkyijnhvi4mckm77bmvpa0jmfg068l26h";
    };
  };
  "3.16.10" = {
    version = "3.16.10";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0z1xw7xm7xkxnslhxqvfzvv5f1q1cl40niwvaxny2cg3fkcvw9kz";
    };
  };
  "3.16.12" = {
    version = "3.16.12";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0mmmswza8f4divl0mvkfq62pcdvm8c56j854wv7z9g6s0rmav7xd";
    };
  };
  "3.16.15" = {
    version = "3.16.15";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1kdjl69vg6103dmiv2kqz7cssvd14spv4l521x6gbzp8qg528csd";
    };
  };
}
