# omniauth_openid_connect — generated by onix. Do not edit.
{
  "0.8.0" = {
    version = "0.8.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "099xg7s6450wlfzs77mbdx78g3dp0glx5q6f44i78akf7283hbqz";
    };
  };
}
