# omniauth-facebook — generated by onix. Do not edit.
{
  "9.0.0" = {
    version = "9.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0m7q38kjm94wgq6h7hk9546yg33wcs3vf1v6zp0vx7nwkvfxh2j4";
    };
  };
}
