# omniauth-cas — generated by onix. Do not edit.
{
  "3.0.2" = {
    version = "3.0.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "03b034imgj5jwflc4db7hsp0n5ivqyqkmsfhc5drlidrcdfv2f0q";
    };
  };
}
