# opentelemetry-instrumentation-faraday — generated by onix. Do not edit.
{
  "0.31.0" = {
    version = "0.31.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "02w4157lmf5p9cjkxq35i5azcsskmrzg5vi09air1261sjbdq00w";
    };
  };
}
