# opensearch-ruby — generated by onix. Do not edit.
{
  "3.4.0" = {
    version = "3.4.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0pd0ihmsjp0m0ckrv3jnwhzmls3kz2pcn21yqas5jg7dddl231ha";
    };
  };
}
