# opentelemetry-instrumentation-net_http — generated by onix. Do not edit.
{
  "0.27.0" = {
    version = "0.27.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1449gz1brzxd1wxqhaq3z1r752csgmqp6kjz7c20jsk4hxc7rbgp";
    };
  };
}
