# opentelemetry-helpers-sql — generated by onix. Do not edit.
{
  "0.3.0" = {
    version = "0.3.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1y9p7xxn491pjdcb9n4m25lvpigr63ywflqw9lfd8vd1sqbq1c2b";
    };
  };
}
