# opentelemetry-instrumentation-active_record — generated by onix. Do not edit.
{
  "0.11.1" = {
    version = "0.11.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "14kwks0130mrggk3irg4qvx5fmwk9gxv6w23dy6ryi50xqs3y20v";
    };
  };
}
