# opentelemetry-instrumentation-active_job — generated by onix. Do not edit.
{
  "0.10.1" = {
    version = "0.10.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "129ajjrxigl4pag1nlzbdv1js5bij4ll92i1ix50c3f24h9338df";
    };
  };
}
