# openid_connect — generated by onix. Do not edit.
{
  "2.3.1" = {
    version = "2.3.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "10i13cn40jiiw8lslkv7bj1isinnwbmzlk6msgiph3gqry08702x";
    };
  };
}
