# opentelemetry-instrumentation-action_pack — generated by onix. Do not edit.
{
  "0.15.1" = {
    version = "0.15.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0wzj0xmivyx243slz526z54lqyhsiyzzrbha4szyxjl30xsdxyl4";
    };
  };
}
