# opentelemetry-instrumentation-excon — generated by onix. Do not edit.
{
  "0.27.0" = {
    version = "0.27.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1fxmhgvj15w4ggamnzb3aic15nzgxwivpaj6cq9y2a031wb6wzix";
    };
  };
}
