# opentelemetry-common — generated by onix. Do not edit.
{
  "0.23.0" = {
    version = "0.23.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0b5k7qc81ln96ayba90hm6ww7qpk8y7lc1r2mphblmwx8y812wns";
    };
  };
}
