# opentelemetry-instrumentation-action_mailer — generated by onix. Do not edit.
{
  "0.6.1" = {
    version = "0.6.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0mqh8z6myff0j11zcnm34s1lc8qzmzzqdrhzk95y2sh6vdmqd143";
    };
  };
}
