# opentelemetry-instrumentation-rails — generated by onix. Do not edit.
{
  "0.39.1" = {
    version = "0.39.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0vy93a3hpi8l8crljxwxzxwmvyf9gg1pff6dnpxl0c2ljmwdynbr";
    };
  };
}
