# opentelemetry-instrumentation-active_storage — generated by onix. Do not edit.
{
  "0.3.1" = {
    version = "0.3.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "17p8zmfyigdqvgy3d1691ayzm6nj4q4nx2n3qk01f7wjakphz6zq";
    };
  };
}
