# opentelemetry-instrumentation-rack — generated by onix. Do not edit.
{
  "0.29.0" = {
    version = "0.29.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0xzk88iiiggx3kdfy5y75cb79cc5gn8jsl1vwg5n8w086s1vnb4y";
    };
  };
}
