# opentelemetry-instrumentation-base — generated by onix. Do not edit.
{
  "0.25.0" = {
    version = "0.25.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "09ysfv2x25svwl4yxrbgmjkwrlkylr7plci3jjb6wkim11zklak4";
    };
  };
}
