# opentelemetry-instrumentation-http_client — generated by onix. Do not edit.
{
  "0.27.0" = {
    version = "0.27.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "03k96103fjz3pfjjj0wd42092psxxrdldmdj6hwnsfvd54hrlqva";
    };
  };
}
