# opentelemetry-exporter-otlp — generated by onix. Do not edit.
{
  "0.31.1" = {
    version = "0.31.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0jj78y79mawj86v5g3kcz6k81izd0m0w47wyyk2br744swbvwn2k";
    };
  };
}
