# opentelemetry-helpers-sql-processor — generated by onix. Do not edit.
{
  "0.4.0" = {
    version = "0.4.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1x13ig8z9fabw5l3p5lrm0ad80qsibmx0cfw8z99n8c751x8s8zc";
    };
  };
}
