# opentelemetry-instrumentation-active_support — generated by onix. Do not edit.
{
  "0.10.1" = {
    version = "0.10.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0zf5kg2h9zgmrwnq7v7by2nyhkxa20gmi5nyqqrpwyaqf4v9isl2";
    };
  };
}
