# opentelemetry-instrumentation-active_model_serializers — generated by onix. Do not edit.
{
  "0.24.0" = {
    version = "0.24.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "05ff7yxy2v96kslsqn1y68669is00798i9fgk9fy85vx2r21xs4g";
    };
  };
}
