# opentelemetry-instrumentation-http — generated by onix. Do not edit.
{
  "0.28.0" = {
    version = "0.28.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1kfafsrd6fx6w6ccwrkmn5q4jp4l86a1y13fs600fx347mcsjih9";
    };
  };
}
