# opentelemetry-api — generated by onix. Do not edit.
{
  "1.7.0" = {
    version = "1.7.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0kr1jyk67zn4axafcb2fji5b8xvr56hhfg2y33s5pnzjlr72dzfc";
    };
  };
}
