# optimist — generated by onix. Do not edit.
{
  "3.2.1" = {
    version = "3.2.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0kp3f8g7g7cbw5vfkmpdv71pphhpcxk3lpc892mj9apkd7ys1y4c";
    };
  };
}
