# orm_adapter — generated by onix. Do not edit.
{
  "0.5.0" = {
    version = "0.5.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1fg9jpjlzf5y49qs9mlpdrgs5rpcyihq1s4k79nv9js0spjhnpda";
    };
  };
}
