# parallel — generated by onix. Do not edit.
{
  "1.24.0" = {
    version = "1.24.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "15wkxrg1sj3n1h2g8jcrn7gcapwcgxr659ypjf75z1ipkgxqxwsv";
    };
  };
  "1.26.3" = {
    version = "1.26.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1vy7sjs2pgz4i96v5yk9b7aafbffnvq7nn419fgvw55qlavsnsyq";
    };
  };
  "1.27.0" = {
    version = "1.27.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0c719bfgcszqvk9z47w2p8j2wkz5y35k48ywwas5yxbbh3hm3haa";
    };
  };
}
