# parallel_tests — generated by onix. Do not edit.
{
  "5.5.0" = {
    version = "5.5.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0rpn88b55q0kf21gxd7x1p5j44fg0fp81w30nfkrch3wl96iwg3q";
    };
  };
}
