# pastel — generated by onix. Do not edit.
{
  "0.8.0" = {
    version = "0.8.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0xash2gj08dfjvq4hy6l1z22s5v30fhizwgs10d6nviggpxsj7a8";
    };
  };
}
