# pdf-reader — generated by onix. Do not edit.
{
  "2.15.0" = {
    version = "2.15.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "11h8dhhd2c8mxssibk9q6qn7ilj4p71crlfirw8pppn8pr85f0n5";
    };
  };
}
