# pg — generated by onix. Do not edit.
{
  "1.5.3" = {
    version = "1.5.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1zcvxmfa8hxkhpp59fhxyxy1arp70f11zi1jh9c7bsdfspifb7kb";
    };
  };
  "1.5.6" = {
    version = "1.5.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "071b55bhsz7mivlnp2kv0a11msnl7xg5awvk8mlflpl270javhsb";
    };
  };
  "1.6.2" = {
    version = "1.6.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0xf8i58shwvwlka4ld12nxcgqv0d5r1yizsvw74w5jaw83yllqaq";
    };
  };
  "1.6.3" = {
    version = "1.6.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "16caca7lcz5pwl82snarqrayjj9j7abmxqw92267blhk7rbd120k";
    };
  };
}
