# pg_query — generated by onix. Do not edit.
{
  "4.2.3" = {
    version = "4.2.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "15ynrzqsmmbmxib8ri8n9k6z3l6rwd91j7y1mghm33nfgdf9bj8w";
    };
  };
}
