# pg_search — generated by onix. Do not edit.
{
  "2.3.6" = {
    version = "2.3.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "18q0prwc6iwqb86agh2fwmfi07kf0bqi9qk96130c6fqf892lbv8";
    };
  };
}
