# pitchfork — generated by onix. Do not edit.
{
  "0.18.1" = {
    version = "0.18.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0n9hf4w76s124ysa6y6q92pcrnfhxq4w1xrjhz90ihjj8c199wlq";
    };
  };
}
