# playwright-ruby-client — generated by onix. Do not edit.
{
  "1.57.0" = {
    version = "1.57.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1x4y7r7h7a3fmy62bf1501jcl5q20lzdgw3b44rwd18fbaidd2wp";
    };
  };
  "1.57.1" = {
    version = "1.57.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "10p9gf2wy0bfa2ysrl4m56qa2mggpzhppxfall5yz167qcbma4c1";
    };
  };
}
