# premailer-rails — generated by onix. Do not edit.
{
  "1.12.0" = {
    version = "1.12.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0004f73kgrglida336fqkgx906m6n05nnfc17mypzg5rc78iaf61";
    };
  };
}
