# prettier_print — generated by onix. Do not edit.
{
  "1.2.1" = {
    version = "1.2.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1ybgks9862zmlx71zd4j20ky86fsrp6j6m0az4hzzb1zyaskha57";
    };
  };
}
