# procore-sift — generated by onix. Do not edit.
{
  "1.0.0" = {
    version = "1.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0y1ya6jh98948gn8pcln0h8f1ahq3wc7hf9rg10nb44vhfviv9a0";
    };
  };
}
