# progress — generated by onix. Do not edit.
{
  "3.6.0" = {
    version = "3.6.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0wymdk40cwrqn32gwg1kw94s5p1n0z3n7ma7x1s62gd4vw3d63in";
    };
  };
}
