# prometheus_exporter — generated by onix. Do not edit.
{
  "2.3.1" = {
    version = "2.3.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "013azj8pmmn6fsj1grnq0960pzb5zbpzmv1f2mdm2frsdjjaf0f5";
    };
  };
}
