# propshaft — generated by onix. Do not edit.
{
  "1.3.1" = {
    version = "1.3.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "14n3fhz5hzpsczp4spqc26csfgk2qga7mgcm7px9z0byyr76dk4s";
    };
  };
}
