# pry-rails — generated by onix. Do not edit.
{
  "0.3.9" = {
    version = "0.3.9";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1cf4ii53w2hdh7fn8vhqpzkymmchjbwij4l3m7s6fsxvb9bn51j6";
    };
  };
  "0.3.11" = {
    version = "0.3.11";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0garafb0lxbm3sx2r9pqgs7ky9al58cl3wmwc0gmvmrl9bi2i7m6";
    };
  };
}
