# pry-stack_explorer — generated by onix. Do not edit.
{
  "0.6.1" = {
    version = "0.6.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0h7kp99r8vpvpbvia079i58932qjz2ci9qhwbk7h1bf48ydymnx2";
    };
  };
}
