# puma — generated by onix. Do not edit.
{
  "5.6.9" = {
    version = "5.6.9";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0a22kb9qznv09m5707d5cnwd1rhk55d4nbldszbch3h8a4j1nw10";
    };
  };
  "6.4.3" = {
    version = "6.4.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0gml1rixrfb0naciq3mrnqkpcvm9ahgps1c04hzxh4b801f69914";
    };
  };
  "6.5.0" = {
    version = "6.5.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1wl9q4fl8gvhwdpfxghx6jdqi4508287pcgiwi96sdbzmdfbglcl";
    };
  };
  "7.1.0" = {
    version = "7.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1pa9zpr51kqnsq549p6apvnr95s9flx6bnwqii24s8jg2b5i0p74";
    };
  };
  "7.2.0" = {
    version = "7.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1a3jd9qakasizrf7dkq5mqv51fjf02r2chybai2nskjaa6mz93mz";
    };
  };
}
