# pundit-matchers — generated by onix. Do not edit.
{
  "1.9.0" = {
    version = "1.9.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0kvbpmp25qkb3s6zpr49ybmb89sb5ra4vr34s909vd5p10y1d25j";
    };
  };
}
