# queue_classic — generated by onix. Do not edit.
{
  "4.0.0" = {
    version = "4.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0npyhajf2fc80apkw9s2kj0n254w5lcl4xpjidg5d5w1fb19abh6";
    };
  };
}
