# rack-session — generated by onix. Do not edit.
{
  "1.0.2" = {
    version = "1.0.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0xhxhlsz6shh8nm44jsmd9276zcnyzii364vhcvf0k8b8bjia8d0";
    };
  };
  "2.1.1" = {
    version = "2.1.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1sg4laz2qmllxh1c5sqlj9n1r7scdn08p3m4b0zmhjvyx9yw0v8b";
    };
  };
}
