# rack — generated by onix. Do not edit.
{
  "2.2.10" = {
    version = "2.2.10";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0ax778fsfvlhj7c11n0d1wdcb8bxvkb190a9lha5d91biwzyx9g4";
    };
  };
  "2.2.21" = {
    version = "2.2.21";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0fgpa9qm5qgza69fjnagg2alxs2wmj41aq7z4kj5yib50wpzgqhl";
    };
  };
  "3.2.1" = {
    version = "3.2.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0cwy1br09dh5fklwf5xna7vabns8c1229kr2v0a0s6y2brz3zbrh";
    };
  };
  "3.2.3" = {
    version = "3.2.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0h9xr8ivrfr0i5f2n7czg74r3ri1pba8wb84bzr78iaqlqykg6i3";
    };
  };
  "3.2.4" = {
    version = "3.2.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1xmnrk076sqymilydqgyzhkma3hgqhcv8xhy7ks479l2a3vvcx2x";
    };
  };
}
