# rack-timeout — generated by onix. Do not edit.
{
  "0.6.3" = {
    version = "0.6.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1cqa9lh2rdqqvhfxbrdys7mj2x4vxhqmf57iww2x8961mhp8jm0p";
    };
  };
}
