# rack-proxy — generated by onix. Do not edit.
{
  "0.7.7" = {
    version = "0.7.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "12jw7401j543fj8cc83lmw72d8k6bxvkp9rvbifi88hh01blnsj4";
    };
  };
}
