# rack-oauth2 — generated by onix. Do not edit.
{
  "2.3.0" = {
    version = "2.3.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0cn6a9v8nry9fx4zrzp1xakfp2n5xv5075j90q56m20k7zvjrq23";
    };
  };
}
