# rack-mini-profiler — generated by onix. Do not edit.
{
  "3.2.0" = {
    version = "3.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "02ksyg68i9b4k6sv3xy4460brfnms9lnfnyx91qfk8792i0rv589";
    };
  };
  "4.0.1" = {
    version = "4.0.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0y1x4rc7bz8x3zn8p6g21rw6ivbjml6a2vl9dhchiy8i6b110n28";
    };
  };
}
