# rack-cache — generated by onix. Do not edit.
{
  "1.17.0" = {
    version = "1.17.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "147by0mlkp18qi5fhz4yhqwyh4dl3y0bp66z4iahyfqpy8z2yna9";
    };
  };
}
