# rack-host-redirect — generated by onix. Do not edit.
{
  "1.3.0" = {
    version = "1.3.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1ywb5391kxsm0bw5rhxqawlbivngbm1ikcjy0bbnyywi95bcky38";
    };
  };
}
