# rails_failover — generated by onix. Do not edit.
{
  "2.3.0" = {
    version = "2.3.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1jcijjfz595nd1h0z4h2jb7iw4md5snrglha0xmryvzxfh3fmmpf";
    };
  };
}
