# rails-i18n — generated by onix. Do not edit.
{
  "7.0.8" = {
    version = "7.0.8";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1k8jvm3l4gafw7hyvpky7yzjjnkr3iy7l59lyam8ah3kqhmzk7zf";
    };
  };
  "8.1.0" = {
    version = "8.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1wvcbdslb5gfvs9dw7kscd9da3xfyr3mdh1w4a28vwmy19ngvmaj";
    };
  };
}
