# rails — generated by onix. Do not edit.
{
  "7.0.8.7" = {
    version = "7.0.8.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1vfd2l3m1802vq7gdqpvd3mkcfhxacpsxixqpx4n6x0mv56ysrsy";
    };
  };
  "7.1.5.2" = {
    version = "7.1.5.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0ikmj9p48n8mms39jq8w91y12cm7zmxc7a1r9i7vzfn509r0i4m2";
    };
  };
  "8.0.3" = {
    version = "8.0.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0igxnfy4xckvk2b6x17zrwa8xwnkxnpv36ca4wma7bhs5n1c10sx";
    };
  };
  "8.2.0.alpha" = {
    version = "8.2.0.alpha";
    source = {
      type = "git";
      url = "https://github.com/rails/rails.git";
      rev = "60d92e4e7dfe923528ccdccc18820ccfe841b7b8";
      sha256 = "sha256-SzsJ41egLhybFG3+JHcn8tAY3lMfVWg/cmU5gg0G8Hg=";
      fetchSubmodules = false;
    };
  };
}
