# rails_multisite — generated by onix. Do not edit.
{
  "7.0.0" = {
    version = "7.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1winy1bzrzspb0ynnx5rcy8fhg1ldkzcnydn7zkvxll6xmjg7b3s";
    };
  };
}
