# railties — generated by onix. Do not edit.
{
  "7.0.8.7" = {
    version = "7.0.8.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0pshckc6b9h2ikl3svk47iv0nq6v908h3q9ndlblpg021cl8bf8s";
    };
  };
  "7.1.5.2" = {
    version = "7.1.5.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "08fnm4bfkmjknnzmi1wkvyw9b2r4c5ammk0jzp4mgfgv1fgwh2mg";
    };
  };
  "8.0.3" = {
    version = "8.0.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1lpiazaaq8di4lz9iqjqdrsnha6kfq6k35kd9nk9jhhksz51vqxc";
    };
  };
  "8.0.4" = {
    version = "8.0.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0iybsmr8yv8gg6a4cikmh0394sk707qr7h85vny4mazzvi9xh0w2";
    };
  };
  "8.2.0.alpha" = {
    version = "8.2.0.alpha";
    source = {
      type = "git";
      url = "https://github.com/rails/rails.git";
      rev = "60d92e4e7dfe923528ccdccc18820ccfe841b7b8";
      sha256 = "sha256-SzsJ41egLhybFG3+JHcn8tAY3lMfVWg/cmU5gg0G8Hg=";
      fetchSubmodules = false;
    };
    subdir = "railties";
  };
}
