# raindrops — generated by onix. Do not edit.
{
  "0.20.1" = {
    version = "0.20.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0c27mcglrj928zkm4d2spj9yh2xkkka8ns5s6bidkwild3zvj3ma";
    };
  };
}
