# rainbow — generated by onix. Do not edit.
{
  "3.1.1" = {
    version = "3.1.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0smwg4mii0fm38pyb5fddbmrdpifwv22zv3d3px2xx497am93503";
    };
  };
}
