# ransack — generated by onix. Do not edit.
{
  "3.2.1" = {
    version = "3.2.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "02j5gdf23jhlyvq1bkyyq0f4ilhvashx6kcynlm7nyqxa8s5wp35";
    };
  };
}
