# rbtrace — generated by onix. Do not edit.
{
  "0.5.3" = {
    version = "0.5.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0gwjrdawjv630xhzwld9b0vrh391sph255vxshpv36jx60pjjcn4";
    };
  };
}
