# rbtree — generated by onix. Do not edit.
{
  "0.4.6" = {
    version = "0.4.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1z0h1x7fpkzxamnvbw1nry64qd6n0nqkwprfair29z94kd3a9vhl";
    };
  };
}
