# rchardet — generated by onix. Do not edit.
{
  "1.10.0" = {
    version = "1.10.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "03rr05qam5d6gcsnsjs85bnwg80qww484xql347j42kj3bb2xsnm";
    };
  };
}
