# recaptcha — generated by onix. Do not edit.
{
  "5.16.0" = {
    version = "5.16.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "01hi639zhwfjj3anjzz2f7mkxvdl8jsj7mj787rd3q4inyqm6jv8";
    };
  };
}
