# redis-client — generated by onix. Do not edit.
{
  "0.22.2" = {
    version = "0.22.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1h5cgdv40zk0ph1nl64ayhn6anzwy6mbxyi7fci9n404ryvy9zii";
    };
  };
  "0.25.2" = {
    version = "0.25.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1w6nz3k1kkg2xwdkbaflkjaj62fvk9j7lgk6p2qgsffs556f6dxa";
    };
  };
  "0.26.1" = {
    version = "0.26.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0wx0v68lh924x544mkpydcrkkbr7i386xvkpyxgsf5j55j3d4f8y";
    };
  };
  "0.26.4" = {
    version = "0.26.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "083i9ig39bc249mv24nsb2jlfwcdgmp9kbpy5ph569nsypphpmrs";
    };
  };
}
