# redis-actionpack — generated by onix. Do not edit.
{
  "5.4.0" = {
    version = "5.4.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0h1mx8shrzpcj27k9kw77f4cq7i217vxfd1ksqb4g485md4zc37i";
    };
  };
}
