# redis-store — generated by onix. Do not edit.
{
  "1.10.0" = {
    version = "1.10.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "17mhr1g3lmacrgjndbmrklngy32g55165n53111q70kykx7qjn7j";
    };
  };
}
