# representable — generated by onix. Do not edit.
{
  "3.2.0" = {
    version = "3.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1kms3r6w6pnryysnaqqa9fsn0v73zx1ilds9d1c565n3xdzbyafc";
    };
  };
}
