# resque — generated by onix. Do not edit.
{
  "2.7.0" = {
    version = "2.7.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1c31p5lxvqf5fx6ac3kwskhs2hkzh6b3rcpr7wc4k9mhi64dqpv8";
    };
  };
}
