# resque-scheduler — generated by onix. Do not edit.
{
  "4.11.0" = {
    version = "4.11.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "189j1ykllf9bm47nq3bwi3fhqvnw0gy1f9qx2h1gwb6cvjng72sf";
    };
  };
}
