# rest-client — generated by onix. Do not edit.
{
  "2.1.0" = {
    version = "2.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1qs74yzl58agzx9dgjhcpgmzfn61fqkk33k1js2y5yhlvc5l19im";
    };
  };
}
