# retriable — generated by onix. Do not edit.
{
  "3.1.2" = {
    version = "3.1.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1q48hqws2dy1vws9schc0kmina40gy7sn5qsndpsfqdslh65snha";
    };
  };
}
