# reverse_markdown — generated by onix. Do not edit.
{
  "2.1.1" = {
    version = "2.1.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0087vhw5ik50lxvddicns01clkx800fk5v5qnrvi3b42nrk6885j";
    };
  };
}
