# rice — generated by onix. Do not edit.
{
  "4.1.0" = {
    version = "4.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1ppba5hkywr329apdvik1wrglbbwazrh0q0dhxw4kr0ycnxh7rpv";
    };
  };
}
