# rinku — generated by onix. Do not edit.
{
  "2.0.6" = {
    version = "2.0.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0zcdha17s1wzxyc5814j6319wqg33jbn58pg6wmxpws36476fq4b";
    };
  };
}
