# rolify — generated by onix. Do not edit.
{
  "6.0.1" = {
    version = "6.0.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1dmmvqx8sh5f8s2y7lx59q2avskfjhmw1k7rlsnwqcs01kvznigy";
    };
  };
}
