# rpam2 — generated by onix. Do not edit.
{
  "4.0.2" = {
    version = "4.0.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1zvli3s4z1hf2l7gyfickm5i3afjrnycc3ihbiax6ji6arpbyf33";
    };
  };
}
