# rpush-redis — generated by onix. Do not edit.
{
  "1.2.0" = {
    version = "1.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0d5x083cf16qbdcjrhnk765niyr1107j6fm9lm7rp5hnc9zx3kdx";
    };
  };
}
