# rpush — generated by onix. Do not edit.
{
  "7.0.1" = {
    version = "7.0.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1cr5kjaxh985x7wbv8h262a6c1k8qm97w2ly02mifs0s8bxv9jkq";
    };
  };
}
