# rrule — generated by onix. Do not edit.
{
  "0.7.0" = {
    version = "0.7.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "11qzhn3y6pl01rfcy0nawa5fcfh00pgc7qsxwbgss1ap7k1nlsw1";
    };
  };
}
