# rspec-sidekiq — generated by onix. Do not edit.
{
  "5.2.0" = {
    version = "5.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0rn2yzkn3ywryvrigmsr1902zd14kx5ya8n41jd1zc1szxkgbpvv";
    };
  };
}
