# rspec-mocks — generated by onix. Do not edit.
{
  "3.12.7" = {
    version = "3.12.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1a66wizqkdq49h74aysp9p0ymm3pj8wxrr98ix2fj7bqg5w0mwdj";
    };
  };
  "3.13.1" = {
    version = "3.13.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0f3vgp43hajw716vmgjv6f4ar6f97zf50snny6y3fy9kkj4qjw88";
    };
  };
  "3.13.7" = {
    version = "3.13.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "071bqrk2rblk3zq3jk1xxx0dr92y0szi5pxdm8waimxici706y89";
    };
  };
}
