# rspec-github — generated by onix. Do not edit.
{
  "3.0.0" = {
    version = "3.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1bv8b6ld7w3rccjnxqypfdg35i91wyv551sr41647r6krbc3rbs6";
    };
  };
}
