# rspec — generated by onix. Do not edit.
{
  "3.12.0" = {
    version = "3.12.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "171rc90vcgjl8p1bdrqa92ymrj8a87qf6w20x05xq29mljcigi6c";
    };
  };
  "3.13.2" = {
    version = "3.13.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "11q5hagj6vr694innqj4r45jrm8qcwvkxjnphqgyd66piah88qi0";
    };
  };
}
