# rspec-retry — generated by onix. Do not edit.
{
  "0.6.2" = {
    version = "0.6.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0n6qc0d16h6bgh1xarmc8vc58728mgjcsjj8wcd822c8lcivl0b1";
    };
  };
}
