# rspec-html-matchers — generated by onix. Do not edit.
{
  "0.10.0" = {
    version = "0.10.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1bp9q28qw4xmxknrrp3ppcr08bbcnnand6r9prw4920407mvy96l";
    };
  };
}
