# rspec-multi-mock — generated by onix. Do not edit.
{
  "0.3.1" = {
    version = "0.3.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0k3rafylxilq9jzdz450vgiwf3bvz4a9l3ppmgncv78xipr71518";
    };
  };
}
