# rspec-support — generated by onix. Do not edit.
{
  "3.12.2" = {
    version = "3.12.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "07bn3c3qs02myyq8h90b9lqxjzwdmcnlmgjjc34l4f6hr6yrlwfy";
    };
  };
  "3.13.1" = {
    version = "3.13.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "03z7gpqz5xkw9rf53835pa8a9vgj4lic54rnix9vfwmp2m7pv1s8";
    };
  };
  "3.13.6" = {
    version = "3.13.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1cmgz34hwj5s3jwxhyl8mszs24nci12ffbrmr5jb1si74iqf739f";
    };
  };
  "3.13.7" = {
    version = "3.13.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0z64h5rznm2zv21vjdjshz4v0h7bxvg02yc6g7yzxakj11byah06";
    };
  };
}
