# rspec-core — generated by onix. Do not edit.
{
  "3.12.3" = {
    version = "3.12.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "03bgkck72xihfg3h619zxhkf7i5l52zzfgv158frfa5clpg8j8bq";
    };
  };
  "3.13.0" = {
    version = "3.13.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0k252n7s80bvjvpskgfm285a3djjjqyjcarlh3aq7a4dx2s94xsm";
    };
  };
  "3.13.6" = {
    version = "3.13.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0bcbh9yv6cs6pv299zs4bvalr8yxa51kcdd1pjl60yv625j3r0m8";
    };
  };
}
