# rswag-specs — generated by onix. Do not edit.
{
  "2.5.1" = {
    version = "2.5.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "00gm5qbf56shi655hwxzas74avsfv8b91v6i8v06i4jdw8y4qky2";
    };
  };
  "2.17.0" = {
    version = "2.17.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1qx9mxhnwz8ia9ry1fwn3hzc2zg7n774gvm4whgp9y49vzvbvcm3";
    };
  };
}
