# rubocop-rspec — generated by onix. Do not edit.
{
  "2.29.1" = {
    version = "2.29.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "04rfx0f0ns3vfz16fvbxgc9ivjh6gkpqfdi0qsg3grq660dfhkjk";
    };
  };
  "3.6.0" = {
    version = "3.6.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0ya4815sp8g13w7a86sm0605fx7xyldck77f9pjjfrvpf5c21r60";
    };
  };
  "3.8.0" = {
    version = "3.8.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0cxb9i1brf1cks8anv8mdj65n9rq6jyldyd1ij9sj8zjng60si18";
    };
  };
  "3.9.0" = {
    version = "3.9.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1qjmvcpk6qwxjdh3w5smr2n7c1glxsdzpv5fi7bkg0j034v0m9wg";
    };
  };
}
