# rubocop-rspec_rails — generated by onix. Do not edit.
{
  "2.28.3" = {
    version = "2.28.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0618lfncmvnvkwa1jb0kga1f2yiiw1809flkj4kg52nagh3z4scp";
    };
  };
  "2.32.0" = {
    version = "2.32.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "004i5a4iww7l3vpaxl70ijypmi321afrslsgadbvksznf8f683aa";
    };
  };
}
