# rubocop-md — generated by onix. Do not edit.
{
  "2.0.1" = {
    version = "2.0.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "16xi11pgvnz7rvbm1q5hk9mxrm3sfvxd6kh6wmfxx2a3akx3msr0";
    };
  };
}
