# rubocop-rails — generated by onix. Do not edit.
{
  "2.24.1" = {
    version = "2.24.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "06dcxrr71sn0kkw8fwh0w884zbig2ilxpkl66s7lcis9jmkggv83";
    };
  };
  "2.30.3" = {
    version = "2.30.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "05d7g0m9mn1582lr6asrpwha0r7s7aa0dj1c51gd25m9v836anpw";
    };
  };
  "2.32.0" = {
    version = "2.32.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1404nfa0gw3p0xzmv4b9zg9v1da0nwc4m7796pl73zi2hwy65k4z";
    };
  };
  "2.33.4" = {
    version = "2.33.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1danlfzfqx3x1kna248sm2b1br5ki369r51x90jc4vbh6xk8zv1l";
    };
  };
  "2.34.3" = {
    version = "2.34.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1llsxc8wm2pq8glpv5mczd1h36fazbri3wwrh7dfqra80a4pklqh";
    };
  };
}
