# rubocop-rails-omakase — generated by onix. Do not edit.
{
  "1.0.0" = {
    version = "1.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0634z61i5fgb6vvkbc1y2abdnqkaf4ij25v8igf06six50hmhqr6";
    };
  };
}
