# rubocop-ast — generated by onix. Do not edit.
{
  "1.31.2" = {
    version = "1.31.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1v3q8n48w8h809rqbgzihkikr4g3xk72m1na7s97jdsmjjq6y83w";
    };
  };
  "1.44.1" = {
    version = "1.44.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "14lf3d9bdr8cv8x3xcn3ijql5x23svk5zy7mdinlzw1f7ch09k73";
    };
  };
  "1.46.0" = {
    version = "1.46.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0ar3y8w36am483ynyzg0x8iwhn8h34y8f4agny4lyqcqbfnzd9qd";
    };
  };
  "1.48.0" = {
    version = "1.48.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0xifbp09jfl1hdy9wwgq9dq2l7mf8y2ycm5d1zgcqvks7yzrppr2";
    };
  };
  "1.49.0" = {
    version = "1.49.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1zbikzd6237fvlzjfxdlhwi2vbmavg1cc81y6cyr581365nnghs9";
    };
  };
}
