# rubocop-capybara — generated by onix. Do not edit.
{
  "2.20.0" = {
    version = "2.20.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0f5r9di123hc4x2h453a143986plfzz9935bwc7267wj8awl8s1a";
    };
  };
  "2.22.1" = {
    version = "2.22.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "030wymq0jrblrdswl1lncj60dhcg5wszz6708qzsbziyyap8rn6f";
    };
  };
}
