# rubocop-performance — generated by onix. Do not edit.
{
  "1.21.0" = {
    version = "1.21.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "16jayzjaaglhx69s6b83acpdzcxxccfkcn69gfpkimf2j64zlm7c";
    };
  };
  "1.24.0" = {
    version = "1.24.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1da08idjsdclcm9cimjbvd1jz2gm6z62fsc8mywrb0rn7vzkkgg5";
    };
  };
  "1.25.0" = {
    version = "1.25.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1h9flnqk2f3llwf8g0mk0fvzzznfj7hsil3qg88m803pi9b06zbg";
    };
  };
  "1.26.1" = {
    version = "1.26.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0d0qyyw1332afi9glwfjkb4bd62gzlibar6j55cghv8rzwvbj6fd";
    };
  };
}
