# rubocop-discourse — generated by onix. Do not edit.
{
  "3.13.3" = {
    version = "3.13.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "17q5i9rjk5vanvpqphwpcr0aiqzinm47cv9plidhqpy4gbirawv3";
    };
  };
}
