# ruby-progressbar — generated by onix. Do not edit.
{
  "1.13.0" = {
    version = "1.13.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0cwvyb7j47m7wihpfaq7rc47zwwx9k4v7iqd9s1xch5nm53rrz40";
    };
  };
}
