# ruby2ruby — generated by onix. Do not edit.
{
  "2.5.0" = {
    version = "2.5.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "04bz2jw3ida07mgk450l9m6xklhzbv0z4s6ak6bl7vp4rhcy41f8";
    };
  };
}
