# rubyzip — generated by onix. Do not edit.
{
  "2.3.2" = {
    version = "2.3.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0grps9197qyxakbpw02pda59v45lfgbgiyw48i0mq9f2bn9y6mrz";
    };
  };
  "2.4.1" = {
    version = "2.4.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "05an0wz87vkmqwcwyh5rjiaavydfn5f4q1lixcsqkphzvj7chxw5";
    };
  };
  "3.2.2" = {
    version = "3.2.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0g2vx9bwl9lgn3w5zacl52ax57k4zqrsxg05ixf42986bww9kvf0";
    };
  };
}
