# ruby_llm-schema — generated by onix. Do not edit.
{
  "0.2.5" = {
    version = "0.2.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0kqhj89y857ja67q1fwj6sr5x4giaqm6fs78w8jh6477ilpd935h";
    };
  };
}
