# ruby-rc4 — generated by onix. Do not edit.
{
  "0.1.5" = {
    version = "0.1.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "00vci475258mmbvsdqkmqadlwn6gj9m01sp7b5a3zd90knil1k00";
    };
  };
}
