# ruby-openai — generated by onix. Do not edit.
{
  "7.3.1" = {
    version = "7.3.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1rwn93vjcjq3rymvxs2ah37mk07c7capk3ks75whzy9awzjbgm31";
    };
  };
}
