# ruby_llm — generated by onix. Do not edit.
{
  "1.8.2" = {
    version = "1.8.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "143gyh4x1cnziy6kqk2pr7plkd2zr3q94d6q3xwn875lmbi74faz";
    };
  };
}
