# ruby-readability — generated by onix. Do not edit.
{
  "0.7.2" = {
    version = "0.7.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "032qqqaj5v09a7r5jpblv7dc37f278qv3b1nag9wsbn6kb4dslbk";
    };
  };
}
