# ruby-lsp-rspec — generated by onix. Do not edit.
{
  "0.1.28" = {
    version = "0.1.28";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "14gl3g8gg8p8zknd07hkzrrgaqqq184pj7l3nw7dgih8pbzv7cqd";
    };
  };
}
