# ruby-statistics — generated by onix. Do not edit.
{
  "3.0.0" = {
    version = "3.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "10fwxwhby6n1q1k61bic2s0mddlfwb9x7a7306vir4s60cvh20v1";
    };
  };
}
