# ruby-lsp-rails — generated by onix. Do not edit.
{
  "0.4.8" = {
    version = "0.4.8";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1bj4bj35l9jas2yf6w93j5ngw3f24lck2j9h5zmxwqs0dn91z7gh";
    };
  };
}
