# safety_net_attestation — generated by onix. Do not edit.
{
  "0.5.0" = {
    version = "0.5.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1apjjd99bqsc22bfq66j27dp4im0amisy619hr9qbghdapfh3kf8";
    };
  };
}
