# safely_block — generated by onix. Do not edit.
{
  "0.4.0" = {
    version = "0.4.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1as1sjb07frp434yxap8227m2gpac6hf151fqkq1vi5paql2qf4q";
    };
  };
}
