# sass — generated by onix. Do not edit.
{
  "3.7.4" = {
    version = "3.7.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0p95lhs0jza5l7hqci1isflxakz83xkj97lkvxl919is0lwhv2w0";
    };
  };
}
