# sassc — generated by onix. Do not edit.
{
  "2.4.0" = {
    version = "2.4.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0gpqv48xhl8mb8qqhcifcp0pixn206a7imc07g48armklfqa4q2c";
    };
  };
}
