# sassc-embedded — generated by onix. Do not edit.
{
  "1.80.5" = {
    version = "1.80.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0gnbp770q1krka70phyf59amzw0dx92c0yx1psc9fkp5in9hqwmj";
    };
  };
}
