# sassc-rails — generated by onix. Do not edit.
{
  "2.1.2" = {
    version = "2.1.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1d9djmwn36a5m8a83bpycs48g8kh1n2xkyvghn7dr6zwh4wdyksz";
    };
  };
}
