# sass-listen — generated by onix. Do not edit.
{
  "4.0.0" = {
    version = "4.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0xw3q46cmahkgyldid5hwyiwacp590zj2vmswlll68ryvmvcp7df";
    };
  };
}
