# sax-machine — generated by onix. Do not edit.
{
  "1.3.2" = {
    version = "1.3.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0fhdflwdj8q0gfgz51k3zn1giq24fwvhvji75104rsly0dw2c4d1";
    };
  };
}
