# scenic — generated by onix. Do not edit.
{
  "1.9.0" = {
    version = "1.9.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1nb3an8af7f08jnhhbn8bxvgfxqb43qc9d5hgrz16ams96h3mv3f";
    };
  };
}
