# seed_dump — generated by onix. Do not edit.
{
  "3.3.1" = {
    version = "3.3.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0pz69f171fsy11sbgll065ha3wx0z8b517srwgpa43kmb6yc8ccm";
    };
  };
}
