# selectize-rails — generated by onix. Do not edit.
{
  "0.12.6" = {
    version = "0.12.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1adzp7b3qyl4ki1432mga914za0j9dzy7401vs92kl4avr40nns2";
    };
  };
}
