# sentry-sidekiq — generated by onix. Do not edit.
{
  "5.19.0" = {
    version = "5.19.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "106bxqzi0mhvxm583mly7a95rv77m89dd51433fwnpdk2m5yq5hv";
    };
  };
}
