# serverengine — generated by onix. Do not edit.
{
  "2.0.7" = {
    version = "2.0.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1gkm880njsi9x6vpb5grsspxb097hi8898drlbbkj1wl9qf2xv8l";
    };
  };
}
