# sexp_processor — generated by onix. Do not edit.
{
  "4.17.0" = {
    version = "4.17.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0vzz9mhg4kkdqf179pm30i204h7iskanxrk53j0csf0qrrs4iajd";
    };
  };
  "4.17.1" = {
    version = "4.17.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "182x05kpdjlckh31qizws50fz7sjk86yjjfmy45z61q3f930j4ci";
    };
  };
}
