# shellany — generated by onix. Do not edit.
{
  "0.0.1" = {
    version = "0.0.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1ryyzrj1kxmnpdzhlv4ys3dnl2r5r3d2rs2jwzbnd1v96a8pl4hf";
    };
  };
}
