# shopify_api — generated by onix. Do not edit.
{
  "14.8.0" = {
    version = "14.8.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1hfddyhsmi95xmjx7x7mhxk7y3yrlm5kfwq0d40jngq7v66fb7ng";
    };
  };
}
