# sidekiq-unique-jobs — generated by onix. Do not edit.
{
  "7.1.33" = {
    version = "7.1.33";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1am17wfx023z1x9sxq90cyjarcmcwb95mi456mcf13m783r4n190";
    };
  };
  "8.0.13" = {
    version = "8.0.13";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "16xfwjahmqd3jvxl0iwry15vzp6w7m8snjpkai0ypdjl98kd9pmp";
    };
  };
}
