# sidekiq_alive — generated by onix. Do not edit.
{
  "2.5.0" = {
    version = "2.5.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "061yjdqzi97zvq49qsndvi72vbjsx6gw6hhi7jcqnrjcav68k0v5";
    };
  };
}
