# sidekiq-cron — generated by onix. Do not edit.
{
  "1.12.0" = {
    version = "1.12.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0v09lg8kza19jmigqv5hx2ibhm75j6pa639sfy4bv2208l50hqv6";
    };
  };
}
