# simplecov — generated by onix. Do not edit.
{
  "0.21.2" = {
    version = "0.21.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1hrv046jll6ad1s964gsmcq4hvkr3zzr6jc7z1mns22mvfpbc3cr";
    };
  };
  "0.22.0" = {
    version = "0.22.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "198kcbrjxhhzca19yrdcd6jjj9sb51aaic3b0sc3pwjghg3j49py";
    };
  };
}
