# simpleidn — generated by onix. Do not edit.
{
  "0.2.3" = {
    version = "0.2.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0a9c1mdy12y81ck7mcn9f9i2s2wwzjh1nr92ps354q517zq9dkh8";
    };
  };
}
