# simplecov_json_formatter — generated by onix. Do not edit.
{
  "0.1.4" = {
    version = "0.1.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0a5l0733hj7sk51j81ykfmlk2vd5vaijlq9d5fn165yyx3xii52j";
    };
  };
}
