# simple_form — generated by onix. Do not edit.
{
  "5.4.1" = {
    version = "5.4.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0208na2s7q1hny77v78b6h677vrhy2v72cjw0d2mazjc0clx5hsq";
    };
  };
}
