# simple_oauth — generated by onix. Do not edit.
{
  "0.3.1" = {
    version = "0.3.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0dw9ii6m7wckml100xhjc6vxpjcry174lbi9jz5v7ibjr3i94y8l";
    };
  };
}
