# sinatra — generated by onix. Do not edit.
{
  "4.1.1" = {
    version = "4.1.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "002dkzdc1xqhvz5sdnj4vb0apczhs07mnpgq4kkd5dd1ka2pp6af";
    };
  };
}
