# slack-ruby-client — generated by onix. Do not edit.
{
  "2.7.0" = {
    version = "2.7.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1lwvshd4h5cpm37wcxjn89xcn67bc93x2s0glb7cmh5gm630c8qa";
    };
  };
}
