# smart_properties — generated by onix. Do not edit.
{
  "1.17.0" = {
    version = "1.17.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0jrqssk9qhwrpq41arm712226vpcr458xv6xaqbk8cp94a0kycpr";
    };
  };
}
