# sneakers — generated by onix. Do not edit.
{
  "2.11.0" = {
    version = "2.11.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1hfgpjjnhy3p4hdsg1x2yy9ba37s3vl65bwxddwispb81ncfg6jk";
    };
  };
}
