# solargraph-rails — generated by onix. Do not edit.
{
  "0.3.1" = {
    version = "0.3.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0f08qcg08rsmg46zjdjzd2xcpv9a19fms1l70ijvxrwcscjyv4nd";
    };
  };
}
