# solargraph — generated by onix. Do not edit.
{
  "0.50.0" = {
    version = "0.50.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0qbjgsrlrwvbywzi0shf3nmfhb52y5fmp9al9nk7c4qqwxyhz397";
    };
  };
}
