# solid_cable — generated by onix. Do not edit.
{
  "3.0.5" = {
    version = "3.0.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0n9l81hmav40zsf72y3f6wiap6l98w8451nzzw5b8x9j20nw52i5";
    };
  };
  "3.0.12" = {
    version = "3.0.12";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0q04dcz4kph9843xcv3f3y64nm9vx90q93glg9idamd4653sas51";
    };
  };
}
