# solid_queue — generated by onix. Do not edit.
{
  "1.1.2" = {
    version = "1.1.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "031nzk36m3nlbrf7n06a91cd55xkvn8dl23mbicsq3fgs6b9730p";
    };
  };
  "1.2.4" = {
    version = "1.2.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0jqfmhn057d58hwbxjxh41pmx3q8dbzv00bnv1vw76ln59azjq5v";
    };
  };
}
