# solid_cache — generated by onix. Do not edit.
{
  "1.0.6" = {
    version = "1.0.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "04f3cvx20qmm0rhl2dgx1jgbklw2j2a1fls240vab9p4zdrwy6py";
    };
  };
  "1.0.10" = {
    version = "1.0.10";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0h8d28zbjp1qvkg9x4r21p9pvdlxrxwnd55mrd1nz2n77bxs41dw";
    };
  };
}
