# sorbet-runtime — generated by onix. Do not edit.
{
  "0.5.11934" = {
    version = "0.5.11934";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1a5v2lv4qkrhaar285mjdfjw9jdr1iz8ckr7w461qhh7g7h7iji1";
    };
  };
}
