# sorted_set — generated by onix. Do not edit.
{
  "1.0.3" = {
    version = "1.0.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0brpwv68d7m9qbf5js4bg8bmg4v7h4ghz312jv9cnnccdvp8nasg";
    };
  };
}
