# spring-watcher-listen — generated by onix. Do not edit.
{
  "2.1.0" = {
    version = "2.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0j8rlra9jg8f0i2vsa26fmda670x4h7fzchnbnwnw0niavcvqn79";
    };
  };
}
