# spring — generated by onix. Do not edit.
{
  "4.1.1" = {
    version = "4.1.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1wvdvwp395cc9srjy0fak5sy0531x7yh358cvmwlkbz0zlb0290x";
    };
  };
}
