# sprockets — generated by onix. Do not edit.
{
  "4.1.1" = {
    version = "4.1.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1qj82dcfkk6c4zw357k5r05s5iwvyddh57bpwj0a1hjgaw70pcb8";
    };
  };
  "4.2.1" = {
    version = "4.2.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "15rzfzd9dca4v0mr0bbhsbwhygl0k9l24iqqlx0fijig5zfi66wm";
    };
  };
}
