# sshkey — generated by onix. Do not edit.
{
  "3.0.0" = {
    version = "3.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1k8i5pzjhcnyf0bhcyn5iixpfp4pz0556rcxwpglh6p0sr8s6nv5";
    };
  };
}
