# sshkit — generated by onix. Do not edit.
{
  "1.23.2" = {
    version = "1.23.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0fr19mqzqkimsz3xn35vwv56f8rmywhp23njp8vsrwzavn7himvn";
    };
  };
}
