# ssrf_filter — generated by onix. Do not edit.
{
  "1.1.2" = {
    version = "1.1.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0ppzg3snx7glnb6p14a0gxsan64570x4glmlfsykz6kg4gnhjci6";
    };
  };
}
