# stackprof — generated by onix. Do not edit.
{
  "0.2.25" = {
    version = "0.2.25";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0bhdgfb0pmw9mav1kw9fn0ka012sa0i3h5ppvqssw5xq48nhxnr8";
    };
  };
  "0.2.26" = {
    version = "0.2.26";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1gdqqwnampxmc54nf6zfy9apkmkpdavzipvfssmjlhnrrjy8qh7f";
    };
  };
  "0.2.27" = {
    version = "0.2.27";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "03788mbipmihq2w7rznzvv0ks0s9z1321k1jyr6ffln8as3d5xmg";
    };
  };
}
