# starry — generated by onix. Do not edit.
{
  "0.2.0" = {
    version = "0.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1c99sj460hdshiv2jps5d4mxcvz7nrvqznfpgcbnjhk9cnhv15i6";
    };
  };
}
