# statsd-ruby — generated by onix. Do not edit.
{
  "1.5.0" = {
    version = "1.5.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "028136c463nbravckxb1qi5c5nnv9r6vh2cyhiry423lac4xz79n";
    };
  };
}
