# stimulus-rails — generated by onix. Do not edit.
{
  "1.3.4" = {
    version = "1.3.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "01nbcxyi1mhikq8yjl0g9swy1cpzx146pli6w16gcfpkl7zpcmkn";
    };
  };
}
