# stoplight — generated by onix. Do not edit.
{
  "5.7.0" = {
    version = "5.7.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "18sj6q25q3kadyixmrf29y1z9zcd89b0c1afrjyvxk1ri4mlj9w7";
    };
  };
}
