# stripe — generated by onix. Do not edit.
{
  "5.55.0" = {
    version = "5.55.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "18z2i02d303bwf9rskzfdkdkyh97zmm0d444ighmrdkd2636c8w7";
    };
  };
  "11.1.0" = {
    version = "11.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "13gr4z9nsvpknyy9y2vg4dvg77817m2ykyx57j03692dgv684vm7";
    };
  };
  "18.0.1" = {
    version = "18.0.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "08jgrk88afdcp9v71mk4k1mjbidk90ybh2bd968na15rhvigiqcv";
    };
  };
}
