# stripe-ruby-mock — generated by onix. Do not edit.
{
  "3.1.0.rc3" = {
    version = "3.1.0.rc3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "02s48fq1bdn8skk45jsrb3ja06fiqw90v8caqf95any33rmr0mzi";
    };
  };
}
