# strong_migrations — generated by onix. Do not edit.
{
  "1.8.0" = {
    version = "1.8.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0p9g8jqcakpwmbs6f77ydmbiwbgx9c5nr6jgwxh4xx6xpig1bphq";
    };
  };
  "2.5.2" = {
    version = "2.5.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0kj5kdf2m4sswzykbhasdkr9ycq9v09icnhs9c58lk5jh93zzyh6";
    };
  };
}
