# swd — generated by onix. Do not edit.
{
  "2.0.3" = {
    version = "2.0.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0m86fzmwgw0vc8p6fwvnsdbldpgbqdz9cbp2zj9z06bc4jjf5nsc";
    };
  };
}
