# syntax_tree — generated by onix. Do not edit.
{
  "6.3.0" = {
    version = "6.3.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0ggi6p7xxjsj42q8pp0yz6z7dbwlbr6fjbs4qnafr667jab5mqjn";
    };
  };
}
