# tailwindcss-ruby — generated by onix. Do not edit.
{
  "3.4.17" = {
    version = "3.4.17";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "09y40d93pi8s5yp076yzj5sf1vjifq0a4mrlmx379ggi8p6bfks6";
    };
  };
}
