# tailwindcss-rails — generated by onix. Do not edit.
{
  "3.2.0" = {
    version = "3.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1k73m1n1fxnypl2lhgfzsqmja9hsqvdla3ihd25ppfnikhgcrnyq";
    };
  };
}
