# telephone_number — generated by onix. Do not edit.
{
  "1.4.20" = {
    version = "1.4.20";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0fbzaizg3f7ydlsp88zshkf47d07pc5jjpn9z7qckvah62f8r7a0";
    };
  };
}
