# temple — generated by onix. Do not edit.
{
  "0.10.4" = {
    version = "0.10.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0b7pzx45f1vg6f53midy70ndlmb0k4k03zp4nsq8l0q9dx5yk8dp";
    };
  };
}
