# terrapin — generated by onix. Do not edit.
{
  "1.1.1" = {
    version = "1.1.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0aakswgqk6cfamq3h6fxdls81ia7v3fi1v825i5pdrgzbh293blw";
    };
  };
}
