# terser — generated by onix. Do not edit.
{
  "1.2.2" = {
    version = "1.2.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1202s910khz7j25v0ggd3gi7fykqdxci3mjasf7nr3zsww6zmpc6";
    };
  };
  "1.2.4" = {
    version = "1.2.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "10ycg71xmrv64c3nn81ms18h3gsrngb6vfwwcd94mvyyzkh4cpy8";
    };
  };
}
