# thor — generated by onix. Do not edit.
{
  "1.3.1" = {
    version = "1.3.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1vq1fjp45az9hfp6fxljhdrkv75cvbab1jfrwcw738pnsiqk8zps";
    };
  };
  "1.3.2" = {
    version = "1.3.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1nmymd86a0vb39pzj2cwv57avdrl6pl3lf5bsz58q594kqxjkw7f";
    };
  };
  "1.4.0" = {
    version = "1.4.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0gcarlmpfbmqnjvwfz44gdjhcmm634di7plcx2zdgwdhrhifhqw7";
    };
  };
  "1.5.0" = {
    version = "1.5.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0wsy88vg2mazl039392hqrcwvs5nb9kq8jhhrrclir2px1gybag3";
    };
  };
}
