# thread_safe — generated by onix. Do not edit.
{
  "0.3.6" = {
    version = "0.3.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0nmhcgq6cgz44srylra07bmaw99f5271l0dpsvl5f75m44l0gmwy";
    };
  };
}
