# thread — generated by onix. Do not edit.
{
  "0.2.2" = {
    version = "0.2.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1xbnfzcxyswi2pz57vmj8yq7pp1g52cqwbpxj28drm3q13909xqf";
    };
  };
}
