# thruster — generated by onix. Do not edit.
{
  "0.1.16" = {
    version = "0.1.16";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1bb80496dckglqrzxg9m2yacb4934k6xjn95z2lgapg7i1dlp9ys";
    };
  };
}
