# tidewave — generated by onix. Do not edit.
{
  "0.2.0" = {
    version = "0.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1j05q101wkhm3ygkbc1q98w4d7b511ylw0widyan4d5c6wwc80dn";
    };
  };
}
