# tiktoken_ruby — generated by onix. Do not edit.
{
  "0.0.15.1" = {
    version = "0.0.15.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0d7q1nxjilj6ydjliyc48axjiz8d67andw76pvi7wsd3spyn0f7y";
    };
  };
}
