# timecop — generated by onix. Do not edit.
{
  "0.9.8" = {
    version = "0.9.8";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0qzmk0gf4j21mgqzfhpyb5m1rjx132p9k41hgl05rcmg9sjnv6c9";
    };
  };
}
