# time_diff — generated by onix. Do not edit.
{
  "0.3.0" = {
    version = "0.3.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1zfnnkqbxay2cjkgyy34915fhp89zq6lmiri3dhb99pv3bxyplil";
    };
  };
}
