# tpm-key_attestation — generated by onix. Do not edit.
{
  "0.14.1" = {
    version = "0.14.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0gqr27hrmg35j7kcb6c2cx3xvkqfs42zpp9jcqw0mzbs79jy9m3z";
    };
  };
}
