# trailblazer-option — generated by onix. Do not edit.
{
  "0.1.2" = {
    version = "0.1.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "18s48fndi2kfvrfzmq6rxvjfwad347548yby0341ixz1lhpg3r10";
    };
  };
}
