# ttfunk — generated by onix. Do not edit.
{
  "1.8.0" = {
    version = "1.8.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1ji0kn8jkf1rpskv3ijzxvqwixg4p6sk8kg0vmwyjinci7jcgjx7";
    };
  };
}
