# tty-color — generated by onix. Do not edit.
{
  "0.6.0" = {
    version = "0.6.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0aik4kmhwwrmkysha7qibi2nyzb4c8kp42bd5vxnf8sf7b53g73g";
    };
  };
}
