# tty-cursor — generated by onix. Do not edit.
{
  "0.7.1" = {
    version = "0.7.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0j5zw041jgkmn605ya1zc151bxgxl6v192v2i26qhxx7ws2l2lvr";
    };
  };
}
