# tty-prompt — generated by onix. Do not edit.
{
  "0.23.1" = {
    version = "0.23.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1j4y8ik82azjxshgd4i1v4wwhsv3g9cngpygxqkkz69qaa8cxnzw";
    };
  };
}
