# tty-screen — generated by onix. Do not edit.
{
  "0.8.2" = {
    version = "0.8.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0l4vh6g333jxm9lakilkva2gn17j6gb052626r1pdbmy2lhnb460";
    };
  };
}
