# tty-reader — generated by onix. Do not edit.
{
  "0.9.0" = {
    version = "0.9.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1cf2k7w7d84hshg4kzrjvk9pkyc2g1m3nx2n1rpmdcf0hp4p4af6";
    };
  };
}
