# turbo-rails — generated by onix. Do not edit.
{
  "2.0.11" = {
    version = "2.0.11";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1kvz74g2j233zbbpqiba2p5gahpjps20vp54samq09rp6r3nfizw";
    };
  };
  "2.0.21" = {
    version = "2.0.21";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1ivb45cpj3v9ky0nr34vwfa0x8i90ycbxmyr0wd8q7fikyi0w1q2";
    };
  };
}
