# twilio-ruby — generated by onix. Do not edit.
{
  "7.6.0" = {
    version = "7.6.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1ddwwg1iz3rsyhrbdi933kc5n24lwnxa5gq9r9x6n8fh15j6ka9m";
    };
  };
}
