# twitty — generated by onix. Do not edit.
{
  "0.1.5" = {
    version = "0.1.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1mm6gxq8jixl26h2pkb1l4pwv6qhigqxh8kj3kqrl0093y2aban6";
    };
  };
}
