# twitter — generated by onix. Do not edit.
{
  "7.0.0" = {
    version = "7.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "13dmkjgsnym1avym9f7y2i2h3mlk8crqvc87drrzr4f0sf9l8g2y";
    };
  };
}
