# twitter-text — generated by onix. Do not edit.
{
  "3.1.0" = {
    version = "3.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1dnmp0bj3l01nbb52zby2c7hrazcdwfg846knkrjdfl0yfmv793z";
    };
  };
}
