# tzinfo — generated by onix. Do not edit.
{
  "2.0.6" = {
    version = "2.0.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "16w2g84dzaf3z13gxyzlzbf748kylk5bdgg3n1ipvkvvqy685bwd";
    };
  };
}
