# uber — generated by onix. Do not edit.
{
  "0.1.0" = {
    version = "0.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1p1mm7mngg40x05z52md3mbamkng0zpajbzqjjwmsyw0zw3v9vjv";
    };
  };
}
