# uglifier — generated by onix. Do not edit.
{
  "4.2.0" = {
    version = "4.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0wgh7bzy68vhv9v68061519dd8samcy8sazzz0w3k8kqpy3g4s5f";
    };
  };
}
