# unaccent — generated by onix. Do not edit.
{
  "0.4.0" = {
    version = "0.4.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0cvk3vhs95123r4faa60vqknishx3r6fiy2kq0bm7p3f04q849yr";
    };
  };
}
