# unf — generated by onix. Do not edit.
{
  "0.1.4" = {
    version = "0.1.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0bh2cf73i2ffh4fcpdn9ir4mhq8zi50ik0zqa1braahzadx536a9";
    };
  };
  "0.2.0" = {
    version = "0.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1aq4bfddln9kx4lycqdgmahsssljsm3vfgbmb6a3y3nq07hw5g76";
    };
  };
}
