# unicode-display_width — generated by onix. Do not edit.
{
  "2.5.0" = {
    version = "2.5.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1d0azx233nags5jx3fqyr23qa2rhgzbhv8pxp46dgbg1mpf82xky";
    };
  };
  "3.1.4" = {
    version = "3.1.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1has87asspm6m9wgqas8ghhhwyf2i1yqrqgrkv47xw7jq3qjmbwc";
    };
  };
  "3.2.0" = {
    version = "3.2.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0hiwhnqpq271xqari6mg996fgjps42sffm9cpk6ljn8sd2srdp8c";
    };
  };
}
