# uniform_notifier — generated by onix. Do not edit.
{
  "1.16.0" = {
    version = "1.16.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1dfvqixshwvm82b9qwdidvnkavdj7s0fbdbmyd4knkl6l3j9xcwr";
    };
  };
  "1.17.0" = {
    version = "1.17.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "19vcdlfcxrlp4vkzx0jn4zwf5jg125ca89s0mnqcqs6i5bnqfiyv";
    };
  };
  "1.18.0" = {
    version = "1.18.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "17ffzyq6482yn27r7rz2k3zslf9jigbz383d90c68vznarapi1s7";
    };
  };
}
