# uri_template — generated by onix. Do not edit.
{
  "0.7.0" = {
    version = "0.7.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0p8qbxlpmg3msw0ihny6a3gsn0yvydx9ksh5knn8dnq06zhqyb1i";
    };
  };
}
