# useragent — generated by onix. Do not edit.
{
  "0.16.11" = {
    version = "0.16.11";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0i1q2xdjam4d7gwwc35lfnz0wyyzvnca0zslcfxm9fabml9n83kh";
    };
  };
}
