# validate_url — generated by onix. Do not edit.
{
  "1.0.15" = {
    version = "1.0.15";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0lblym140w5n88ijyfgcvkxvpfj8m6z00rxxf2ckmmhk0x61dzkj";
    };
  };
}
