# valid_email2 — generated by onix. Do not edit.
{
  "5.2.6" = {
    version = "5.2.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0mhil4g0pswk4r5l04h8010flqifjndr6snsvsqr99wzr1d17y6r";
    };
  };
}
