# vcr — generated by onix. Do not edit.
{
  "6.3.1" = {
    version = "6.3.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1v83xjgj5y1fzp7nm4s5dixwpy5yr8crklyjyjilc13jgqanxd9p";
    };
  };
}
