# vite_ruby — generated by onix. Do not edit.
{
  "3.8.0" = {
    version = "3.8.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1zz6az33bgwhfhibcmjpmy2bynfrkrx50d1anm7061jwhm11ihlh";
    };
  };
  "3.9.2" = {
    version = "3.9.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0wj9ia0s7vywn66pf2jn49pfsy5h5rncjjwhaymwq32r3f2pq2p1";
    };
  };
}
