# vite_rails — generated by onix. Do not edit.
{
  "3.0.17" = {
    version = "3.0.17";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1k4bllg0zpmpkjfmk1gybc2ygca4v40l2fmlplf9h0jqwniqa3mr";
    };
  };
  "3.0.20" = {
    version = "3.0.20";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "10p6jrfzkliqg9xsb5y598w1ggd99wmqc5wcljqdkd637fmgjasq";
    };
  };
}
