# w3c_validators — generated by onix. Do not edit.
{
  "1.3.7" = {
    version = "1.3.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0ip7igzx9vim1vs0y6qzllashmfcj0rnjj9akz7w5mnli89zi197";
    };
  };
}
