# warden — generated by onix. Do not edit.
{
  "1.2.9" = {
    version = "1.2.9";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1l7gl7vms023w4clg02pm4ky9j12la2vzsixi2xrv9imbn44ys26";
    };
  };
}
