# wcag_color_contrast — generated by onix. Do not edit.
{
  "0.1.0" = {
    version = "0.1.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1fb2pqgwnlwkdp6d19sxir5ffsbcqzw78v5niddqjys9b07sjidc";
    };
  };
}
