# web-console — generated by onix. Do not edit.
{
  "4.2.1" = {
    version = "4.2.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "087y4byl2s3fg0nfhix4s0r25cv1wk7d2j8n5324waza21xg7g77";
    };
  };
}
