# web-push — generated by onix. Do not edit.
{
  "3.0.1" = {
    version = "3.0.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "13diqh61rl658gwq0c2ds41z59i0x4plj5k4v98qkgd3pgrd4kav";
    };
  };
}
