# webfinger — generated by onix. Do not edit.
{
  "2.1.3" = {
    version = "2.1.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0p39802sfnm62r4x5hai8vn6d1wqbxsxnmbynsk8rcvzwyym4yjn";
    };
  };
}
