# webrick — generated by onix. Do not edit.
{
  "1.8.2" = {
    version = "1.8.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "089gy5494j560b242vi173wnbj2913hwlwnjkpzld58r96ilc5s3";
    };
  };
  "1.9.1" = {
    version = "1.9.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "12d9n8hll67j737ym2zw4v23cn4vxyfkb6vyv1rzpwv6y6a3qbdl";
    };
  };
  "1.9.2" = {
    version = "1.9.2";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0ca1hr2rxrfw7s613rp4r4bxb454i3ylzniv9b9gxpklqigs3d5y";
    };
  };
}
