# websocket — generated by onix. Do not edit.
{
  "1.2.11" = {
    version = "1.2.11";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0dr78vh3ag0d1q5gfd8960g1ca9g6arjd2w54mffid8h4i7agrxp";
    };
  };
}
