# websocket-driver — generated by onix. Do not edit.
{
  "0.7.6" = {
    version = "0.7.6";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1nyh873w4lvahcl8kzbjfca26656d5c6z3md4sbqg5y1gfz0157n";
    };
  };
  "0.7.7" = {
    version = "0.7.7";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1d26l4qn55ivzahbc7fwc4k4z3j7wzym05i9n77i4mslrpr9jv85";
    };
  };
  "0.8.0" = {
    version = "0.8.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0qj9dmkmgahmadgh88kydb7cv15w13l1fj3kk9zz28iwji5vl3gd";
    };
  };
}
