# websocket-client-simple — generated by onix. Do not edit.
{
  "0.9.0" = {
    version = "0.9.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "029iar7fnnrgmc1k463xlkpr4n72s4zdgri13rqmmcr295g7r8zr";
    };
  };
}
