# websocket-extensions — generated by onix. Do not edit.
{
  "0.1.5" = {
    version = "0.1.5";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0hc2g9qps8lmhibl5baa91b4qx8wqw872rgwagml78ydj8qacsqw";
    };
  };
}
