# wisper — generated by onix. Do not edit.
{
  "2.0.0" = {
    version = "2.0.0";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0ar2wn3pxnffyzcmf67y67b8lnhgn9zayqhqp26jwqa3d73j71kd";
    };
  };
  "2.0.1" = {
    version = "2.0.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1rpsi0ziy78cj82sbyyywby4d0aw0a5q84v65qd28vqn79fbq5yf";
    };
  };
}
