# working_hours — generated by onix. Do not edit.
{
  "1.4.1" = {
    version = "1.4.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "11lhzh7s8qy9nam7ws7hqpm3giix3lkinagf5x4knn77l2520vdv";
    };
  };
}
