# xorcist — generated by onix. Do not edit.
{
  "1.1.3" = {
    version = "1.1.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1dbbiy8xlcfvn9ais37xfb5rci4liwakkmxzbkp72wmvlgcrf339";
    };
  };
}
