# yard — generated by onix. Do not edit.
{
  "0.9.36" = {
    version = "0.9.36";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1r0b8w58p7gy06wph1qdjv2p087hfnmhd9jk23vjdj803dn761am";
    };
  };
  "0.9.38" = {
    version = "0.9.38";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "03q1hf12csqy5q2inafzi44179zaq9n5yrb0k2j2llqhzcmbh7vj";
    };
  };
}
