# yard-activesupport-concern — generated by onix. Do not edit.
{
  "0.0.1" = {
    version = "0.0.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1vwhhgkkrw57anbbsyv5aihmhhxpr255jqvhcy3jwgn2xyq0qydy";
    };
  };
}
