# yard-activerecord — generated by onix. Do not edit.
{
  "0.0.16" = {
    version = "0.0.16";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1mvd46d8wyalacifvgl3cvlb1j336i02bxbfcxsq249cmid5fp6i";
    };
  };
}
