# zeitwerk — generated by onix. Do not edit.
{
  "2.6.13" = {
    version = "2.6.13";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1m67qmsak3x8ixs8rb971azl3l7wapri65pmbf5z886h46q63f1d";
    };
  };
  "2.6.17" = {
    version = "2.6.17";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "1b1azc3qlyzlnld4d5yav9j13dlqlyygnml5qf4gqpzaj861d588";
    };
  };
  "2.7.3" = {
    version = "2.7.3";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "119ypabas886gd0n9kiid3q41w76gz60s8qmiak6pljpkd56ps5j";
    };
  };
  "2.7.4" = {
    version = "2.7.4";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "12zcvhzfnlghzw03czy2ifdlyfpq0kcbqcmxqakfkbxxavrr1vrb";
    };
  };
}
