# zendesk_api — generated by onix. Do not edit.
{
  "1.38.0.rc1" = {
    version = "1.38.0.rc1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0yizpglgfwml6a2w696m97d1q50hq3v0vldja431rv93s9sjbgly";
    };
  };
}
