# zonebie — generated by onix. Do not edit.
{
  "0.6.1" = {
    version = "0.6.1";
    source = {
      type = "gem";
      remotes = [ "https://rubygems.org" ];
      sha256 = "0saywdxq4zrrm6sdh2y7s3dxpqckgi4sw4xbb0fsi9ljacxxlqi7";
    };
  };
}
